### ISSUE TITLE
Request: Collision.hitObjectList[x].localImpulse

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#10]
is there any way to record the collision impact from bullet for each hitObject in the hitObjectList?

Collision.hitObjectList[x].localImpulse = localized force impulse from collision

??? how would I tag Erwin Coumans ???

**Comment by BluePrintRandom** [comment]
Does this work?
https://github.com/erwincoumans

**Comment by panzergame** [comment]
@BluePrintRandom you wanted a list of tuple : (object, [contacts]), no ? Could you give more precisions ?

**Comment by BluePrintRandom** [comment]
A tuple would be excellent,

like collision.hitObjectList[0]= [hitObject,contactPoints,impulse]

**Comment by sdfgeoff** [comment]
I would think that extending the collision callbacks API to include the applied impulse as well as multiple hit objects would be more useful.

**Comment by BluePrintRandom** [comment]
yeah like

collision.hitObjectListProps = [Objects,Contacts,Impulses]

collision.hitObjectListProps[0] = collision.hitObjects
collision.hitObjectListProps[1] = collision.hitContacts
collision.hitObjectListProps[2] = collision.hitImpulses

**Comment by panzergame** [comment]
I propose:
> collision.hitContactPointList 

What do you think ?

**Comment by BluePrintRandom** [comment]
That is good, but the data it returns,

will be like

[[Obj1_hitContact1, Obj1_hitContact2],[Obj2_hitContact1, Obj2_hitContact2]]

?

a list of lists?
and you can use the list index + hitObjectList to sort out what contacts
are for who?

**Comment by panzergame** [comment]
items will be a CListValue of ClistWrapper of KX_CoillisionContactPoint.

**Comment by BluePrintRandom** [comment]
So the end user, how do they detect which collision contacts are for which
item?



HitContact[0] = [hitObjectList[0]'s hit contacts?]

**Comment by panzergame** [comment]
Yes, it will be aligned with object list.
