### ISSUE TITLE
Render attachments working in 0.2.3 + render attachments for recent master

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#1000]
[2.4-render-attachment-test.blend.zip](https://github.com/UPBGE/blender/files/2798729/2.4-render-attachment-test.blend.zip)

test file works - in upbge 0.2.3 + render_attachments branch
![image](https://user-images.githubusercontent.com/7190873/51783840-f79ecf80-20f4-11e9-92cd-d3ef275ee8ed.png)

black screen in upbge 0.2.4
![image](https://user-images.githubusercontent.com/7190873/51783843-fc638380-20f4-11e9-822f-572c01634bc7.png)

**Comment by lopas85** [comment]
...also the use of bgl_DataTextures instead of bgl_RenderedTextures does not solve

**Comment by BluePrintRandom** [comment]
@lopas85  I can close this now?

**Comment by lopas85** [comment]
yes yes close!!

**Comment by lopas85** [comment]
yes!! :)  https://www.youtube.com/watch?v=ye0yC9Ufkj8
