### ISSUE TITLE
UPBGE Status

### ISSUE THREAD

**Issue by lordloki** [UPBGE/blender#1006]
Hi everybody!!

As you have seen last month the activity of the UPBGE repository has been very low.

Mainly it was because the laptop was broken but the background reality is that every time I have less interest (and more pressure added each time) in continuing with the engine.

I'm sorry but I have neither the strength, nor the knowledge, nor the time to carry out such a big project alone.

I will try to merge a great majority of the pull requests that are open, fix some bugs and publish a last UPBGE 0.2.5.

After that I'm going to abandon the development of UPBGE.

If someone wants to continue the project send me a private email and I will give them access to the repository.

Thanks for everything. It has been a pleasure to contribute to make games with you.

**Comment by RomStef** [comment]
I know it's an hard work , thanks a lot for the passion and dedication

**Comment by youle31** [comment]
@lordloki : Thanks very much for all your works. This is the same for me. I'll continue to update my 2.8 branch as a hobby, and I begun to look at some bugs on BF tracker to see if I can contribute to some simple bug fixes. BTW, there is no need to put yourself pressure about 0.2.5. This is only if we want.

Thanks again, the ambiance was not really good the last times anyway, partly because of me I guess too.

I wish you to be more relax from now, and to find a good new hobby! See you later!

**Comment by Masterblop** [comment]
OMG! Right now that I was working hard to donate my little work to you. I will do the same! It's a promise!
In any case, I understand the situation! 
Thank you so much for the effort you have shown for the game engine :)

**Comment by BluePrintRandom** [comment]
Thank you for everything @lordloki  and @youle31 @panzergame  !

**Comment by MkeC4128** [comment]
Very sad day.  I also want to thank you all.

**Comment by BluePrintRandom** [comment]
So I will be here trying to get a nice set of template blend files, and GLSL scripts, and documentation

we have 100's of features added since splitting from BF that are not known about by the general public or understood.

We will try and build front end enhancements in BPY  and extend the engine, and learn to code C or accept the help of new C devs.

**Comment by jhonphilipps** [comment]
impossible les gars, UPBGE fonctionne très bien il ne lui manque pas grand chose pour sortir des hits ! De toutes façon là ou il est rendu il peu déjà sortir un hit qui aiderai au financement. à titre personnel je n'ai pas les compétences mais chaque jour me permet en bidouillant d'avoir de plus en plus de compétences. Même si UPBGE s'arrête de ce développer d'ici demain, un jeu peux toujours sortir demain ou même dans 5 ans et relancer son développement ! La technologie qui est utilisée est très loin d'être désuète ;)
EEVEE, real time ray trace, tout ça c'est bien mais perso je m'en tape ! Je suis un noob mais j'aime upbge c'est oldschool dirai certain mais je suis pas d'accord pour moi c'est OP

**Comment by zicklag** [comment]
I just want to share, for those of you who don't already know about it, [Armory3D](https://armory3d.org) is an under-developement game engine with a full Blender integration similar in some ways to UPBGE, but implemented completely differently. It isn't fully stable yet and there is a lot of development to be done, but it is getting better all the time and is progressing quickly.

If you have any questions about it you can ask on the [forum](http://forums.armory3d.org/?u=zicklag).

**Comment by UglinessInTheUI** [comment]
Come on people we need this thing going until it beats Cry Engine and Unreal Engine. Does anybody know how to program in C++ properly without adding more bugs and performance issues ?

**Comment by chicortiz** [comment]
Thank you so much @lordloki ! I wish all the best for you. I hope that we can keep the BGE alive somehow...

**Comment by marechal-p** [comment]
@BluePrintRandom really, deleting posts? I am curious to see what was said.

@UglinessInTheUI wanna try?

@lordloki thanks for the update, this is indeed a big project to hold on so few shoulders.
On the other hand, people might keep playing and hacking around, don't you worry :)

**Comment by BluePrintRandom** [comment]
Deleted spam Telling us to move to armoury.

**Comment by RomStef** [comment]
I think all of us known the other branches of bge available and ready to use. The reason why we follow this branch is because we are interested in upBGE. It's an easy answer :D

**Comment by zicklag** [comment]
> Deleted spam Telling us to move to armoury.

I wasn't spamming. The project was potentially going to go unmaintained and I wanted to let anybody who hadn't heard of Armory know that there was another Blender game engine out there if this one went down and they were out of an engine.

I didn't tell anybody to switch to Armory, I just said, "For anybody who doesn't already know, there is Armory3D".

**Comment by UglinessInTheUI** [comment]
Hey , don't abandon the project. We need this thing going. How do I send that private email ?

**Comment by EndSSgamesStudio** [comment]
we have not updated for more than 20 days.
we must at least adjust these major performance problems...

**Comment by marechal-p** [comment]
@EndSSgamesStudio indeed, pull-requests are welcome!

**Comment by JoshS** [comment]
noooo i love this engine :(
