### ISSUE TITLE
Scary issue...Python errors referencing lines of code from other files on HDD!?

### ISSUE THREAD

**Issue by statikregimen** [UPBGE/blender#1011]
This is a very disconcerting issue, but no clue where to start on support so here it is.

Sometimes, when I cause a Python error, the traceback shows lines of code from files not remotely associated with my .blend or any script associated with it - I mean, it's pulling lines of code from apparently random files on my hard drive.

Example of non-working code:

```
from bge import logic
from opensimplex import OpenSimplex
from mathutils import Vector

seed = 123
chunkSize = 16
noiseScale = 0.1
threshold = -0.1
blockSpacing = 1

noise = OpenSimplex(seed).noise3d

s = logic.getCurrentScene()


class Chunk(list):
    def __init__(self, x=0, y=0, z=0):
        self.x, self.y, self.z = x, y, z

        d = [
            [[0 for dz in range(chunkSize)] for dy in range(chunkSize)]
            for dx in range(chunkSize)
        ]

        for dx in range(chunkSize):
            for dy in range(chunkSize):
                for dz in range(chunkSize):
                    n = noise(
                        (dx+x)*noiseScale,
                        (dy+y)*noiseScale,
                        (dz+z)*noiseScale
                    )

                    if n > threshold:
                        d[dx][dy][dz] = n

        super(Chunk, self).__init__(d)

    def neighbors(self, x, y, z):
        # Return 6 neighboring blocks
        return [
            self[x+1][y][z], #if x+1 < chunkSize else 0,
            self[x][y+1][z], #if y+1 < chunkSize else 0,
            self[x][y][z+1], #if z+1 < chunkSize else 0,
            self[x-1][y][z], #if x-1 > chunkSize else 0,
            self[x][y-1][z], #if y-1 > chunkSize else 0,
            self[x][y][z-1] #if z-1 > chunkSize else 0
        ]

    @property
    def visible(self):
        for x in range(chunkSize):
            for y in range(chunkSize):
                for z in range(chunkSize):
                    v = self[x][y][z]
                    a = all(i for i in self.neighbors(x,y,z))

                    if v and not a:
                        yield ((x,y,z), v)
                    elif a:
                        print("invisible", v)

    def __iter__(self):
        for x in range(chunkSize):
            for y in range(chunkSize):
                for z in range(chunkSize):
                    v = self[x][y][z]

                    if v:
                        yield ((x,y,z), v)

chunk = Chunk()

for i in chunk:
    print(chunk.neighbors(*i[0]))
```

```
Error: Python(Camera), Python script error
Traceback (most recent call last):
  File "test.py", line 76, in <module>
    
  File "test.py", line 45, in neighbors
    #~ "cat /dev/input/event0", stdout=subprocess.PIPE
IndexError: list index out of range
Blender Game Engine Finished
```

The reason I get this error, is because I comment out the constraints in Chunk.neighbors(), but the error message is referencing some commented out line in a completely different file that has never been associated with this .blend file/project in any way...it merely resides on the same drive. It's funny, though - the line numbers are right.....just the line of code it shows is way outside of any file UPBGE/Blender should even have opened.

This is the 3rd time in my session tonight that this has happened, but I can't remember how to reproduce the first two.

Any help is appreciated!

**Comment by statikregimen** [comment]
I've found the issue to be that I had created the script within UPBGE using the same name as a file in the same directory.

Thus, this may not be a bug, per-se, and certainly a very rare use-case, but perhaps UPBGE or BF could implement a check and issue a warning or something?

Either way, I will leave you with this information to do with what you will, and hope you have a pleasant day!

**Comment by marechal-p** [comment]
> Thus, this may not be a bug, per-se, and certainly a very rare use-case, but perhaps UPBGE or BF could implement a check and issue a warning or something?

That's kind of how the import mechanism in Python works, if anything, it should be documented that any in-editor files have precedence over filesystem files (or is it the other way around?)
