### ISSUE TITLE
Strange Python Behavior

### ISSUE THREAD

**Issue by statikregimen** [UPBGE/blender#1013]
Good day,
I wrote the following script to visualize 3D OpenSImplex noise in the game engine. When I move my chunk (by passing ox,oy,oz which act as origin offsets), it appears that somehow my range(chunkSize) gets jacked up.

```
# Sample noise directly
from bge import logic, types
from opensimplex import OpenSimplex
from time import time
#from mathutils import Vector

seed = 123
chunkSize = 16
noiseScale = 0.1
threshold = 0

noise = OpenSimplex(seed).noise3d

s = logic.getCurrentScene()


def n(x,y,z):
    v = noise(x*noiseScale,y*noiseScale,z*noiseScale)

    return v if v > threshold else 0


def chunk(ox=0, oy=0, oz=0):
    ns = noiseScale

    for x in range(chunkSize):
        for y in range(chunkSize):
            for z in range(chunkSize):
                print(oy, y, oy+y)
                x, y, z = ox+x, oy+y, oz+z
                v = n(x, y, z)

                if v:
                    if not all((
                        n(x+1, y, z),
                        n(x, y+1, z),
                        n(x, y, z+1),
                        n(x-1, y, z),
                        n(x, y-1, z),
                        n(x, y, z-1)
                    )):
                        o = s.addObject("Cube")
                        o.worldPosition = x,y,z
                        #yield o


t = time()

chunk(0,16,0)
```
Here is some sample output (of the print() statement):
16 191 207
16 207 223
16 223 239
16 239 255
16 255 271

As you can see, I print information in a place where it seems like I should get pure results from the "for" loops, yet as I said: when I move the chunk by passing ox,oy,oz, I get apparently insane results from them. It seems to get worse, the higher the numbers I pass... If I leave ox,oy,oz at 0, it works as expected.

I'm using UPBGE 0.2.4

I haven't messed with the built-in Python other than installing OpenSImplex. I am unsure which, if any logs, would be relevant. I have a similar script that does not have this issue, but uses extremely similar code...It has it's own issues that I am not sure yet if could be related to this. 

I would attach the project file, but it will not allow me.

Any help is appreciated!

**Comment by marechal-p** [comment]
You are reassigning `y` inside the `for z in range(chunkSize)` loop.

**Comment by statikregimen** [comment]
Not before the print statement, which clearly is outputting a result way outside of the range. I tried commenting out the rest of the for loop, like so:

```
def chunk(ox=0, oy=0, oz=0):
    ns = noiseScale

    for x in range(chunkSize):
        for y in range(chunkSize):
            for z in range(chunkSize):
                print(oy, y, oy+y)
                """
                x, y, z = x+ox, y+oy, z+oz
                v = n(x, y, z)

                if v:
                    if not all((
                        n(x+1, y, z),
                        n(x, y+1, z),
                        n(x, y, z+1),
                        n(x-1, y, z),
                        n(x, y-1, z),
                        n(x, y, z-1)
                    )):
                        o = s.addObject("Cube")
                        o.worldPosition = x,y,z
                        #yield o"""
```

And I get the correct result. So can someone please explain why modifying the result AFTER printing it, is causing incorrect output?

**Comment by statikregimen** [comment]
I just did this test:

c = 16

for x in range(c):
    for y in range(c):
        for z in range(c):
            print(x,y,z)
            #x,y,z = 1,2,3

And I was able to reproduce the issue outside of UPBGE so there is apparently something fundamental I do not understand about Python that has somehow eluded me for years....
