### ISSUE TITLE
Performance Problem

### ISSUE THREAD

**Issue by UglinessInTheUI** [UPBGE/blender#1015]
It seems that UPBGE is way slower than Blender 2.79b in this scene. In 2.79b logic stays at 7%. In UPBGE it reaches 25% or 26%. Almost 4 times slower compared to 2.79b.

[Sim 003.zip](https://github.com/UPBGE/blender/files/2871902/Sim.003.zip)

![2019 02 16-05 36](https://user-images.githubusercontent.com/12206146/52899930-29afc880-31ad-11e9-9572-baea0b31a33c.png)

**Comment by BluePrintRandom** [comment]
You have to look at the milliseconds not the percentages

Post a side by side eh? 

Also any errors in the console?

**Comment by UglinessInTheUI** [comment]
Here are the screenshots. We have 1.09ms versus 4.27ms. It's 4 times slower in UPBGE compared to 2.79b. Sorry i forgot to pack the texture that's why it looked wrong.


[Sim 003.zip](https://github.com/UPBGE/blender/files/2872342/Sim.003.zip)
![upbge](https://user-images.githubusercontent.com/12206146/52904663-43243500-31ec-11e9-8e6a-94b02090c94d.png)
![2 79b](https://user-images.githubusercontent.com/12206146/52904664-43243500-31ec-11e9-97bc-ca10c918830a.png)

**Comment by UglinessInTheUI** [comment]
No errors in the console at all. It doesn't even hold the 60 fps properly. In 2.79b it has a solid 60 fps. I only get errors in the console when i try to switch to 16x Anti Aliasing.

**Comment by UglinessInTheUI** [comment]
Also the 16x AA from User Preferences doesn't work in UPBGE. I have to set the AA in the Properties Panel.

**Comment by UglinessInTheUI** [comment]
2.79b has a much cleaner image quality because the AA gets enabled from User Preferences. I forgot to enable AA in UPBGE , because AA only works from the Properties Panel and it's still 4 times slower. You can see in the images. The 2.79b has much cleaner red lines.

**Comment by BluePrintRandom** [comment]
have you disabled environmental lighting? - some performance issues can come from that.

are you using render quires ? - this decreases performance also,
 do you have un-applied modifiers?

typically UPBGE is the same or faster, however there is extra stuff on by default.

**Comment by UglinessInTheUI** [comment]
I disabled all the shading options including AA and the result is the same. UPBGE is 4 times slower in logic compared to 2.79b. Check screenshot. Every scene i tried it was slower in UPBGE. Can you show me one scene or a blend file where UPBGE is faster than 2.79b ? Thanks in advance.


![2019 02 16-14 28](https://user-images.githubusercontent.com/12206146/52905413-3c4eef80-31f7-11e9-900e-93ec3a5d16cd.png)

**Comment by BluePrintRandom** [comment]
If logic is 4x slower it sounds like your likely printing errors in the console.

I am working atm so I can't snag your file, however it sounds like this is user error.

**Comment by UglinessInTheUI** [comment]
What do you mean user error ? I compared them side by side. Every scene was 4 to 6 times slower in UPBGE. Look at this buggy scene for example. It gives 5 fps in UPBGE and 33 fps in 2.79b. That's over 5x slower in UPBGE. 

![house 2 79b](https://user-images.githubusercontent.com/12206146/52905510-7076e000-31f8-11e9-9108-5ef35d8ac4b5.png)
![upbge 5x lower fps](https://user-images.githubusercontent.com/12206146/52905511-7076e000-31f8-11e9-8974-c9149ec9032e.png)

**Comment by UglinessInTheUI** [comment]
Here is another test with V sync removed and 4x AA for each one. It has half the performance compared to 2.79b. Image quality is also worse for some reason in UPBGE. Both were set to 4x AA. 


![upbge a](https://user-images.githubusercontent.com/12206146/52907583-99f83180-3221-11e9-9254-49906bae2969.png)
![bl a](https://user-images.githubusercontent.com/12206146/52907584-99f83180-3221-11e9-8f7f-4fe046fa97ca.png)

**Comment by BluePrintRandom** [comment]
The above scene has render queries active.

I will check your file when I get a chance.

**Comment by UglinessInTheUI** [comment]
That's true but if i turn those off it still has half the performance compared to 2.79b. I hope they can improve performance and image quality , not make it worse.

**Comment by EndSSgamesStudio** [comment]
> O que quer dizer erro do usuário? Eu os comparei lado a lado. Cada cena foi 4 a 6 vezes mais lenta no UPBGE. Olhe para esta cena de buggy por exemplo. Dá 5 fps em UPBGE e 33 fps em 2.79b. Isso é mais de 5 vezes mais lento no UPBGE.
> 
> ![casa 2 79b](https://user-images.githubusercontent.com/12206146/52905510-7076e000-31f8-11e9-9108-5ef35d8ac4b5.png)
> ![upbge 5x mais fps](https://user-images.githubusercontent.com/12206146/52905511-7076e000-31f8-11e9-8974-c9149ec9032e.png)

**Please disable this option, and re-test...**

![screenshot_20190216234409](https://user-images.githubusercontent.com/35436445/52907678-e3a64380-3244-11e9-8af3-df167f5d2bcb.png)

**Comment by UglinessInTheUI** [comment]
OK here is the retest. I turned off those things.

![b1](https://user-images.githubusercontent.com/12206146/52907722-88fcef80-3224-11e9-84f7-f8bbe46a92f0.png)
![b2](https://user-images.githubusercontent.com/12206146/52907723-88fcef80-3224-11e9-8214-bece05d37c55.png)

**Comment by UglinessInTheUI** [comment]
It's still 3 times slower in UPBGE even with those things turned off. Very buggy scene by the way.

**Comment by Cotaks** [comment]
i agree upbge 0.2.4 is kinda slow, i noticed this as well.

**Comment by UglinessInTheUI** [comment]
Here is a comparison with an empty scene , all shading options turned off and the CPU locked at 3.35Ghz.

![fps 02](https://user-images.githubusercontent.com/12206146/53130738-4c810a80-3528-11e9-9819-78411f43b561.png)
![fps 01](https://user-images.githubusercontent.com/12206146/53130739-4d19a100-3528-11e9-9ceb-daa48de12470.png)

**Comment by youle31** [comment]
The project is paused/stopped. Thanks to not open new issues

**Comment by marechal-p** [comment]
Issues are still valid :)

**Comment by youle31** [comment]
enabling render queries drastically decreases performances, then you can't compare enabling render queries. Else, at this point it becomes too difficult to compare upbge and bge because they are not the same at all. Some bugs have been fixed which make logic slower sometimes because for example we update the depsgraph each time we call ApplyRotation or ApplyMovement. This is not the case in BF Blender, and this causes frames gap between the moment when you call the function and the moment when it is executed. There are tons of factors to take into account (this was just a random example and there are 1000 other examples)

The only thing to do to track performances issues is to do bisects with github (find if a specific commit has an enormous performances impact). Bisects are long and boring.

Else, UPBGE requires a lot of technical knowledge to optimize scenes but has many more options than bge to do it.

**Comment by UglinessInTheUI** [comment]
OK , so , should we close the issue ? It looks like it's way too complicated to fix it. Or , nobody knows how to fix it.

**Comment by marechal-p** [comment]
https://git-scm.com/docs/git-bisect

**Comment by UglinessInTheUI** [comment]
Thanks marechal-p , i will try the documentation and videos , hopefully i find an older version that has better performance. I will let you know if i figure it out.

**Comment by UglinessInTheUI** [comment]
OK , I'm either doing something wrong or all the versions that I checked-out are bad and compile with errors. I did something like this:

1. git checkout 96148a6    <--- it compiled with errors
2. git checkout 8e5c407    <--- it compiled with errors

Do i have to do other commands in between checkouts or before/after ?
What am i missing here ?

**Comment by BluePrintRandom** [comment]
you have to ensure you have the correct libs during each release

I think you need a SVN command to go with your git commands

**Comment by youle31** [comment]
Yeah, bisects can be long and boring because of that. On windows I use a program named tortoise SVN to see the "lib" folder SVN log. I checkout the libraries at the date just before the commit date:

This looks like that for me:

![1](https://user-images.githubusercontent.com/10052509/53293753-5d58a700-37da-11e9-9867-5c57606fbd0b.jpg)
![2](https://user-images.githubusercontent.com/10052509/53293754-6184c480-37da-11e9-860f-0738fe52a278.jpg)

**Comment by UglinessInTheUI** [comment]
I guess that's what it is. My libs are out of sync. Thanks guys. I will try again.

**Comment by UglinessInTheUI** [comment]
OK , so i managed to compile commit 89a48994ef313951848f67a9ec1526c010bdbdf0 without any errors , only 103 warnings , warnings mostly from ffmpeg i guess and the performance numbers look only a tiny bit better but it's still slower than 2.79b. LOL

![2019 02 23-20 03](https://user-images.githubusercontent.com/12206146/53294592-c6bec280-37a6-11e9-87d5-20989ad75b31.png)
![2019 02 23-20 02](https://user-images.githubusercontent.com/12206146/53294593-c6bec280-37a6-11e9-8a41-7376cc1ecb0e.png)

**Comment by youle31** [comment]
The comparison between upbge and bge for a single scene is not relevant because of the reasons I mentionned before. The scene must be adapted for upbge. The bisect can tell you if 1 specific commit has a performance impact on 1 single specific area (transparent alpha sorting, constant uniform materials, update scene graph on applymovement, change color management, use bullet 2.87 instead of 2.82............................). I close this issue because we can't find what ARE the reasonS why "this specific scene" is slower in upbge than in 2.79b.

**Comment by UglinessInTheUI** [comment]
Better close it because I can't find the solution either.
