### ISSUE TITLE
Antialiasing 16x gives the following error on RX580 and ruins performance 

### ISSUE THREAD

**Issue by UglinessInTheUI** [UPBGE/blender#1016]
Blender Game Engine Started
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
GPUFrameBuffer: framebuffer incomplete error 36054 'Incomplete attachment'
Blender Game Engine Finished

**Comment by Cotaks** [comment]
Already a know issue

**Comment by UglinessInTheUI** [comment]
Right , but with the latest AMD driver , version 19.2.2 , i get a completely different behavior now and no errors are displayed in the console of any kind , just a frozen game frame that looks like this 👍 

![2019 02 18-14 28](https://user-images.githubusercontent.com/12206146/52977323-13ab2f00-338a-11e9-8e33-1b042e03b4dd.png)

**Comment by Cotaks** [comment]
seems to me that your graphic card has some issues

**Comment by UglinessInTheUI** [comment]
It's definitely possible but i tried it with many games from Steam and Origin and i didn't find any issues in those. I never tried 16x AA before but still. In 2.79b works fine with 16x AA.

**Comment by UglinessInTheUI** [comment]
In UPBGE looks like this and there are no errors in the console. 

![2019 02 20-06 06](https://user-images.githubusercontent.com/12206146/53093930-fe431b80-34d5-11e9-8e43-381393922a16.png)

**Comment by Cotaks** [comment]
read this, it's on the main page: https://github.com/UPBGE/blender/issues/988
