### ISSUE TITLE
Timer, Gravity, Mass, Friction, Score, MLA, AA = Broken

### ISSUE THREAD

**Issue by UglinessInTheUI** [UPBGE/blender#1019]
Here is a broken benchmark for you guys to run and post the final scores. Run it in UPBGE and 2.79b if possible so we can compare both. In 2.79b , the timer is counting bullshit but not seconds. Gravity is also screwing around. Mass and friction are also pointless and useless. Mouse Look Actuator is also broken. Vsync not doing crap. Navmesh broken. Collisions broken when gravity is maxed. AA 16x broken. Anything else ? There's gotta be more. Make a full list of all broken items.

My score for 2.79b is :  1,933,196

PS :  For UPBGE set Gravity to zero and run it. No other changes needed. Timer seems to work better in UPBGE compared to 2.79b. Score is also going to be much higher because of that.

[Broken.zip](https://github.com/UPBGE/blender/files/2875383/Broken.zip)

![2019 02 18-05 02](https://user-images.githubusercontent.com/12206146/52949862-bcca3900-333a-11e9-80de-33ca0d405443.png)

![2019 02 18-05 57](https://user-images.githubusercontent.com/12206146/52952604-43cedf80-3342-11e9-8001-81c863dcb8ed.png)

**Comment by UglinessInTheUI** [comment]
Blender Game Engine Started

GPUShader: compile error:
Fragment shader failed to compile with the following errors:
ERROR: 0:4: error(#202) No matching overloaded function found: texture2D
ERROR: 0:4: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:11: error(#162) Wrong operand types: no operation "+" exists that takes a left-hand operand of type "default in 4-component vector of vec4" and a right operand of type "highp 2-component vector of vec2" (or there is no acceptable conversion)
ERROR: 0:11: error(#202) No matching overloaded function found: texture2D
ERROR: error(#273) 4 compilation errors.  No code generated

Blender Game Engine Finished

**Comment by Cotaks** [comment]
Your benchmark is broken big time lol.

i ran it till windows turned of my screen +-10 minutes, due to screen goes in sleep mode blender called the suspend scene option thus stopped benching.

results for 10 minutes in upbge:
![a broken benchmark test](https://user-images.githubusercontent.com/41304048/52955723-b44f1e00-338d-11e9-8d27-82991c9738cf.png)

- timer works correctly
- gravity works correctly
- mass and friction working correctly
- Mouse Look Actuator, hmm should work.
- Vsync not doing crap, depends on how you set it. and you driver settings.
- AA 16x broken, this is true x16 has some problems all other is fine

9.8 is normal gravity, what do you expect to get if you put it on 10.000? lol put physics substeps on a higher niveau you see that stuff is getting better. If you have problems up it let it do more calculations a frame to get more accuracy.

**Comment by UglinessInTheUI** [comment]
LOL. I think my Vsync is turned off in the control panel but the Mouse Look Actuator doesn't work if you save and reload your blend file. The errors must be from the shader or the custom GLSL 2D filter. Can you post your errors please ? Thanks.

PS: Set your power options to performance mode and disable screen going to sleep.

**Comment by Cotaks** [comment]
> PS: Set your power options to performance mode and disable screen going to sleep.
Hehe and let it run forever? in upbge spheres going offscreen, thus not getting rendered.

> Can you post your errors please
sure give me a few minutes

**Comment by Cotaks** [comment]
> Mouse Look Actuator doesn't work if you save and reload your blend file.

That can be, just saying it's broken doesn't help anyone, now you added the cause so they can take a look at it.

> Collisions should always work regardless of gravity settings

Not true, if you put gravity to high physics can't be calculated correctly, upping the physics substeps (should) solve this issue.


> AA is broken for all fast moving objects. All fast moving objects have no AA.
Now you added  a cause and they can look at it. is it so hard to add the cause right away in the opening post, just saying it's broken does not help anyone. But in this case no clue, actually never payed attention to it.

> GLSL filters are also broken

define broken

> I'm sure there has to be more.

Ooh i'm sure about this one as well ;)

**Comment by Cotaks** [comment]
mouselook works perfectly fine here
[mouselooktest.zip](https://github.com/UPBGE/blender/files/2876049/mouselooktest.zip)
works perfectly fine here

**Comment by UglinessInTheUI** [comment]
I set the margins pretty high on collisions. Come on man. Be realistic. The margins are already way too high. Collision should always work if enabled. At any settings. Without ridiculously high margins as they are right now. Same thing for camera clipping. You have to set the margins very high for camera clipping.

**Comment by Cotaks** [comment]
i always set margin at 0.001 had no issues so far.

> Collision should always work if enabled. At any settings.
As i said not true. 1. depends on physics type 2. depends on gravity settings, 3. depends on speed, 4 depends on physics calculation

**Comment by UglinessInTheUI** [comment]
OK , now , try this on your mouse look test and you will see it's not working properly with the following settings. 

1. Go to Scene and set FPS to 10,000.
2. In Scene settings change all sub-steps from 5 to 1.
3. Check to see if it's still working by pressing P in the 3d view. You will see lots of stutter.

**Comment by UglinessInTheUI** [comment]
True or False ? Yes or No ?

**Comment by UglinessInTheUI** [comment]
Come on man. You are not being realistic again. Did you try what i just said ? True or False ? Yes or No ?

**Comment by UglinessInTheUI** [comment]
How much time do you really need to test it and to try what i said ? You are not being realistic. I'm sorry.

**Comment by UglinessInTheUI** [comment]
Works fine with those settings or what ? The collisions also work fine when gravity is set to max and sub-step is set to 1. I told you are not being realistic. At all.

**Comment by UglinessInTheUI** [comment]
Anyway , thanks for bench-marking my broken file. I appreciate it.

**Comment by Cotaks** [comment]
Wow dude, chilout omg. can't be 24/7 at my pc you know, got things to do as well.

anyway here is my proof and now be friendlier! omg.
https://youtu.be/Ltr1kz18ry4

**Comment by UglinessInTheUI** [comment]
There must be something wrong on my system because I'm getting very bad stutter with those settings. Thanks for testing it.

**Comment by UglinessInTheUI** [comment]
Did you try to also disable Vsync ? Maybe it's from that. On my system the Vsync is disabled from the control panel.

**Comment by Cotaks** [comment]
No problem, it can be blender itself as well, try a fresh download/install maybe that helps

**Comment by Cotaks** [comment]
yes, i turned vsync off(else it caps at 75FPS for me) and frame limiter off as well

**Comment by UglinessInTheUI** [comment]
Damn. That means my system is broken in some way. Or the build that i downloaded. I will try other builds. I get very bad stutter from the Mouse Look Actuator. Only the script with 2 motion actuators works. Thanks anyway for trying it.

**Comment by UglinessInTheUI** [comment]
Could be the AMD driver screwing around again. It's not the first time nor the last.

**Comment by Cotaks** [comment]
i'm using 19.1.2

**Comment by UglinessInTheUI** [comment]
I will download the latest driver or latest beta and I'll try that one. I will let you know if it fixes the issue.

**Comment by UglinessInTheUI** [comment]
OK , i bet you had Vsync On in Blender in the Render panel , under System. Turn off the Vsync there and try it one more time. With Vsync On works ok but with Vsync Off it stutters like hell. I downloaded the latest driver and if i turn off Vsync in Blender it stutters like hell.

**Comment by BluePrintRandom** [comment]
If you create a new project in upbge you have these issues?

**Comment by Cotaks** [comment]
> , i bet you had Vsync On

look at the video, it's off.

**Comment by UglinessInTheUI** [comment]
It's the Vsync. There is the problem. If i turn Vsync off it stutters like hell the entire Mouse Look Actuator.

**Comment by UglinessInTheUI** [comment]
I'm using the 19.2.2 driver and it's doing the same thing if i turn Vsync off everywhere.

**Comment by UglinessInTheUI** [comment]
I will try to create a new project. Brb.

**Comment by Cotaks** [comment]
strange thing, can you try a resource of mine? https://blenderartists.org/t/first-person-movement-script-with-key-and-mouse-bindings/661842

fully scripted mouselook, does it stutter as well, or is it really only with the mouselook actuator?

**Comment by UglinessInTheUI** [comment]
OK here is a file that stutters 100% sure on my system. Try it and let me know.

[StuttersWithMouseLookActuator.zip](https://github.com/UPBGE/blender/files/2876740/StuttersWithMouseLookActuator.zip)

**Comment by Cotaks** [comment]
Sorry to say, works perfectly fine here

**Comment by UglinessInTheUI** [comment]
It's something on my system. If i turn Vsync On it works without stutters.

**Comment by Cotaks** [comment]
here to proof it to you: https://youtu.be/XbYyeLJKpDI

**Comment by UglinessInTheUI** [comment]
it's definitely something wrong on my system. With Vsync On works fine and with Vsync Off it turns in small increments like a very bad stutter.

**Comment by UglinessInTheUI** [comment]
I will definitely have to use your script because i like Vsync Off and it stutters like hell. Thanks you for those links and files.

**Comment by UglinessInTheUI** [comment]
So the GLSL 2D filters are broken for you guys as well. At least that's refreshing. LOL

**Comment by UglinessInTheUI** [comment]
I found a fix you guys. Unbelievable. Now it works properly with Vsync Off. God damn it. It took me forever to figure out something so simple. I had to go into the source code and modify line 80 from the file KX_MouseActuator.cpp to say false. Here is the code:

if (bNegativeEvent) {
              // Reset initial skipping check on negative events.
	m_initialSkipping = true;
		return false;
}

Just set the m_initialSkipping = false; 

And it finally works properly with the Vsync Off. God damn it. Wow. I can't believe this crap.

![2019 02 18-11 57](https://user-images.githubusercontent.com/12206146/52971373-75609e80-3374-11e9-915e-f07d4feff93e.png)

**Comment by UglinessInTheUI** [comment]
Can somebody narrow it down a little bit more the performance problem we are seeing in the Sim 003.zip example ? Maybe we can fix that issue too. We already know the bug is in the logic controllers and actuators somewhere. Some kind of similar amateur work in the code for sure.

**Comment by UglinessInTheUI** [comment]
There were definitely a few performance bugs introduced in the Ray sensor for sure by some amateurs but that accounts for only 4% of logic performance when turned off or disabled. Any ideas where the other performance bugs are hiding ? Anyone ?

**Comment by UglinessInTheUI** [comment]
18% of logic performance drop comes from the Property Sensor and the Track To actuator. So we should definitely start checking for bugs there. At least we figure out that much. For now.

**Comment by UglinessInTheUI** [comment]
Services seem to cause a lot of performance drop. Does anybody know where I find the "Services" in the C++ source code or what does "Services" mean ?

**Comment by UglinessInTheUI** [comment]
When i say Custom GLSL shaders used as 2D Filters are broken , I'm talking about this error right here:

GPUShader: compile error:
Fragment shader failed to compile with the following errors:
ERROR: 0:4: error(#202) No matching overloaded function found: texture2D
ERROR: 0:4: error(#160) Cannot convert from: "const float" to: "highp 4-component vector of vec4"
ERROR: 0:11: error(#162) Wrong operand types: no operation "+" exists that takes a left-hand operand of type "default in 4-component vector of vec4" and a right operand of type "highp 2-component vector of vec2" (or there is no acceptable conversion)
ERROR: 0:11: error(#202) No matching overloaded function found: texture2D
ERROR: error(#273) 4 compilation errors. No code generated

**Comment by UglinessInTheUI** [comment]
Also the Motion Blur Filter 2D doesn't work on my system.

**Comment by UglinessInTheUI** [comment]
Can anybody confirm about the Motion Blur Filter 2D ?

**Comment by UglinessInTheUI** [comment]
I'm glad that we fixed the Mouse Look Actuator. That skipping option was supposed to run only once , on Init only , but instead it ran every single frame completely killing the rotation. Thanks guys.

**Comment by Cotaks** [comment]
You should not even need to change the source, works correctly here so don't make a workaround but search for the cause.

**Comment by UglinessInTheUI** [comment]
I don't commit my changes. These are just local changes for me to play with. The cause is , on negative events it should do nothing but somebody modified the source code and broke it. That's what 2.79b is doing. I compared the files side by side. The cause is clearly in the code. It should not do any skipping in an update function. That's a one time only thing , it's supposed to do it only once when it initializes. On my computer it was skipping all the time , on every update , completely killing the rotation. But only when I turned off the Vsync. With Vsync On it was working fine. So , there is the cause. It's in the source code. Somebody modified the code and made it more buggy and slow. It's 4 times slower than 2.79b in that Sim 003.blend example.

**Comment by UglinessInTheUI** [comment]
I think i know why on your computer works ok with Vsync disabled. It's because you have Freesync On all the time even when you disable Vsync. Just connect a TV as a monitor that doesn't have Freesync ON all the time and you will see the problem on your computer as well.

**Comment by UglinessInTheUI** [comment]
The best score I got so far is this. When gravity was set to 30. Any ideas why ? 

![2019 02 20-04 46](https://user-images.githubusercontent.com/12206146/53090219-fda58780-34cb-11e9-8681-7b603b43e7d1.png)

**Comment by UglinessInTheUI** [comment]
Turn off FreeSync and also turn off Vsync and try again. Let me know.

**Comment by UglinessInTheUI** [comment]
True / False ? Yes / No ? What is it ?

**Comment by Cotaks** [comment]
Not true, if you don't know how freesync or a pc works then don't be a pain in the ass. If you watched the video you had the answer already.

**Comment by UglinessInTheUI** [comment]
The video showed FreeSync enabled.

**Comment by Cotaks** [comment]
watch again

**Comment by Cotaks** [comment]
and still read up on how freesync works, i had it off. and my freesync range is 30-75 fps so at 500 fps no freesync if it's on or not.

**Comment by UglinessInTheUI** [comment]
You probably have to restart the computer for FreeSync OFF to really take effect.

**Comment by UglinessInTheUI** [comment]
Could be a bug in the driver. You have to try it with a TV like mine. No FreeSync here.

**Comment by Cotaks** [comment]
Oh man, my butt hurts now, so i need to scratch my head. silly right?

OFF = OFF

**Comment by UglinessInTheUI** [comment]
Your adaptive sync is still going in the background. That's what it is.

**Comment by UglinessInTheUI** [comment]
I have a regular 55" TV as a monitor with no FreeSync and I'm telling you for sure that it stutters like hell when i turn Vsync OFF.

**Comment by Cotaks** [comment]
Man just admid that there is something wrong with eiter your pc / graphicscard and or driver.

I know what i'm talking about, so i won't respond anymore. Good luck finding out your problem.

**Comment by UglinessInTheUI** [comment]
I already found the problem and the fix in the source code. No problem. Does anybody else have this issue when Vsync is turned off ?

**Comment by UglinessInTheUI** [comment]
All my games run properly but without 16x AA. AMD doesn't support 16x AA for some weird reason.

**Comment by Cotaks** [comment]
@BluePrintRandom Test his file please.

**Comment by UglinessInTheUI** [comment]
Which file ? It's not the file. The issue is in the settings. Vsync + Freesync + AdaptiveSync need to be off everywhere for the problem to be visible.

**Comment by Cotaks** [comment]
> OK here is a file that stutters 100% sure on my system. Try it and let me know.
> 
> [StuttersWithMouseLookActuator.zip](https://github.com/UPBGE/blender/files/2876740/StuttersWithMouseLookActuator.zip)

this file

**Comment by UglinessInTheUI** [comment]
That file works fine if i set Vsync to ON. Only when I turn Vsync OFF then it stutters like hell. So yeah , we need somebody else to test that file but to turn Vsync OFF during the test. That should work.

**Comment by UglinessInTheUI** [comment]
Nobody ? Come on people cause it's a real issue. Anybody ? I know what I'm talking about. LOL. Preferably somebody who doesn't use any FreeSync or AdaptiveSync.

**Comment by UglinessInTheUI** [comment]
@BluePrintRandom come on man test that file cause Cotaks doesn't use a regular old style monitor. Please ?

**Comment by UglinessInTheUI** [comment]
Cotaks do you have an old style monitor or TV without any FreeSync ? Test it with that if you have it. Please.

**Comment by UglinessInTheUI** [comment]
FreeSync gets automatically turned on in the driver when you connect a compatible monitor so there is no way to turn it off. You have to use an incompatible monitor then it gets turned off automatically. Come on BluePrintRandom test this bullshit please. Where are you ? Don't sleep so much. We need you. ASAP. LOL

**Comment by UglinessInTheUI** [comment]
OK , here is the deal. I will pull out my RX580 and will use an old Nvidia GT 9500. Deal Cotaks ? Fair enough ?

**Comment by UglinessInTheUI** [comment]
But if i do that you also have to test it with an old monitor or TV that doesn't have FreeSync. Fair enough ?

**Comment by UglinessInTheUI** [comment]
Hey Cotaks , do we have an accord ? Deal ? Fair enough ?

**Comment by Cotaks** [comment]
what is so hard to understand?

freesync off = off.
freesync if on, it's range is between 30-75 fps(my monitor)
Any fps high or lower then it's off (even if the setting would be on)

> FreeSync gets automatically turned on in the driver when you connect a compatible monitor so there is no way to turn it off.

As i said you have no idea what freesync is or does or how it acts.

I can turn it off in the driver (watch the damn video) and i can turn it of in the monitor's OSD itself.

the blend hass 500 fps so its off no matter how i set the settings.

No deal, so have a good day.

**Comment by UglinessInTheUI** [comment]
OK , so i tested on a Geforce 9500 GT and if i turn Vsync ON it the rotation stops completely. It rotates in big stages. So yeah , my fix only seems to work for the RX580. With Vsync Off it rotates a little bit more nicely but it still stutters a little. So we are both right and wrong. It looks like on different video cards it gives different results. There is no proper way to fix it for all hardware.

**Comment by UglinessInTheUI** [comment]
Whoever needs a fix for the RX 580 8GB they can find it right on this page but the fix doesn't work at all for a Geforce 9500 GT. At least we figured out that much. Different hardware , different results.

**Comment by lordloki** [comment]
@uglinessintheui please stop flodding the issue. It is not necessary to send a message each 10 minutes to expose your issue

**Comment by UglinessInTheUI** [comment]
I closed it already. It seems only I have this issue. Nobody else seems to have this issue.
