### ISSUE TITLE
add Keyword args for scene.addObject and other methods maybe

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#102]
In some methods, we can write keyword arguments: eg: createConstraint(physicsid_1, physicsid_2, constraint_type, flag = 128) where flag is an optionnal arg in 10th position.

We could do the same for scene.addObject, no? scene.addObject("Cube", time = 100)

I didn't look at the sources for the moment. If you're ok I'll propose a patch.

**Comment by panzergame** [comment]
@youle31 : Look for PyArg_ParseTupleAndKeywords like in KX_GameObject::playAction, also here you will economize only one argument.

**Comment by youle31** [comment]
@panzergame : ok Thanks! I'll have a look :)

**Comment by youle31** [comment]
I had a quick look and tried but it didn't work.... As It was more by curiosity, I close the request... I'll eventually give it another try later.

**Comment by youle31** [comment]
oh, I just forgot something: works like that: http://www.pasteall.org/69405/diff

**Comment by youle31** [comment]
not really needed. It was more curiosity
