### ISSUE TITLE
Custom Filter 2D errors and issues on a RX 580 8GB

### ISSUE THREAD

**Issue by UglinessInTheUI** [UPBGE/blender#1020]
Blender Game Engine Started

GPUShader: compile error:

Fragment shader failed to compile with the following errors:
ERROR: 0:42: error(#143) Undeclared identifier: get_view_space_from_depth
ERROR: 0:42: error(#202) No matching overloaded function found: get_view_space_from_depth
ERROR: 0:42: error(#160) Cannot convert from: "const float" to: "highp 3-component vector of vec3"
ERROR: 0:71: error(#202) No matching overloaded function found: get_view_space_from_depth
ERROR: 0:71: error(#160) Cannot convert from: "const float" to: "highp 3-component vector of vec3"
ERROR: error(#273) 5 compilation errors.  No code generated

Blender Game Engine Finished

[SSAO.zip](https://github.com/UPBGE/blender/files/2885922/SSAO.zip)

**Comment by youle31** [comment]
This is not the right place to ask. I think you'd better to ask help to other bge users on bge forums about a 2D filter compilation issue
