### ISSUE TITLE
[Proposal] Change in the visual

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#1021]
in these last days I thought to improve the visual way UPBGE.

because in my opinion, we should stay in blender 2.79 and never change to 2.8, I do not know if some of you have any intention of sometime switching to 2.8

so since yesterday I'm changing some things and putting some things from 2.8 to UPBGE, and I think they're getting very interesting

and I wanted to share a little with you

![screenshot_20190224020259](https://user-images.githubusercontent.com/35436445/53295444-5762c600-37da-11e9-9feb-e38bcf1e36c4.png)

![screenshot_20190224020900](https://user-images.githubusercontent.com/35436445/53295433-3306e980-37da-11e9-9429-a77e37ed7270.png)

What do you think of the idea?
There are still some mistakes. but I still have to fix them.

anxious for answers

**Comment by UglinessInTheUI** [comment]
Are you adding python scripts or what are you adding from 2.8 ?

**Comment by EndSSgamesStudio** [comment]
@UglinessInTheUI I'm just changing a few things in the "Release"

![screenshot_20190224122731](https://user-images.githubusercontent.com/35436445/53301304-d6361e00-382f-11e9-8df7-00c952303664.png)

I'm getting things from 2.8 and putting in Upbge 2.79

How, Icons, Brushes among others...
