### ISSUE TITLE
Compound object child shape not updated when remove parent of child shape

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#1023]
@panzergame  - we could use your help fixing physics 
it's in master.

we are trying to figure out how to finish the release targets,
however this is a little tricky.

a bug crept in and we don't know the source really.

if you parent a child shape to a compound object -> remove parent the shape is not updated.

**Comment by marechal-p** [comment]
You should try to use a native debugger, place a breakpoint somewhere related to the parenting and then step through it to see what gets called and what doesn't.

I cannot help with this, but that would be the way to better understand the cause of this issue.

Visual Studio basic documentation:
https://docs.microsoft.com/en-us/visualstudio/debugger/quickstart-debug-with-cplusplus?view=vs-2017

I don't know how difficult it is to debug a program on Windows, but last time I tried running `gdb` on a debug build of `blenderplayer` I had nothing more to do than `gdb blenderplayer args...`.

**Comment by BluePrintRandom** [comment]
it's more like whatever manages parent / child releationships is not updating the physics setting on remove parent* - I have been digging through the source looking at recent commits trying to see what broke it and when*

**Comment by UglinessInTheUI** [comment]
Try switching it to Convex Hull and back. Maybe it forces it to update.

**Comment by UglinessInTheUI** [comment]
I'm here to help guys. Which C++ file deals with parenting and physics shapes ?

**Comment by UglinessInTheUI** [comment]
Look in "KX_GameObject.cpp" at line 3640. There is the "RemoveParent()". Just add a physics reset after that. Try to add "m_physicsController.reset();" after line 3640. Try that. I hope it works.

**Comment by BluePrintRandom** [comment]
https://github.com/UPBGE/blender/blob/e9b111834e8124428cf967deb665c1bf750e64c2/source/gameengine/Ketsji/KX_GameObject.cpp#L424

I added a printF here to see if removeCompoundChild was being called and it's not
https://snag.gy/naHk0b.jpg

**Comment by BluePrintRandom** [comment]
I solved it!
old code
```c
// Set us to the right spot
    m_node->SetLocalScale(m_node->GetWorldScaling());
    m_node->SetLocalOrientation(m_node->GetWorldOrientation());
    m_node->SetLocalPosition(m_node->GetWorldPosition());

    m_node->DisconnectFromParent();
    NodeUpdate();

    if (m_physicsController) {
        // get the root object to remove us from compound object if needed
        SG_Node *rootNode = m_node->GetRootSGParent();
        KX_GameObject *rootobj = static_cast<KX_GameObject *>(rootNode->GetObject());
        PHY_IPhysicsController *rootCtrl = rootobj->GetPhysicsController();
```

new code
```c
// Set us to the right spot
    m_node->SetLocalScale(m_node->GetWorldScaling());
    m_node->SetLocalOrientation(m_node->GetWorldOrientation());
    m_node->SetLocalPosition(m_node->GetWorldPosition());
    //here is the parent to check
    KX_GameObject * parent = static_cast<KX_GameObject *>(m_node->GetParent()->GetObject());
    

    m_node->DisconnectFromParent();
    NodeUpdate();

    printf("%s \n", "firing child remove");
    if (m_physicsController) {
        // get the root object to remove us from compound object if needed
        SG_Node *rootNode = m_node->GetRootSGParent();
        KX_GameObject *rootobj = static_cast<KX_GameObject *>(rootNode->GetObject());
        
       
       
        
        PHY_IPhysicsController *rootCtrl = parent->GetPhysicsController();
````

**Comment by marechal-p** [comment]
@BluePrintRandom make a branch with a commit holding your changes, and make a PR.

**Comment by UglinessInTheUI** [comment]
I don't really understand what was the bug. Something with compound objects and removing the parent but i still can't figure it out. Can you help me recreate your scene so i can see the bug first ? You should've included a blend file. I don't know how to recreate your scene so i can test it.

**Comment by BluePrintRandom** [comment]
I solved it already there is a pull request

**Comment by UglinessInTheUI** [comment]
That's really great that you solved it but i'm not sure how to recreate your scene. Everything i tried didn't show me any bugs. I only found a parenting bug like , when the child moves the parent moves with it. Which is wrong. The child is not the parent so it should not move the parent.

**Comment by BluePrintRandom** [comment]
The issue is that if you parent a shape to a object who is marked compound,
the physics shape is absorbed by the parent object

 (colliding with the child applies impulse to the root object and
collision.hitObject with the child will return the parent object)

When we remove parent on a compound child object, we must remove the child
shape from the parent mesh.
(this was broken by a commit to refractor the scenegraph)

The commit I pull requested checks the parent object to see if it's
compound, the bug was from the remove parent happening, and then it
checking the root object (which was now itself) instead of its parent.

**Comment by UglinessInTheUI** [comment]
OK but , that means that the bug that i found is completely different. Check this bug out. Just open the file , press P to run it and then press W to move the child and you will see that the collision shape for the child is not being updated.

[bug001.zip](https://github.com/UPBGE/blender/files/2922491/bug001.zip)

**Comment by UglinessInTheUI** [comment]
So the question is , how do we solve that bug ? How do we force it to update ? It's not updating the child shape.

**Comment by UglinessInTheUI** [comment]
From what i see it fails to update the child shape and it also fails to update the compound shape. That's a double bug right there. I tried to find the update function but no luck so far. Then i tried to introduce the NodeUpdate() in many different places and that didn't work either.

**Comment by BluePrintRandom** [comment]
Unparent child
Move /Rot child
Set parent

Each frame

**Comment by UglinessInTheUI** [comment]
Is that what you did in your modification ? Or that's what i have to do ? I don't understand. Did you see my example bug ? Is that a bug or am i doing something wrong ? I think it's a double bug. Not updating the child collision shape (1) and not updating the compound shape (2).

**Comment by BluePrintRandom** [comment]
that is how I update the collision shape of a actor
(I remove parent / reparent a bunch of shapes each frame)

it's much cheaper than rebuilding triangle mesh and works better.

**Comment by UglinessInTheUI** [comment]
I see. Well , if it works i guess it's OK. Did you get a chance to look at my file ? Any ideas how I can fix it in the code ?

**Comment by BluePrintRandom** [comment]
https://discord.gg/TPKBhpv
