### ISSUE TITLE
Eevee в BGE

### ISSUE THREAD

**Issue by zweryok** [UPBGE/blender#1025]
Do you plan to switch to Eevee render? Version 2.7 will disappear soon and 2.8 will remain

**Comment by BluePrintRandom** [comment]
https://github.com/UPBGE/blender/tree/eevee_merge8

https://github.com/lordloki/UPBGE-EEVEE

**Comment by zweryok** [comment]
Then I suggest that people lay out ready-made assemblies, let them be inferior, but people will know that the project has not died.
