### ISSUE TITLE
Vehicle Controller Physics [Question]

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#1029]
hi.
it would be possible to put two more rear wheels?
I'm trying to make a truck.

I created a script following this API: https://upbge-docs.readthedocs.io/en/latest/manual/editors/properties/physics_vehicle.html
but it is not as detailed as the BGE that was deleted, so I'm having trouble.

thanks.

**Comment by marechal-p** [comment]
https://pythonapi.upbge.org/bge.types.KX_VehicleWrapper.html

You can certainly add as many wheels as you want, I used to make planes using this API with 3 wheels: 2 fixed at the back and 1 with direction at the front.

Just add as many wheels as required, and look at the example blend file from your link.

**Comment by EndSSgamesStudio** [comment]
Thanks @marechal-p I'll take a look.

**Comment by EndSSgamesStudio** [comment]
ok!
I was able to put one more...

Something is happening, it has become very unstable, but I think I can solve it

![01](https://user-images.githubusercontent.com/35436445/54079023-96048000-42b2-11e9-9e49-5b7971be1562.gif)


![ScreenShot_20190309213753](https://user-images.githubusercontent.com/35436445/54079078-a6692a80-42b3-11e9-97ce-7c9850188937.png)

but I need 6 wheels, when I add the last one, it happens.

![ScreenShot_20190309211535](https://user-images.githubusercontent.com/35436445/54078944-dcf17600-42b0-11e9-8984-0d7fad02170f.png)

Do you have any idea what that might be? @marechal-p 

![ScreenShot_20190309212358](https://user-images.githubusercontent.com/35436445/54078988-b4b64700-42b1-11e9-934e-8f3661186b51.png)

**Comment by EndSSgamesStudio** [comment]
Ok.
I was able to solve.

![ScreenShot_20190309225357](https://user-images.githubusercontent.com/35436445/54079595-3f04a800-42be-11e9-8ee0-bee0081c1076.png)


thanks!
