### ISSUE TITLE
Sugestion: Using Properties as input to Logic Bricks Actuators.

### ISSUE THREAD

**Issue by HickySnow** [UPBGE/blender#1030]
`Hello,` not a programmer here, but I've being working with projects using the logic bricks system, I know its a long forgotten system, but I'm gonna give a try to draw attention to this question. I think it is really good system and with some little improvements it can achieve a way higher level of complex possibilities with them and should enhance much the power of the bricks system.
 
I have some few suggestions but I gonna tell the main idea first and see if we're rolling. 

The idea is simple: Ability to use variables (aka "properties") references, math and python operations syntax into bricks parameters fields. Example: Placing a Motion Actuator brick and instead of putting an static value in the motion parameter you can put an reference to a variable that can be controlled. this can simplify much the array of bricks used and expand the possibilities that can be done with them.

Illustrative Example Image: 
https://drive.google.com/open?id=1RXITQ5UV5i6ucUXw6DiEQLwYCYyH3jB-

**Comment by supermoaaa** [comment]
it's easy to do this in python logic brick is out dated I think it's better to work in modern node system

**Comment by BluePrintRandom** [comment]
this is a good idea in theory but the logic nodes addon now writes py for you in blender 2.8

and in pre 2.8 / you can use python to do this or the logic node addon.
