### ISSUE TITLE
texture shadow issues

### ISSUE THREAD

**Issue by vvhanxing** [UPBGE/blender#1031]
![shadow_issues](https://user-images.githubusercontent.com/33742233/55285171-cbcfec80-53b8-11e9-946f-453e7adf8220.gif

Hello!
I had a problem about transparent texture shadow issues.

I am using UPBGE V0.2.4
windows 10 64bit
Inter(R) HD Graphics 5500

**Comment by Carpynch0** [comment]
Material -> Game Settings -> Alpha blend : Alpha Clip

**Comment by youle31** [comment]
Looks solved when I see the emote. I close the report
