### ISSUE TITLE
 UPBGE.org site is not available

### ISSUE THREAD

**Issue by Frankjore** [UPBGE/blender#1032]
The UPBGE.org site is not available, it has disappeared

**Comment by marechal-p** [comment]
Duplicate https://github.com/UPBGE/blender/issues/637

**Comment by mauriciodelos** [comment]
Hi @marechal-p, it seems to be the same issue but the previous one was fixed a year ago. current issue is present in the site. I can't access either.

**Comment by marechal-p** [comment]
@mauriciodelos this is a recurring issue, the SSL certificate used by the UPBGE website has to be renewed every year. But apparently the website has been taken down for real now.

**Comment by BluePrintRandom** [comment]
twister showed up for like 4ms the other day, I wonder if the two are
related?
