### ISSUE TITLE
renderToTexture colors are not correct at all

### ISSUE THREAD

**Issue by Cotaks** [UPBGE/blender#1034]
Here a picture showing both bge and upbge, the colors are not what it should be at all in upbge, what causes this?

![darker rendertotexture upbge](https://user-images.githubusercontent.com/41304048/56081819-cdb29a80-5e11-11e9-80e9-8067e14380fa.png)

**Comment by BluePrintRandom** [comment]
Maybe it's not the same color space, maybe it's hdr?

**Comment by Cotaks** [comment]
> Maybe it's not the same color space, maybe it's hdr?
Hmm in blender and upbge it's on sRGB, but if i set the texture to linear in upbge the colors are good, but the background color is not being rendered.

**Comment by BluePrintRandom** [comment]
can you set the color space in the background scene? or is it the 'world'
background not rendering?

**Comment by Cotaks** [comment]
> can you set the color space in the background scene? or is it the 'world'
background not rendering?

no, there is no option there, also minimap scene has no world, i added it now it renders the background of it white and adds a strange border on the opposide direction when the background is being rendered, if there is only the map the wierd border is gone as well, but i still need to put the minimap texture to linear as well to get the right colors.

You can download the minimap from BA and see for yourself if you like.

**Comment by youle31** [comment]
if you use upbge 0.2.4, color management changed. You can try an earlier version to see if the problem is still there. Else I did builds based on last BF 2.7 master which don't include color management refactor: https://github.com/UPBGE/blender/issues/1041
