### ISSUE TITLE
How to download ?

### ISSUE THREAD

**Issue by yann2008ytb** [UPBGE/blender#1035]
We can't download it, it's mission: impossible...
How to download it ?

**Comment by marechal-p** [comment]
Right now one has to build from the sources, hosted on this repository. Maybe upload it then.

A good place for it, in my opinion, would be GitHub releases. What do you think?

**Comment by yann2008ytb** [comment]
It's a good idea

**Comment by yann2008ytb** [comment]
but have you a mirror link ?

**Comment by marechal-p** [comment]
I don't, @BluePrintRandom @shuvit-game do you?

**Comment by BluePrintRandom** [comment]
I have a copy of master from the end of march, win 64
https://drive.google.com/open?id=12PabAgmGK7X5huwDGrQorswc8vrJ9KI_

also have a linux 64 link to a build someone built for me on the discord
server.
https://drive.google.com/file/d/1I6mARTgL8G21GJk85HOfzoW7cW4jxFdH/view?usp=sharing

**Comment by yann2008ytb** [comment]
thx blueprint

**Comment by lordloki** [comment]
I have added last builds in a MEGA directory. Link is in upbge.org

**Comment by marechal-p** [comment]
I have been setting up a CI service to automatically build commits on master, as well as PRs.

https://github.com/bge-community/upbge/pull/1

Issue is: To attach the service I need to be administrator, so for now it is only on a fork :(
cc @lordloki

But you can get artifacts from my [last attempt](https://ci.appveyor.com/project/marechal-p/upbge/builds/24005922):
- Windows: https://ci.appveyor.com/api/buildjobs/lcg81hydx2edg60h/artifacts/build%2Fupbge-debug%2Fbin%2Fupbge.zip
- Ubuntu 16.04: https://ci.appveyor.com/api/buildjobs/7pu6t49stacisx5q/artifacts/build%2Fupbge.tar.gz

Please note that the links will expire in 6 months, I still need to setup the builds to upload to GitHub when we do releases, these will be permanent.

**Comment by lordloki** [comment]
I have put in place a new UPBGE website. Copy from Armory3d (its MIT license allow it)

**Comment by BluePrintRandom** [comment]
looks really nice!

**Comment by shuvit-game** [comment]
Thank you very much @lordloki .

**Comment by Frankjore** [comment]
Thank you very much @lordloki . The new page is very good but I am missing the donation section. I would like to contribute to the continuity of the project

**Comment by lordloki** [comment]
Hi @Frankjore . Thanks for the offer but it is very complicated to receive anonymous donations in Spain. I prefer keep way from them.

**Comment by BluePrintRandom** [comment]
maybe we can start a .org and have donations go to fund features? like the
BF?

maybe even get GSOC students some day?

**Comment by mziskandar** [comment]
This is sad.. I'm able to enter upbge.org.

**Comment by marechal-p** [comment]
@mziskandar Try again, it should work.

**Comment by youle31** [comment]
I close this report because there's a pinned message to download
