### ISSUE TITLE
Animation not rendering in 3d viewport

### ISSUE THREAD

**Issue by ThyQueen** [UPBGE/blender#1037]
UPBGE 0.2.4
Linux Mint 18.3 Cinnamon (64)

I wanted to make an object gradually disappear and I tried several options. In the end, I found that in 
MATERIAL/GAME SETTINGS
there is an **Invisible** option which does exactly what I want.
However, the object does become invisible in Play mode but I cannot see the result when
playing the animation in the 3d viewport (it's supposed to be smoke that eventually dissolves).
This means that I cannot check the quality of the animation.

Please, have a look at this brief video to see the problem in detail:
[Animation bug](https://www.dropshots.com/miracleshappensgoogl/date/2019-04-23/22:14:13)

I also tried animating the traditional BGE way (OBJECT/OBJECT COLOR/ALPHA) but I didn't get any result. 

In the Outliner, Restrict Rendering **does work** if used together with the Restrict Viewport Visibility but the object disappears all of a sudden and not in a gradual way.

**Comment by BluePrintRandom** [comment]
Check the transparency options in the material panel,

A gradual fade is alpha blend,

And animating object color is a good method, you can get noise from cycles
nodes and animate it for the fade also.

**Comment by ThyQueen** [comment]
Ok, I just found an old issue with a similar problem.
Basically, in Material/Game Settings
all the constant value must be unchecked, then everything works like a charm!
Not a bug but I think it would be a good idea to be pointed out in the manual for beginners like me.
