### ISSUE TITLE
Lights does not work with groups

### ISSUE THREAD

**Issue by UnidayStudio** [UPBGE/blender#1039]
If you add a lamp into a group and then instantiate the group, it will not work.

**Comment by BluePrintRandom** [comment]
This is a known limitation, instead use a list of lamps and free / check
them out

**Comment by marechal-p** [comment]
@UnidayStudio did you assign yourself to this issue because you want to fix it? :)

**Comment by UnidayStudio** [comment]
@marechal-p yes. I will investigate it.

**Comment by UglinessInTheUI** [comment]
How long is that investigation going to take ?

**Comment by BluePrintRandom** [comment]
UglinessInTheUI

a workaround was posted.

unless your doing it yourself, please try not to add crunch.

we do this for fun.

**Comment by UglinessInTheUI** [comment]
So what's the fix for it ? The workaround is not the fix I'm guessing.

**Comment by BluePrintRandom** [comment]
in glsl / forward render you can't have a instance of a lamp - there are
only so many 'fixed' pipeline lamps available anyway.

the workaround is to have a list of lamps, like a library where one can
check out a lamp, and when finished, return it.

this works quite well for me.

to go any further with lamps you will need to swap to a differed pipe,

**Comment by UglinessInTheUI** [comment]
I see. I was thinking that maybe there was a way to fix it in the source code. Obviously not. OK.
