### ISSUE TITLE
Upbge 0.2.4 *has a few bugs we need separate detailed reports on *

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#1040]
The new physics is worse than the previous one, or was poorly implemented.
she has a gigantic delay to calculate(0.2.4), extremely different from the previous(0.2.3)

Bullet 2 (Upbge 0.2.4 https://github.com/UPBGE/blender/commit/6fbb75a8115b8557b1cfe54ab7e3707719ac97c5)
![Upbge 0 2 4](https://user-images.githubusercontent.com/35436445/56857986-f2e2f500-6949-11e9-8812-d9c0824d109b.gif)

Bullet (Upbge 0.2.3b)
![Upbge 0 2 3](https://user-images.githubusercontent.com/35436445/56857999-1a39c200-694a-11e9-8eda-abf23e3a2e45.gif)

**Comment by BluePrintRandom** [comment]
AFAIK your not supposed to ever start the engine with intersecting bodies*

also the new bullet is able to be multithreaded / and soft body has many
new options.

about the behavior - have you tried a test where there are many object
spread out over a large area?

**Comment by Carpynch0** [comment]
Properties -> Scene -> Physics -> Physics Steps -> Substeps

**Comment by EndSSgamesStudio** [comment]
what I'm trying to say is that the new physics Upbge has some problems with very large projects...

when we press "P" on large projects it takes a few seconds or milliseconds for the game to start,
In this period, physics is not calculated👎, but logic is calculated👍, this makes dynamic objects and rigid bodies come out across the floor.

this is a serious problem for Upbge, we can not make great games without having problems with the new built-in physics.

We also have issues with tools we often use in games: Pathfinder, BlenderPlayer, World(KeyFrame), Stereo(Anaglyph), Obstacle Simulation and even the use of animations below 30Fps!

example: https://github.com/UPBGE/blender/issues/991 Error Still Working.
![51278730-3b286980-1990-11e9-9bf5-97516d38d699](https://user-images.githubusercontent.com/35436445/57005501-e27f8400-6bae-11e9-9021-fea7e4854bab.png)

My way I was planning to solve these problems would be
Get Upbge 0.2.3 source code, deploy most of Upbge 0.2.4 features, and analyze.

**Comment by UglinessInTheUI** [comment]
Collisions are also broken. If you make a scene where collisions repeat in a loop after a while the objects start to pass through each other and they completely fail to detect the collisions. But it takes a while and more than a few repeats to see it. It has tons of problems for sure.

**Comment by BluePrintRandom** [comment]
so, the new system has new default settings, and you will need to tinker to get the same results.

about object passing through other objects - what are you trying to do in game?

it sounds like your making a mess, and saying , man my mess is broken.

about pathfinding - I also noticed this behavior, and wrote my own pathfinder using A* based on redblobgames blog post, and made it a octree, and not only was it accurate it was quite a bit faster.

the built in navmesh does need to be fixed* however it's not super flexible anyway.

keyframe world - there is a option for static uniforms you have to uncheck.

- please refrain from dumping your issues in a big pile - 

open issues, and post clear reports and try and include simple test files.

**Comment by BluePrintRandom** [comment]
we should also bisect and find exactly when the behaviors became broken.

using git - and svn you can build upbge at older points.

**Comment by UglinessInTheUI** [comment]
No , i was trying to make a drum machine based on collisions but it didn't work.

**Comment by BluePrintRandom** [comment]
read about CCD @UglinessInTheUI

**Comment by UglinessInTheUI** [comment]
It's pointless. In 2.79b it worked better the drum machine file. I compared them side by side.

**Comment by BluePrintRandom** [comment]
Navigation mesh is still broken as far as I know, I will bump that issue and close this.
