### ISSUE TITLE
Creating Constraint in Runtime on Deactivated Dynamics

### ISSUE THREAD

**Issue by FredEmm** [UPBGE/blender#1043]
Creating a Rigid Body Constraint with Python between a Static and a Rigid Body with Suspended Dynamics causes a Crash.

[show.zip](https://github.com/UPBGE/blender/files/3166342/show.zip)

**Comment by BluePrintRandom** [comment]
ok don't do that*

I think you can set 'suspended' in a object as a prop when suspending it, and if it's suspended don't create the joint eh?
