### ISSUE TITLE
Actions/animations disapear

### ISSUE THREAD

**Issue by ThiagoMoraesGD** [UPBGE/blender#1049]
Some of my actions are gone when close/reopen blend file.

**Comment by BluePrintRandom** [comment]
You must check F for fake user

**Comment by ThiagoMoraesGD** [comment]
Ok, checked and work. Didnt know about this. Thanks.

**Comment by BluePrintRandom** [comment]
No problem, it's set up so if no armature is using a animation to ditch it
(pretty much every thing is this way - images etc)

adding a fake user is like saying "I want to keep this"
