### ISSUE TITLE
Near and Collision Sensor Brick Memory Leak

### ISSUE THREAD

**Issue by ethicalfive** [UPBGE/blender#1050]
I tracked down a memory leak that was filling up 7-8gb RAM and 7-8gb of virtual memory within about 8-12 hours of run time. I thought it was my code and after hours of checking every line, i discovered my code wasn't the culprit.

I included a couple of simple demos demonstrating the leaks.

Basically, spawn in 5-10 cubes each with a near sensor linked to an and(or python) block and blender starts noticeably eating RAM. Or 20+ cubes with a collision sensor start eating RAM but nowhere near as fast.

The specs of my machine are an i5 2500k + gtx660ti running on linux. I dont notice the memory leak until adding multiples of those cubes+sensors so you may need to spawn more cubes than me.

https://drive.google.com/open?id=1Wukd_vAZ9VdB6ye78e2qNGoDAtIDYXl1
https://drive.google.com/open?id=1g7o9DrbZIwzJiJKAJpL3SeufpjcfzLeC

**Comment by ethicalfive** [comment]
This memory leak is unique to the UPBGE, vanilla BGE doesn't suffer the same memory leak and it seems to have been introduced into UPBGE at least as far back as last year.

**Comment by ethicalfive** [comment]
Is it related to the implementation for the later bullet version? There are many problems with the latest implemention of bullet. I know the devs are retired now but the collision sensor is a fundamental component of the game engine that almost everyone uses rendering the latest release of upbge broken and it should be avoided unless rectified.

**Comment by BluePrintRandom** [comment]
try upbge 0.2.0 -> and keep moving up until you spot the bug again - we can
then try and get a finer bisect from there

**Comment by ethicalfive** [comment]
I dont have the time or data to track down the exact commits but I have supplied a SIMPLE test (still unverified by anyone), narrowed it down to the changes in the way those sensors get the collision information from other objects, which seem to be tied to the changes for the later bullet version.

Ive gone back to vanilla BGE and recommend no one use UPBGE in its current form until the serious memory leaks are addressed first. Who wants to work with a game engine that leaks like a seive with devs that could care less. Theres a few nice things in UPBGE but they're not worth memory leaks of fundamental components.

**Comment by rijnswand** [comment]
> Ive gone back to vanilla BGE and recommend no one use UPBGE in its current form until the serious memory leaks are addressed first. Who wants to work with a game engine that leaks like a seive with devs that could care less.

Development stopped quite a while ago, why are you even complaining?

**Comment by BluePrintRandom** [comment]
actually we have new test branches for a stable version of 0.2.4

0.2.3a  
and if you can fix it @ethicalfive  try to patch that would be great.
(I have been busy all summer but school starts in 3 weeks)

**Comment by rijnswand** [comment]
> actually we have new test branches for a stable version of 0.2.4

my bad, i had no idea and thought he was just screaming into the void.

**Comment by youle31** [comment]
The leak appears between 0.2.2 and 0.2.3. There are few commits to check related to Collision and Near sensors

**Comment by youle31** [comment]
The memory leak comes from this commit: https://github.com/UPBGE/blender/commit/e5bd8a54d12a187d2f593d64113c8ad4a1818dca

**Comment by youle31** [comment]
Fixed in ge_23a_youle: https://github.com/UPBGE/blender/commit/a7e0b11a64024375f148b7fcbe72c8497f4b88ea

This commit can be applied to any branch doing:

git cherry-pick a7e0b11a640243

a7e0b11a640243 is the hash of the commit.

I just reverted the problematic commit because when I tested to add some objects with a near sensor, I didn't saw the issue with collisionMasks. Anyway, as this memory leak is more annoying that an issue with collisionMask, I did that.

Test file:
http://pasteall.org/blend/index.php?id=52122

**Comment by youle31** [comment]
You can test one of these builds if you want: https://drive.google.com/drive/folders/1Kzj-4MN7EddvXXG5icDgdD7jUpDQsvIx?usp=sharing based on last 2.7 master. Else the leak appeared beween 0.2.2 and 0.2.3 then you can use 0.2.2 if you find it better
