### ISSUE TITLE
Why is there link to armory3d on upbge website?

### ISSUE THREAD

**Issue by BlackGoku36** [UPBGE/blender#1051]
Why is there link to armory3d on upbge website? is'nt armory3d enemy of upbge?
![image](https://user-images.githubusercontent.com/36535717/61180801-fc6f2580-a639-11e9-84a7-a41727cd750b.png)

**Comment by lordloki** [comment]
Armory3d is not an enemy. It is simply another software.

I put the link to armory3d as i take the website structure from them and i think that it would be a good reward.
