### ISSUE TITLE
Feature request: Logic Bricks settings and property

### ISSUE THREAD

**Issue by Trample-ingame** [UPBGE/blender#1054]
hi, i'm new around here but i used the blender engine for some years and now i'm working with UPBGE, i don't use script, i always use only the logic to do all i want, but there are limits that i can't solve with only logic.
So i'm here (and i don't know if i should ask here this) to ask if:
will it be possible to add an options in logic bricks to manipulate some values like (audio volume or pitch, or motion blur intensity etc...) with properties as we do in action frame?
and also option to add a bloom and his intensity directly from the 2D filter logic brick

**Comment by marechal-p** [comment]
cc @BluePrintRandom @UnidayStudio

**Comment by BluePrintRandom** [comment]
currently it's much easier to just do this in py.

if property changed---------this py----------your actuator 

```python
import bge
cont = bge.logic.getCurrentController()
actuator = cont.actuators['TheNameOfTheActuator']

actuator.volume = own['volumePropertyName']
```
here is the py api
https://shuvit.org/python_api/
search the actuator you want to affect, and look up what attributes you can adjust.


and adding more 2d filters is a good idea, but having them in the text editor templates with variables clearly identified up top is good too / documented 

(so you can just do -use template ->bloom etc.)
