### ISSUE TITLE
>> REQUEST -> list/array property

### ISSUE THREAD

**Issue by Cotaks** [UPBGE/blender#1055]
Would be great to have a list/array property.

If we set it though python, you can't use bricks to alter/empty it.
this allows us for easy debugging as well.

would be use full for logic brick users as well, they can then use the expression brick with it (i guess). 

my req would be to read it out, much easier then sending everything to a text object.

**Comment by BluePrintRandom** [comment]
we will close this for now - it's a great idea but there is quite a bit to do first
