### ISSUE TITLE
Sound Actuator Not Working

### ISSUE THREAD

**Issue by githubusernameunavailable** [UPBGE/blender#1056]
I am trying to make it so that when I click on an object, a sound plays (among other things). I have everything set up correctly (to my knowledge), but the sound just won't play. I switched all of the settings just to make sure something hadn't been changed from blender 2.79b, but nothing worked.
This is my logic set up for the object.
![Sound Fail](https://user-images.githubusercontent.com/55612174/65367707-b19dfb00-dbf2-11e9-8928-23386b45fdb0.png)

**Comment by BluePrintRandom** [comment]
does the object have a collision bound ?

if you can't get it working, append just the speaker to a new blend and I will test for you

**Comment by githubusernameunavailable** [comment]
So, I later discovered that it does work, but only after UPBGE has been restarted (closed and reopened). This has been consistant for every project I have started in UPBGE. It can be quite a pain to have to close the program every time I add a sound, just to test if the volume is right!

 

Also, there have been weird things going on with the collisions. When I use the normal motion actuator, using the location function (let’s just say I was moving a cube forward), when the cube bumps against a wall, instead of just sitting there, it rebounds off of the wall over and over, sometimes crawling up on the wall!

Furthermore, if the cube is going at a moderately fast pace, it often just pushes through other objects as if they are not there. This also happened in the original blender 2.79, but I am wondering if you guys can fix it, or if I am doing something wrong.

 

Thank you so much for circling back to me on this!

**Comment by BluePrintRandom** [comment]
when things seem corrupt / not working correctly, it usally helps to append them into a fresh empty .blend 1 layer at a time using groups 

this tends to fix everything for me*
it can be caused by going between versions of bge / upbge
