### ISSUE TITLE
Finish linking up BL_action.cpp so blending etc works in 0.3.0

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#1059]
currently Bl.action.cpp is unfinished for upbge 0.3.0

https://github.com/UPBGE/blender/blob/eevee_merge8/source/gameengine/Ketsji/BL_Action.cpp?fbclid=IwAR1l-l6yhanHjbiZ2bRTHOkWUFFZFSfRnZxw5Tu2sPwuAJoLUC14_UUaGpY#L424

animation data moved in 2.8 breaking some pointers.

animation influence now lives at
BPYObject.animation_data.action_influence

**Comment by youle31** [comment]
It should work now, but the issue with spaw armtured objects is still there

**Comment by youle31** [comment]
I note this commit: https://developer.blender.org/rBfe05f97841c0ee3e2a6e15f2252ad160fefc3509
to try to see what was done about armatures replication

**Comment by BluePrintRandom** [comment]
thank you youle I have been using armatures recently

I noted - cont.decativate(cont.actuators['AcutatorName'])) does not work
but armature.stopAciton(layer) does

**Comment by youle31** [comment]
It seems to work for me in this file:

http://pasteall.org/blend/index.php?id=52554

(spacekey to play, S key to stop)

This requires to compile last upbge0.3 to test (it is a shapekey action).

According to play action method (PING_PONG, LOOP_STOP, PLAY....), the behaviour is not the same, but it seems to work...

**Comment by BluePrintRandom** [comment]
Thank you @youle31 everything appears to be working correctly !
