### ISSUE TITLE
0.3: Issues since VideoTextures module restore

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#1062]
test file: https://drive.google.com/file/d/1gFqw1F-qDgcYyO1HZ47weHwTDP4H1dx8/view?usp=sharing (4thJuly)
Backtrace: 
![4thJuly](https://user-images.githubusercontent.com/10052509/66291536-6ec26f80-e8e2-11e9-987d-d9a4884418f1.PNG)
steps: press P then exit

I'll add other example files later

Notes: The VideoTexture module is not used but I have crashes with the patch which restore VideoTextures module and no crash without. Maybe something is wrong with FreeAllTextures? Or with the change in ge_common? idk

patch to revert VideoTextures:

https://drive.google.com/file/d/1-HtAXV8c_hgUJuH0Rx9QL4XjWn6Gytap/view?usp=sharing

path to apply VideoTextures:

https://drive.google.com/file/d/1abcEQsLWkBjRUZvjOqUPqhGmoRQK6Dd9/view?usp=sharing

**Comment by lordloki** [comment]
I will check it later.
Maybe instead of delete totally the #define nullptr 0 we can change it by
'''#ifndef __cplusplus
static const void *nullptr = 0;
#endif'''
or something similar. 

Thanks for report.

**Comment by nestanqueiro** [comment]
Hi all, Thank you for trying to get this back working... I also tried it, but it crashes as soon as bge starts. just a simple ffmpeg video (segfault)... I can report in more detail or try more things to help debug... 
thanks

**Comment by youle31** [comment]
I add this test file: https://drive.google.com/file/d/1c3F45KpJr35RnIhluWCv9kzHEAPln3H8/view?usp=sharing (spiral stairs) which doesn't seem to cause issues when vieotexture module is not there but which causes weird crashes related bpy sometimes when videotexture module is here

**Comment by youle31** [comment]
I close this as this is known issue now
