### ISSUE TITLE
bpy.data.objects['ObjectName'].select_set() - fails silently 

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#1063]
trying to use ops in game I get - bpy.data.objects['ObjectName'].select_set() - fails silently 
```
bpy.data.objects['ObjectName'].select_set(True)
print(bpy.context.selected_objects) 
```
prints "[ ]"  after the command is called
unlike in python console where it prints

[ BPY_OBJECT[objectName] ]

**Comment by youle31** [comment]
It is working for me: http://pasteall.org/blend/index.php?id=52438

And you don't provide any example file + I don't accept bug reports (this is too experimental).

If lordloki or a dev wants to reopen it he can

**Comment by BluePrintRandom** [comment]
https://drive.google.com/file/d/1Udc6czVPTYrj7c5OzE9iIRDm6_7f7Swh/view?usp=sharing
here is it not working in bge


https://drive.google.com/file/d/1RSo4LgS1woxDtfcKdrm4WQ7IaMgHmTwV/view?usp=sharing
here it works in bpy / run script (operates on selected)

**Comment by youle31** [comment]
imo it is your usage of bpy which is not good, as I have it working in my file + this is bpy, not related to the gameengine, then there is no reason to have such report in our tracker + I don't accept bugs reports for my branch.

**Comment by youle31** [comment]
As I already said, i don't want that people come here, give us work whereas we work for free. If you have an issue, solve it

**Comment by BluePrintRandom** [comment]
I investigated it, but I don't understand what you did in the first place to get bpy working*

there is no docs to look through just source.

can you point me in the right direction?

**Comment by BluePrintRandom** [comment]
https://github.com/BluePrintRandom/Compound_merge_prototype  - solved
