### ISSUE TITLE
Python Component initialisation 0.3

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#1068]
I was doing random tests to try to initialize a python component with a fresh file created in 2.8, and with luck, I had it working picking code from KX_PythonInit:

- Patch: https://pastebin.com/cycGppQy

- Test file: http://pasteall.org/blend/index.php?id=52520

**Comment by youle31** [comment]
This magic code works also for VideoTextures to fix crash when we create a videotexture:

patch: https://pastebin.com/MUQ9f8e4

test file: http://pasteall.org/blend/index.php?id=52521

**Comment by youle31** [comment]
In fact in last master ge_videotex seems to not crash even without the lines i added... sorry

**Comment by lordloki** [comment]
@youle31 for me python component code continues crashing.
But if you pass the `state = PyGILState_Ensure();` just after Initthreads it works ok.
```
    /* Initialize thread support (also acquires lock) */ /* Needs later revision UPBGEXXX */
    PyEval_InitThreads();

    state = PyGILState_Ensure();

    bpy_import_init(PyEval_GetBuiltins());
    bpy_import_main_set(maggie);
```

Could you test this way?? Thanks in advance

**Comment by youle31** [comment]
For me it is working just adding these 2 lines:

https://pastebin.com/8tnRaqK2
