### ISSUE TITLE
Export to game engine (add-on) not appearing in the export menu

### ISSUE THREAD

**Issue by Gorgo13** [UPBGE/blender#1070]
Hi there!

I've just installed the "Import-Export: Save As Game Engine Runtime" add-on, restarted the app, but the export option does not appear in the "File> Export" menu (see attached picture).

![UPBGE-EEVEE-Win64-2019-10-21_export_to_runtime](https://user-images.githubusercontent.com/37718864/67940492-0f4f3b00-fbd4-11e9-855e-85686d7d1d2e.png)

Thanks.
G13

**Comment by youle31** [comment]
hi,

fixed in https://github.com/UPBGE/blender/commit/63d48c61703e9992bfa00823ba5de3e4a0df8060

**Comment by youle31** [comment]
(if you want, you can search the save as game runtime with search menu (spacebar or F3))

**Comment by Gorgo13** [comment]
Great, thanks!
