### ISSUE TITLE
Cutscene Issue under BGE 2.8

### ISSUE THREAD

**Issue by rgggg50** [UPBGE/blender#1073]
BGE apparent has a problem with API interface with the video calls.  UPBGE can still video edit a normal video file.  However, when I use the standard code available on Youtube.  It has a problem which is associated with newly complied version of blender. 2.7X first of the series.  It does still work with 2.79 version.  ht
![New Bitmap Image](https://user-images.githubusercontent.com/37917130/68406286-699d4e00-0136-11ea-8fcc-32cf3a6f09ed.jpg)

tps://www.youtube.com/watch?v=P2W_fQayYcA

**Comment by nestanqueiro** [comment]
Are you refering to UpBGE3.0 or 2.4? The workflow on 3.0 is actually beeing restored, and some functionality is already in place... ffmpeg video does work thanks to great effort put on this by lordloki 

in 3.0 make sure you have an object with a material with some texture (preferably connected to emit, base color set to black, and Specular and Roughness to zero)...

in logic panel, attach an "always" with pulse mode active to a python controller, and set it to Text.refresh

create a new Text and paste the following code, ajusting the path/to/file, respecting the direction of the slashes (copy paste in windows won't work)

```
import bge
from bge import texture

cont = bge.logic.getCurrentController()
scene = bge.logic.getCurrentScene()
own = cont.owner

own["tex"] = texture.Texture(own, 0, 0)
own["tex"].source = texture.VideoFFmpeg('C:/path/to_any/video_file.avi')  #note the direction of the slash
own["tex"].source.play()
own["tex"].source.framerate = 1.0
own["tex"].source.repeat = -1


def refresh():
    
    own["tex"].refresh(True)
    bge.logic.getCurrentScene().resetTaaSamples = True
     
```

And that's it... good luck

**Comment by BluePrintRandom** [comment]
I will mark this as solved
