### ISSUE TITLE
Upbge 0.3.0 - restore timer in the material node editor

### ISSUE THREAD

**Issue by RomStef** [UPBGE/blender#1077]
Is it possible to restore the timer node in the material node editor as the old versione of upbge ?

**Comment by youle31** [comment]
idk if someone is interested to work on this but if you want there are several ways to use "time" in shader node editor.

1. Python:

import bpy

material = bpy.data.materials["Material"]
node_tree = material.node_tree
nodes = node_tree.nodes
musgrave = nodes["Musgrave Texture"]
musgrave.inputs["Scale"].default_value += 0.1

I hope i remembered correctly the API.

2. Action actuator.

In the timeline, on frame 1 press i on a value in shader notree.
Go to frame 30.
Change value and press i again.
Add an action actuator, and play Shader Nodtree action.

**Comment by BluePrintRandom** [comment]
musgrave and a few others also have a 4d mode now*

you can set a time offset -> even make it loop

**Comment by BluePrintRandom** [comment]
https://wiki.blender.org/wiki/User:OmarSquircleArt/GSoC2019/Final_User_Report

**Comment by RomStef** [comment]
Thanks for the reply, i will try
