### ISSUE TITLE
HUD elements disappear when viewing a negative-scaled object

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#108]
Working in BF 2.7, broken since UPBGE 0.0.6 or older

Framerate and Profile, text objects, and bgui elements all disappear when a negative-scaled (aka mirrored) object is in the camera view.

Example:  http://www.pasteall.org/blend/41879

**Comment by youle31** [comment]
good in v0.0.4, bad in v0.0.5.... I check gitk

**Comment by youle31** [comment]
void KX_GameObject::UpdateBuckets()
{
	if (GetSGNode() && m_meshUser) {
		if (GetSGNode()->IsDirty())
			GetOpenGLMatrix();

		m_meshUser->SetColor(m_objectColor);
		m_meshUser->SetCulled(m_bCulled || !m_bVisible);
		m_meshUser->SetFrontFace(!m_bIsNegativeScaling);
		m_meshUser->ActivateMeshSlots();
	}
}

m_meshUser->SetFrontFace(m_bIsNegativeScaling); solves the issue in the .blend

**Comment by panzergame** [comment]
Fixed in 9dda417bf081206cde77c5a81fae13beff81d99a.
