### ISSUE TITLE
Text objects from linked groups rendering where they shouldn't

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#114]
When linking a group containing a text object, the text will always render on the original layer/location regardless of where the instances are placed.

Example: https://dl.dropboxusercontent.com/u/19279604/temp/textlink.zip

I tested UPBGE master (hash d009b36) all the way back to Blender 2.57, so it's probably been around since the inception of modern-day text objects.  A simple workaround is to save the original object in a layer that's not visible in-game.

**Comment by panzergame** [comment]
The bug is created by the fact that every fonts object are rendered (active + inactive).

**Comment by panzergame** [comment]
Fixed in 7038db28fa6715915235df06a075d1a8f5282dd8.
