### ISSUE TITLE
[Solved]Arch linux v0.0.7 build error

### ISSUE THREAD

**Issue by alabd14313** [UPBGE/blender#115]
Hello friends!
I have an error in Arch Linux build:
[error.txt](https://github.com/UPBGE/blender/files/276268/error.txt)

**Comment by panzergame** [comment]
" internal compiler error: Segmentation fault", is not due to the source compiled but more by the compiler or your system. I very don't like this error message because the last time i saw it my RAM was dead. @alabd14313 : Check your memory with memtester.

**Comment by alabd14313** [comment]
Thx! My problem solved.
Here is Arch Linux binary:
[UPBGEv0.0.7(2.77).tar.gz](http://www.mediafire.com/download/f5lu7l5r56djf6i/UPBGEv0.0.7%282.77%29.tar.gz)
