### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by alabd14313** [UPBGE/blender#116]
As we see during last months ago, there is not any attempt in [developer.blender.org](developer.blender.org) to solve BGE bugs.
Do you agree to commit UPBGE as a whole to upstream (main blender git)? It can be a good start for blender 2.78 (eventually 2.8).
UPBGE can continue it's work in this fork. May be it solve some BGE problems (specially paid developers cold view to game engine).

**Comment by youle31** [comment]
Hi! The problem is that we changed not only bge code but viewport code too (as bge use a part of the viewport code) and I'm quite sure the modifs we made in the viewport code wouldn't be accepted/approved by the blender official developers... And I'm not sure the changes made in bge sources would be approved too :/ Maybe I'm wrong.

**Comment by panzergame** [comment]
@alabd14313 : As you saw the BF (and developer with) don't have time to review the current BGE patch waiting. Then how it will be possible that they review an entire fork ? Also i will not use the authority argument.

**Comment by alabd14313** [comment]
Finally, BF must pay costs of this work. My be your changes in viewport code isn't very hard to other developers adopt their work. They must remember that they said: ""
I regret that a useful engine have a bad days, because of disappointed developers. I do not expect from BF, Cycles, VSE uses to support BGE, as most of theme agree to drop BGE from blender.
Ogre, Panda3d, and so on have their features, bust BGE has features that many of those engines lacks. Even more I see BGE, I can't see any huge difference between it and Unreal engine.
I like it's GPL license.
As I said before, BGE has bugs => So BGE is alive!
I'm sure when blender drop BGE, It also will drop all of it's other components one by one.
Please see LLVM how absorb Two Tyshh free developers. because they don't know difference between free and open source: 
Believe it that there is not any huge distance between BGE and luxurious engines...
Thanks you because of your work in this fork.

**Comment by Akira1San** [comment]
My personal opinion is that. The devs that left; Moguri and Kupoman want to drop the bge and replace it with Panda3d. Thats why they are working on a plugins: https://github.com/Moguri/BlenderPanda and https://github.com/Moguri/BlenderRealtimeEngineAddon 
That will permit to run panda3d inside blender viewport in the same time adding an external game engine. :)

**Comment by youle31** [comment]
discussion finished. I do clean up so I close
