### ISSUE TITLE
Ingame api to increase/decrease level of detail distance?

### ISSUE THREAD

**Issue by Maujoe** [UPBGE/blender#120]
One thing that I miss for the lod-system since it was integrated is api that allow to adjust the distance ingame.
In my opinion that would be a nice thing because it would gives the opportunity to make ingame options for adjusting the proportion between graphic and performance.

It could look something like this:

A global value for the whole scene that will multiplied with the distance value of the lodlevels.
for example:   scene.lod_scale(value)    or   scene.lod_scale = value  

For detailed options there could be a function in the object to set the distance of the lodlevels directly (not so importent but would a nice extra)

**Comment by panzergame** [comment]
@Maujoe : A python api for lod is planed in 0.0.9

**Comment by panzergame** [comment]
oups, closed sorry :/

**Comment by Maujoe** [comment]
Thanks, that's good news :)

**Comment by youle31** [comment]
Hi! @Maujoe : Would you be interested to try to implement it with my help? (If you are interested to begin with blender sources coding). I don't know lod but this kind of stuff sounds pretty nice to begin.
Connect to #upbgecoders if you want and I could help both to build upbge and begin with code sources (we can use team viewer (screen sharing program so I can show you))

**Comment by youle31** [comment]
@Maujoe : I prepared the terrain: https://github.com/UPBGE/blender/commit/4d46e43ac01e5bd3a07007a47f1badbe96f1b463

So if you want to experiment things you can make tests with this branch.

**Comment by BluePrintRandom** [comment]
this is also essential for zoom scopes, and binoculars, or sometimes even
for story telling,

**Comment by Maujoe** [comment]
@youle31 Thanks youle,
I'm interested to become more familiar with this kind of things but the next 1-2 weeks I must spend for a exam. Another problem could be language and my programming skills but I will see.

**Comment by youle31** [comment]
@Maujoe : Ok, no problem, feel free to join #upbgecoders on IRC (freenode) if you want later.
So I'll write the API like that at KX_LodLevel (this means for each lod level you couls get/set or only get the following attributes:

1) Get:

- meshName (not really needed as the level name is the meshName...but the method is already implemented so...). This could eventually be used with replaceMesh python method (don't know if it can be useful)
- distance
- hysteresis
- useHysteresis (bool to see if hysteresis is used)

2) Set:

- distance
- hysteresis

@panzergame and @Maujoe: Are you ok with this API and with the chosen names?
Do you think other method would be useful at KX_LodManager level?
(KX_LodManager class contains the list of all lod levels so you can implement python methods that affect all the lod levels for a KX_GameObject. So instead of set the attributes in KX_LodLevel (for only 1 level), you can iterate in lod levels list and set attributes for all lod levels). We can do that in the sources or the user can use a for loop in python: for level in gameobj.lodManager.lodLevels: ...

**Comment by Maujoe** [comment]
@youle31 Yes, I think thats good.

**Comment by BluePrintRandom** [comment]
what about a generic level of detail, and you can push the level of detail
level out/in for all objects without iterating?


like

scene.modAllObjectsLod(-10)

or

scene.modAllObjectsLod(+10)

**Comment by youle31** [comment]
@BluePrintRandom : Hi, the thing is that this API to set lod levels distance for a/some KX_GameObject won't be used "each frame" I guess. I guess this can be used on some event only 1 time. So I think doing a for loop in python at this moment is not an inconvenient.
You could find specific cases where it could be useful but it's very specific... I guess.
So I don't want to implement setting lod in real time for a group of gameobjects unless there is a very good reason to do so. 

(I already implemented set all levels distance for a gameobj at the same time...)

**Comment by BluePrintRandom** [comment]
using a zoom lens on a gun,

binoculars,

zooming in with a camera etc,

what about the modifier being true/false?

every lod level = old level+(modifier)

not using is = old level+0

**Comment by youle31** [comment]
Indeed, this sounds a good reason.

@Maujoe: Is this for this kind of stuff that you wanted a LOD API?
@panzergame and @DCubix : what do you think? In KX_Scene, could we create an API to allow the user to make lists of gameobjects with the same property for example... std::vector<KX_GameObject *>m_customGameObjectList[50]. Each time the user wants to create a fast list, we create m_customGameObjectList[0], m_customGameObjectList[1] and then we implement some python methods for this custom lists written in c++.
like: 
- create(m_customGameObjectList index, pythonObjectList) m_customGameObjectList[index] = converted pythonObjectList (I don't know if a conversion is needed)...
- setLod(m_customGameObjectList index) for ob in custom list ->setLod

and other methods... I don't know if it's feasible. I'm wondering if this could speed up the big lists management that is slow (I think) in python.

**Comment by panzergame** [comment]
I'm not fully agree to create multiple custom lists…

About the lod distance scale, what about a setting per lod manager and per camera ?
e.g:
```
gameobj.lodManager.distanceScale
camera.lodDistanceScale
```

What do you think ?

**Comment by youle31** [comment]
@panzergame : Hi, gameobj.lodManager.distanceScale is already implemented.

About camera.lodDistanceScale, this seems a bit weird as the "tree of inheritance" is:

KX_LodLevel->KX_LodManager->KX_GameObject.

I made a list of object in KX_Scene as KX_Scene contains a list of KX_GameObject.

But if you think it's dangerous, I'll remove that.

Ohh, I think I've a better idea: make the lodLevel.distance depend on KX_Camera.lens whatever happens. I'll think about it.

**Comment by panzergame** [comment]
@Maujoe : the `camera.lodDistanceScale` should normally be only to multiply the lod distance in lodmanager. Why ? : if you use two camera for the screen you will certainly want an independent lod distance, also this can be very useful for ImageViewport e.g rendering the scene with a very low lod distance.

**Comment by Maujoe** [comment]
Yes, thats sounds perfect! That's a very good idea :)

**Comment by youle31** [comment]
@panzergame : but I don't understand, lodManager belongs to a KX_GameObject. Each KX_GameObject has its own LodManager. So we need a list of KX_GameObjects to apply LOD settings for this KX_GameObjects... Is there already a list of objects in the camera field of view for which we could apply a LodObjectScale?

**Comment by panzergame** [comment]
KX_LodManager is shared between game object currently.

**Comment by youle31** [comment]
? I'm not sure...

cf BL_BlenderDataConversion:

KX_LodManager *lodManager = lodlist_from_blenderobject(ob, kxscene, converter, libloading);
		gameobj->SetLodManager(lodManager);

each KX_GameObject has its own KX_LodManager: in KX_GameObject: m_lodManager

So there is 1 instance of KX_LodManager per object KX_GameObject

**Comment by panzergame** [comment]
Yes, unshared for original objects (because they are unique) but it will be shared for added objects.

**Comment by youle31** [comment]
yes... So I don't know how to deal with that for the moment...

**Comment by youle31** [comment]
So finally I found a solution that is good in my opinion. Here is the final commit message for the ge_pylod branch:

- KX_LOD is refactored in 2 files: KX_LodManager (each KX_GameObject has
  its own LodManager that contains a list of all levels of detail) and
  KX_LodLevel that contains the attributes of each level of detail.

- A new python API is created at several levels for more control:

1) KX_LodLevel: you can set the attributes of a single level of detail
(distance, hysteresis) and get infos about this level of detail (the mesh
name used for this level of detail, and if this level of detail use

hysteresis override option.
2) KX_LodManager: you can set the distance of all levels of detail
contained in levels of detail list for a specific KX_GameObject. An
3) KX_Scene: A method setLodScale(PythonObjectList, scale) is implemented.
This way, the user can create his own lists of KX_GameObjects with LOD
and pass his list of KX_GameObject to the function and apply a scale to all the list.

If KX_GameObjects are added during runtime, they will share the same
instance of KX_LodManager than the original object but the distance to the
camera of this object won't be the same so there is no problem I think.
When he adds objects (trees for example as I have a lot of imagination),
he can append this objects to its initial list of trees and when he remove
trees he can pop the trees from his list. So he manages his lists as he
wants. The better is to do small lists of course.

So I think that no one will use this API but I was happy to do it
nevertheless.

**Comment by Maujoe** [comment]
@youle31 Thanks that you spend your time for this feature. Yes it would be nice when you (or someone else) could make me a build for windows. 
I'm not sure if I understand everything correctly that you explained above but when I have a build I can test it myself and see if there's some trouble. 

I also can try to make a better testfile if you want.

**Comment by youle31** [comment]
@Maujoe : I'll make changes suggested by panzergame before I post a build. I'll inform you.

**Comment by youle31** [comment]
Here is the build win 32: https://drive.google.com/file/d/0B3GouQIyoCmrcjVvM2M0T2ZvSW8/view?usp=sharing
And my test file for last API with camera: http://www.pasteall.org/blend/42173
All current API is is .rst files on this branch: https://github.com/UPBGE/blender/pull/121/files

This API is not definitive. I seen that panzergame opened a new branch about lod so it can change.

**Comment by Maujoe** [comment]
Thanks, I have tested it a little bit and I think it works good and it's very useful
I will use it definitely and when it's finished I think I will make a demo scene to show this.

**Comment by BluePrintRandom** [comment]
fallout 4 sniper rifle :D

**Comment by panzergame** [comment]
Done.

**Comment by BluePrintRandom** [comment]
Thank you Tristan!
