### ISSUE TITLE
Text not rendering in one exact blend

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#123]
In one .blend file the text is not rendering in game. There's just nothing at the place of text. Even more - the profiler and debugger don't show up. I enable them, but there is nothing on screen when I run game. This occures in UPBGE-only. I can't share the .blend(there're reasons). Unfourtunately, I couldn't reproduce the issue. However, I think that this is major bug and must be solved ASAP. I have shared the .blend to panzergame only. Hopefully he can do something for this.
Thanks! :smile:

**Comment by panzergame** [comment]
@adriansnetlis : Can you compile a UPBGE version yourself since i have some troubles with the buildbot ?

**Comment by adriansnetlis** [comment]
Yes, of course. ;)

**Comment by adriansnetlis** [comment]
It's fixed in the latest version, I'm not sure where, though:D
