### ISSUE TITLE
Apply modifiers at game start.

### ISSUE THREAD

**Issue by lordloki** [UPBGE/blender#127]
To avoid any issue with the modifiers and to assure that the performance be maximum then it would have to exist an option to apply all the modifiers during the process of launch the engine.

**Comment by youle31** [comment]
Yeah, it would be very cool. And some modifiers doesn't work with the bge.

Maybe we could look at bpy API and at the console when we apply modifiers: http://www.pasteall.org/pic/103875

I don't know if we can view the commands used when we make undo (ctrl+z) to write the undo script at engine exit.

**Comment by panzergame** [comment]
@lordloki : Do you have time and motivation to investigate on ?

**Comment by lordloki** [comment]
Yes, I will chek.

**Comment by youle31** [comment]
this: http://www.pasteall.org/70789/diff seems to half works... Half because it cause crash sometimes and undo_steps are not restored correctly in KX_BlenderSceneConverter destructor. And the code could maybe be launched elsewhere than in blendersceneconverter... In new LA_Launcher?

**Comment by panzergame** [comment]
@lordloki : We need first to see if there's no case modifiers are needed by the users. I don't know : subdivison surface on armature, displace...

**Comment by youle31** [comment]
another version more functionnal but still prototype: http://www.pasteall.org/73964/diff

**Comment by panzergame** [comment]
Done :P
