### ISSUE TITLE
Request: Hardware Skinning

### ISSUE THREAD

**Issue by lordloki** [UPBGE/blender#13]
Hi, 

in this link is the Moguri's thesis implementing hardware Skinning for the BGE: https://github.com/Moguri/blender/commits/thesis

If I find time, I will try to make a pull request with the changes. Anyway, feel free to implement it if you have motivation/free time before me :-).

**Comment by BluePrintRandom** [comment]
ZOMG :+1:

**Comment by Akira1San** [comment]
That would be a cool and wanted feature. :+1:

**Comment by youle31** [comment]
@lordloki: I didn't know what was hardware skinning a week ago, but it seems a very very well feature. If you want to implement it in the upbge (as an option to keep the old computers compatibles), you are very welcome :)

**Comment by BluePrintRandom** [comment]
This is a little weird but a while back I was thinking about something, 

the ability to use a game object as a bone ..... (I know this sounds off topic)

The idea was bullet 3 will have physics simulations living on the GPU,
GPU can skin armatures....

The idea was, physics animated actors, like ragdoll, would not cost any cpu time, as the physics simulation lives on the gpu, and so does the hardware armature skinning algorithm and rasterizer,
so why involve the CPU at all?

this would be VERY fast from what I understand, and you could always call the Bone/objects 'static'
and update them just like the old system right? 

Just a thought to get out there, (I also noted Hg1 running a compute shader in the bge....)

**Comment by Akira1San** [comment]
Test scene ->
https://drive.google.com/file/d/0B6yNvVGWiWysRE9qR094ZnQza1E/view?usp=sharing

Ive made a test with 2 chars: Dragon and a Sintel model.
Dragon: 37 998 tris, armature with IK.
Sintel: 5073 tris, Armature with IK.
80 Sintel models gives - 19fps
6 dragon models gives - 30fps
I know this is not the perfect example, but will Hardware skinning, do any change?

**Comment by DCubix** [comment]
Again, really old request. So now it's high priority.

**Comment by Akira1San** [comment]
I was looking at this pdf Fast skinning. It looks like with simd sse3 gives some nice speed up.
link -> http://fabiensanglard.net/doom3_documentation/37728-293750.pdf
Also i found this vid -> https://www.youtube.com/watch?v=h4v0PgNGnk4
Compute shaders can be used to to gpu skinning too. :)

**Comment by BluePrintRandom** [comment]
any progress in this area?

**Comment by DCubix** [comment]
@panzergame  ?

**Comment by panzergame** [comment]
@DCubix, i'm waiting for @lordloki currently.

**Comment by lordloki** [comment]
Sorry, but i need, at least 4-5 hours of continuos free time, to push something usable. But I wont have a free day to can dedicate exclusively to upbge until second week of december.

If some of you want to participate in this branch, feel free to do it.

**Comment by DCubix** [comment]
This request is one of the oldest requests now. Should we wait until 0.2?

**Comment by lordloki** [comment]
I'm working on it right now. Anyway, I close it as I will open a pull request when it is ready
