### ISSUE TITLE
Suggestion: "Simplification" of logic bricks into common groups

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#131]
Hello!

Taking a look through the Python API of the BGE, in the "types" sections, I've seen that there are different classes of functions in the same logic bricks, like the "Edit Object" logic brick - that have "KX_SCA_AddObjectActuator", "KX_SCA_EndObjectActuator", "KX_SCA_ReplaceMeshActuator" and others, all grouped in the "Edit Object" logic brick and selected through the mode selector.

Since there's a lot of common purpose logic bricks and the most logical path for the upcoming logic bricks is the of the pre made functions (like the "Mouse Look" actuator, that is a big time saver), it's clear that the add logic bricks drop down menu can become a mess in the future. I suggest the merging of logic bricks just like the mentioned "Edit Object", and "Motion" actuators, being able to select the mode, and the merged logic bricks be of common tasks. For example, the "Joystick", "Keyboard" and "Mouse" sensors could become a "Input" sensor, and then you could select one of the three through a mode drop down menu, just like the "Motion" and "Edit Object" actuators. The "Collision", "Movement", "Near", "Radar" and "Ray" sensors could become a "Physical Sensor" sensor, and the same mode selection drop down menu. The "Actuator", "Message" and "Property" sensors could become a "Logical Sensor" with the same mode selection, and so on. The same logic could be used to actuators, but I'm just giving examples here, I'm sure you have understood.

I believe that it's a simple implementation, but could be a good start in a organization effort of the Logic Editor, and be a important step for the future implementations, as mentioned.

**Comment by panzergame** [comment]
I agree to merge actuator that should be like the "Edit Object" actuator, but for actuator like mouse or keyboard i don't agree since it will create a actuator with a lot of attributes which will be for the 3/4 not used.

**Comment by joelgomes1994** [comment]
You mean, attributes accessed through Python? My suggestion is just for the interface of the Game Logic window, not the Python classes, just for the sake of organization, and there would not be an class "SCA_InputSensor" where the "Keyboard", "Mouse" and "Joystick" sensors would inherit, just like there's not an "SCA_EditObject" class, all the "KX_SCA_AddObjectActuator", "KX_SCA_EndObjectActuator", "KX_SCA_ReplaceMeshActuator" and "KX_SCA_DynamicActuator" are in the same logic brick of "Edit Object" actuator, that is just an convention of the interface itself, and the according class is instanced based in the active mode of the logic brick. As you can see, when we ask for the type of the actuator "Edit Object", it results in different classes according to the mode:

`from bge import logic

cont = logic.getCurrentController()
actuator = cont.actuators["Edit Object"]

print(type(actuator))`

In "End Object" mode: <class 'KX_SCA_EndObjectActuator'>
In "Add Object" mode: <class 'KX_SCA_AddObjectActuator'>

I'm sure that there will not be an problem of a lot of attributes that will not be used, in the interface or in the Python.

**Comment by lordloki** [comment]
I think that it would be better to classify the bricks by type as we do with the nodes but I don't know if the logic bricks space will allow it.

**Comment by BluePrintRandom** [comment]
can we rip out the bricks,

code a 'container' system, so that any bricks added to sub folders inside
the container get built? have a sub folder for each brick, with all code
for that brick? some how funnel that data where it needs to go?



so you can duplicate a existing sensor or actuator and make a alternate
version without editing 6 files?

**Comment by joelgomes1994** [comment]
Here's an schematic and example logic bricks of how it could look like.

![bge_schematic](https://cloud.githubusercontent.com/assets/19820741/15928434/2ab75eb4-2e1d-11e6-94bb-83d80ed2ca8f.png)

**Comment by panzergame** [comment]
Indeed groups in UI are nice (even if the logic brick box will be bigger now due to the mode line). But for the internal sources i prefer the separated sensors classes.

Also doing groups will request a huge compatibility support if we simply merge the DNA/UI classes.

**Comment by joelgomes1994** [comment]
The @BluePrintRandom 's idea sounds even better than mine, a container system just for the UI organization, that won't mess with existing logic bricks classes.
What I suggested is not urgent (cause there are not that many logic bricks to worry about organization), but what @BluePrintRandom suggested is, because the logic bricks easily become a mess as the game gets more complex (especially because there are logic bricks to do stuff that Python can't by its own ways), the existing filters aren't enough and the states aren't intended for this kind of organization.
However, it would be needed an drag and drop support for the logic bricks or something like to attach a brick to a container, and this probably would be the real problem to implement (but most useful than the existing up/down buttons).

**Comment by joelgomes1994** [comment]
An possible example of a container:
![bge_schematic_container](https://cloud.githubusercontent.com/assets/19820741/15943016/5871e938-2e5d-11e6-8600-7ab1f3833f58.png)

**Comment by BluePrintRandom** [comment]
That is also a great idea Joel, but I was talking about the code in the
source,

right now, to add a copy of a brick, you need to edit like 5 or 6 files,

what I purpose is to re-write the system that handles the bricks, to add
all bricks in folder, and grab UI stuff from 1 file.

basically, logic bricks are distributed in many files, and it sucks to try
and understand, and everyone is too busy to talk me through understanding
it.

**Comment by Akira1San** [comment]
In one of the BF conferences, Ton mentioned, that the logic bricks need to get rewriten and the basis will be this pdf -> https://www.blender.org/api/logic_editing_proposal.pdf
As you see from the file, now the logic bricks looks more appealing and advanced! But of course this looks like a 3 months of work. :)

**Comment by joelgomes1994** [comment]
@BluePrintRandom Yeah, I've read that the source of the game engine is hard to work with, there's a lot of dependencies, old code mixed with new code, a lot of deprecated content, and I understand it. But it's very cool what @Akira1San said, I'll read it for sure. And three months of work is not too much compared to the years of delay of the BGE. :P 
Source: https://mogurijin.wordpress.com/2014/06/12/why-is-the-blender-game-engine-difficult-to-maintain/

**Comment by lordloki** [comment]
Good idea,

I will investigate containers/groups by group of sensors or controllers or actuators in a separate way and also containers/groups containing sensors, controllers and actuators as a whole.

@BluePrintRandom check the new answer in [http://stackoverflow.com/questions/14335058/how-do-i-create-a-new-logic-brick-for-blender/37741926#37741926](url)
