### ISSUE TITLE
Culling LOD

### ISSUE THREAD

**Issue by Wisaam** [UPBGE/blender#133]
In the object tab under Levels of detail, after adding the new level of detail there could be a check box like "Cull at this LOD" so the object is culled when this LOD is reached and not drawn.

I don't know if this would be easy or hard to implement  but it would be really helpful performance wise and a lot of modern game engines have this feature too.

**Comment by panzergame** [comment]
It's a duplicate of an old issue request, the major issue noticed was that even if the object will be never draw w need to cull it to know if we have to update the lod of this object. To summarize you will economize redner time but not culling time as obj.visible.

**Comment by panzergame** [comment]
If the user can accept it, no problems.

**Comment by Wisaam** [comment]
If the render time is reduced then won't it also improve performance, sorry I am no expert on this type of stuff.

**Comment by Wisaam** [comment]
If it will make no difference as it is culled anyway then it can be dropped.
