### ISSUE TITLE
Release download checksums

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#134]
Myself and others have been getting corrupt/incomplete downloads, perhaps due to the file host or our own backwoods internet connections.  It would be convenient if checksums were listed on the download page.

**Comment by panzergame** [comment]
Done : http://download.upbge.fr/download/buildbot/branch/

**Comment by xan2622** [comment]
Hi. 

For security reasons, I would also like to be able to compare checksums (**sha256** files) between download links ([here](https://github.com/UPBGE/upbge/releases) or [here](https://mega.nz/folder/k9MW1KiZ#UOKzjh3IQ0GEgjQ6GUc7ug)) and the UPBGE archive files that I download.

**Could you please consider providing .md5/.sha256 files alongside your files?**

Blender, for example, provides them: 
- https://download.blender.org/release/Blender3.0/
- https://builder.blender.org/download/daily/

<img src="https://user-images.githubusercontent.com/1732773/146760257-e79601a2-18bc-4244-a9db-68b177943fbc.jpg" width="60%" height="60%">

<img src="https://user-images.githubusercontent.com/1732773/146759625-d5b3957b-d254-4c74-b03b-63177a91338c.png" width="60%" height="60%">


![70153](https://user-images.githubusercontent.com/1732773/175779336-fb1cc19f-88ab-4748-99f6-a55823e9ece8.png)

Thank you in advance. 🙏

**Comment by lordloki** [comment]
Yes, I will implement for next releases.

**Comment by lordloki** [comment]
I just added for UPBGE Release 0.3 (Github & Mega)

**Comment by xan2622** [comment]
Thank you for providing checksums. 👍
If you allow me to ask another request: may I suggest to use **sha256** or **sha512** ?
Those might take slightly longer to generate but _md5_ and _sha-1_ are known to be compromised: [link1](https://automationrhapsody.com/md5-sha-1-sha-256-sha-512-speed-performance/) - [link2](https://infosecscout.com/md5-vs-sha256/).
**sha256** is a good compromise.
