### ISSUE TITLE
Request:Cubemap Node

### ISSUE THREAD

**Issue by Wisaam** [UPBGE/blender#135]
A cubemap node in the material node editor would be helpful.

 It could use a standard blender format cubemap texture as input, or more preferably, there could be six inputs to input up/down/right/left/front/back textures separately.

It would be useful in rendering realtime cubemaps when used with the videoTexture module.

**Comment by adriansnetlis** [comment]
I would love to have something like this
For 6 inputs you can check HG1's real-time relfections setup and change textures(and disable the rendering script). However, one image use could improve performance. I'd love to see it together with per-node mipmap settings:)

**Comment by Wisaam** [comment]
@adriansnetlis

Yeah I have looked at HG1's setup and that's exactly what gave me the idea to have this type of node, HG1's setup is cool and all but in my opinion its really messy and difficult to setup and having to copy paste the nodes every time is not really my thing.

Instead having a built-in node to do that would be super helpful.
Having one image for a cubemap is already kind of available in blender isn't it?
But I can't see how a single image could be used for realtime cubemaps.

YES! I was exactly thinking that too, having per-node mipmap settings would really cool too.

**Comment by youle31** [comment]
This has been done by Blender4Web team it seems: https://blenderartists.org/forum/showthread.php?402321-BGE-News-Static-cube-map-reflection

So I close the thread. You can already have static cubemap reflections since 2.77a. There is a tuto in the thread. I close this feature request.
