### ISSUE TITLE
Geometry Instancing not working on intel HD 4000

### ISSUE THREAD

**Issue by Wisaam** [UPBGE/blender#136]
In my computer, after activating "Geometry Instancing" in the material the tab, the object does not render.

It gives an error in the console:

"Not enough space for defined varyings."

My GPU: Intel HD 4000

Example file: [https://drive.google.com/open?id=0B_AU4X5su9P_YVZ3T3hRTTlUdGM](https://drive.google.com/open?id=0B_AU4X5su9P_YVZ3T3hRTTlUdGM)

My system info: [http://www.pasteall.org/70474](http://www.pasteall.org/70474)

I am not familiar with GLSL programming but I was wondering if maybe the maximum number floats can be decreased in the shader to meet the minimum requirements.

As my maximum float limit is only 41 and the shader apparently exceeds it.

**Comment by lordloki** [comment]
If you check the intel web page (http://www.intel.com/content/www/us/en/support/graphics-drivers/000005524.html?_ga=1.210046685.910756442.1465576176) the intel HD4000 support opengl 4.
Maybe you are using intel driver from laptop manufacturer that it is not updated totally.
Here you have intel driver link (http://www.intel.com/content/www/us/en/support/graphics-drivers/intel-hd-graphics-4000-for-3rd-generation-intel-core-processors.html)

**Comment by Wisaam** [comment]
@lordloki 

So I tried multiple times to update, it just said that it is alreasdy upto date, I tried to manually download but it gave me an error saying that my device is not compatible, I tried to use intel update utility and it too said that it is upto date, so I am pretty sure by now that I have the latest driver that can run on my system.

So do you need opengl 4.0 for instancing to work?

**Comment by panzergame** [comment]
About the varying number, we can't reduce it…

**Comment by youle31** [comment]
or maybe there are different versions of intel HD 4000 (like intel HD 4000 for 3rd generation processors, intel HD 4000 for 2nd generation processors... I don't know)

**Comment by panzergame** [comment]
@Wisaam GI is only for Opengl 3.1 at least.

**Comment by Wisaam** [comment]
@panzergame I have 3.3.0 and I guess my GPU is : intel hd graphics 4000 for 3rd generation core to be exact.

**Comment by Wisaam** [comment]
It says in the system info that varying float limit is "Implementation dependent Limitation for openGL" what does that mean?

**Comment by youle31** [comment]
My laptop cpu is intel i5 3230m with intel hd 4000 iirc. @Wisaam : Maybe you can compare my cpu specs with yours to see if there are any differences about intel hd 4000.

**Comment by Wisaam** [comment]
@youle31 Apparently you must also have 3rd generation.
Can you tell me your driver version.
Mine is 8.15.10.2712

**Comment by youle31** [comment]
10.18.10.4276

date: 17/08/2015

**Comment by Wisaam** [comment]
I have tried multiple times to download from that page but it keeps giving me an error:
"This driver is incompatible with your computer."
But I asked HG1 on one of the forums and he said that different driver versions don't normally cause different varying limits.

**Comment by Wisaam** [comment]
So I managed to download version 9.17.10.2843 for acer which apparently the latest I can get from there, but it didn't solve the problem.

Maybe its because I have a 32-bit operating system?

**Comment by youle31** [comment]
You could try with a ubuntu live cd 64 bits (linux)

**Comment by Wisaam** [comment]
Ok guys so I had to do a workaround and basically force my pc to install the latest driver s and now I have:

version: 10.18.10.4425
date : 04-Apr-16

And it WORKS!!
So you guys were right after all, it was a driver problem. Weird that my pc kept telling me its upto date.

**Comment by youle31** [comment]
Cool :) This is panzergame job :+1:

**Comment by youle31** [comment]
You could share your tip to force driver update on intel hd 4000 on BA. It could be interesting for some users...
