### ISSUE TITLE
Forward rendering improvements

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#141]
For Global illumination check:
http://perso.telecom-paristech.fr/~boubek/papers/FLC/

**Comment by panzergame** [comment]
Can you provide more infos, try summarize the paper, or even think to the futur with the implementation : What options ?

Did this request deferred rendering ?

**Comment by BluePrintRandom** [comment]
it does not appear to require deferred rendering*

**Comment by BluePrintRandom** [comment]
why is this closed?

**Comment by lordloki** [comment]
For improvements related to big number of lights in the scene check Forward Plus rendering:
Paper: https://takahiroharada.files.wordpress.com/2015/04/forward_plus.pdf
Slides: http://www.slideshare.net/takahiroharada/forward-34779335

Basically, performs better than deferred rendering, the pros are:
- Manage better a high number of lights
- It can manage semi-transparent objects (deferred not)
- Memory

the cons are:
- It needs a compute shader (therefore opengl 4.3) for light culling.

The forward+ consist in divide the screen in X tiles (generally 16 tiles) and only do the shading in each tiles for the light affecting to that tile, for this we need:
1- a Z-depth pre-pass
2- a light culling pass using before info.
3- light accumulation and shading.
The better the light culling pass the better the performance of global method.


Other insteresting links:
- Forward+ implementation (MIT license): https://www.google.es/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi2gdSK-73OAhVJXBQKHcvRBaUQFggfMAA&url=https%3A%2F%2Fgithub.com%2Fbcrusco%2FForward-Plus-Renderer&usg=AFQjCNEOc7aJcy6TfrVX0EXvXxDQbzp4Cw&sig2=eQ2pqjRLmhfBfND6b7trGw
- different types of light culling algorithms for Forward+: http://computing.derby.ac.uk/ojs/index.php/da/article/download/21/57
- Comparison between Forward, Deferred and Forward+ rendering in directx11: http://www.3dgep.com/forward-plus/

**Comment by panzergame** [comment]
Thank you lordloki for the research, i will look what i can do until 0.2.0 or 0.1.7.

**Comment by Akira1San** [comment]
That Forward Plus rendering looks awesome!

**Comment by DCubix** [comment]
@panzergame , @lordloki , @Akira1San 
Light Indexed Deferred Rendering (a new technique)
https://www.opengl.org/discussion_boards/showthread.php/163783-Light-Indexed-Deferred-Rendering-new-technique

**Comment by BluePrintRandom** [comment]
Explain when closing eh?

**Comment by lordloki** [comment]
It was closed to make a issue list clean up. It is in our list to access to it when we implement it.
Thanks for the support
