### ISSUE TITLE
Issue: Geometry instancing problem with textured materials.

### ISSUE THREAD

**Issue by Wisaam** [UPBGE/blender#142]
Again this might just be on my GPU but the geometry instancing doesn't work with materials using any texture.

I had a problem before but it got fixed by updating the driver but unfortunately I didn't test it using a texture.

Now it does work if you remove the texture but with the texture it simply doesn't render.
I have no errors in the console this time.

My GPU: Intel HD 4000
I am using UPBGE 0.0.8 for win32

Blend file : [https://drive.google.com/open?id=0B_AU4X5su9P_Q1VyN0FtMEx0XzQ](https://drive.google.com/open?id=0B_AU4X5su9P_Q1VyN0FtMEx0XzQ)

EDIT: I did some testing and it seems this problem only occurs when I use UV or generated coordinates for the textures.

**Comment by panzergame** [comment]
@Wisaam : I can't reproduce the bug, i guess is about maximum number of attributes arrays. I don't see how to reduce it in the shader.

**Comment by Wisaam** [comment]
@panzergame I don't get any errors in the console though, but why does it happen only with UV coordinates?

How much does the shader require?

I found the following info about my openGL:

renderer:	'Intel(R) HD Graphics 4000'
vendor:		'Intel'
version:	'4.0.0 - Build 10.18.10.4425'

Maximum Fixed Function Texture Units:	8
Maximum DrawElements Vertices:	1048576
Maximum DrawElements Indices:	1048576

GLSL:
Maximum Varying Floats:	64
Maximum Vertex Attributes:	16
Maximum Vertex Uniform Components:	4096
Maximum Fragment Uniform Components:	4096
Maximum Vertex Image Units:	16
Maximum Fragment Image Units:	16
Maximum Pipeline Image Units:	96

**Comment by panzergame** [comment]
@Wissam, if you enable "object color" in material, did you get wrong rotation or position ?

**Comment by youle31** [comment]
@panzergame: This http://www.pasteall.org/73100/diff makes geometry instancing (textured objects) working with intel HD 4000

**Comment by panzergame** [comment]
@youle : in your patch the both line are needed ? or only one is enough ?

**Comment by youle31** [comment]
commenting the second line is enough (glDisableVertexAttribArrayARB(unit);)

**Comment by panzergame** [comment]
@youle31 : What's the value of unit in this line ?

**Comment by youle31** [comment]
http://www.pasteall.org/73297

**Comment by panzergame** [comment]
@Wisaam : If you can compile can you test with last master, please ?
Else:
@youle31 : Can you make a windows build, please ?

**Comment by youle31** [comment]
Hi, so here is a complete build for windows 32 bits: https://drive.google.com/file/d/0B3GouQIyoCmrOHlJM2JkQ1B5Wjg/view?usp=sharing

Panzergame normally fixed the bug on intel HD 4000.

@Wisaam : Don't hesitate to make tests with your .blends to report eventual bugs that we didn't see yet. Thanks!

**Comment by Wisaam** [comment]
@panzergame and @youle31 Thanks for your efforts, geometry instancing works properly now, both with and without textures.

Also I am having no problems when I activate object color.
