### ISSUE TITLE
Standalone Installer and blenderplayer external install(GPL workaround?)

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#146]
It would be just great if the standalone export would create an installer. The installer could than store and encode game files in one user defined location and blenderplayer(modified for decoding the game files) in other user defined location. Than those 2 installations can have each a seperate license + we get a nice installer that allows to compress the game files and remove manual file placements making it user friendlier + the game files can(optionally) be encoded meaning that it becomes really hard to get them abused. What do you think?:)

**Comment by panzergame** [comment]
About the encoding of files there's the BBPlayer project, the author already contacted us. For the two patch, i don't really know.
