### ISSUE TITLE
Local Screen-Space Reflections

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#147]
Local Screen-Space Reflections is a method for high-quality psuedo-raytrace reflections in real-time. Some decent game engine(like UE4) uses it. This method wokrs in screen-space(can be applied as filter, but is most effective in deferred space, is also possible to apply in usual forward rendering scene, but than it becomes hard to implement). It uses depth buffer, normal buffer and rendered image to calculate reflected pixel color. Original method has many artifacts and empty holes(due to the fact that it has access only to the rendered data), but blending with cubemap + some approximations to smoothen it out and clear the artifacts makes it look cool. From my experience, it is quite expensive method(my old PC, GT 610 - scene with cube and floor(textured with tiles) ran at 15-20 FPS), but a bit stronger computers(like my laptop - GTX 960M) can handle it at solid 60 FPS. This will definetly improve scene quality.

**Comment by panzergame** [comment]
@adriansnetlis : If it use cubemap, then is not really a screen space, no ?

**Comment by adriansnetlis** [comment]
I said - blend with cubemap. The reflections use screen space reflections. And they don't cover whole object as some data isn't avialbe. You just replace that with cubemap.
To get better quality, you can render depth buffer, normal buffer and color buffer into cubemap and sample screen space local reflections in cubemap-space instead of screen-space. THis would give you more of raytraced reflections, less missing data, but would be very inefficient.
