### ISSUE TITLE
16-bit color depth FBOs for post-processing

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#148]
Currently the BGE uses 8-bit(32-bit / 4(rgba) = 8-bit) rendering for both - the final image of screen(which, of course, can't be different because our screens are limited to 8-bit) and for post-processing(which can be actually anything - it's just data that we manipulate, we just need to care about performance a bit). But most of modern game engines use 16-bit(64-bit / 4(rgba) = 16-bit) depth for most of post processing components. It's critically important for many methods(like local reflections) that works in screenspace using depth buffer as they often need extremely high accuracy. 16-bit depth is 256 times more accurate than 8-bit depth while uses just 2 times more memory and processing power(actually less because you bind it just once and binding 2x bigger value doesn't take 2x more time). 16-bit depth also has advantage when using basic colors. Firstly, it allows tone mapping to work more efficiently(current sRGB tone mapper produces banding because it stretches out some of the dark colors that way skipping some colors while repeating others multiple times). However, if it used 16-bit depth, when tone mapping and than converting to 8-bit it would keep the smoothness and use up all the aviable colors. Lastly - 16-bit allows to render brightnesses above 1, which can be useful for objects like light sources or strong reflections from bright light sources. This can help to produce high-quality bloom which depends on the strength of light source.
As you can see, using 16-bit depth for post processing can be useful. It can also be used before drawing image to the screen in order to produce smoother tone mapping without bandings. And it could lead our post-processing capabilities to a new level.

**Comment by panzergame** [comment]
@adriansnetlis : We are looking to use a full FBO rendering for 0.1.0 and then at the end transfer to the screen. It will allow us to specify the image quality.

**Comment by adriansnetlis** [comment]
And, of course, it will allow you to have better color correction(and maybe you can somehow add customization of color correction in UI?). That's good idea. It can even let you implement deferred overlay shaders(e.g. screenspace reflections). But HDR is important.

**Comment by youle31** [comment]
the source image is in RGBA8, the image copy used in 2D filters is in RGBA8. RGBA8 is enough and we can't modify all the source code to replace all RGBA8 with RGBA16 so I close the issue.

**Comment by adriansnetlis** [comment]
:sob: :scream:
