### ISSUE TITLE
Other: Make Lib like BGE that is LGPL?

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#15]
is it even possible to rewrite the BGE module and release it under a new license?

Not copy, but rewrite from scratch ?  "clean-room implementation"
How long would that take?

what about Mathutils?

I intend on releasing my games GPL, but apparently importing BGE is linking,
so people who would make large projects are scared off by this.

so if people could do 

    import upbge
    import upbgemathutils

and both libs were LGPL this would fix that right?

Please correct me anywhere I am wrong, etc.

**Comment by BluePrintRandom** [comment]
Ok I looked at it, and it looks like no matter how it is coded, it would be a derivative.

**Comment by panzergame** [comment]
@BluePrintRandom : Indeed the GPL is a big issue. All things using a code in GPL is GPL, it's why they created the LGPL. So since the BGE use blender (and it will be forever) it will be in GPL.

**Comment by BluePrintRandom** [comment]
Ok , I have been talking to Ton, Lawyers, etc,

it is 'import bge' that causes a project to be infected with gpl,

Loading a game engine project does not infect the game with GPL ->
importing a GPL module does,

I have asked Ton to help me get a list of sources for the bge module and
mathutils module, to get there licences only, converted to LGPL. It is a
massive undertaking, but will remove a large barrier to any commercial use
of the bge.

**Comment by Akira1San** [comment]
Sounds good, but why LGPL? Why not BSD or MIT?

**Comment by panzergame** [comment]
I don't see how can we make the UPBGE API under LGPL.

**Comment by BluePrintRandom** [comment]
OK!

I think I have a work around, when a blend is opened by blender or by standalone player, build a scene list, and a object list per scene, and store it as a database , and any added objects/removed objects update this data base,

so the user can call a alternative to getCurrentController and scene.objects, 
and avoid calling import BGE at all,

for mathutils / Vector -> you can mutate a object.worldPosition.copy() to build a vector,
and never invoke GPL !

**Comment by panzergame** [comment]
the alternative getCurrentController will use the same C/C++ internal source which are in GPL too.
There's no more activity on this topic since a long time, i close it, fell free to reopen if any news.
