### ISSUE TITLE
Blender closing when the Python console interpreter is activated

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#154]
Tried to test the Python console feature just after the 0.0.9 version is released, but Blender is closing without any advice when I press the shortcut to enable the console (both 32 and 64 bit Windows versions). I've followed the instructions described at https://doc.upbge.fr/releases.php?id=0.0.9 .

Running through the command line with debug mode activated, don't know if this information is useful, but here it is:

![image](https://cloud.githubusercontent.com/assets/19820741/16911903/9489dad4-4cb7-11e6-808d-384ad263bd4c.png)

**Comment by panzergame** [comment]
@joelgomes1994 : Can you please provide more infos about your system. e.g what windows version ? 32 or 64 ?

Sorry, for the moment i don't have any compile environment on windows, i will let @youle31 test the bug.

Else @joelgomes1994, you can run the UPBGE with a debugger in MVSC or gdb.

**Comment by joelgomes1994** [comment]
Windows 7 Ultimate 64 bit, Intel Core i3 processor, 2.20 GHz, 4GB RAM.
I will try to get and a run some debugger tool to do this, I never used any before.

**Comment by panzergame** [comment]
@joelgomes1994 : Can you test with latest master ?

**Comment by joelgomes1994** [comment]
@panzergame You mean, build from the source by myself? I don't know how to do this and I don't have the tools too, I'm not a developer, just a regular user, sorry.

**Comment by youle31** [comment]
@joelgomes1994 : hi, could you confirm that the bug is solved in this small build (last master with minimal options): https://drive.google.com/file/d/0B3GouQIyoCmrSVgwYjM2QmItb2s/view?usp=sharing It works for me

**Comment by joelgomes1994** [comment]
@youle31 It's working with this build now! Great work!
