### ISSUE TITLE
LOD Bias not Working for Environment Textures

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#155]
I tried adjusting the LOD bias for cubemap which I've set up for my material, but it didn't work. The cubemap didn't become more blurry and rough. I set it even up to 1000, but it still gave no effect.

Running latest bleeding edge version(0.0.9, updated just 15 minutes ago).

**Comment by panzergame** [comment]
Please, test file.

**Comment by adriansnetlis** [comment]
http://www.pasteall.org/blend/42767

The ground was supposed to be blurry, but it's not...

**Comment by panzergame** [comment]
The background is not able to use lodbias currently (there's no lodbias setting in the world texture). for the cube map lodbias it's fixed in b51d7c6a66a36b9834402ffa3482ca556f3259cf.
