### ISSUE TITLE
GGX specular shader

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#156]
Currently BGE supports following specular shaders:

- Cook-Torrance
- Phone
- Blinn
- Wardiso
- Toon

However, none of them are physics based.  The closest one is Wardiso, but it's still not good.    
In nowadays GGX is like a standart. It's very realistic and accurate.

A good reference:
https://github.com/wdas/brdf/blob/master/src/brdfs/d_ggx.brdf

**Comment by DCubix** [comment]
I implemented it in a simple online shader editor. It looks nice but not so impressive... http://goo.gl/lgzuLK

**Comment by adriansnetlis** [comment]
But what about full Disney BRDF shading model?
https://github.com/wdas/brdf/blob/master/src/brdfs/disney.brdf

It includes GGX.

Mārtiņš Upītis implementation:
https://www.youtube.com/watch?v=cnfj0Fru2u8&feature=youtu.be

As you can see, it looks indeed great. But with reflections, different lamp types and full texture support it'd look incredible;)
By the way - UPBGE could replace current BGE/BI material system with PBR similar to Disney BRDF(also use GGX, include correct energy conservation, clear coats, retro reflections etc.). And keep the current material set up workflow(just replace what we currently got with things like base color, specular tint, roughness, etc.) and in texture tab replace current options on the down part with the new ones. What do you think?:)

**Comment by Akira1San** [comment]
I like it!

**Comment by adriansnetlis** [comment]
:cry: :sob:

**Comment by axredneck** [comment]
@adriansnetlis https://blenderartists.org/forum/showthread.php?387752-A-new-fork-of-the-engine&p=3078652&viewfull=1#post3078652
> Also, we want you guys to understand that it's normal that we Close and Re-Open issues and request if needed, because sometimes that request gets old or unfixable or undoable. Please don't be mad if your request was closed!
