### ISSUE TITLE
Better attenuation for point/spot lights

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#158]
https://imdoingitwrong.wordpress.com/2011/01/31/light-attenuation/
I found this article and it seems to be good for spherical area lights. We could slowly replace our point lights with this.

I tested and can confirm that it looks good;)

Note that bigger sphere radius results in brighter light in overall.

**Comment by DCubix** [comment]
The current shading model does this already, no?
This is a quite global formula

**Comment by adriansnetlis** [comment]
Currently we have:
custom curves which just allows to make some lamp-specific effects
inverse square (1 / distance^2) which is good approximation for infinitely small point lights and is used by most game engines
constant(I don't see any use of it, but maybe... for example - a very basic global illumination setup with low-radius point lights? Than constant would boost performance a little)
inverse linear (similar to constant)
lin/quad weighted (blend between inverse square and inverse linear)
And last is inverse coefficients (1 / (const + lin * distance + quad * distance * distance)).

The method I show is extension of inverse squared. It adds radius factor to the lights. That allows for effecient attenuation calculation for spherical area lights.
