### ISSUE TITLE
Simple client/server network

### ISSUE THREAD

**Issue by lordloki** [UPBGE/blender#159]
Basically it is to use the message infrastructure to send/received internet messages.
Formerly, the skeleton of this internet client was in the Network code but it was deleted as it wasn't implemented (I think NaN went backrupt just before).
I have a patch in a oscure place of my computer for this (using enet library). I will search it , complet it, clean it and upload it.

**Comment by lordloki** [comment]
Former network structure: https://developer.blender.org/rB148eb5ca9c4fed270209dd662b2d7cadcea0afd4

Some pictures from my old patch:
![blender_client-server2](https://cloud.githubusercontent.com/assets/1015605/17012468/3cfec9ba-4f18-11e6-8d19-9a2ad018b632.jpeg)
![blender_client-server](https://cloud.githubusercontent.com/assets/1015605/17012476/451e6862-4f18-11e6-829a-bc69ada98c00.jpeg)

**Comment by youle31** [comment]
Looks great! Thanks!

**Comment by adriansnetlis** [comment]
Looks like something really cool! :wink:

**Comment by lordloki** [comment]
I close this as it wont be available for 0.1 milestone. I will open later
