### ISSUE TITLE
Request: Skybox + cubemap + Environment mapping

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#16]
Add support for Skybox + cubemap + Environment mapping. This feature should give the user game developer the ability to add reflection and refraction using a single global texture.
Example link -> http://learnopengl.com/#!Advanced-OpenGL/Cubemaps

**Comment by lordloki** [comment]
Related:
https://developer.blender.org/D1461
https://developer.blender.org/D1414

**Comment by youle31** [comment]
Thanks. For skybox, it seems feasible (maybe we'll ask HG1 if he wants to integrate his patch into the upbge...) But for cubemap reflections, as say Moguri, it's an enormous technical challenge to integrate this into the "main shader" code. We have nevertheless added a GLSL template for cubemap reflections in the upbge (for 1 light source and 1 cubemap texture)

**Comment by BluePrintRandom** [comment]
Light probes eventually would be pretty neat,

Hg1's realtime cube mapped reflections shader is pretty sweet,

https://www.youtube.com/watch?v=OloKmKAlleM

that said, it's not easy to just duplicate and use it again,

(like to use the player cube map and math to fake cube maps on everything
around you)

**Comment by Akira1San** [comment]
I see.

**Comment by youle31** [comment]
Finally it was feasible https://youtu.be/jbFFyU28Py8 :)

**Comment by Akira1San** [comment]
Looks cool!

**Comment by panzergame** [comment]
Ske/background render are now implemented : https://github.com/UPBGE/blender/commit/b89ff69de8db9ef76c8d07c526046770597b5422.
