### ISSUE TITLE
Environment Lighting not Proper for "Real Sky"

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#161]
When I enable ambient lighting, it works very well and proper. When I set it to sky color, it also seems to work good. However, if I enable "Real Sky", the environment lighting ignores that. It stays like it was.

**Comment by panzergame** [comment]
Please provide an example file to speedup the work.

**Comment by adriansnetlis** [comment]
It's as simple as:

- Make smooth sphere to see lighting better
- Ensure that there are no lights in scene
- Enable environment lighting
- Set the environment lighting to use sky color or sky texture
- Set sky to 'blend sky' and 'real sky'
- Set zenith and horizon colors to something very different(e.g. red and green)
- Watch at scene

You'll see that environment lighting doesn't match sky color. If you disable the 'real sky', it's gone not change and will look like expected.

**Comment by youle31** [comment]
no file. I close the issue
