### ISSUE TITLE
UPBGE freezes when clicking on the screen while the ingame console is opened

### ISSUE THREAD

**Issue by Momel15** [UPBGE/blender#166]
Hello,

when you click on the Blender screen (doesn't matter if it's the 3D view or else) while there is an opened ingame console, Blender will freeze until you close the console. Of course, the game should stop while the console is open, but Blender shouldn't freeze, instead it should just do nothing (or maybe print a warning in the console?).

_(I'm not talking about the fixed bug that caused blender to crash when the console opened on Windows)_

Please solve this bug, thank you :)

It would be great too if the main Blender Window would be "activated" after closing the console, otherwise you have to click on it every time before Blender gets an input of the user.

**Windows 8.1, 64bit
UPBGE 0.0.9b (the latest bugfix test version) from #154 Issue**

![crash](https://cloud.githubusercontent.com/assets/17685000/17108729/0ffbce42-5295-11e6-8b3b-9ee01976ce0f.jpg)

**Comment by panzergame** [comment]
@Momel15 : Thanks for the bug report first. Second : it seems that windows considerate a dead program a program doing a wait loop. I think (i hope) there's a window function to avoid this.
Third : i don't know if it's possible to set a windows active from blender, i will look.

**Comment by panzergame** [comment]
@youle31, @DCubix : Can you test to add a call to `DisableProcessWindowsGhosting` in LA_Launcher or LA_PlayerLauncher ?
https://msdn.microsoft.com/en-us/library/ms648415%28v=vs.85%29.aspx

**Comment by youle31** [comment]
I tried it: http://www.pasteall.org/72603/diff . It seems to have an effect but this is still unstable. Furthermore I had to remove python security macro that prevented the console to launch

**Comment by Momel15** [comment]
@youle31 : Thank you so much :) It works now! 

@panzergame : Have you already found a solution for the mouse "problem"?

While i was testing the build, I've found another small "bug"/"problem": If you switch to another window, you can only switch back to the console, not to blender itself, so you have to close the console first before you can see the game again. I think it's not that important, but you have to decide that :)

**Comment by panzergame** [comment]
@Momel15 : Can you compile UPBGE on the branch ge_console_windows with WITH_PYTHON_SECURITY=OFF in cmake ?

**Comment by Momel15** [comment]
Unfortunately not... I don't know how to compile and how branches work. Sorry, i'm just a normal user, not a developer. (I wish I would, but I don't know how to code in C++, I work only with python and java)

**Comment by youle31** [comment]
@panzergame : on windows we have to remove this line: 
mark_as_advanced(WITH_PYTHON_SECURITY)  # some distributions see this as a security issue, rather than have them patch it, make a build option.

from /cmakelists.txt to see the option in cmake build options and it is enabled by default. I can't build your branch... I don't know why.

**Comment by panzergame** [comment]
Apparently mark_as_advanced mean that the variable is not showed by cmake by default : https://cmake.org/cmake/help/v3.0/command/mark_as_advanced.html. 

I think you have an option in MVS for advanced mode. Else maybe we should add a separated option to avoid compile with the console or main loop override. WITH_GAME_SECURITY=OFF ?

**Comment by youle31** [comment]
I don't know. It's as you want but console is a cool feature, I guess not only for the developers. It could be always built by default (or with macro #ifdef WITH_PYTHON) if you want (I don't think console is dangerous for the user as it's difficult to enable it (you have to look in Scene tab than press ctrl+alt+shift+T)).

**Comment by panzergame** [comment]
Ok, I will add a different option which will compile the console by default.

This WITH_PYTHON_SECURITY was here to prevent any user to access to a game which manage itself encrypt/decrypt.

**Comment by panzergame** [comment]
I added WITH_GAMEENGINE_SECURITY=OFF, ge_console_windows is rebased on master too, @youle31 : Can you retest the branch please ?

**Comment by youle31** [comment]
Hi, so I tested. I had the same compilation errors than before. Moving #ifdef WIN32 #include <Windows.h> #endif at the top of includes in LA_Launcher solves the issues.

It works :)

I think a message like:  print("On Windows press CTRL+C to quit the console") in interpreter.py could be fine to indicate to the user how to close the console on windows.

**Comment by panzergame** [comment]
Did you commited the #ifdef WIN32 on top ? Else i will add the little message, it's not Ctrl+Z+Enter in windows ?

**Comment by panzergame** [comment]
I commited b69e59a9bc9067122f686e51e58f7345c6281174 for debug message.

All should be fine now.
