### ISSUE TITLE
UPBGE KX_INPUT_ACTIVE and KX_INPUT_NONE not working?

### ISSUE THREAD

**Issue by Leralasss** [UPBGE/blender#167]
i recently switched from normal bge to upbge.

in the normal bge i used

w = keyboard.events[bge.events.WKEY] == bge.logic.KX_INPUT_ACTIVE

and then use it like:
if w:
    do smt

(keyboard keys in python with always sensor)

but in the upbge keyboard.events is deprecated, so i tried to change it to keyboard.inputs but ran into some trouble.

1. w = keyboard.inputs[bge.events.WKEY] == bge.logic.KX_INPUT_ACTIVE doesnt work. (because inputs seems to be something different than events)

2. then i tried: wja = bge.logic.KX_INPUT_JUST_ACTIVATED in keyboard.inputs[bge.events.SKEY].queue

that seems to work. (wja = w just activated)

3. but w = bge.logic.KX_INPUT_ACTIVE in keyboard.inputs[bge.events.SKEY].queue doesnt work.

4. KX_INPUT_NONE also doesnt work.

is this a bug or am i doing something wrong? (or how do you correctly use keys with an always sensor in the upbge)

**Comment by panzergame** [comment]
it's:
```
w = bge.logic.KX_INPUT_ACTIVE in keyboard.inputs[bge.events.SKEY].status
```
http://pythonapi.upbge.fr/bge.types.SCA_InputEvent.html#bge.types.SCA_InputEvent.values
(i'm fixing the doc)

**Comment by Leralasss** [comment]
oh nice thank you!
