### ISSUE TITLE
USD for bge

### ISSUE THREAD

**Issue by lostscience** [UPBGE/blender#168]
Could you impliment USD for the bge?Here is the link?
https://blenderartists.org/forum/showthread.php?403719-Pixar-has-just-released-the-USD

**Comment by Akira1San** [comment]
I dont see whats this good for Upbge.

**Comment by lostscience** [comment]
Did you read this part on the websight?

Pipelines capable of producing computer graphics films and games typically generate, store, and transmit great quantities of 3D data, which we call "scene description".  Each of many cooperating applications in the pipeline  (modeling, shading, animation, lighting, fx, rendering) typically has its own special form of scene description tailored to the specific needs and workflows of the application, and neither readable nor editable by any other application.   Universal Scene Description (USD) is the first publicly available software that addresses the need to robustly and scalably interchange and augment arbitrary 3D scenes that may be composed from many elemental assets.  

USD provides for interchange of elemental assets (e.g. models) or animations.  But unlike other interchange packages, USD also enables assembly and organization of any number of assets into virtual sets, scenes, and shots, transmit them from application to application, and non-destructively edit them (as overrides), with a single, consistent API, in a single scenegraph.  USD provides a rich toolset for reading, writing, editing, and rapidly previewing 3D geometry and shading.  In addition, because USD's core scenegraph and "composition engine" are agnostic of 3D, USD can be extended in a maintainable way to encode and compose data in other domains.

Concretely, USD is an OpenSource project released under a modified Apache license.

**Comment by Akira1San** [comment]
But BGE or UPBGE is not such an engine.

**Comment by panzergame** [comment]
Corresponding to our politic about feature request describe by Diego (TwisterGE) and as this request can be compared to ask us adding a new mesh modelling tool (no link with our work) : I close the issue.
