### ISSUE TITLE
Request: More options in steering actuator

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#17]
Currently the steering actuator moves and rotates at the same time, it just looks strange to see someone back up and do a 180 at the same time and not change rate in speed,

Can we have a min face angle mode? 

where the actor rotates in place until he is lined up and then walks?

This is for Pagio's point and click, most of his art is done, but this has been bugging him,

I hacked out a few solutions, but a out of the box character navigation system is very handy, and eats far less CPU time then doing NavMesh.findPath() and comparing a bunch of angles in python.

**Comment by BluePrintRandom** [comment]
This is so Pagio point and click can move forward, they would greatly appreciate it.

**Comment by pqftgs** [comment]
I have this mostly done in a local branch.  Will make a pull request when it's ready.

**Comment by BluePrintRandom** [comment]
:+1

**Comment by pqftgs** [comment]
Not a complete solution, but #57 exposes the steering actuator's path to Python.  Though you'll still need to hack something together, at least we're not wasting CPU re-calculating the path.

My endeavor to add the angle limit was a complete failure.  It couldn't be done without either changing the behavior (effectively breaking other games, which is what I sorta did), cluttering the code with if statements, or completely re-designing the actuator.  With logic nodes on the horizon I couldn't justify the redesign.

Unless someone has more to add, I think we can safely close this one.

**Comment by BluePrintRandom** [comment]
You can already get a path using navmesh.findpath

I already implemented it, and have a almost desited behavior,
and it also is a mess of if's :D

**Comment by pqftgs** [comment]
Yes.  This commit is for the deranged soul who seeks a foul incarnation of logic brick and Python without using navmesh.findPath to re-calculate the path.  There is no performance gain unless already using the actuator.
