### ISSUE TITLE
Several Major Improvements in Post Processing System

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#170]
Hello!
I've been trying out the 2D filter system of BGE and noticed a few problems. This issue contains both - feature requests and questions.

- [Q] How do I get the texture coordinates if I use #version130? gl_TexCoord[0] are deprecated, but I can't find any detail of how to get the coordinates. It's nowhere on internet, for sure.
- [FR] Multiple render targets - yeah, I noticed that many filters require to store some data in seperate image(e.g. to handle blur or some other stuff with the modified image data). The best way is using multiple render targets, but, as far as I know, it's yet not possible in Blender.
- [Q/FR?] Texture LOD(mipmaps) can be used in post processing as base blur pass which can be than adjusted. If I use basic 2-loop blur and set high radius, it results in very liny, low quality blur. If I use kernel gaussian blur, I need to set high sample count for high radius and thus - destroy performance. So high-radius blurs can be enchaned with mipmaps. If it isn't in BGE yet, than it would be handy.
- [FR] Color depth setting for buffers could be handy. It'd be indeed cool if I could just go to game settings and set the depth of color, normal and depth buffers between 8-bit, 16-bit and 32-bit. Thus I could either choose good performance(8-bit), common medium(16-bit) or extreme graphics(32-bit). This would allow to make HDR filters, correct bloom etc.

I hope that you find those useful aswell as can answer my questions. Good luck all!:)

**Comment by DCubix** [comment]
That's nice but goes against what I stated in BA about rendering-related request. This one will be closed until the 0.1 milestone. We won't work a lot on rendernig stuff.

**Comment by axredneck** [comment]
There is some work already done: https://github.com/Moguri/blender/tree/harmony2
