### ISSUE TITLE
Stream Terrain?

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#171]
For large complex terrains either a threaded Tree structure is needed for loading/unloading meshes, or Terrain Streaming - 

here is a paper for terrain streaming -https://www.cs.unc.edu/~isenburg/papers/il-sm-05.pdf

**Comment by panzergame** [comment]
@BluePrintRandom : I already work on a terrain generator 6 month ago : https://github.com/panzergame/bge_terrain https://www.youtube.com/watch?v=dnyitBQsvtg.

Please talk about this project after 0.1.0.

**Comment by adriansnetlis** [comment]
I just wanted to ask which is more efficient way:

- Use terrain streaming where you unload one component, load new one and generate vertex and normal data.
- Move terrain tiles around and generate vertex and normal data.

Possibly the second method could be better for infinite terrains. The texture data, though, must be obtained via streaming.
Streaming would be good thing in overall. This technology, for example, is what helps UE4 become so powerful. Once of best optimization components. I give full :+1: for this feature after 0.1.0(as I do for my post-processing suggestion as I think it's major feature).
