### ISSUE TITLE
Enum Properties(for easier modular script setup) [after 0.1]

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#172]
So I thought how to make some things easier for me and I noticed - I often have dictionaries where I got a name of something and a value and than I have property which contains one of the names in dictionary. Than I use this property to get the value out of dictionary. I use this to easier control some parameters for modular scripts(where many objects use the same script, but different properties). However, I figured out that in this property case it'd be cool if I could make Enum property that reads all the keys of a specific dictionary in the script and sets them for a dropdown menu. This property could return a string which the user has selected in the dropdown. This feature would be cool for making some modular script where user can choose some of properties as this would function as a nice UI for it.

Of course, this request is targeted after 0.1 milestone is reached:)

**Comment by panzergame** [comment]
Something similar to the python component enum property, no ?

**Comment by adriansnetlis** [comment]
I tried the KX_PythonComponent, but I couldn't find a way to use it this way. Propably lack of documentation?

**Comment by panzergame** [comment]
http://pythonapi.upbge.fr/bge.types.KX_PythonComponent.html
```
("Enum", {"Enum 1", "Enum 2", "Enum 3"}),
```

**Comment by adriansnetlis** [comment]
And how do I access that value anywhere in script?

**Comment by DCubix** [comment]
@adriansnetlis 
Learn about OOP in Python, http://www.tutorialspoint.com/python/python_classes_objects.htm

In the `def start(self, args)` function:
`args["Enum"]`

**Comment by adriansnetlis** [comment]
I tried to set it up, but failed. Do I need instance of the class with KC_PythonComponent argument to access it's variables?

**Comment by panzergame** [comment]
@adriansnetlis : The documentation + examples in http://pythonapi.upbge.fr/bge.types.KX_PythonComponent.html is not engough ?

**Comment by adriansnetlis** [comment]
Nope. It doesn't say how to use a single argument from the component somewhere in script outside the component. I tried once, made a script that really made sense to me, but it yet didn't work and threw some errors(I didn't save the script so I can't tell you what exactly, however, I didn't fully understand them).

**Comment by DCubix** [comment]
> It doesn't say how to use a single argument from the component somewhere in script outside the component.

@adriansnetlis that goes against the component architecture.
Why did you get errors? What errors? ...

You should carefully read the docs and try again, basing yourself in the example ThirdPerson component.
I've seen your OOP in some of your Python scripts and they're are not really good. I recommend you to study and prectice http://www.tutorialspoint.com/python/python_classes_objects.htm

**Comment by panzergame** [comment]
Any news ?

**Comment by panzergame** [comment]
No answers since more than a week. Closing.
