### ISSUE TITLE
Cubemap Shadows for Point Lights [after 0.1]

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#177]
Hello!
There is a nice way to get high-quality dynamic shadows for point lights. It, however, requires to render depth into a cubemap.
Short step by step rendering of cubemap point-light shadows.

1. Render perspective cubemap depth texture from the point where the light is located.
2. Get the light vector in vertex shader and pass to fragment shader(vector from light to vertex). In fragment shader normalize it(this will be pretty good unit vector for each of the fragments).
3. In the rendered cubemap depth texture use the unit vector(calculated in step 2) as the texture coordinates. Find the depth.
4. Use the length of light vector(obtained in the first part of step 2) and compare with the depth value in cubemap(must be decoded from texture with the logarithmic equation) accounting the bias value(to prevent self-shadowing).
5. If the fragment is further from light than the shadow depth at given sample, than don't receive light from the light source.

Most of steps are similar to point light shadows. Only texture coordinates for shadow map sampling are different(easier to obtain) and it need to render cubemap(a bit less performance friendly).

Most likely people will reneder those cubemaps at low resolutions(e.g. 256 or 512 per-face) and thus the performance won't suffer much. This method is already being used by many game engines, e.g. Unreal Engine 4. I hope that after 0.1 UPBGE will implement this as this is really simple, but yet amazing feature!:)

**Comment by adriansnetlis** [comment]
Wow, you've put far milestone for this.:D

**Comment by DCubix** [comment]
I believe we will have a more solid renderer until 1.5, so it's far :P
We have bigger features to work on, like mesh batching.

**Comment by adriansnetlis** [comment]
Well, yeah. What I mean is that this is pretty easy to implement since you already got shadows for spot lights. It's basically the same, except that it's using real-time rendered cube map of depth texture.

**Comment by youle31** [comment]
All is easy for You so code it

**Comment by Akira1San** [comment]
Just wanted to post the link to the technique: http://learnopengl.com/#!Advanced-Lighting/Shadows/Point-Shadows
