### ISSUE TITLE
Range and exprossure values in Python + expand range

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#181]
In world tab under the colors for horizon and zenith there are 2 sliders - exprossure and range. Those sliders are very useful, for example, when using different range lights(e.g. sun lamp with natural intensity of 100 outdoors, but point light with intensity 0.75 indoors) as it allows to scale the brightness and simulate eye dilation. However, it's yet impossible to set those values runtime via Python. Also the range currently doesn't allow to scale down brightness of 100 realisticly as it's maximum is 5. It'd be great if I could set the range bigger(at least through Python) and change it dynamicly.

**Comment by DCubix** [comment]
Done #246
