### ISSUE TITLE
object.removeCollision and object.restoreCollision 

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#187]
currently one cannot disable the physics bounds of a static object in a scene, to remove it's physics cost per tic.

is this possible?

 - [my workaround ](http://www.pasteall.org/blend/43236)- https://www.youtube.com/watch?v=4bYdHQfAG54

add/removing collision should in theory be faster, because you are not adding/ removing objects per frame?

**Comment by panzergame** [comment]
I understand the issue and your solution. I'm just asking if the user prefer an UI option or only a python API ?

**Comment by youle31** [comment]
It's easy to do in suspendDynamics: GetPhysicsEnvironment()->UpdateCcdPhysicsController(this,                       0.0f,	btCollisionObject::CF_STATIC_OBJECT | btCollisionObject::CF_NO_CONTACT_RESPONSE, btBroadphaseProxy::StaticFilter,
 btBroadphaseProxy::AllFilter ^ btBroadphaseProxy::StaticFilter);

However, if the object is ghost, btCollisionObject::CF_NO_CONTACT_RESPONSE is the flag choose by default so it will be more practical to use an API to set the object as ghost without changind suspend dynamics function (if it's not already possible.) I'll check

**Comment by youle31** [comment]
can I close the issue?

**Comment by BluePrintRandom** [comment]
suspend dynamics does not remove the item from the physics stimulation,

**Comment by BluePrintRandom** [comment]
an python api would be best, and potentiality a brick later*

**Comment by youle31** [comment]
I make an API to remove physics controller and restore it

**Comment by youle31** [comment]
https://github.com/UPBGE/blender/pull/188

**Comment by BluePrintRandom** [comment]
Thank you youle :D
