### ISSUE TITLE
Request: multicore bge

### ISSUE THREAD

**Issue by lostscience** [UPBGE/blender#19]
Could you add multicore support for the whole bge?Here is a link for the improvements it would cause.http://wiki.blender.org/index.php/Dev:Ref/Requests/GameEngine

**Comment by DCubix** [comment]
I think that would require the engine to be rewritten.

**Comment by BluePrintRandom** [comment]
I think this should become a development target, after bullet 3 releases,

and thread Animation, physics ，potentially logic,
Animation is a severe bottle neck at the moment , so hardware armature
skinning is the fix there.

**Comment by DCubix** [comment]
I don't think "rewriting" should really be a development target.

**Comment by BluePrintRandom** [comment]
Actually, I hope to find some way to pay the UPBGE developers for their
efforts, I was hoping through wrectified, but I still have a long battle
before then, and even when it assures nothing,

A paetron page or a kickstart is a good idea, and with what you have been
doing, I think it would fly,

Then the money can be used to hire each of you with grants, the same way
the blender foundation does it,

**Comment by Akira1San** [comment]
I think the multi-core is an interesting discussion, and that all of the upbge devs should express their opinion, vision. As its said in the wiki page: "Add multi-core support for the whole GE - This would affect physics and realtime rendering. This would severely optimise the GE without any major rasterizer re-write." i think this is an interesting line(This would severely optimise the GE without any major rasterizer re-write), but the developer didnt add any docs.
So i found something interesting -> MSc Dissertation – Multi Core Game Engine, link here -> https://nunoleiria.wordpress.com/portfolio/msc-dissertation-multi-core-game-engine/
The page contains the doc, the pdf, the source code and a demo. It looks interesting, but the developers could really tell.

**Comment by panzergame** [comment]
I don't really see where we can add multi core support without rewrite everything and add a thousand of bugs. Animation are already multithreaded, physics will be with the new bullet3 i guess, rasterizer part can't be because of opengl state shared and logic must be strictly not threaded. The only think i see (and i'm not very sure) is for the scenegraph part.

**Comment by lostscience** [comment]
Any improvement is better than nothing.Could you check and see if the
scenegraph can support multicores?

**Comment by panzergame** [comment]
I close this issue for a more precise one or a pull request.
