### ISSUE TITLE
Standalone player bug - objects with custom shader and same image are black

### ISSUE THREAD

**Issue by Maujoe** [UPBGE/blender#194]
When I create custom glsl-shaders for different materials that use the same image as texture, all objects which use this image are black in the standalone player but not in the embedded player. In bf-blender both players work fine. The file is created in upbge 0.09 so there is no compatibility issue. 

I also have tested the different upbge versions and the issue appears since upbge 0.06 maybe it's a bug that come with the new python texture class or something like that. 

Here is a example:
[tex_bug.zip](https://github.com/UPBGE/blender/files/435826/tex_bug.zip)

I also had a strange bug in the standalone player where a object with a custom shader had a false texture from another object  but I can't reproduce the bug so maybe it's the same issue.

**Comment by youle31** [comment]
Hello, I tested your file with last upbge sources and I have the same result in embedded and standalone so I guess this is fixed. In 1 or 2 weeks we'll share upbge 0.1.0 so you could test if the bug is still there...

**Comment by youle31** [comment]
@Maujoe : Hello, do you still have this bug with the master I shared here: https://blenderartists.org/forum/showthread.php?387752-A-new-fork-of-the-engine/page32 ?

Can I close the issue?

**Comment by Maujoe** [comment]
No the bug is fixed in the master version, so I think the topic can be closed.
