### ISSUE TITLE
Add 'activate actuator' function or method

### ISSUE THREAD

**Issue by vlad1777d** [UPBGE/blender#195]
_When I programmed several projects under BGE all times one moment corrupted me all the architecture. I could not activate actuator from not connected to it controller. So I suggest will be better to:_

 **Remove necessity connecting actuators to controllers to activate actuators.**

Why:
-(a) if in scene will be hundreds of objects, physically will be difficult to connect all their actuators to controller.
-(b) to simplify working with BGE: no need to make extra connections.
-(c) this will increase amount objects, with which module can interact; this can make something like interface: object can have actuator with certain name, for example, 'wind_animation' and module will have no need to know: which keyframes will that animation have, what is it's name and etc. Module will be written once, than 3D artists could add objects with certain sign (or certain name, or certain parent), which will be processed automatically by the module.
Example:
controller_1.activate(scene.objects['sphere.008''].actuators['wind_animation'])

_I thought about idea "interfaces" more time and then came to next suggestion:_

**Create method or function for activating sensors, controllers, actuators.**

Details:
When we run activate(actuator) or actuator.activate(), the actuator of certain object will act like it was activated by controller.
Objects can be received dynamically at the runtime, 3D artists have no need to add lines to scripts or lines to logic bricks, they need just to create object with certain interface (for example, actuator with certain name) and BGE will proceed it.

Why to actuators:
-(a) to expand the idea of "interfaces" and make it more easy to implement: no need to run contr.activate(), just object.actuators.activate() or activate(actuator_object).
-(b) all like in 1.(c)

Why to controllers:
-(c) What about the programmers? If a programmer will create some object which will have not actuator, but python script, which makes certain actions. Than he BGE will activate it and programmer will have no need adding lines to previous script\module or creating lines and adding lines to certain module.
Yes, the interface can be based on thesis that the object must have or controller or actuator with certain name. If object must do some complex logic - it can use Python controller instead of simple actuator.

Why to sensors:
-(d) in a heap to rest.
-(e) if object already has difficult logic, several sensors and each sensor is responsible for certain parameter. Than each script can change certain parameter (sensor) and object will analyze all itself.

_This easy to implement solutions, as I think, will make BGE more convenient instrument for all people, who work with it._

P.S 1. Also with goal not to create extra connections between logic bricks of different objects can be implemented **activate brick actuator**.
This actuator can have three lines to choose in: 1. Object; 2. Type of logic brick to activate (sensor, controller, actuator). 3. Logic brick to activate (by name).
Why:
-(a) this actuators can say "goodbye" to long connections between several objects and searching needed one between them.

_What do you think about this? Maybe you can improve such decisions?
Thank you._

**Comment by DCubix** [comment]
"Remove necessity connecting actuators to controllers to activate actuators." That would go against of what SCA means.
If you want complex logic, use Python. We also have Python Components in UPBGE: https://pythonapi.upbge.fr/bge.types.KX_PythonComponent.html

**Comment by vlad1777d** [comment]
Thanks for answer, but I'll disagree with you.

As I know, SCA means sensor, controller, actuator. Sensor receives some information, controller proceeds it, actuator makes some actions. In model, that I suggested, all logic bricks do the same tasks, as they did before.

What really goes against SCA principles, that the Python controller makes the tasks of actuator (really it can do both tasks: of controller and of actuator). So the Python actuator could fix this misunderstanding, but this will be too much =)

I suggested only to reduce amount of lines on the screen and add more flexibility to logic programming, as I guess, with not very difficult way to implement.

Sensors still will make their tasks: receiving states, controllers - proceeding information, actuators - making some tasks. But with more easy way.
Standard model of logic bricks can do this too, but with more difficult and bulky way: you can add message sensor, and controller, connect last to actuator. But this didn't work in last Blender's release, also it clogs logic editor with extra logic bricks and connections.

Also we could create Python modules, that proceed certain objects by certain signs (certain actuators, etc). So modellers could fill scene with objects with no need to edit module's code.

So, as I think, it's a good and straight way giving logic programmers do what they want.

**Comment by sdfgeoff** [comment]
The system you are describing exceeds the capacity of the logic bricks to describe, and removing the necessity of links will solve it in this case, but not in every case.

What you are trying to do is to define a complex action inside a single logic brick in the way you would a per-object function. You're trying to define the function "playWalkAnimation()" such that it can be accessed by outside objects. The way to handle this in logic bricks is to use messages. The way to handle this in python is to write that function and bind it to the object in some way. The correct way to bind a behaviour to an object is to use the PythonComponent.

If you have the PythonComponent:
```
import bge

class Enemy(bge.types.KX_PythonComponent):
    args = {}

    def start(self, args):
        print("Mutated Enemy")

    def update(self):
        pass
    
    def doSomething(self):
        self.object.applyRotation([0,0,0.5])
```

Then from another script you can run:

```
enemy = cont.owner.scene.objects['Cube']
enemy.components[0].doSomething()
```

**Comment by vlad1777d** [comment]
@sdfgeoff , thanks for answer. I agree, it'll solve not in all cases. And I agree, that there are many different solutions for current problem. 
But even for me creating of logic brick seems much easier, than creating component. And ability to combine their work is not bad (logic brick with animation seems much clear than such lines: https://pp.vk.me/c837127/v837127447/25e0/X6Hy32frbt0.jpg ).

Why do I prefer the .activate() method and "activate actuator" to sending messages?
- because they do action directly and don't waste extra place for extra sensor, extra controller on target object, extra system resources.

Where do I faced with need to activate actuator from not connected to it controller:
- I had player object with children: 'player_camera_empty' (on which I wanted to place all actuators with 2d filters) and 'player_water_empty', which were connected to controllers with one module and different functions. 
If I would connect them, than too many bricks were on screen and I could not operate with them.
I could send message, I thought that extra bricks will decrease clearness of logic, so I moved actuators with 2d filters to 'player_water_empty'.

Nothing critical was happened, but it would be better (more convenient) if such constrain will be removed.

**Comment by youle31** [comment]
I close low low priority feature requests for now. They are still visible in closed pull requests list.

**Comment by rameshsuvvada** [comment]
For this logic below 
//
import bge

cont = bge.logic.getCurrentController()
I am getting the following error, can anyone help me

Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
AttributeError: module 'bge' has no attribute 'logic'

**Comment by sdfgeoff** [comment]
You have to run the script by adding it as a component to the object. You do this by going to the logic panel and selecting add component. Then you type the modulename and class name. (module name will be whatever the textblock is called, classname for the above component is "Enemy")
