### ISSUE TITLE
The old Alpha Blend and Alpha Sort problems

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#197]
As may be long known, there are problems with the depth sorting of alpha materials when using the Alpha Blend, Alpha Sort and Opaque modes (Alpha Clip and Alpha Antialiasing works, but don't look good).

In editor:
![image](https://cloud.githubusercontent.com/assets/19820741/18022887/5bcd8f52-6bc9-11e6-8e0a-065a0d2fa89e.png)

In standalone player:
![image](https://cloud.githubusercontent.com/assets/19820741/18022898/81383ecc-6bc9-11e6-8658-2c993b2f5a6f.png)

The material settings:
![image](https://cloud.githubusercontent.com/assets/19820741/18022949/13292972-6bca-11e6-87d7-efcd946cf6dd.png)

I know that it is a old and known problem, but I don't know if the effort to solve this problem exists, so here it is reported. Thanks. :)

**Comment by adriansnetlis** [comment]
Alpha sort _should_ fix this, but for some reason it doesn't. There gotta be better sorting than triangle averages. Propably per-fragment sorting? However, the problem which you show there occurs in every single game engine I've ever saw in action(Blender Game Engine, Unity 5, Unreal Engine 4). Nobody's found a good solution, appearantly. However - alpha clip looks fine if you know how to set up textures for it.
If you don't care much about performance, you can do some sort of "manual sorting". That, however, requires you to seperate and split many parts of mesh into seperate objects. Sorting algorithms will than work nicely, but performance will have a big hit.

**Comment by DCubix** [comment]
This is an unfix-able problem. I'm closing this until we have a plan.
