### ISSUE TITLE
Standardized error messages.

### ISSUE THREAD

**Issue by panzergame** [UPBGE/blender#199]
I open this issue to talk about a standardized error format for python error and logic brick error.
Indeed currently every commit introduce it's own message format.

for the moment i propose some of my idea:
Python:
"Class(InstanceName): attribut/function message"

Bricks:
"Class(InstanceName): message"

@youle31, @DCubix, @lordloki : What are your format message ?

**Comment by DCubix** [comment]
Cool, here's my proposal:
Python:
`script_name.py(line_number): Error message`

Bricks:
`object_name(brick_name): Error message`

**Comment by youle31** [comment]
for python, I'd say like you panzergame: PyErr_SetString(PyExc_ValueError, "KX_ClassName:attribute/function(args): Expected a boolean")

**Comment by panzergame** [comment]
@DCubix : I agree to pass the srcipt name and the line number for a warning message, but for a error message there's the python backtrace.

What about 3 categories:
Error
Warning
Note

then:
For warning:
Warning in srcipt.py(line) class(instname): Message

For error:
Attribut error:
Error in class(name).attribut: Message

Other error:
Error in class(instname): Message

Note:
Note in srcipt.py(line) class(instname): Message

What do you think guys ?

**Comment by panzergame** [comment]
for functions error or attributs error the wrong values passed should be printed ?

**Comment by youle31** [comment]
I think the line and the args name are enough

**Comment by panzergame** [comment]
I will create a directory name like Common for these tools.

In it i propose a file named Message.h containing functions:

CM_LogicBrickWarning/Error(object, brick, message):
Warning/Error: objectname(brickname), message.

CM_Warning/Error(message):
Warning: message.

CM_PythonWarning/Error(message)
Warning/Error: script(line), message

CM_PythonWarning/Error(class, message)
Warning/Error: script(line): class, message

CM_PythonWarning/Error(class, attributename, message)
Warning/Error: script(line): class.attributname, message

I think macro will be better to passing a message like: "msg" << value << "msg".

**Comment by panzergame** [comment]
If the message will be colored, we will use https://github.com/ikalnitsky/termcolor.

**Comment by panzergame** [comment]
Current status:

![capture datant de 2016-10-28-11h34min27s](https://cloud.githubusercontent.com/assets/8046004/19802145/87e5cfc2-9d02-11e6-8fb3-c9c27fde4bb2.png)

**Comment by youle31** [comment]
great :)
