### ISSUE TITLE
Character jump does not work on linked instances created in official blender

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#2]
[jump.zip](https://github.com/UPBGE/blender/files/65947/jump.zip)

Tested with UPBGE 6fe25a0 on Linux64

**To replicate**
Open attached main.blend in UPBGE.  Observe character jumping does not work.  Space = Python, A = logic bricks.  The same blend in official blender *does* work.

**Workaround**
Open character.blend with UPBGE, select the player object, save, then re-open main.blend

**Steps to recreate the example**
1.  Using official blender - create a character physics object, add to a group, and save as character.blend
2.  Link the group to another blend
3.  Open the new blend in UPBGE, observe that jump does not work

**Comment by panzergame** [comment]
it seems to be a error during the conversion of max jump value from older files. HG1 is the author of a commit about expose max jump value in UI, may he forgotten to add a conversion.

**Comment by pqftgs** [comment]
Did some more testing and it seems to be an issue in master as well.  Probably should have checked that before reporting here.  I've opened https://developer.blender.org/T47014
