### ISSUE TITLE
Reflect Grid -bake grid of static cube map reflections

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#200]
add BPY button  and also an 'in game' API call to bake a grid of static cube maps and store the data in some sort of array,
in a external directory or even packed into a blend (it's going to be a lot of data*)

as objects move through space, somehow we need to blend these maps per actor/object or even rooms.

**Comment by youle31** [comment]
Hi, in bpy, you can already make a little bpy script to do such things. In bge, we implemented cubemap.autoUpdatep API to update/skip the update of cubemap so you can play with it to have static cubemaps. If we implement probes, we'll do it properly but this will be later. For the moment I close the request.

**Comment by youle31** [comment]
@BluePrintRandom : For grids, you can easily make a system yourself like: http://pasteall.org/blend/index.php?id=43293 -> you can decide to update the cubemaps only in a part of the grid

**Comment by BluePrintRandom** [comment]
yes, but how do I interpolate between them in the game engine? (this is the
issue I don't know how to solve*)

**Comment by youle31** [comment]
You dont need to interpolate. Just update one time the cubemaps That enter the camera frustum for example... There are tons of possibilities other than the one You imagine This Is the only one... You don't need to copy the way of work of other engines. I think You have all what You need with the existing system and with the existing api (in ge-cubemap)

**Comment by BluePrintRandom** [comment]
I was thinking along the lines of using a kit like this

https://www.youtube.com/watch?v=gDcL6W-IWxs

I suppose I can create a cubemap that is local to each object somehow, but
how do I maintain instancing and all using 1 material?

The grid solution I think is to deal with these cases,

however I am open to any suggestions as to how to update each panel without
killing the performance.
