### ISSUE TITLE
Standalone is not running for me win 64 - 0.0.9

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#205]
Results on pressing P are very different embedded and stand alone

https://www.youtube.com/watch?v=guIrw6kUUTg&feature=youtu.be

is this already fixed in a newer build? (this is latest official build I think)

**Comment by Akira1San** [comment]
Try the latest build from the forum post: https://blenderartists.org/forum/showthread.php?387752-A-new-fork-of-the-engine&p=3094249&viewfull=1#post3094249

**Comment by BluePrintRandom** [comment]
https://www.youtube.com/watch?v=ScJ7NFWJDyA&feature=youtu.be
[http://pasteall.org/pic/show.php?id=106347](url)
I tried that 2.77.3 and it appears to be starting into the wrong layer*

**Comment by BluePrintRandom** [comment]
why is this not marked as a bug?

**Comment by youle31** [comment]
We can't do anything without a .blend

**Comment by BluePrintRandom** [comment]
[NRRD_upbgeTest3.zip](https://github.com/UPBGE/blender/files/452830/NRRD_upbgeTest3.zip)


this was meant to test reflection mapping anyway :D

**Comment by BluePrintRandom** [comment]
I will try opening a fresh .blend in upbge, and appending all my work and
see if it fixes it,

the workflow at the moment is broken, because I need to use vanlilla
blender for cycles and modeling, then open the work with upbge.

I am thinking this bug is from opening a normal blender file with upbge but
I am not 100% certain.

On Sep 2, 2016 12:58 PM, "youle31" <notifications@github.com> wrote:

We can't do anything without a .blend

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/UPBGE/blender/issues/205#issuecomment-244473390>, or mute
the thread

**Comment by BluePrintRandom** [comment]
Ok- appending to a clean blend fixed it
