### ISSUE TITLE
SCA_PythonJoystick not available

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#206]
The list of sca python joysticks is created in KX_PythonInit -> it creates SCA_PythonJoysticks from availables DEV_Joystick. But Dev_Joystick list is created only when there is a joystick event. So we have to refactor a bit the system to build the SCA_PythonJoystick list after they are created with DEV_Joystick event and refresh the list at each plug/unplug... I'll try to do it but there are things that I never used before so I'm not sure I can do it.

(print(bge.logic.joysticks) always returns an empty list for me)

**Comment by lordloki** [comment]
I will check it

**Comment by youle31** [comment]
Thanks lordloki!

**Comment by youle31** [comment]
this: http://pasteall.org/77607/diff seems to work fine but I'm wondering if we have to do something with decref/incref or if we have to free new SCA_PythonJoystick... What do you think?

**Comment by lordloki** [comment]
I would prefer avoid SCA_PythonJoystick related into DEV_Joystick module.
Maybe something like this: http://pasteall.org/77697/cpp

What do you think?

**Comment by youle31** [comment]
Yeah I'm not very good in code organization... So it's as you and panzergame want.

**Comment by lordloki** [comment]
It is difficult to obtain the joystick index when you are out of DEV module. Maybe the youle's solution (passing de 2 functions to DEV_Joystick.cpp) be the more appropiated. panzergame, what do you think?

**Comment by lordloki** [comment]
@youle31 Could you test this patch? I have no joystick available at this moment.
http://pasteall.org/77937/diff

I think the possible issues are if you can connect 2 or more joysticks at same frame.

**Comment by lordloki** [comment]
Sorry, could you test this one?. It should be work with any number of joysticks connected.
http://pasteall.org/77972/diff

**Comment by youle31** [comment]
Hi, it seems ok :) I just fixed a crash (sometimes I had item non initialized). I took the liberty to push it in a branch ge_joyfix.

**Comment by lordloki** [comment]
Thanks @youle31.
