### ISSUE TITLE
Game exits when you press P key.

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#207]
Game exits when you press P key. Tried the game in Upbge 0.9 and master dev build. In normal bge dont exits. link to game -> https://github.com/jesterelly/sfrenzy

**Comment by DCubix** [comment]
I had the same problem. You have to disable WITH_INPUT_NDOF in CMake.

**Comment by Akira1San** [comment]
Its off in my cmake.

**Comment by youle31** [comment]
http://pasteall.org/77891/diff (a mtex without tex...)

**Comment by panzergame** [comment]
Fixed in master.
@youle31 : the patch is for ?

**Comment by youle31** [comment]
On windows there is a crash not related to play/quit issue. There is a crash because textureinit is called and there is a mtex without tex -> it causes a crash

**Comment by panzergame** [comment]
Fixed in master.

**Comment by SalatielSauer** [comment]
This bug still in the last "stable" version 1.8.
