### ISSUE TITLE
Request: Textured area lights

### ISSUE THREAD

**Issue by alabd14313** [UPBGE/blender#21]
Hi!
I have 2 questions:
1 - Did this fork implement martin upitis's textured area light?
2- When we see Upbge's commits in blender master branch?
Good luck!

**Comment by panzergame** [comment]
Hello @alabd14313.

About the textured area light : the patch should be updated to current blender, cleaned a bit, ect... it can take a lot of time, if you have experience you can start the work and propose a patch or ask for bugs/features.

I'm a bit pessimistic about move commits on blender, for this all the UPBGE commits should be moved, indeed there's to many commit to extract only one of them and apply it on blender.

**Comment by alabd14313** [comment]
I asked second question, because I haven't good memories about candy and harmony branch (They approximately died!). I hope this branch be more persistent...
However, I think future is bright!
http://blenderartists.org/forum/showthread.php?389374-The-bright-future
I' busy on a cookbook and I hope finish it on April, but I try to find bugs.

**Comment by DCubix** [comment]
See pull request #157
