### ISSUE TITLE
UPBGE crash when loading another blend file with logic bricks

### ISSUE THREAD

**Issue by hugobarreira** [UPBGE/blender#215]
Just open upbge 0.0.9 set  keyboard sensor connected to a 'game' actuator, choose blend file to load.
Run game
With embebbed player doesn't crash always
With Standalone Player it crashes everytime

**Comment by BluePrintRandom** [comment]
the file you are loading, was it made in upbge?

**Comment by hugobarreira** [comment]
yes, I was having the issue in a file created on bf bge then I tracked the bug with a file created on UPBGE

**Comment by panzergame** [comment]
See the branch ge_game_reload.

**Comment by hugobarreira** [comment]
tested it and now it works as 2.77, no crash, but still as in 2.77 crashes after 32 loads between 2 files, should I make a bug report on blender bug tracker for the 32 times crash?

**Comment by panzergame** [comment]
@hugobarreira : If you can provide minimal file to reproduce the bug, yes.

**Comment by hugobarreira** [comment]
open 1 of the files, start standalone player press W key 33 times
standalone player will crash

[load 33 times crash.zip](https://github.com/UPBGE/blender/files/466651/load.33.times.crash.zip)

**Comment by panzergame** [comment]
Fixed in 51762c3b80b31b5b940beae78445578dec576acf.
