### ISSUE TITLE
UBGE closes when right clicking onion skin options of armature

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#216]
Tested on official Blender 2.77 and UPGE 0.0.9.
To reproduce this issue, add an armature, go to the armature tab in properties and right click the following area (in any onion skin method).
![bone_ghost_issue](https://cloud.githubusercontent.com/assets/19820741/18421346/d674cd78-785e-11e6-8811-33394414eeea.png)

In official Blender the context menu shows up, but in UPBGE the program closes without any warnings.

**Comment by panzergame** [comment]
UI issue ae very rarely related to the UPBGE, also we are using the BF blender 2.78 not 2.77. @joelgomes1994 : Could you test the same example with a 2.78 build found here http://download.blender.org/release/Blender2.78/ ?

**Comment by joelgomes1994** [comment]
It's working with the 2.78 version, let's hope it works in the upcoming UPBGE release as well. And thanks for the information about the versions. :smile:

**Comment by youle31** [comment]
Hi, this bug is not in upbge 0.1.0 RC so I close the issue.
