### ISSUE TITLE
UPBGE 0.1.0 crash when an object without vertices and a texture is in the scene

### ISSUE THREAD

**Issue by hugobarreira** [UPBGE/blender#218]
no vertices or 1 vertex crash
1 edge doesn't crash
steps:
-Open file with UPBGE 0.1.0 Release-BuildMasterDev
-run embedded or standalone player
-game engine crash
[obj_without_vertices and with a texture_crash GE.zip](https://github.com/UPBGE/blender/files/470675/obj_without_vertices.and.with.a.texture_crash.GE.zip)

**Comment by lordloki** [comment]
I have no crash with lastest sources. Windows 10 64bit

**Comment by hugobarreira** [comment]
I'm also using Windows 10 64bit, are you using the Release-BuildMasterDev ?

**Comment by lordloki** [comment]
I have checked again and this time it crashed but when I previously changed the blender window size only. I will check deeper this evening.
Thanks

**Comment by youle31** [comment]
I can only reproduce the bug in release mode (not in debug mode). When I change mapping from UV to generated or other the crash doesn't happen anymore so I guess this is related to ge_vertex. I make a bisect to confirm.
