### ISSUE TITLE
include basic AI example -> (Follow) - (Follow Attack) -(turret)

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#223]
Can we include some basic BGE AI examples in UPBGE?

No meshes or anything, (Suzannes?)

 But a state machine with chase, flee, and navigate waypoints? also a simple turret ai?

I can code it if you wish.....

**Comment by Akira1San** [comment]
You mean something like a logic brick?

**Comment by BluePrintRandom** [comment]
actually I was thinking like pre-made examples that work well,

templates if you will.
python driven AI can be much more flexible, as bricks can't pass sensor
attributes on positive at the moment.

if we had sensors that set properties that actuators then used.....
something with bricks would be simple.

**Comment by BluePrintRandom** [comment]
Ray(set property target =
Ray.hitObject)----------and-----------SteerTo(target)

**Comment by youle31** [comment]
@BluePrintRandom : I close the request because:
- This is not specific to upbge.
- The thing we need is more video tutorials about upbge features.
- I think this kind of examples have more their place on BA ressource section than on upbge website.
