### ISSUE TITLE
I can donate for help you? Where....

### ISSUE THREAD

**Issue by DaighHiroshi** [UPBGE/blender#225]
I want to help because I value the effort they are giving to improve blender game engine. I think many expect new changes to BGE. Good Luck Staff Blender!! Regards from argentina.

**Comment by youle31** [comment]
Thanks it's nice :) But for the moment we don't have a "donations" account, neither juridic and financial (bank account) structures to accept donations.

**Comment by vlad1777d** [comment]
@youle31 maybe he could donate right to developer's personal bank accounts (by Western union or SWIFT)?

**Comment by panzergame** [comment]
For the moment the status of the project/team is not very clear, so i ask you to delay donations.

**Comment by songproducer** [comment]
Accepting Bitcoin donations does not require much effort. I'd be happy to help or be custodian of btc - I know how to hold them securely and am a long time Bitcoin member in the community.

**Comment by BluePrintRandom** [comment]
http://1.bp.blogspot.com/-TOgDrFlCJXg/UN1S1aiIIWI/AAAAAAAAG-s/OLYGiiW1yw8/s1600/freedomsponsors-kickstarteralternative.png

this may be a good idea ?

**Comment by joelgomes1994** [comment]
@youle31 @panzergame Any news about donations? I would love to donate monthly to the project, and I'm sure that a lot of people would want to do so, especially through easy ways (like Patreon, see how Godot is using it in a nice way: https://www.patreon.com/godotengine ). I hope to see news about this topic. :smile:
