### ISSUE TITLE
Emergency stop in upbge 0.1

### ISSUE THREAD

**Issue by vlad1777d** [UPBGE/blender#227]
Error:
```
vlad@deb:~/Programs/3D/upbge-0.1$ '/home/vlad/Programs/3D/upbge-0.1/blender' 
Read new prefs: /home/vlad/.config/blender/2.78/config/userpref.blend
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x00007fb8bf624580 (most recent call first):
Аварийный останов
vlad@deb:~/Programs/3D/upbge-0.1$
```

_("Аварийный останов" translates like "Emergency stop")_

System: Debian x64 unstable Cinnamon
Version of UPBGE: 0.1
Source: https://download.upbge.fr/download/release/linux64/

**Comment by razvanc-r** [comment]
Also get this error on Ubuntu 16.04, two versions of python installed: 2.7.12 & 3.5.2. Don't know which one upbge picks up

**Comment by youle31** [comment]
When you open blender, it is just a warning message? No crash? @panzergame : Did you built with static libs?

**Comment by panzergame** [comment]
@youle31 : Yes, i built with static libs. @vlad1777d : what's the output of `ldd blender` ?

**Comment by razvanc-r** [comment]
@youle31 I don't understand the question. This happens when you try launching it... this is the crash. This is what I get:

```
 15:24:razvan@alienware:~/Downloads/UPBGEv0.1.0b2.77Linux64$
 🙰  ./blender
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x00007fbc0ca5f800 (most recent call first):
Aborted (core dumped)

 15:24:razvan@alienware:~/Downloads/UPBGEv0.1.0b2.77Linux64$
 🙰  ldd blender
        linux-vdso.so.1 =>  (0x00007fff375fa000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc385747000)
        libpugixml.so.1 => /usr/lib/x86_64-linux-gnu/libpugixml.so.1 (0x00007fc38550f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc385205000)
        libspnav.so.0 => /usr/lib/libspnav.so.0 (0x00007fc385001000)
        libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007fc384d92000)
        libGL.so.1 => /usr/lib/nvidia-361/libGL.so.1 (0x00007fc384b02000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fc3847c8000)
        libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fc3845b8000)
        libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fc3843b4000)
        libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fc3841ae000)
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fc383fa4000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fc383da0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc383b83000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc38397f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc3835b5000)
        /lib64/ld-linux-x86-64.so.2 (0x000055bd5ca12000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fc383393000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc38317d000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc382dfa000)
        libGLX.so.0 => /usr/lib/nvidia-361/libGLX.so.0 (0x00007fc382bc8000)
        libGLdispatch.so.0 => /usr/lib/nvidia-361/libGLdispatch.so.0 (0x00007fc3828e0000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fc3826bd000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fc3824ab000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fc3822a6000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fc3820a0000)
```

**Comment by youle31** [comment]
@panzergame : b2.77? https://download.upbge.fr/download/release/linux64/

**Comment by vlad1777d** [comment]
@panzergame , myne:
>vlad@deb:~$ ldd '/home/vlad/Programs/3D/upbge-0.1/blender' 
	linux-vdso.so.1 (0x00007ffdb65e7000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f543fdd7000)
	libpugixml.so.1 => /usr/lib/x86_64-linux-gnu/libpugixml.so.1 (0x00007f543fb9e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f543f89a000)
	libspnav.so.0 => /usr/lib/libspnav.so.0 (0x00007f543f696000)
	libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f543f427000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f543f0eb000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f543eda8000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f543eb98000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f543e995000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f543e78f000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f543e585000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f543e380000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f543e163000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f543df5f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f543dbc1000)
	/lib64/ld-linux-x86-64.so.2 (0x00005601c728a000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f543d994000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f543d77d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f543d3fa000)
	libnvidia-tls.so.361.45.18 => /usr/lib/x86_64-linux-gnu/tls/libnvidia-tls.so.361.45.18 (0x00007f543d1f6000)
	libnvidia-glcore.so.361.45.18 => /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.361.45.18 (0x00007f543b566000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f543b354000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f543b132000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f543af2c000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f543ad26000)
vlad@deb:~$

**Comment by razvanc-r** [comment]
downloaded `UPBGEv0.1.0b2.77Linux64.tar.xz	2016-09-30 09:29` and works :+1:
