### ISSUE TITLE
LOD system for complex objects

### ISSUE THREAD

**Issue by vlad1777d** [UPBGE/blender#228]
Hello dear friends.
Today I had problems with current LOD system, here are my thoughts about it.

**New idea about LOD system for complex objects:** https://github.com/UPBGE/blender/issues/228#issuecomment-260218535

**Old idea:**
**Subject**:
Many of game objects are made from several objects and are united into groups, or are children of other object.
There is no ability to use Blender's internal LOD system with them, because it only replaces meshes and materials.

**Possible solutions**:
- s1.  place empties on the place of needed objects, place objects itself into hidden layers and use script, which will replace empties to objects, depending on distance from camera to empties.

_**benefits**: 
\> LOD system will work; 
\> every user can set up lod system as he wants;
**disadvantages**: 
\> there is no realtime modelling. Or 3D artist doesn't see what is he doing and how the scene will look like after all; or the the work need to be divided into parts: at first 3D artist made scene, after other people optimized it and created LODs, ect;
So there will be no possibility to edit and preview scene every time it's needed. It's a big disadvantage and all modern game engines try to avoid this.
\> User must more or less know programming on Python;
\> It's slower than to use internal LOD system, written on C++;
\> It'll make .blend files more complex, therefore, it'll be more difficult to navigate in it and edit it;
\> It requires extra efforts from user._
- s2. Combine all objects into one mesh and use Blender's internal LOD system.

_**benefits**: 
\> internal system is enough fast; 
**disadvantages**:
\> we cannot see any time main object, because it appears only when camera in viewport is on certain distance from it, other time it shows LOD objects
(there will be a problems if you need to see all big object, but when you move camera away, it's exchanged to another one. Of course, you could create copy of it on the hidden layer, but it'll enlarge your file and will break the logic if you linked objects to current file);
\> You cannot edit final object normally. You cannot quickly change materials of object's parts  (because GE supports only 1 material with many textures), you cannot quickly move some parts to another places, etc.
This breaks benefits of 3D editor and game engine in one program: you can edit objects any time, simply. And also this means game creation process to be divided into parts: level designing, optimizing, etc, and this will lead to waste of time and powers. One person could not create his little game normally;
\> It requires extra efforts from user._

- s3. **Change LOD system to exchange empties with duplication groups depending on distance from them to camera in viewport and runtime**.
  Than objects with groups will be on the hidden layers (they can be linked from other files), specially created empties on final scene will be replaced with them. This empties can be copied wherever in the final scene. 

What I mean under duplication groups:
![2016-09-26 18-20-14](https://cloud.githubusercontent.com/assets/12682937/18840092/18e90328-8416-11e6-83b0-0bf6aed47ad1.png)
LOD tab may have selector of mode: "group" or "mesh".
"mesh" mode's tab will stay as it was before, "group" tab will be the same to "mesh", but with one exception: there will be the field to choose group, not object:
![lod_groups_v2](https://cloud.githubusercontent.com/assets/12682937/18843096/141f44e2-8420-11e6-98dc-648d8bee4b4b.png)

_**benefits**: 
\> internal LOD system works enough fast;
\> it's convenient to edit objects any time it's needed;
\> it doesn't not litter .blend file and it's convenient to search needed objects;
\> it has explicit intuitive logic structure, and does not require from user special skills;
\> it supplements current LOD system and uses old handles in old places;
\> it doesn't require special object structure, user can choose the most convenient structure himself
(examples of structures: -all parts of complex object are separate objects; -all parts of complex object are children of main object (mesh or empty) (some of them could be children of other parts too))
**disadvantages**: 
\> It touches Blender's parts of code;
\> It requires extra efforts from developers_

Please, tell me what you think about this, maybe we could discuss and decide: which way is better, maybe there are another way, maybe you have some corrections.

Best regards,
Vladislav.

P.S. 
**Temporary decision**: https://github.com/UPBGE/blender/issues/228#issuecomment-260122472

**Comment by youle31** [comment]
With actual code, this seems to not possible. I wait for @panzergame opinion.

**Comment by vlad1777d** [comment]
**Temporary decision**: place origins of objects - parts of one bigger complex objects to one place and set equal LOD distances.
To those objects, which are not needed to display any more, we can assign object with 0 polygons as LOD object.

But this is only a temporary decision - because it decrease convenience in further editing of this object.
And convenience in any-time editing, i think, is one of the main advantages of united program of editor and game engine.

**Comment by vlad1777d** [comment]
I thought about this problem little bit more. 
There must be easier decision, thank binding complex objects to groups.
LODs for complex objects could be set manually.

When you add LOD1, for example, after you specified one object for LOD, there appears another object to choose object, you chose another - appeared third entry. So when will disappear main object, several other objects will appear on certain distance.
Also if complex object consists from several objects, some of them may need to disappear, some of them must stay. So we can add Remove objects entry. At first, there would be only one entry to specify object, which we will remove, when you'll specify one object - another same entry will be added.
And so for each LOD level.


**Advantages:**
- LOD system can handle with complex objects;
- it's more flexible, than approach with groups - some objects can stay for several LOD levels, other may change each LOD level, some objects can be removed at all on certain level, some new objects can be added on certain LOD level;
- It's easier to implement, than approach with groups.

**Disadvantages:**
- requires extra work from game engine developers

**Comment by youle31** [comment]
I close low low priority feature requests for now. They are still visible in closed pull requests list.
