### ISSUE TITLE
Implicit behavior of .setParent() method

### ISSUE THREAD

**Issue by vlad1777d** [UPBGE/blender#230]
Hello dear friends.

Today my friend appealed to me and said, that he wanted to change camera's parent, but it didn't work. 
After this he gave me the test scene. I found and implicit behavior in it, that may confuse not fluent with Python people.

There is an implicit behavior of .setParent method of KX_GameObject.
Example scene: 
[Parent.blend.zip](https://github.com/UPBGE/blender/files/495811/Parent.blend.zip)

Here we have "Sphere" on active layer; "Cube", "Suzanne" on hidden layer ("Cube" is parent of "Suzanne").
Pressing "w" we activate moving of "Cube" forward, "s" - backward; pressing "space" will activate function main() of parent.py. We launch file:
![2016-09-27 18-04-50](https://cloud.githubusercontent.com/assets/12682937/18879433/f34607e8-84dc-11e6-8ef3-d25ef0d2859f.png)

Then we press "space" and move appeared cube:
![2016-09-27 18-07-28](https://cloud.githubusercontent.com/assets/12682937/18879525/465bad52-84dd-11e6-86bb-25767e0033a5.png)
From terminal we see objects in scene: Sphere, Lamp, Camera, \_\_default\_\_cam\_\_, Cube, Suzanne;
and "Cube"'s children: [Suzanne].
So "Sphere" does not became child of "Cube". 
It's all right, because in API we can read that .setParent() needs a KX_GameObject as parent argument, but we gave it the name of object: "Cube".

Let's press "space" another time and then move objects:
![2016-09-27 18-13-14](https://cloud.githubusercontent.com/assets/12682937/18879760/2b27305a-84de-11e6-91c7-41c8ae7fab94.png)
We see, that another "Cube" and "Suzanne" were added successfully:
Objects in scene: Sphere, Lamp, Camera, \_\_default\_\_cam\_\_, Cube, Suzanne, Cube, Suzanne, Sphere.
Cube's children: [Suzanne]
But there was added another instance of Sphere! **<< implicit behavior**
And "Cube" does not became "Sphere"'s parent. **<< implicit behavior 2**
Then when we added new instance of "Cube", new instance of "Sphere" was added too. But original "Sphere" does not got needed parent (it's parent still was "Cube" from hidden layer).

**_Implicit behavior_**: "Sphere" got parent from hidden layer, after adding that object from hidden layer, automatically added all his children, including another instance of "Sphere".
**_Implicit behavior 2_**: method .setParent() must receive only KX_GameObject, but it has worked with string - name of object, which made confusing and another object (object from hidden layer) was made as parent to "Sphere".

Also made confusing fact, that object from hidden layer could be parented; and those fact, that several instances of one object can have one name. 
And those fact, that there was added another instance of object ("Sphere"), that was not on hidden layer. 
(but it's not a bug, if there would not such confusing situation, behavior with adding instances of children objects (whose parents are on hidden layers), would be expected, I think that if after .addObjects() generally are adding all child objects, excluding ones that are on active layer will be more unexpected by users. Also such excluding may lead to that some complex objects will have not some of components.)

If we will repeat pressing "space", there will be just added new instances of "Cube", "Suzanne" and "Sphere". If we would give to .setParent() not string, but KX_GameObject, than all would be well.

**Variants of expected behavior**:
- 1. .setParent() will not apply string and returns an error.

Benefits: 
\> explicit behavior, we certainly know, which object will be parent of which.
Disadvantages: 
\> we need to receive KX_GameObject first, and this is extra efforts, extra amount of code; 
\> flexibility and possibilities of method are reduced.

- 2. .setParent() will apply strings - names of objects, this would be added into API wiki. But every instance must have different name - added suffixes ".inst001" and etc.

Benefits: 
\> explicit behavior, we certainly know, which object will be parent of which; 
\> there would not be objects with same name - uniqueness in namespace.
Disadvantages:
\> extra efforts from developers to implement;
\> untested behavior may lead to confuses and errors.

- 3. .setParent() will apply strings - names of objects, this would be added into API wiki. But it will not add to object parent from the hidden layers, only from active ones.

Benefits: 
\> more explicit behavior 
(if object is on hidden layer - it's excluded from game process, it cannot move, etc. There are not many matters parenting to object, which is in hidden layer (only if you're building a complex object in runtime and going to add new instances of complex object to scene));
Disadvantages:
\> very rare could be such situations, when user will need make object from hidden layer parent to another one.
\> could be confusion on choosing object from several it's instances.

- 4. **.setParent() will apply strings - names of objects, this would be added into API wiki. But at first it'll search through instances of objects that are in active layers, only if there were not such objects, it searches through objects in inactive layers. If second - it'll write warning to terminal.**

Benefits: 
\> more explicit behavior 
Disadvantages:
\> could be confusion on choosing object from several it's instances.

**I suggest to implement 4 variant**, but to think and discuss making different names to all instances.

Could be such situations, when you need choose certain object from several it's instances as parent to another object. If they'll have different names, you'll need to check theirs location or other properties to choose needed one.

Best regards,
Vladislav.

**Comment by panzergame** [comment]
About names, you can change it by assigning to `KX_GameObject.name`. I will look to discard inactive to active parenting.

**Comment by vlad1777d** [comment]
@panzergame , maybe not to discard, but at first search through active layers, at last - on inactive?
And if object from inactive layer was chosen, than to write warning to terminal.

This will not narrow possibilities of Game Engine and will solve such problems.

**Comment by BluePrintRandom** [comment]
setParent() works great - using unique names like panzergame suggested is a
good idea,

also you can use properties and hierarchies to find objects or even group
members.

what are you trying to do that you can't??

**Comment by vlad1777d** [comment]
@BluePrintRandom , bacause of "implicit behavior 2".

Not I, another person wanted to make parent recently added object, but it didn't worked.
He passed to setParent() string, what is not described in API, but this method worked with string. And made wrong object (inactive) parent instead of making recently added object parent.

**Comment by BluePrintRandom** [comment]
added = own.scene.addObject('TheNameOfTheObject',own,0)
added.setParent(object,0,1)

what is the nature of the added item that parents to?

**Comment by vlad1777d** [comment]
@BluePrintRandom It's object with mesh - "Cube".

**Comment by BluePrintRandom** [comment]
I mean, in what context do you need to parent?

many times I use a ray, or a property or even distances to find who is who
and what is what.

like

end = own.worldOrientation.col[0]*100
ray = own.rayCast(end,own.worldPosition,'',0,0,0)

if ray[0]:
    added=own.scene.addObject('BulletDamageSprite',own,0)
    added.worldPosition=ray[1]
    added.alignAxisToVect(ray[2],2,1)
    added.setParent(ray[0],0,1)

#add a bullet damage sprite to where a ray hits

**Comment by vlad1777d** [comment]
@BluePrintRandom after pressing "space", "Sphere" got unlinked from "Cone", adds "Cube" with "Susanne", got "Susanne" as parent and removes near "Cylinder".
[parentandendobgect.blend.zip](https://github.com/UPBGE/blender/files/496496/parentandendobgect.blend.zip)

The essence from this will be next:
man goes to horse, after pressing button man will be removed + will be removed near horse. And on their place will be added model of man on horse, and empty with camera will be set as child to that mode.

**Comment by BluePrintRandom** [comment]
then you will check for horse with a keypress to climb on?

during this check,  (ray.hitObject, or near.hitObject, or radar.hitObject)

you have the horse.
you have the man you are adding
you have the man you remove.

you should be good to go.

**Comment by vlad1777d** [comment]
@BluePrintRandom yeas, all right.

**Comment by youle31** [comment]
We'll maybe add a warning to tell that you are parenting to an object in an inactive layer. I add it to our task list (@panzergame: I add it to the framapad) and close the bug report.

**Comment by vlad1777d** [comment]
@youle31 and searching on active layers first?

**Comment by youle31** [comment]
@vlad1777d : We'll find a good fix (I added it to our task list)

**Comment by vlad1777d** [comment]
@youle31 thanks =)
