### ISSUE TITLE
Quad Tree and Oct Tree for mathutils

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#240]
for game development we need to sort through large tables of vectors every frame for things like LOD and dynamic loading or terrain streaming,

KDtree is faster to then a python based quadtree or octree for these tasks at the moment,
only because KDtree is in C / native code

I also purpose we investigate feeding a whole game mesh into KDTRee and BVHTree.
(for in game mesh editing and painting that can update each frame without killing the FPS)

**Comment by BluePrintRandom** [comment]
@Nazg-Gul 
Do you know if this would also be welcome in master/vanilla blender?

**Comment by Nazg-Gul** [comment]
For Blender it might be handy to use QBVH with good vectorization. But such things are to be discussed within Blender's ML imo since all the active developers in related are in there.

**Comment by BluePrintRandom** [comment]
I get moderated right out of that list Sergey -* no matter how valid my
topic is.*

I guess I can propose it on irc - but they tend to ignore me there as well*

**Comment by youle31** [comment]
I close low low priority feature requests for now. They are still visible in closed pull requests list.
