### ISSUE TITLE
Animated Textures not working in UPBGE

### ISSUE THREAD

**Issue by Awesomeplayer** [UPBGE/blender#241]
hey, I love UPBGE, it has all these cool features including reflection. so I thought I would make a realistic water using animated normal maps and realtime reflections. But turns out, it doesnt work, neither does any animated texture. Can you guys look into it quickly?

**Comment by Maujoe** [comment]
Hm I'm not a developer but I have tested an animated texture and for me it working in upbge, so maybe there is something missing in your settings? You could upload a little example file.

**Comment by panzergame** [comment]
Hello @Awesomeplayer. Sorry we can't do nothing without any example files showing the issue.

**Comment by youle31** [comment]
@Awesomeplayer : I think you won't have good results with cubemap reflections. We are working on planar reflections but it might take a while to implement. To follow development: https://github.com/UPBGE/blender/pull/239

About your animated textures bug, could you share a .blend please?

**Comment by Awesomeplayer** [comment]
Here is a file, but you have to rename it to UP.blend in the properties in order to open it in UPBGE.
I  renamed it like this cz there was no other way of uploading it :p 

[UP.txt](https://github.com/UPBGE/blender/files/508397/UP.txt)

**Comment by youle31** [comment]
You surely did a mistake while setting up the animated texture. It works for me: http://pasteall.org/blend/index.php?id=43823 (I started with a new setup). iirc animated textures must be created in a specific order, else it doesn't work. As your .blend didn't work in BF bge too, it is not specific to upbge, so I close the issue. For support about bge, I think the best is to ask on blender artists forum, or to find a good tutorial on the net :)

**Comment by Awesomeplayer** [comment]
well, I probably missed something :p 
anyways, thanks for taking the time to see into it!
