### ISSUE TITLE
Does UPBGE support Area Lights yet?

### ISSUE THREAD

**Issue by Awesomeplayer** [UPBGE/blender#242]
So I was thinking if UPBGE supports Area Lights or not, if so, it'd be severely cool :v

**Comment by Maujoe** [comment]
I think they haven't integrated area lights into the last upbge release because there are some problems with it at the moment ([https://github.com/UPBGE/blender/pull/157](url)). But maybe area lights are supported in the future.

**Comment by youle31** [comment]
Hi, we are stuck for the moment about area lights but it is still a WIP and I hope it will be merged in a future release, but I can't say when. To follow development:  https://github.com/UPBGE/blender/pull/157
