### ISSUE TITLE
Bug while reading script module name in SCA_PythonController.cpp

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#248]
I have a bug when I open this file in upbge: http://pasteall.org/blend/index.php?id=43853

Python controller found the module but could not access the function - object 'Cube', controller 'Python':
AttributeError: module 'test' has no attribute 'main'

**Comment by panzergame** [comment]
iirc `test` is also the name of a built-in python module. Try rename the module `Test` for example.

**Comment by youle31** [comment]
Yeah it's surely that. when I renamed to test1 it worked so I searched on my desktop if I had no folder or file named "test" but it was not the case so I made a bug report. I forgot to look at builtins modules. Must be that because there are many test folders in blender build folder. I close the issue so
