### ISSUE TITLE
Layered Variance Shadow Maps

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#25]
I found this "Layered Variance Shadow Maps", looks like an upgraded VSM.
link to pdf -> http://www.punkuser.net/lvsm/lvsm_web.pdf
forum post -> https://forum.beyond3d.com/threads/layered-variance-shadow-maps.42174/
This looks interesting, what do you think?

**Comment by adriansnetlis** [comment]
This would give a huge graphical boost!:)
