### ISSUE TITLE
How can I compile on OSX?

### ISSUE THREAD

**Issue by songproducer** [UPBGE/blender#251]

**Comment by Akira1San** [comment]
Use this -> https://wiki.blender.org/index.php/Dev:Doc/Building_Blender/Mac

**Comment by songproducer** [comment]
Thanks. I'm having some trouble compiling at the moment:
https://developer.blender.org/T49598

But once I can, I will give it a shot!

**Comment by BluePrintRandom** [comment]
it works ?

**Comment by songproducer** [comment]
Yes but there were some problems with the textures, see https://github.com/UPBGE/blender/issues/255

I will try the hack today to see if it's been resolved.
