### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by songproducer** [UPBGE/blender#254]

**Comment by youle31** [comment]
No there is no mobile support. It would be very difficult to implement. Maybe we'll do it but it's not for tomorrow. Sorry ...

**Comment by BluePrintRandom** [comment]
after 2.8 when the immediate mode draw calls are all gone, it will be a
different story correct?

**Comment by Akira1San** [comment]
I think, that to do android, the bge will need to be able to change the backend From OpenGL to OpenGLES. So far the raster and other parts using GL calls need to be replaced with GLES calls, is that correct? If so, then a good example would be to mimic the JMonkeyengine, where they recode its engine raster to be easy and changeable backend.
