### ISSUE TITLE
SCA_IActuator attribute that shows if actuator is currently active

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#257]
Hello! It's an feature request that probably is easy to implement, but it still very useful.
Since the only way (that I know) to check if an actuator is running is using the Actuator sensor, and it may not be friendly to check several different actuator states this way (by adding one sensor to each actuator), I think that all the actuators (the class SCA_IActuator) should have an attribute showing its current state, something like isActive, status, or such.
The idea came to me when I was trying to check if an sound is playing with the Sound actuator, and the only way was using the Actuator sensor (since the Sound actuator is active while the sound is playing, by my Python experiments).
I know that some (most) of the actuators are active only during a logic tick (ex: Add Object), and the attribute isActive could be useless to them, but other actuators could benefit enormously by this addition.
I hope you consider the request, and thanks! :smiley:

**Comment by youle31** [comment]
In fact each actuator has a method Update that return true or false. This bool is if the actuator is active or not. So it would be relatively easy to do...

**Comment by joelgomes1994** [comment]
Since this is possible (probably easily), can this be implemented, please? About the 1 frame lag, I don't know.
I don't even know why this issue has been closed.
