### ISSUE TITLE
Camera lod factor (UI/API)-option for realtime reflections/refractions

### ISSUE THREAD

**Issue by Maujoe** [UPBGE/blender#260]
Hey, I think the render time of realtime reflection/refraction could be improved by the camera lod factor.

So far I know it's a common technique to render the scene with less detail 
(for example GTAV Environment Cubemap :http://www.adriancourreges.com/blog/2015/11/02/gta-v-graphics-study/) 

So for now it would be a nice step if there would be a UI/API option to set the camera lod factor for the individuel cubemaps and planar reflections/refractions renderings similar to the clipping settings.

(I have another idea to improve this kind of renderings but I don't want to make to many feature requests at the same time)

**Comment by youle31** [comment]
Hehe I did it :P https://youtu.be/9doafRuMa8I It was not easy: https://github.com/UPBGE/blender/pull/263

**Comment by Maujoe** [comment]
Oh Thanks, I haven't known that it isn't so easy. 
I thought the lod works for all cameras that render something, so that only the lod factor must be set for the cubemap camera. Sorry for that :/

Even more bad that it doesn't gives improvements. 
So probably the lod operations (calculation + replace) take to much performance (I haven't thought that it takes so much). Normally rendering 25k polys should be slower than one cube.

Can you give me a compiled testbuild or is it to complicated?

**Comment by youle31** [comment]
@Maujoe : Here is a win64 build: https://drive.google.com/file/d/0B3GouQIyoCmreG1PM2ZUYVNNZmc/view?usp=sharing

**Comment by BluePrintRandom** [comment]
what are you using for the spatial search?

is it accelerated using a tree structure in Kupoman's original patch?


I have been reading about QBVHTree

**Comment by BluePrintRandom** [comment]
https://www.uni-ulm.de/fileadmin/website_uni_ulm/iui.inst.100/institut/Papers/QBVH.pdf

**Comment by youle31** [comment]
@BluePrintRandom : I use Kupoman LOD for blender part. And custom code + all what I thought I can reuse in bge part.
@Maujoe : A more stable release I think: ...uploading...

**Comment by Maujoe** [comment]
@youle31 Thank you. You are right there are cases where it makes no improvements to the performance. But I also have cases where it increase the performace. But currently I'm not completly sure when it's the case. It looks like it depends a little bit on the amount of objects and their polycount. I will make some more tests..

**Comment by youle31** [comment]
In fact i'm not convinced about This option because You Can have a low poly copy of your scène in layer 2 and use ignoreLayer 1 so the objects rendered Will be low poly... Maybe This Is a better approach

**Comment by Maujoe** [comment]
You can ignore layers? Or do you talk about a feature that can do that?

**Comment by youle31** [comment]
Yeah we can ignore layers and control culling. All Is explained in the release notes and i made a vidéo tutorial too ( also in the release notes)

**Comment by Maujoe** [comment]
Oh sorry, I must have overlooked it. Yes this should run better than the lod, that's right.

**Comment by BluePrintRandom** [comment]
do you think you may use a depth mask for composting static cube maps into
realtime?

(like cubemap layer 2 is pre computted grid of cubemap of all objects on a
layer, and all dynamic objects are rendered on top of it, if their zdepth
is closer then the zdepth of the static map?)

*like mirrors edge*

**Comment by youle31** [comment]
@BluePrintRandom : You can already uncheck auto update-> this will create a static cubemap at ge start. Then you can choose to update your cube map with the objects you want using IgnoreLayers with python api:

e.g: if own.getDistanceTo(cubemapobj):
cubemap = cubemapobj.meshes[0].materials[0].textures[0].cubeMap
cubemap.ignoreLayers = (1 << 1) | (1 << 3) #render only objects in layer 3 (first layer is (1 << 0))
cubemap.update() #the static cubemap will be updated (rendered) with this call

**Comment by BluePrintRandom** [comment]
the idea of the cubemap grid is to prerender the really heavy stuff,
I will then use a tree structure to load in and out the images,

but one issue, is the cubemap texture unique per object?
(not per material*)

**Comment by youle31** [comment]
you can have several cubemaps per objects (didn't test but the code doesn't break at the first cubemap texture found). So I guess you can have one static in first texture slot and one dynamic with a python script in the second texture slot

**Comment by youle31** [comment]
http://pasteall.org/blend/index.php?id=44007

**Comment by Maujoe** [comment]
So I think the original feature request is answered now. 

I don't know why I haven't seen the ignor layer option but it works perfect. 
In general a render layer system per camera would be a nice idea so that you can configure the render layer for the cameras independent from the global viewport setting. 

But it isn't so essential at the moment and it is another topic so I think this request can be closed.
