### ISSUE TITLE
Sintel Docs level crash with master compiled

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#268]
Tested with latest master branch. Use vbo, use frame rate off, p key and blender exits, standalone will crash.

(20/10/2016)

**Comment by youle31** [comment]
I confirm and I guess this is the same bug that I mentionned ("random crash in desert level"). Maybe related to vao, not sure.

**Comment by youle31** [comment]
@Akira1San : Can you confirm that this build doesn't crash anymore: https://drive.google.com/file/d/0B3GouQIyoCmrdHpTWmNEZzJQcnc/view?usp=sharing (I just removed vao from VBO::Bind and VBO::UnBind)

**Comment by Akira1San** [comment]
No crash.

**Comment by panzergame** [comment]
Did 0a4ae9cf3446385e704872a3153197d16e783cad is solving the issue ?

**Comment by panzergame** [comment]
It should be fine after ecb53e7080866944b691b88b1614b012ed936751.

**Comment by youle31** [comment]
@panzergame : Sorry it still crashes for me :/

**Comment by youle31** [comment]
fixed in https://github.com/UPBGE/blender/commit/beb9189b687d75227aee5c3993a248c0ebc91bf4
