### ISSUE TITLE
Request: Allow in-game switching of materials

### ISSUE THREAD

**Issue by sdfgeoff** [UPBGE/blender#27]
Currently a game object is stuck with the material it starts with. The only way to change it is by setting the source of GLSL fragment and vertex shaders. This has two disadvantages:
 - They need to be GLSL shaders and therefore can't have shadows
 - Each time you change the material in this manner it recompiles the shader which is slow

I propose adding a setMaterial function to the mesh object:
    obj.meshes[0].setMaterial(mat_id_to_replace, bl_shader_instance)

While you still have to use an existing bl_shader instance, this should be relatively easy to implement and vastly speed up one thing I'm working on.

**Comment by youle31** [comment]
@sdfgeoff: I don't know if changing material during runtime can be easy... I think this is like light.type (we can't change it without to have to recompile the shader... But maybe Tristan has a better idea about that.
But what we could do is a function that copy all other material properties and apply it to our material.

- Copy  a material properties and assign it to our material can already be done (for the most part) with new KX_BlenderMaterial API:

KX_PYATTRIBUTE_RW_FUNCTION("alpha", KX_BlenderMaterial, pyattr_get_alpha, pyattr_set_alpha),
	KX_PYATTRIBUTE_RW_FUNCTION("hardness", KX_BlenderMaterial, pyattr_get_hardness, pyattr_set_hardness),
	KX_PYATTRIBUTE_RW_FUNCTION("specularIntensity", KX_BlenderMaterial, pyattr_get_specular_intensity, pyattr_set_specular_intensity),
	KX_PYATTRIBUTE_RW_FUNCTION("specularColor", KX_BlenderMaterial, pyattr_get_specular_color, pyattr_set_specular_color),
	KX_PYATTRIBUTE_RW_FUNCTION("diffuseIntensity", KX_BlenderMaterial, pyattr_get_diffuse_intensity, pyattr_set_diffuse_intensity),
	KX_PYATTRIBUTE_RW_FUNCTION("diffuseColor", KX_BlenderMaterial, pyattr_get_diffuse_color, pyattr_set_diffuse_color),
	KX_PYATTRIBUTE_RW_FUNCTION("emit", KX_BlenderMaterial, pyattr_get_emit, pyattr_set_emit),

RW means read and write.

- For shadows in custom shaders, you can have a look here: http://blenderartists.org/forum/showthread.php?390765-Custom-GLSL-Materials-with-Shadows

**Comment by panzergame** [comment]
@sdfgeoff : So you want to replace material for a RAS_MeshObject not per game object : RAS_MeshSlot ?
If yes i propose the following API:
KX_MeshProxy.replaceMaterial(matid, KX_BlenderMaterial)

But here we will get some trouble because there's no way to find a KX_BlenderMaterial other than found it in a mesh, so if we replace it, it's lost the the material.....
The solution shoudl be to expose a list of all material in a python proxy for the KX_BlenderSceneConverter.

**Comment by sdfgeoff** [comment]
Well I believe materials are associated with meshes, or at least, a texture slot in a mesh. As such it makes sense for the operation to be on a mesh.

If you replace it it's lost. That's fine by me.

**Comment by axredneck** [comment]
Is it possible to implement tweaking the same material by passing some per-object "uniforms" to the shader, like "Object Color" already does? I know it's not exactly "switching of materials" but it can serve the same purpose, especially if passing these "uniforms" to node material.

**Comment by panzergame** [comment]
@axredneck : I was thinking of a python callback ran just before update object uniform of the custom shader. But it's only for custom shader not for blender material.
Else material switch will be targeted in 0.1.1.

**Comment by panzergame** [comment]
https://github.com/UPBGE/blender/pull/244
