### ISSUE TITLE
Framerate issue when vsync off and use framerate disabled

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#270]
hbar reported an issue: http://pasteall.org/86828 (there is the TwisterGE link to the old discussion inside)
I'm having troubles too with this file for example:
http://pasteall.org/blend/index.php?id=44023

All is "accelerated".

Conversation suite: http://pasteall.org/86830

hbar gave me this link: http://fabiensanglard.net/timer_and_framerate/

**Comment by panzergame** [comment]
The logic is executed for every frame, so if you rotate the camera at 800FPS instead of 200FPS it will be a lot faster.

There's generally two solutions :
- the user multiply the rotation by the frame time or use an animation ;
- the engine doesn't run at every frame the logic.

@youle31, @DCubix , @lordloki: For you what is the best choice ?

For the moment i will try working in the second solution.

**Comment by panzergame** [comment]
I'm not very sure about clamping logic framerate: If we took the example of the water shader scene, if the logic frame are clamped only the physics, animations and the render we will be done more, But as this file depends on an ImageRender which is done in logic the result will be very weird. The water will look static for a very short time.

**Comment by youle31** [comment]
For me, when we disable vsync and use framerate, all should be accelerated.
The frametime has not to be capped. It means the fps has to be the maximum fps supported by the computer.

What is wrong in my opinion, is to make bullets physics collisions checks per seconds a reference for any other computation of framerate.

I mean, when "use framerate" option is checked, it should not be related to physics framerate, but an other framerate option. Physics should have its own framerate. And the new option should be used to compute logic time and and render loop time.

But my ideas are not 100% clear about that.

**Comment by youle31** [comment]
I close the issue as it is not really an issue.
