### ISSUE TITLE
Bug with GLSL shader (I think) (ground)

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#278]
http://pasteall.org/blend/index.php?id=44123 (works in BF Blender 2.78, not in upbge)

**Comment by panzergame** [comment]
Can you bisect the faulty commit ?

**Comment by youle31** [comment]
I'll try when I'll have motivation :)

**Comment by youle31** [comment]
First bad commit: https://github.com/UPBGE/blender/commit/0f527cebe45d76cb49228b6312e1aeaf3d912285

**Comment by panzergame** [comment]
Similar issue to https://github.com/UPBGE/blender/issues/279. But here the shader need a bit more rewrite.
