### ISSUE TITLE
Render to texture via a texture slot (like environment map)

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#281]
can we move render to texture into a texture slot (like a cube map?)

this can then also have things like ignore layers etc (like the cube maps)

Thanks!

**Comment by youle31** [comment]
Hi, maybe such thing could be done but we need to think about it.

This would allow to avoid python scripting and we could take example on cubemaps UI.

But VideoTexture module is enormous, contains many features (video, viewports, mirror etc...) and I don't know if we could put all of that into a/some UI(s). So this may be a hard task.

We already implemented planar reflections (alternative to ImageMirror) with a specific UI (I think I should try to refactor planar reflections UI taking example on CubeMaps UI... I need to think about it to see if it's easy/possible).

So this task will depend on devs motivation and we'd need to discuss it.

**Comment by BluePrintRandom** [comment]
what about just doing modes one at a time with a dropdown,
only support 1 initally etc?

**Comment by BluePrintRandom** [comment]
Why close? 

This exposes high level features to newbz.
