### ISSUE TITLE
Feature Request: Logic Brick to Interact with Python Component

### ISSUE THREAD

**Issue by sdfgeoff** [UPBGE/blender#283]
If you have a python component, it would be nice to be able to present a logic-brick interface to it.

**Use cases:**
 - A FPS movement script, that exposes functions like "duck" to the logic brick interface
 - A vehicle that expose functions like "drive" and "toot horn"
 - A "damage" component that provided a logic brick interface for "onDeath" and "onHit" as sensors.
 - A "keymapper" component that abstracts from "W" on the component to the "Forwards" action.
 - A "hover-car" component that allows the user to control the size of the flames coming out the back.
 - A weapon component that exposes a "reload" and a "shoot" interface.

**Suggested interface from python:**
Ideally two dictionaries of: 
```
{
component_function_name: {parameter_name:default_value, parameter_name:default_value}
component_function_name: {parameter_name:default_value, parameter_name:default_value}
}
```
But could be a 3-deep tuple instead:
```
(
component_function_name, ((parameter_name, default_value), (parameter_name, default_value))
)
```
It needs two of them, one to allow the python component to act as a sensor, one to allow it to act as an actuator.

**Suggested interface from logic bricks:**
 - A drop down box to select from python components attached to the body
 - The parameters appear in the brick

**Comment by DCubix** [comment]
That would be completely against the purpose of Python Components: Avoid LBs :stuck_out_tongue:

**Comment by pqftgs** [comment]
My use-case is a 3D platformer with simple button puzzles.  Put a component on the button, designer can link them up and perform an action when all buttons are pressed.

As it is, you can document valid properties and have your designers add them by hand (which is what I'm doing now) but that workflow is far from optimal.  Something like sdfgeoff mentioned, combined with user-defined help links, is the silver bullet at least in my opinion.

**Comment by sdfgeoff** [comment]
> That would be completely against the primary purpose of Python Components: Avoid LBs
If you write a python component, you may want to share it without requiring the receiving party to have to understand python. Currently sharing python scripts is pretty useless as you have to be able to understand a python script to use it. If we can provide a way to create interfaces for them, then it isn't.

>You can already tweak parameters by adding properties to the args dictionary. The UI is automatically generated.
Yes, but that's static. I want something editable at runtime. Consider a FPS script. Either I can have as arguments strings for what keypresses do what, or I could have a much more "normal" interface of using BGE's logic system to handle it.

Here's a screenshot of the setup I use for a walking robot:
![](https://s22.postimg.org/pv52t9xzl/walking_robot.jpg)
(Video of robot here: https://www.youtube.com/watch?v=D-7q9aHWVsc)
Pretty much I use the linear velocity of the robot to control everything within the component. But this is not sufficient in all cases (and barely sufficient in this one). It would be better to expose a custom run-time interface in an actuator.
(Another application could be a "damage" component that provided a logic brick interface for "onDeath" and "onHit")

**Comment by vlad1777d** [comment]
I had similar situation (not very, but similar), suggested to add "activate brick actuator" and "activate brick methods" here: https://github.com/UPBGE/blender/issues/195
They could partially implement interface ideology.

Also I have not time to create issue to add into "Property" logic brick possibility to select object, on which you could change property. I'll create such issue later.
Maybe it's good idea to add into this logic brick possibility to select Python components besides of objects as target to change their properties.

**Comment by youle31** [comment]
For the reasons I exposed here: https://github.com/UPBGE/blender/issues/292, I put this request in low priority for now.

**Comment by youle31** [comment]
I close low low priority feature requests for now. They are still visible in closed pull requests list.
