### ISSUE TITLE
Animation of Sun's energy value doesn't work from actions

### ISSUE THREAD

**Issue by vlad1777d** [UPBGE/blender#288]
Hello dear friends.

There is a problem when animation of sun's energy value doesn't work.

**When it works?** _<file, where it works: [test_sun_animation_works.blend.zip](https://github.com/UPBGE/blender/files/572790/test_sun_animation_works.blend.zip)>_
\-When you create keyframes in the Dope Sheet, not in action editor (you can see keyframes properly). Than created animation (default, which is one per object) belongs to Lamp object (child of main Sun object), not to the main Sun object:
![2016-11-05 00-51-36](https://cloud.githubusercontent.com/assets/12682937/20024909/4365697a-a2f2-11e6-8aba-efeeff6cde36.png)
\-We run game engine (previously created appropriate logic bricks), animation works well.

**When it does not work?** _<file, where it doesn't work: [test_sun_animation_doesnt_work.blend.zip](https://github.com/UPBGE/blender/files/572801/test_sun_animation_doesnt_work.blend.zip)>_
\-When you create action in Action Editor first, than you add keyframes.
_(keyframes are added into the animation of Lamp object (child of Sun), not to Sun object:
![2016-11-05 01-07-27](https://cloud.githubusercontent.com/assets/12682937/20025205/e652b866-a2f4-11e6-8870-8a3fded217fd.png).
(you cannot see keyframes in Action Editor, but you can see them in Dope Sheet)
And animation of Lamp object is absent in Action Editor's list:
![2016-11-05 01-13-29](https://cloud.githubusercontent.com/assets/12682937/20025243/3421c870-a2f5-11e6-9568-603a82d61559.png)
, this makes confusing)_

\-We run game engine (previously created appropriate logic bricks), animation doesn't work.

_(because we add animation that was in action list (Sun object's), not that animation, which is absent there (Lamp object's). But keyframes adds only to animation, which is absent in list. 
So to fix this we can add to logic brick name of Lamp object's animation (it's present in logic brick's list), but than we could not create several different animations with different keyframes for different purposes to Sun object. It wides possibilities and flexibility of engine very much.)_

**Ways to correct this situation:**
\- Make that after selecting Sun object and creating action in Action editor, when you press "insert keyframe" after right mouse button click on some property, keyframes are added to selected action (animation), not to default action.

**Details:**
\- How do I add keyframes? _\>Right click on Sun's energy value, than "insert keyframe"._
\- Was sun's energy value present in keyring set? _\>No, I got an error: "Cannot add property to built in keyring set" when I tried to add it there._

System: Debian x64 unstable
UPBGE's version: 0.1.0 (01.10.2016, 12:08)

Best regards,
Vladislav

**Comment by youle31** [comment]
When you go to sun panel, place your cursor on sun energy and type i. Then go ten frames later, set a new energy value and type i again. This creates a sun energy action. This is the simplest way. No need to look at dopesheet or so, just timeline. We can't make a new logic brick for that as it is really simple to have it working. As this is not really a bug, as it doesn't concern upbge only, as it is more a BF Blender internal non upbge thing, I think we can close this issue.

But I wait for panzergame opinion on the subject.

quick test file: http://pasteall.org/blend/index.php?id=44161

**Comment by vlad1777d** [comment]
@youle31 , no, you still cannot switch to another action because created action, that cannot be changed.
You cannot see it's keyframes in Action Editor and you cannot have several actions of this value.

Another thing - Cube object. You can create action for it in Action Editor. Than you can add keyframe to it with "insert keyframes on ..." from timeline and keyframes will be added to this action.
Then you can create new action, keyframes will be added to it.

So you can play several actions for Cube object in game engine, depending of case.
<your file with Cube's animations: http://pasteall.org/blend/index.php?id=44167 >

**Comment by youle31** [comment]
Sorry i don't understand. There are many things about actions to know, related to fake users for example... I don't know if it Is related  to your problem. But i still think it comes from a wrong usage of actions and That it concerne more blender than blender game... However i'm not totally sure because i don't really understand the problem...

**Comment by youle31** [comment]
https://developer.blender.org/T45753
