### ISSUE TITLE
ray true set property

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#289]
add a method to the ray brick (checkbox?)
that exposes two dropdowns, one dropdown is available properties the other is data gathered from the ray being positive,

this could tie into logic node type behaviors from simple bricks, one function at a time.

**Comment by vlad1777d** [comment]
I did not understood what do you mean certainly, but data, gathered from the ray is in next properties:
\- KX_RaySensor.hitObject;
\- KX_RaySensor.hitPosition;
\- KX_RaySensor.hitNormal;
\- KX_RaySensor.hitMaterial.

There is only one property available in one logic brick, as I know, so dropdown is not needed.
Such property you can receive from Python so:
\- KX_RaySensor.propName;

Also you could enable searching not for property, but for material by setting to True   KX_RaySensor.useMaterial, but I don't know how to set such material from Python. Maybe you need to specify name of material in KX_RaySensor.propName, not the property name.

**Comment by youle31** [comment]
The data gathered from the ray sensor is only available during runtime, so it's not possible to create a dropdown UI menu to expose the data gathered. So I close the request. If a dev doesn't agree, he can reopen it.

**Comment by BluePrintRandom** [comment]
the data used to set the property is a pre selected slot,
(like hit object or hit position)

when a sensor is true data from this 'slot' gets popped into a property

a ray sensor can even have data when it is false,
like ray.hitObject = None.

the drop downs would be data 'holdouts' for data gathered by a sensor.

**Comment by youle31** [comment]
I don't really understand sorry... But I think this is not the time to work on logic bricks as we don't know the ways the logic will be refactored on 2.8

**Comment by BluePrintRandom** [comment]
Currently One can use this logic

ray--python--steering actuator

python

import bge
cont = bge.logic.getCurrentController()

ray = cont.sensors['Ray']

steering = cont.actuators['Steering']

if ray.positive:
(tab)steering.target=ray[0]
(tab)cont.activate(steering)

what I purpose would do the same thing but by using a property to hold a
game object set by the ray,

using this logic

ray(set property target to ray hitobject)-------and-----steering(to target)

**Comment by BluePrintRandom** [comment]
the property is acting like a node link*

**Comment by vlad1777d** [comment]
@BluePrintRandom , there could be too much values for dropout, as I think.
Than we could filter them, if such value is already present, than not double it.

But this is very specific behavior, it's needed very rarely. I think that there is no need to write C code to implement this (this'll not low speed very much, but it'll make UI more complex).

If needed, this could be implemented with several lines in Python:
"""
import bge
scene = bge.logic.getCurrentScene()
ray_sensor = scene.objects['ObjectWithRay']

values_list = []
current_object = KX_RaySensor.hitObject
if current_object:
....if str(current_object) not in values_list:
........values_list.append(current_object)
"""

**Comment by BluePrintRandom** [comment]
I can do almost anything I want in python right now,

here is some of my work - https://www.youtube.com/watch?v=M9UqUYQBHfw

the dropdowns already exist in the property sensor (check it out)

(to select a property inside the game object containing the sensor)

the sensor being true would fire just like normal, except if a checkbox is
ticked it would also set a property.

the only dropdown that does not exist already is for the sensor  attributes
(ray.hitObject, ray.hitPosition, ray.hitNormal etc)

eventually more attributes like hitDistance would be useful as well.

**Comment by vlad1777d** [comment]
@BluePrintRandom , that's all because "Property sensor" can listen to only one object and only one property. There is no need to write it manually - dropdown lists can help us with this.

But ray sensor searches only properties or materials. It's not bound with any objects. That's why there is absent object dropdown list.

Ray sensor can search for any property, even if it's absent on objects now. Such properties can be specified with scripts in runtime. That's why there is no dropdown list for properties. Because in such lists cannot be chosen value, that is absent there.

One thing - materials, that currently use dropdown lists. But materials can also be imported while runtime with libLoad. So I don't know: good or bad, that there is present dropdown lists for material, because I cannot specify there material, which is currently absent (for such cases I can use Python API's rayCast() method).

**Comment by BluePrintRandom** [comment]
You don't understand

See this ? 

with this 1 actuator - 1 controller and 1 sensor -> we have an ai that will chase ANY object with the property 'Enemy' in it. 

(currently to get flexibility like this out of a system you must use python)


![sensorset_property_actuator_use_property](https://cloud.githubusercontent.com/assets/7190873/20109702/2206defc-a596-11e6-8aac-bbfc346eb0cc.png)
