### ISSUE TITLE
Steering actuator accept property as target

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#290]
if a property is set as a target and is a valid game object - proceed to run steering actuator targeting this game object.

combined with ray set property, one could make ai very simple.

**Comment by BluePrintRandom** [comment]
ray set property target--------and-----------steer  to property target

**Comment by youle31** [comment]
When you use property for ray sensor, it detects the first object with the given property hitted by the ray (hitobject). In actuator, which object with the given property will the object seek?

In my opinion, this request seems undoable. Furthermore, it seems to me that it is not enough important to deserve that we rewrite an actuator. So I close the request for now. If a dev consider that the request should be reopened, he can reopen it.

Sorry, I'm doing the "killerjoy" job closing what I consider not so important or undoable :/ Bad job, I'm creating myself ennemies

**Comment by BluePrintRandom** [comment]
you are not my enemy,  I just think you don't understand the utility.

if we do this

(sensor can set properties and actuators can use properties)

then total newbs to python could make Ai etc,

this is to expand the adoption of the engine.

ray is true, set property target as ray hitobject,
trigger steering actuator (steer to target)

**Comment by youle31** [comment]
but several objects can have the same property so which object we choose?

**Comment by BluePrintRandom** [comment]
only the properties inside the object containing the actuator and sensor

sensors can set properties only in objects they are in

actuators can only access properties to use from objects they are in

with the exception of the property actuator
(it could set a target property in other objects)

**Comment by BluePrintRandom** [comment]
another use case that would work well with the system

message(set property to property recieved in message body)

so one could easly make external self contained controls for other objects

mouse over -----and----(send message property value)
left click----------/

message(set value)----and----actuator(use value)

**Comment by vlad1777d** [comment]
@BluePrintRandom , it's so hard to understand you. 

"only the properties inside the object containing the actuator and sensor" - but what about other properties from other objects? Sensor must react to all of them.

"sensors can set properties only in objects they are in" - sensors cannot set properties. Only actuators can do that.

"actuators can only access properties to use from objects they are in" - this is a bad behavior. I think here would be better to add two dropdown lists for user to choose:
-object, on which the property will be changed;
-property, which will be changed (all properties of chosen object would be in list).

**Comment by BluePrintRandom** [comment]
no, you don't understand.

the property to be set, would NOT be the property trigger of the sensor

.adding 2 drop downs,(prop and sensor attribute) would give the ability for
a sensor to set a property if the sensor is true (before evaluating) would
mean in 1 logic tic you could feed a property to an actuator.

1. ray looking for property 'enemy' detects a object
2. senor sets property target in own to the gameobject hit by the ray
3. fire logic pulse
4. controller fires actuator
5. steering actutor seeks actor painted by ray

ray(enemy)-(set prop Target=hitObject)---and---steer to property Target

On Nov 7, 2016 12:43 PM, "Vladislav" <notifications@github.com> wrote:

@BluePrintRandom <https://github.com/BluePrintRandom> , it's so hard to
understand you.

"only the properties inside the object containing the actuator and sensor"
- but what about other properties from other objects? Sensor must react to
all of them.

"sensors can set properties only in objects they are in" - sensors cannot
set properties. Only actuators can do that.

"actuators can only access properties to use from objects they are in" -
this is a bad behavior. I think here would be better to add two dropdown
lists for user to choose:
-object, on which the property will be changed;
-property, which will be changed (all properties of chosen object would be
in list).

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/UPBGE/blender/issues/290#issuecomment-258956631>, or mute
the thread

**Comment by vlad1777d** [comment]
@BluePrintRandom , Now I think that I understood you (partially). 
You wrote another time: "would give the ability for a sensor to set a property", and it's confusing because sensors do not set properties.
".adding 2 drop downs,(prop and sensor attribute)" - to what object do we need to add this drop downs?
" would NOT be the property trigger of the sensor" - I don't know about properties sensor's triggers.

Well, it's good. I agree that it's good to add to property actuator dropdown list, where you could choose object, on which property would be changed.

But I do not agree to add to property actuator dropdown list, where you could choose sensor, that must be true to activate this actuator. Because it'll make property logic brick more complex and less understandable. 

And if to add drop down list to property sensor (list,  where you could choose: on which object are you looking for properties), than you could make such construction, that will work for 1 frame:
![document_001](https://cloud.githubusercontent.com/assets/12682937/20101746/f65069b4-a5cb-11e6-9d74-d0dc4a90ad11.png)

Is this the result, that you need?

**Comment by BluePrintRandom** [comment]
look at this mock up

when a sensor is true, it can set a property then it triggers the logic
pulse to the and controller -> then the actuator uses the property set that
frame.
