### ISSUE TITLE
Frame drop or normal behavior & different color.

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#295]
The file grass tut from : https://blenderartists.org/forum/showthread.php?409103-Tutorial-on-how-to-make-amazing-grass!-(New-little-nature-demo-included!) shows this behavior, i dont know if its correct.
The file shows a frame drop of upbge, however if i check the material constants the speed increased. also the color between bfbge and upbge seams different.
img 1: bf bge 278a - left- 118fps. Upbge 011: right-  109 -10fps.
http://pasteall.org/pic/index.php?id=108631
img 2: upbge: 011: with material constants: 125 fps
http://pasteall.org/pic/index.php?id=108632

**Comment by youle31** [comment]
In the file there are 2 filters on the same pass. I don't know for BF BGE, but upbge don't allow that (warning displayed in the console. In BF bge, no warning). So I removed one of the 2 filters that shared the same pass (Levels.glsl) and I compared:

Here is the result: http://pasteall.org/pic/index.php?id=108636 (the images are the same)

About the framerate, we have a slight difference but there are several factors that can explain this. What you said about constant materials can be one of this factors: I explain: In upbge we have many dynamic uniforms (we can set dynamically many things like texture alpha, light color...............). When we open a file saved with BF Blender, all the uniforms can be set dynamically (no constant is checked by default). As upbge has more dynamic uniforms than BF bge, upbge may be a bit slower than BF bge.

I think other factors are possible as upbge code is now far from BF bge code. But in this specific file, I think nothing is alarming related to upbge performances as it can be explained.

So as everything can be explained and that nothing is alarming (I don't think there is a bug here... But I may be wrong), I think we can close the issue.

But I wait for @panzergame opinion to close the issue.

My test file is here: http://pasteall.org/blend/index.php?id=44243

**Comment by Akira1San** [comment]
Ok, i understand. :)

**Comment by Akira1San** [comment]
One more thing, the fps drops in standalone compared to the embedded player? I also notices, that its the same in bf bge 2.78a. Embedded = 200fps, standalone  = 150fps.

**Comment by panzergame** [comment]
@Akira1San : What is the resolution of the embedded player compared to the standalone player ?

**Comment by Akira1San** [comment]
My mistake, it was cos of the desktop checked.
