### ISSUE TITLE
Big drop of fps after the latest master build! (+ Crash (youle))

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#296]
Big drop of fps after the latest master build(commit: UPBGE: Optimize bounding box update.)
Made an image: left -upbge011, right: latest master build. The fps drop even more in standalone.
http://pasteall.org/pic/index.php?id=108647

**Comment by youle31** [comment]
I don't know for perfomances for now but I have a crash http://pasteall.org/pic/index.php?id=108648 in desert level. I updated my master from 92601f699ead4d69fc27a1426b4434b1be448e8a to the last commit about bounding boxes 8f84e7a797ed50279a5ef5e397304d94d47043c8 sot it's one of the 2 last commits that generates the crash. And I guess this is the last about bounding boxes...

**Comment by panzergame** [comment]
The crash is fixed in 86458a84149af8fb4af50e7fd749b6339e4cd182 and a forgotten debug message is removed too.

@Akira1San : Can you check that now without the debug message all is fine ?

**Comment by youle31** [comment]
This is good to me

**Comment by Akira1San** [comment]
Its perfect! :D
