### ISSUE TITLE
Object vanishes when I play if I turn on Geometry Instancing

### ISSUE THREAD

**Issue by Awesomeplayer** [UPBGE/blender#297]
I dunno how to use the Geometry instancing thingy in the materials tab, Wikipedia says, it's used to speed up a game with a lot of similar objects, but if I turn it on, the object vanishes when I play :( 
Does anyone know why? Or am I missing something? Help

**Comment by panzergame** [comment]
@Awesomeplayer : Please provides more info. What's is your GPU, driver version, OpenGL extensions, OS, the file your using ?

**Comment by youle31** [comment]
@Awesomeplayer : In most case, this means that your hardware doesn't support our implementation of geometry instancing.

This happens generally on old graphic cards, or old intel HD graphics.

The bug has already been reported several times. Unfortunately we don't have enough infos to know exactly when geometry instancing won't work. So for now we didn't display a message that tells -> "Your hardware is not supported".

About intel HD graphics: Someone had the same issue than yours and forced update of his intel HD 4000 graphic drivers and after it worked. His old drivers only allowed 41  Max varying floats. When he updated his drivers he had 64 Max varying floats.

This info is displayed when you start standalone player in the console. If you can tell us what is your graphic card and what are the infos displayed when you run standalone, it could help us.

If you have intel HD 4000, you can try to "force" your drivers update. If it's older, I doubt geometry instancing can work, but you can still try.

In any case, if you can tell us what are your infos running standalone, Thanks in advance.

**Comment by panzergame** [comment]
Should be fixed in b5238de3623d93c2484fa7ac532b4bd988190ac8.
