### ISSUE TITLE
LOD of my object doesn't work

### ISSUE THREAD

**Issue by vlad1777d** [UPBGE/blender#299]
Hello dear friends.

I added to object "power_line" lod "power_line_LOD1" from hidden layer.
But in 3d View it is displayed not depending on distance to it's origin, but more on angle from camera to object.
Video: https://youtu.be/PYlkjzcwRWo
File: [Pylon_3_v7.blend.tar.gz](https://github.com/UPBGE/blender/files/588038/Pylon_3_v7.blend.tar.gz)

System: Debian x64 unstable
Upbge: 0.1.1 Linux 64 (on 0.1 this bug appeared too).

Best regards,
Vladislav

P.S.
If I choose object and press ".", that after rotating, making camera be far away from object or closer to object does not affect on appearing LOD object. LOD object does not appear at all.

**Comment by panzergame** [comment]
Behaviour in orthographic view can be strange.

**Comment by vlad1777d** [comment]
It would be interesting to know, is it a bug or not?
I always work with models in orthographic view.

**Comment by youle31** [comment]
Sorry I think I didn't understood thez bug and I and I had a bad answer...

**Comment by vlad1777d** [comment]
@youle31 , in your file for testing LODs all works well in perspective view, nothing is happened in orthographic view.

**Comment by youle31** [comment]
As it is viewport stuff, as LOD is designed to work only in perspective for now, as it seems a big task and as no dev wants to implement LOD for orthograohic for now, I close. For now.
