### ISSUE TITLE
Request: Static Draw call batching?

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#3]
Now that we are adding VBO support is it possible to implement static draw call batching?

I have a level assembly kit that is used repeatedly and uses a atlas, and the world could be much more robust if I had static draw call batching,

thank you for all your efforts!

**Comment by BluePrintRandom** [comment]
@panzergame also, is there a paypal for UPBGE? 

your efforts are appreciated.

**Comment by Akira1San** [comment]
http://http.developer.nvidia.com/GPUGems2/gpugems2_chapter04.html -> an interesting information about how batching works, called Segment Buffering.

**Comment by panzergame** [comment]
@Akira1San & @BluePrintRandom : thanks for these infos.
I propose to merge all vertexes in one big array and make one indices array  per mesh slot, in this case we will send only needed indices array via glMultiDrawElements.

**Comment by Akira1San** [comment]
Sounds good. Heres some more examples
http://www.geeks3d.com/20100629/test-opengl-geometry-instancing-geforce-gtx-480-vs-radeon-hd-5870/
http://www.geeks3d.com/20100210/opengl-3-2-geometry-instancing-culling-on-gpu-demo/

**Comment by panzergame** [comment]
@Akira1San : geometry instancing is not geometry batching.
I already have patch for geometry instancing but i should update it.

**Comment by BluePrintRandom** [comment]
Thank you Tristan,

**Comment by Akira1San** [comment]
Oh, i see. So geometry instancing will be for like grass, trees, particles, etc... Batching will be for merging objects, like different boxes into one object.

**Comment by panzergame** [comment]
For the moment i planned to just add a batch option in the material and that all object with the same material and in the same group object will be merged, do you agree ? do you have something simpler ?

**Comment by Akira1San** [comment]
Sounds good to me. :)

**Comment by panzergame** [comment]
I don't really know where put python function about bacthing and i don't want add it directly in KX_GameObject.

For me the best way is to add a KX_MeshObjectUser class which contains all unique mesh info for the game object, and in this class add a KX_BatchGroup which control update merge and split.
I add an extra level with KX_MeshObjectUser because this class can contains later dynamic uv transform unique for the object ect...

It will look like : 
obj.meshUser.batchGroup.merge(other)
obj.meshUser.batchGroup.split()
obj.meshUser.batchGroup.update()
obj.meshUser.batchGroup.destruct()

What do you think guys ? There's a nicer and simpler way ?

**Comment by Akira1San** [comment]
I like it.

**Comment by panzergame** [comment]
Currently the batched array will be in world space without orientation, so no gmae object owner of the group, it's problematic ?

**Comment by Akira1San** [comment]
If you ask me, i dont know. It have to be tested in a game environment.

**Comment by BluePrintRandom** [comment]
once it's written I will test it in my level builder system (it's all going to use 1 atlas)

**Comment by panzergame** [comment]
Targeted for 0.1.2.

**Comment by panzergame** [comment]
Done :P

**Comment by BluePrintRandom** [comment]
Did you get my bug solved?  (with mesh batching?)

**Comment by panzergame** [comment]
I close the issue because it was just requesting batching support.
