### ISSUE TITLE
Request: Particle system

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#30]
Today game engines support build-in particle systems. It would be nice to have a build-in particles into UPBGE. Some features, they could have: The particles could be multitreaded, could use instances, they could cast shadows.

**Comment by panzergame** [comment]
I written an old patch for this : http://www.pasteall.org/54880/diff.
demo : http://youtu.be/Z1fmmY2JmAI
blenderclan.tuxfamily.org/html/modules/newbb/viewtopic.php?topic_id=42040&forum=3&post_id=520553#forumpost520553

**Comment by Akira1San** [comment]
Looks interesting.

**Comment by BluePrintRandom** [comment]
check this out!

openCL driven particle sims in real time!
http://enja.org/2010/12/16/particles-in-bge-fluids-in-real-time-with-opencl/

**Comment by Akira1San** [comment]
Yeah, opencl particles.

**Comment by Akira1San** [comment]
Link -> https://github.com/Kupoman/conceptparticles
Theres been an old branch of Kupoman, about "A demonstration of how particles can be done in the Blender Game Engine using PyOpenGL". How Good would that be as a testing PyOpenGL with UpBge or making build-in particles?
