### ISSUE TITLE
bge object properties limited to 10000

### ISSUE THREAD

**Issue by hugobarreira** [UPBGE/blender#300]
Is there a reason to limit the integers and float properties of a game object to 10000 and 10000.000 when manually set them? We can change it via python. Also the mass value of an object

**Comment by youle31** [comment]
there is no comment in the code about these clamping values for properties (rna_property.c lines 160 and following.) I think we could replace with macros INT_MAX, INT_MIN, FLT_MAX, FLT_MIN.

For mass, I'm not sure, there is this note in btScalar.h:

//keep BT_LARGE_FLOAT*BT_LARGE_FLOAT < FLT_MAX
#define BT_LARGE_FLOAT 1e18f

so maybe we could use clamp beetween -BT_LARGE_FLOAT and BT_LARGE_FLOAT.

**Comment by panzergame** [comment]
Fixed in e291c4ae63581a94a5ce1a3d9bc1c2fad3088674
