### ISSUE TITLE
Bug: Multiples UV bug

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#301]
http://pasteall.org/blend/index.php?id=44386 The star (second UV) moves at ge start (Don't look at batch script: I realized this error while testing ge_batch but this error is in master)

I don't know if this is a bug. We can see changement when we select one UV or the other in the viewport. I'll investigate more later.

**Comment by panzergame** [comment]
Fixed in b7b3dee048536bd7c65a366a78bd83be18302698
