### ISSUE TITLE
Vertex Color Broken

### ISSUE THREAD

**Issue by sdfgeoff** [UPBGE/blender#302]
A build done only an hour or two ago reveals that vertex color is broken.
(Commit id: e280d91e3296ce9947caee1d616e37710b705406 )

Demo file:
http://pasteall.org/blend/index.php?id=44402

In viewport:
![viewport](https://cloud.githubusercontent.com/assets/13490050/20506362/575915fc-b0b8-11e6-93fc-c77f7f038407.png)

In game:
![ingame](https://cloud.githubusercontent.com/assets/13490050/20506371/5f3da29c-b0b8-11e6-8e87-18691ec1e955.png)

**Comment by panzergame** [comment]
@sdfgeoff : There's no color layers in your cube's mesh, it is normal ?

**Comment by sdfgeoff** [comment]
Hmm. Very strange. To make that blend I opened blender, went into vertex paint, painted it red. As can be seen when you open it, it is red.

But now if you go into vertex paint mode, it goes back to being white and creates a vertex color layer. Looks like this was a one-off.
