### ISSUE TITLE
Bug: Performance issue in a file

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#303]
https://drive.google.com/file/d/0B3GouQIyoCmreUNDUVBKQnpTSGs/view?usp=sharing

upbge: 120 fps
BF bge: 500+ fps

**Comment by Akira1San** [comment]
The file got modifiers. Have you removed the modifiers?
When the modifiers got removed i have: upbge master build: 440, bf bge: 470.

**Comment by youle31** [comment]
@Akira1San : Yes I already tried to remove modifiers and I have a performance increase when I remove modifiers, but I try, keeping the file as it is, to find the commit that caused performance decrease... It seems very old. I'm bisecting.

**Comment by youle31** [comment]
It seems that there are several commits that cause issues in this file:

The most inportant one is: f3d4e80c85d05dd09d558ed295110820b57ce704

**Comment by youle31** [comment]
I don't why display list for derived meshes were removed. Can't we restore it? Or we wait for the patch to apply modifiers at game start.

**Comment by youle31** [comment]
I close this waiting we do a patch to apply modifiers at game start
