### ISSUE TITLE
Bug: Game Property not available at the first frame

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#306]
http://pasteall.org/blend/index.php?id=44421 (I printed own["t"] which is a timer property -> it causes an error in the console at the first frame)

**Comment by panzergame** [comment]
@youle31 : The script fps.py is ran from two objects: `Empty` and `Plane`, but only `Plane` object has a property named `t`.

For me it's not a bug, reopen if i'm wrong.

**Comment by youle31** [comment]
Oh sorry oops
