### ISSUE TITLE
Request: Cascaded Shadow Maps

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#31]
Cascaded shadow mapping is a technique to shadow large areas at reasonable memory and run-time cost. The basic idea is simple: Split the view frustum into several sub frustums and render a shadow map for each split. Since, naturally, splits closer to the viewer cover less area in world space (i.e. under perspective projection) you get better shadow map resolution close to the camera and less resolution further away.
I believe this shadow technique will be quite useful for UPBGE game devs.
Links ->
http://developer.download.nvidia.com/SDK/10.5/opengl/src/cascaded_shadow_maps/doc/cascaded_shadow_maps.pdf
https://msdn.microsoft.com/en-us/library/windows/desktop/ee416307(v=vs.85).aspx
http://dev.theomader.com/cascaded-shadow-mapping-1/

**Comment by Akira1San** [comment]
Some examples too:
http://asawicki.info/news_1283_cascaded_shadow_mapping.html
http://aras-p.info/blog/2009/11/04/deferred-cascaded-shadow-maps/

**Comment by BluePrintRandom** [comment]
:+1:

**Comment by youle31** [comment]
We have a patch for this from Kupoman. I don't know when we'll implement it... But I think we'll do it.

**Comment by Akira1San** [comment]
Sounds good.

**Comment by adriansnetlis** [comment]
It's great that you received it. However, the day when I was talking with him about this topic, he said that there were a few issues. I am sure that UPBGE team is gone fix them, though!;)

**Comment by aksyom** [comment]
You can make a lower quality version of shadow cascades by using multiple lights, where only one light illuminates and casts shadow, while the other lights merely cast shadow.  The problem here is setting the shadow bias and other things correctly for each light (illuminating and shadow-only), which is not an easy task tbh.
