### ISSUE TITLE
BUG: ImageRender.image broken.

### ISSUE THREAD

**Issue by sdfgeoff** [UPBGE/blender#311]
When trying to extract the image data from a render to texture, you use the [image](https://pythonapi.upbge.org/bge.texture.html#bge.texture.ImageRender.image) property.

Doing so works in BFBGE, allowing the image to be sampled from python. 
However, in UPBGE, as soon as you do tex.source.image it:
1) Produces invalid data
2) corrupts the image being displayed

Sample blend:
http://pasteall.org/blend/index.php?id=44485

Move your mouse over the plane and the RGB value of the pixel will be displayed in the console. It works in BFBGE but not UPBGE.

**Comment by youle31** [comment]
Waiting we find a solution to this bug, I finally did my code work with a 16x16 texture:

http://pasteall.org/133967/python

**Comment by ondredeniso** [comment]
Also game crash, if in focus any material with enabled Depth Transparency. 
My configuration is:
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GT 740M/PCIe/SSE2
GL_VERSION:  4.5.0 NVIDIA 365.19

**Comment by panzergame** [comment]
`unsigned short index = m_offScreens.GetCurrentIndex();` If you have to replace it, maybe it's because its value is -1, could you check this ?

**Comment by youle31** [comment]
First bad commit: 732d176d09b6c2497232bd3ecfced9042b66deff

**Comment by panzergame** [comment]
@youle31, @sdfgeoff : I have a fix in master: 5ae8cbde14c80e47691f8c71e4ff4b8372fc6a01, could you compile, test and close if the bug is fixed ?

@ondredeniso : Did you keep investigating on your issue ?

**Comment by youle31** [comment]
It's ok for me.

**Comment by sdfgeoff** [comment]
Seems to work in my (limited) testing. On Monday I'll be integrating this into the system it was planned for. I'll re-open if there are any issues.
