### ISSUE TITLE
Rigid body bug

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#312]
Rigid body makes objects to slide on collide. Bf bge 2,78 works fine. This bug effects all the blend files.
Test file; http://pasteall.org/blend/index.php?id=44489

**Comment by panzergame** [comment]
@Akira1San : Is the friction in physics panel to 0.0 ?

**Comment by Akira1San** [comment]
Yes.

**Comment by panzergame** [comment]
@Akira1San : I think you saved your file in UPBGE with a temporary version between 0.1.1 and 0.1.2, see 687df77ec09819d341db8f6b17c5c7ad39c92119.

**Comment by Akira1San** [comment]
Well the same thing is even with the bgmc game - UnderTow

**Comment by panzergame** [comment]
@Akira1San : could you test with latest master ? if it works please close the issue.

**Comment by Akira1San** [comment]
It works now. :)
