### ISSUE TITLE
keyframe uv cords 

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#314]
add ability to keyframe uv cords for use in texture actions and sprite actions via the existing action system.

**Comment by youle31** [comment]
This is a very big patch to do because there is lot of Blender code to change (not only bge) and as we already have python, we agree with panzergame to say that it is not a prior feature.

**Comment by BluePrintRandom** [comment]
if you do it very smart (keyframe uv cords) - Ton may want to pull it back
the other way, maybe ask him if it's a good idea?

**Comment by youle31** [comment]
When we'll do IPO for textures options, this will be included. Waiting for that, you can use python in last master to animate GPU texture coordinates, offset, scale, rotation since a3b07fe8b980f07b1b9afecb5142f78eacc0ad52

**Comment by youle31** [comment]
I close low low priority feature requests for now. They are still visible in closed pull requests list.

**Comment by BluePrintRandom** [comment]
@Nazg-Gul 
Do you think this is something that could happen in all blemder? 
Keyframe uv?

**Comment by Nazg-Gul** [comment]
Don't think it'll be best idea to support animation on UVs. This will become a huge pain when changing topology. Additionally, in both BI and Cycles you can use animation on shader nodes to achieve such an effects.

**Comment by BluePrintRandom** [comment]
Thanks Sergey, makes sense, just introduces complexity to animating
sprites, however it's not that big of a deal :D
