### ISSUE TITLE
Bug: Crash at game engine start

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#315]
a .blend picked on BA: http://pasteall.org/blend/index.php?id=44516

backtrace: http://pasteall.org/pic/show.php?id=109441

**Comment by youle31** [comment]
first bad commit for crash: a3b07fe8b980f07b1b9afecb5142f78eacc0ad52

**Comment by panzergame** [comment]
@youle31 : Could you test with latest master and close if it is fixed please ?

**Comment by youle31** [comment]
It's ok 👍
