### ISSUE TITLE
Bug: Problems with properties

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#316]
game: https://drive.google.com/file/d/0B_DSg35urBhDTEVBUV90RVhpcGM/view

launch MainMenu then click new game: an animation should be launched.

First bad commit: https://github.com/UPBGE/blender/commit/cbfbf9bc7fb55cca3d7ed6f1aaebbd721448d219

**Comment by youle31** [comment]
A simpler test file: http://pasteall.org/blend/index.php?id=44531

**Comment by ondredeniso** [comment]
Work, is True write as TRUE

**Comment by youle31** [comment]
@ondredeniso : hi, could you test before https://github.com/UPBGE/blender/commit/cbfbf9bc7fb55cca3d7ed6f1aaebbd721448d219 and after ? Because on my computer (windows 10 upbge last master), it worked before this commit and not after. Could you tell us also if you have problem playing the animation in Thatimster game (link in the first post). Thanks!

**Comment by ondredeniso** [comment]
Hi. I have the same. Debug bool property shows True-False with upper case. No ideas, how to fix it.

**Comment by youle31** [comment]
yeah ok thanks!

**Comment by youle31** [comment]
fixed in https://github.com/UPBGE/blender/commit/8df84937389cfee89fc5a8e36fa52c2b70ba1241 Thanks panzergame 👍
