### ISSUE TITLE
LibLoad material with cubemap texture failed

### ISSUE THREAD

**Issue by ondredeniso** [UPBGE/blender#317]
Open mirrorLoad.blend for load mirror.blend file.
https://www.dropbox.com/s/2sdjtqy3fd94eew/UPBGE_mirror_cubemap_probl.zip?dl=0

**Comment by panzergame** [comment]
Confirmed, two bugs were found in this file. First the mouse actuator lib load failed, this is fixed in 28f1ef4fb1c640257a20eb6c6a248abbdfc83805. Second the cube map are not added merged during libload, i have a solution for this one.

**Comment by panzergame** [comment]
Fixed in fa278508b4ff5279dd6110443a8c2adc67255c0e.

**Comment by youle31** [comment]
thanks :)

**Comment by ondredeniso** [comment]
Nice job. Thanks you!
