### ISSUE TITLE
Feature Request: List uniforms in BL_Shader

### ISSUE THREAD

**Issue by sdfgeoff** [UPBGE/blender#319]
I'd like to see the ability to list uniforms in a shader:

**Why?**
When shaders are compiled, unused uniforms are compiled out, and this can splat your console with "Invalid Uniform" warnings. So if you replace a shader with one to help you debug, then your console is useless. It doesn't even appear as a python error, so it can't be caught/handled.

Adding the ability to list uniforms would allow this to be checked beforehand to stop the errors happening.

**Suggested Implementation**
The simple solution:
`BL_Shader.getUniformList()`

The amazing solution:
`BL_Shader.uniform_dict = {'color':mathutils.Vector([0.5, 0.2, 0.1]), 'other_uniform':7}`

**Comment by youle31** [comment]
http://pasteall.org/141496

I propose to say:

if (location == -1 && weAreInFirstFrame) {
           CM_Error("invalid uniform value: " << name << ".");
}

to avoid to slow down the shader after the first frame.

About uniform list, I look at https://www.opengl.org/wiki/Program_Introspection (Uniforms and blocks) to see if I can add an API.

**Comment by youle31** [comment]
I don't know about this request if this is important enough.
@sdfgeoff : Do you have a test file that shows a case where this feature would be really/very useful ?
@panzergame : What do you think? Do you see other advantages to have uniforms list ?

**Comment by panzergame** [comment]
The current API obligate the user to know it's uniform type, with a list or dict it will be a little be harder to set an uniform because the user have to know: the name, the type and the value.

@sdfgeoff : Maybe you though about an option for debugging ?

**Comment by sdfgeoff** [comment]
The case where it would be useful is when writing more general shader management tools. In a complex system, you may have a shader management system, that wants to treat all shaders the same. In this case, being able to know if a shader has a specific uniform is important. 

I have a render pipeline made from 9 render to textures. Each stage has an associated shader on the plane it displays. Now some of these have common uniforms, such as zoom (influences blur radius), and some clipping plane data. But some of the shaders do not use these. As a result, I can't just do a blanket "for pass in render_passes: set_zoom_uniform(pass)" because it floods the console with warnings about invalid uniforms. (This system is huge and is under NDA, so I can't share it with you as a test blend).
I can't write a system that does shader text introspection either, because uniforms that aren't used get compiled out.

@panzergame
I would propose the creation of a vec2f() vec3f() classes for storing the values in. I already have this in the above system (see code below). This is only necessary because mathutils doesn't have support for integer-only vectors. Mathutils.Vector would works fine for vec2f etc

```
def set_uniform(obj, name, val, matid=0):
    '''Sets the uniform of a shader using some intelligence to pick the
    type.

    Supports floats, integers and booleans as well as vec2 and vec3
    (float only). Support should be added for more as it is required.
    '''
    # This is based around a Lookup table (lut) that translate an object
    # type into a function to call on the shader
    # This is local to this function because the functions are class members
    # and this function gets called hundreds of times per frame (so doing
    # a get_attr has significant performance loss
    shader = get_shader(obj, matid)
    uniform_lut = {
        float: shader.setUniform1f,
        int: shader.setUniform1i,
        bool: shader.setUniform1i,
        vec2f: shader.setUniform2f,
        vec3f: shader.setUniform3f,
        vec2i: shader.setUniform2i,
        vec3i: shader.setUniform3i,
    }
    if hasattr(val, "__iter__"):
        uniform_lut[type(val)](name, *val)
    else:
        uniform_lut[type(val)](name, val)


# There are also some classes to assist in assigning arrays of values
# These classes __iter__ method should return the values intended to be passed
# into the shader setting function. Each class should have an entry in the
# uniform lookup table in "set_uniform"

class vec2f(mathutils.Vector):  # pylint: disable=C0103, R0903
    '''Standin class for a vec2 when setting shader parameters'''
    def __init__(self, raw_values):
        if len(raw_values) != 2:
            raise ValueError('Expected Two Values for vec2f')
        super().__init__()

    def __iter__(self):
        return iter([self.x, self.y])
```

**Comment by youle31** [comment]
> In a complex system, you may have a shader management system, that wants to treat all shaders the same. In this case, being able to know if a shader has a specific uniform is important.

> Now some of these have common uniforms, such as zoom (influences blur radius), and some clipping plane data. But some of the shaders do not use these.

- The shader won't know what uniforms will be active or not before you set them with shader.setUniform...
So you're the only one to know if a shader will use an uniform or not. So the console will be splatted with "Invalid uniform" warnings if you don't solve the problem in your shader management system with a function or a class that updates "uniforms shared by several shaders" AND "uniforms specific to one shader".

For the question adressed to panzergame, I let him answer.

**Comment by sdfgeoff** [comment]
> The shader won't know what uniforms will be active or not before you set them with shader.setUniform...
Is a hardware/driver limitation? That you cannot know what uniforms exist in a shader? 

> So you're the only one to know if a shader will use an uniform or not. So the console will be splatted with "Invalid uniform" warnings if you don't solve the problem in your shader management system with a function or a class that updates "uniforms shared by several shaders" AND "uniforms specific to one shader".
Another use case:
During development of a shader, you may comment out a chunk of code to test only a certain aspect of it. If this bit is the only use of a uniform, then you also have to modify any code attempting to interface to the shader to prevent your code from splatting the console with the invalid uniform warnings.

> You could have a complete uniforms list reading the "string" of your shader. In this case, you can see what uniforms are common to several shaders and what uniforms are specific to one shader.
Except if I compile the shader:
```
uniform int notused = 0;
void main(){
    glFragColor = vec4(0.0)
}
```
the uniform "notused" is compiled out, and thus calls to setUniform with it as the target will fail. Trying to guess if a variable is going to be compiled out requires a lot of 'understanding' of GLSL by your shader system. It has to understand comments, multiplying by zero, "if False" statements etc.

**Comment by DCubix** [comment]
OpenGL has a nice function to retrieve every active uniform in a shader program object. We can use it to make a list and then access it by doing `shader["uniform"]`, which can be a write-only list since there's no way to know the current value of the uniform.
```cpp
int uniforms = 0;
glGetProgram(bindCode, GL_ACTIVE_UNIFORMS, &uniforms); // Gets the number of ACTIVE uniforms.
// If the uniform isn't used in the shader, it will not count here.
for (int i = 0; i < uniforms; i++) {
    char uniform_name[256];
    int uniform_size; // 1 if it's a normal variable, else it's the array size if it's an array
    glGetActiveUniform(bindCode, i, 256, nullptr, &uniform_size, nullptr, uniform_name);
    // Add the uniform to a list.
    // If the uniform is an array (uniform_size >1) you have to add the uniform array elements
    // individually. eg: name[0], name[1], name[2], etc ...
}
```
I think I can take this as a project. It seems to be simple to accomplish...

**Comment by significant-bit** [comment]
I made something similar for the upcoming Blender 2.8 -- ShaderInterface gets active uniforms and vertex attributes right after compile/link. It doesn't handle storage of uniform **values** but does know the names and data types. See intern/gawain/src/shader_interface.c for details.
