### ISSUE TITLE
Bug: Artifacts with overlay scene

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#320]
https://drive.google.com/file/d/0B29hKf6-B52cZE5URlE5YUs4UU0/view?usp=sharing

(find the commit that fixes grey screen for overlay scene to see what has been done and if it can explain these artifacts -> after 0.1.1)

**Comment by youle31** [comment]
- Before: 48e2109576f1824bdd2b83ccd20e36ac0fcea69f it worked
- 48e2109576f1824bdd2b83ccd20e36ac0fcea69f makes the BPR file crash
- the commit just after: 8ce3b3bed6b73dcb82e1e9ad8ea853aabd94fef8 fixes the crash but the overlay scene is grey. (Note: I didn't see text objects in BPR file. @BPR: Are there any text objects in your file?)
- Beetween : 8ce3b3bed6b73dcb82e1e9ad8ea853aabd94fef8 and b286d182658ca32083afea85e626a4d715617463 we are blind because the overlay scene is grey.
- After: b286d182658ca32083afea85e626a4d715617463 overlay works again but with artifacts.

**Comment by youle31** [comment]
In KX_KetsjiEngine,

replacing: 
- this:
const int target = lastscene ? RAS_IRasterizer::RAS_OFFSCREEN_FINAL : RAS_IRasterizer::RAS_OFFSCREEN_RENDER;
PostRenderScene(scene, target);
- with: 
const int target = RAS_IRasterizer::RAS_OFFSCREEN_FINAL;
PostRenderScene(scene, target);

**Comment by panzergame** [comment]
@youle31 : Could you test and close if the bug is fixed with latest master ?

**Comment by youle31** [comment]
Fixed in 0f8a297d7aed79b4895abcf2d8ceec848fdb0caf (panzergame commit)
