### ISSUE TITLE
cubeMap of Texture gone after loading from .blend with LibLoad

### ISSUE THREAD

**Issue by Yethiel** [UPBGE/blender#323]
After loading a game asset with LibLoad (`logic.LibLoad(blend_path,  "Scene", async=True)`), the cubeMap is gone. The asset just shows the default texture (grid map).

After trying to update the cube map with a python script (example from the API docs), I noticed that `mat.textures[0].cubeMap` just yields `None` (I made sure that it is the correct texture).

`AttributeError: 'NoneType' object has no attribute 'clipStart'`

**Comment by Yethiel** [comment]
Found out that this issue was closed 3 days ago.

**Comment by youle31** [comment]
Hi, could you share a .zip with your .blends? Thanks!

**Comment by youle31** [comment]
ah sorry I didn't understood... I thought you still had the problem

**Comment by ondredeniso** [comment]
Sry for reply, this cubemap sort of headpain, because 2 new bugs:
1. Still work and usage cpu, if cubemap object placed on innactive layer.
2. Crash game on quit event, when cubemap object removed with:

> for X in g.LibList():
>     g.LibFree(X)
