### ISSUE TITLE
Nodeeditor for Vertex shader a possible and useful idea?

### ISSUE THREAD

**Issue by Maujoe** [UPBGE/blender#33]
I don't know if a nodeeditor for vertex shader is possible or makes sense but in my opinion it would be a good feature in context to the current material nodeeditor that only edit the fragment shader. Because so we would be able to manipulate geometry  (for example  for wind or wave.. animations) without writing a custom shader manually. This would have some advantages.
- users don't need full knowledge about writing glsl shaders
- it saves time because you don't need to rewrite the complete material
- easier to edit / make changes to material
- and maybe changes are visible in the viewport (?)

What you think about that?

By the way an property node would also an nice feature also for the current nodeeditor so we could have ingame controll about the material via logic bricks/python.

**Comment by panzergame** [comment]
Yes, it's a good idea, but i already investigate on it, the shader system doesn't generate vertex shader, we have to write a lot of code for this.

> and maybe changes are visible in the viewport (?)

Of course, BGE and viewport materials are the same.

**Comment by youle31** [comment]
I'm wondering if we can do something with \source\blender\gpu\shaders\gpu_shader_vertex.glsl...
