### ISSUE TITLE
Bug: Mouse isn't recognized in water demo MSVC debug mode

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#332]
in debug mode in water demo 0.99, mouse sensor isn't recognized. Python error in mousellok.py

Error: cont(Cube), Python script error
Traceback (most recent call last):
  File "MouseLook.py", line 23, in <module>
KeyError: 'requested item "Mouse" does not exist'

**Comment by youle31** [comment]
First bad commit: cbfbf9bc7fb55cca3d7ed6f1aaebbd721448d219

**Comment by panzergame** [comment]
This will be fixed by using string objects instead of pointer to char. It will be done in ge_string.

**Comment by youle31** [comment]
ok I close this so.
