### ISSUE TITLE
Performance: MSVC 2015 Perfs diag

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#333]
- text drawing:
http://pasteall.org/148035/diff

- attrib layers:
void RAS_OpenGLRasterizer::SetAttribLayers(const RAS_IRasterizer::AttribLayerList& layers)
//m_storageAttribs.layers = layers; -->Big performances leak. (in sponza scene MSVC debug mode 80 to 100 fps when I comment)

- static void cdDM_drawFacesGLSL(DerivedMesh *dm, DMSetMaterial setMaterial)
dm->drawMappedFacesGLSL(dm, setMaterial, NULL, NULL); Baaad

... I don't make an exhaustive list. Better to see that with panzergame.

**Comment by significant-bit** [comment]
Text drawing is redone in the blender2.8 branch, look there if you're interested! I still have one more thing on deck for BLF -- setting draw color with a new BLF_ function instead of using glColor.

**Comment by youle31** [comment]
Thanks very much! I'll have a look. Anyway, panzergame works on an upbge branch based on 2.8. Normally upbge 0.1.3 (the next release) will be based on 2.8 branch so we'll work only on it very soon :)
Thanks for text drawing refacor!

@panzergame : About this report I close it for now, I'll open either issues or pull requests on each individual case when I'll have investigated more.
