### ISSUE TITLE
batched raycast

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#334]
currently one can use a python loop and a list of raycasts, and call a function if the ray is true, or if the ray is false, this works fine for a few raycasts, but eventually raycasts really add up.

own.rayBatch([list of raycasts to perform])

where a single cast looks like a regular raycasts arguments, with 2 extra
(function to call if true, function to call if false)
functions also except None*

the calling of functions could not be accelerated I dont think
but the raycasts themselves can.

so in theory with large complex games a dev could do more using a system like this.

example use cases
(bullet manager system using marched raycasts)

home made custom physics like gravity

hundreds of ai units

etc

**Comment by BluePrintRandom** [comment]
I can post a few examples of systems to be accelerated using the technique, wrectified assembly components almost all use 1 raycast each and an enemy could be made of many pieces potentially

(feet = detect ground) (weapon = do damage) (head =raycast vision cone) (ground effect thruster  = detect ground) etc.

**Comment by youle31** [comment]
see my #337 comment about new features requests policy

**Comment by youle31** [comment]
I close low low priority feature requests for now. They are still visible in closed pull requests list.
