### ISSUE TITLE
ingestigate realtime glsl node setup 

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#336]
we need a baseline pbr node setup for people to plug maps in from substance painter and substance designer

albedo spec etc

after we have a good working node setup, 
maybe we can add a ui for it and make it another material type?
(like wire, halo, surface etc)?

basically improve the workflow from the industry into the bge.

**Comment by youle31** [comment]
Hi, we'll see that according to 2.8 design and code. For now, I put this request in low priority.

**Comment by youle31** [comment]
I close low low priority feature requests for now. They are still visible in closed pull requests list.
