### ISSUE TITLE
Slow Parent Broken

### ISSUE THREAD

**Issue by sdfgeoff** [UPBGE/blender#339]
As said in title. Slow parent, both via the GUI and via obj.timeOffset acts just like a normal parent.

**Comment by panzergame** [comment]
Isn't the case in BFBGE too ?

**Comment by youle31** [comment]
this file: http://pasteall.org/blend/index.php?id=44652 works for me

**Comment by sdfgeoff** [comment]
I am vastly confused, because many of the bugs I encounter fix themselves upon rebooting my PC. I fought this for half an hour and implemented a replacement function in python, and now when I try again, it works.
