### ISSUE TITLE
Default FX -Water 

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#34]
Here is a ray_marched water shader. 

https://www.shadertoy.com/view/lsXGzH

This is pretty neat and could be useful for glass etc, though I am not sure how useful it is 
as I don't understand GLSL yet,

**Comment by panzergame** [comment]
When you ask a feature, always ask you something :"Did this feature will be reused for more that only one strict case ?" if the answer is no, then thing about something more general.

Here the answer is no.
