### ISSUE TITLE
Action Controller

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#342]
Hello! I know there's a lot of other urgent issues to solve, and more feature requests are quite cumbersome, but I think that it's important to document and share stuff like that.
What I'm proposing is an "Action Controller": a controller that triggers actuators synced in a action timeline. I've tried to make some concept sketches, and they are present in here.

**Motivation**
Syncing tasks is quite frustrating in BGE, with a lot of work involved. When making time based tasks, Timers could help, but when something gets complex, it's unmanageable. For example, when you need to make a cutscene, playing sounds of a character speaking at given times needs a lot of researching, and a lot of Python checkings like:
`if game_object.getActionFrame() > 1.0 and object.getActionFrame < 4.0:`
`cont.activate(object_sound)`
Or maybe a simple weapon reloading animation, when you need to play sounds and change properties according to the given animation time and don't want to do a lot of checking and Timer operations.
Part of the idea was taken for Godot engine, where you can animate almost everything, from variables, spatial events, texture changing, etc, and it saves a lot of work. Initially I thought about just a mode in Action Actuator, but since actuators can't activate another actuators (following the SCA concept), the idea moved to a controller.

**Concept**
Attaching to the controller an action made especially to trigger actuators, the controller activates or deactivates the connected actuators based on the action events, following the timeline. It could be like this:
![logic_editor_view](https://cloud.githubusercontent.com/assets/19820741/21228293/5f18339a-c2c4-11e6-9874-872168a33bd3.png)

**Action Model**
The choices to an action model to implement this could involve a lot of options, and these are what I thought:
- Shape Keys Actions: Adding shape keys to the objects with the same name of the actuators to be processed is the most promissing way I tought. The actuators could be activated with a 1.0 value and deactivated with a 0.0 value, and different actuators could be processed at the same time. The downside is that only objects with mesh can have shape keys.
![execution_timeline_shapekeys](https://cloud.githubusercontent.com/assets/19820741/21228523/3d23be84-c2c5-11e6-833f-2e6dd2a00082.png)

- Local Markers In Actions: I'm not sure, probably they are just Blender GUI helpers and could not be processed. However, if they could be converted to some kind of event, each marker could have the name of an actuator to activate. The downside is they can't be deactivated and two or more markers can't be added at the same frame, so there's only one activation per frame.
![execution_timeline_markers](https://cloud.githubusercontent.com/assets/19820741/21228755/22ebdc26-c2c6-11e6-8d68-90bee6f73afe.png)

- Transform Actions: Since objects transforming animation is limited to visual transform and delta transform, this is pretty limited (6 channels, so 6 actuators to activate only). However, transform channels could be renamed to actuators names and multiple actuators could be activated at the same time in this way, just like the shape keys method. The downside is that actuators could not be deactivated and the channel's amount are too limited.
![execution_timeline_transform](https://cloud.githubusercontent.com/assets/19820741/21229055/68c60d1a-c2c7-11e6-91b5-a3e2f544c9ac.png)

I hope this request is worth of discussing, because could be pretty helpful. :smile:

**Comment by youle31** [comment]
This would be too hard to implement (this is not bge code, but mainly blender code) and we have enough work for month so I put the feature requerst in low priority.
You can manage your actions in several ways in bge. With controller states. With python. With python this is really easy. https://www.blender.org/api/blender_python_api_2_78a_release/bge.types.KX_GameObject.html?highlight=playaction#bge.types.KX_GameObject.playAction

**Comment by joelgomes1994** [comment]
Yes, as I said I was sharing a idea and documenting it for it not becoming lost, and maybe ensuring a discussion on how to improve the idea in the meantime, what is the main reason I decided to post it. :smile: 

And about managing actions, I know these ways and I've been using them. However, complex sequences of tasks soon become daunting to do, and almost impossible for a non Python programmer to do or manage in logic bricks. This controller could relief everyone in this kind of tasks, even Python programmers. :smiley:

**Comment by BluePrintRandom** [comment]
I would have a few generic functions called by a list.


walk over to here, play action, change property etc as python functions,
and use a list to call them and then pop them once they are called.

https://www.youtube.com/watch?v=cX4d5QiKYEQ

if you like I have an example

**Comment by youle31** [comment]
I close low low priority feature requests for now. They are still visible in closed pull requests list.
