### ISSUE TITLE
debug number of draw calls

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#343]
now that we have instancing, and soon static draw call batching, it would be informative to see how many draw calls we are calling per frame (as a option that can be turned on / off) or maybe included in debug?

Thank you

**Comment by panzergame** [comment]
A try about render information was made in the old branch `ge_render_info`. But this branch was abandoned as it create major slowdown counting meshes, material, light ect…

**Comment by youle31** [comment]
I close low low priority feature requests for now. They are still visible in closed pull requests list.
