### ISSUE TITLE
Regression in a file

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#345]
Regression in a file:  https://drive.google.com/open?id=0B6yNvVGWiWysMlBTLVljbjFOTFk
The file is modified and save with Upbge master build from the last week.
pic -> http://pasteall.org/pic/index.php?id=110240
Left upbge, right bf bge 278a. It seams to show less fps and more logic, than in bf bge 278.

**Comment by Akira1San** [comment]
I think, that the drop of fps is from the python controller.

**Comment by youle31** [comment]
@Akira1San : When I fix python errors in this file: http://pasteall.org/blend/index.php?id=44734 ,  I have slight better performances in upbge than in bge (print errors in console takes huge performances--I didn't checked if the printed messages are the same in bge/upbge. If the messages are the same, maybe the color of the printed message can slow down upbge. Anyway, performance tests can't be done if there are python errors printed each frame during runtime).

Can you confirm and close if my answer solved the issue? Thanks

**Comment by Akira1San** [comment]
Its fixed.
