### ISSUE TITLE
Warning: MSVC about messages (NetworMessageManager)

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#347]
http://pasteall.org/161035

https://msdn.microsoft.com/fr-fr/library/074af4b6.aspx

**Comment by panzergame** [comment]
Well, this error seems to be caused because MSVC doesn't support long function signature. I don't really see at the moment how to properly fix it. The solution gives by the documentation is to create a new type.

**Comment by youle31** [comment]
We'll see later, when my debugger will remind me this warning... Not very important. I close.
