### ISSUE TITLE
Actions seem to lock up in UPBGE but not run armature

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#35]
I can't seem to reproduce the error in a simple test file, 
https://www.youtube.com/watch?v=pn7AFOZP4_w
would you like my full game? (all rights reserved of course)
@panzergame

**Comment by panzergame** [comment]
@BluePrintRandom : So, the ug is the walk animation half played. This walk animation is an what layer, priority, do you use setActionFrame ?
It will be nice if you can send a minimum example file, e.g : only the player.
