### ISSUE TITLE
Bug: Crash at standalone exit

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#350]
http://pasteall.org/blend/index.php?id=44846 (start standalone then exit -> it crashes for me)

Happens with a simple cube.

Happens only in Win 32 build. In the console, the message error: Totblock: 1 doesn't appear contrarly to win64 builds

Backtrace: http://pasteall.org/pic/show.php?id=110570

**Comment by youle31** [comment]
First bad commit: https://github.com/UPBGE/blender/commit/09803161efe387deedc597154943170e7d2d8c8d

**Comment by panzergame** [comment]
@youle31 Is the the issue fixed ?

**Comment by youle31** [comment]
@panzergame : Yes, it's fixed :) Thanks!
