### ISSUE TITLE
Animation bug

### ISSUE THREAD

**Issue by alabd14313** [UPBGE/blender#352]
Hello!
There is a bug in playing animations (or animation layers !). Here is a file :
[Advanced game character - MarllonxD3.tar.gz](https://github.com/UPBGE/blender/files/678994/Advanced.game.character.-.MarllonxD3.tar.gz)

**Comment by youle31** [comment]
When we change the layer of the BL_ActionActuator this fixes the issue: http://pasteall.org/blend/index.php?id=44868

**Comment by panzergame** [comment]
@alabd14313 : For me the bug is fixed in the branch ge_armature_fix. Could you confirm that nothing else is broke by the fix, please ?

**Comment by youle31** [comment]
It's ok for me in the test file :)

**Comment by alabd14313** [comment]
I tested ge_armature_fix branch and this bug solved.
Thanks!

**Comment by alabd14313** [comment]
Youle, please reopen this issue.

**Comment by panzergame** [comment]
This bug is still actual ?

**Comment by alabd14313** [comment]
I have this bug in v0.2.1 too.

**Comment by Akira1San** [comment]
Tested it. Works in bf bge. In Upbge i had to set the layer to 1, to make the char to walk. Maybe the bug is in the Layer.
