### ISSUE TITLE
Parallax scale bug

### ISSUE THREAD

**Issue by alabd14313** [UPBGE/blender#354]
Hello!

_System_:
Arch Linux
Nvidia 8400gs (OpenGL 3.3)
Ubuntu 16.04
Intel HD

In master branch, It seems parallax scale have no effect but v0.1.2 is fine:
http://pasteall.org/blend/index.php?id=44866
Here is video for comparison:
[video.zip](https://github.com/UPBGE/blender/files/681321/video.zip)

**Comment by alabd14313** [comment]
Hello!
Changing 0 to 0.0 in gpu_shader_material.glsl didn't solved this bug.
`height = textureLod(ima, texco.xy - delta * (1.0 - depth), 0).a;`

**Comment by youle31** [comment]
hello! And with 0.0 in textureLod +

and with the for loop? for (float i = 0.0; i < numsteps; i += 1.0)

**Comment by alabd14313** [comment]
I tested :
i)
`height = textureLod(ima, texco.xy - delta * (1.0 - depth), 0).a;
for (float i = 0.0; i < numsteps; i += 1.0)
`

ii) texture2DLod()
iii) texture2D()
unfortunately have not any effect.
@youle31: texture2d() is deprecated in 3.3 and above, but it kept in compatibility profile.

**Comment by youle31** [comment]
I just looked at your video. Ok your parallax works. It's just the "heightscale" that doesn't work. It's normal, panzergame removed it from the shader. You can have a look at the patch: https://github.com/UPBGE/blender/commit/686112da3bdb527447933fbf1fa0f7684ae433ca
vec2 texuv = texco.xy + height * scale * 0.005;
this line has been replaced by vec2 delta = vec2(-vv.x, vv.y) * bumpscale / vv.z;

I guess it's a mistake. I already told it to panzergame.

@panzergame : Is this a mistake or is it will?

**Comment by youle31** [comment]
Removed option in https://github.com/UPBGE/blender/commit/b6e7205ce57da3605804b0e3a32b0073b19f3a25
