### ISSUE TITLE
Bug: Something wrong with CValue not freed at ge exit

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#356]
http://pasteall.org/177719/diff

Steps to reproduce the bug:

- Build upbge in Debug mode
- start ge then exit
- look at the console

might be related to #350

**Comment by panzergame** [comment]
Should be fixed in latest master, could you check and close please ?

**Comment by youle31** [comment]
Yes :) Fixed in https://github.com/UPBGE/blender/commit/003b4950de7657c294035d7eb2de03ef4aa505fa
