### ISSUE TITLE
static draw call batching problem

### ISSUE THREAD

**Issue by lostscience** [UPBGE/blender#366]
Long load times with 5,528 cubes and static draw call batching it is akira_san build of upbge. 
I am on a computer that has 64 bit version of windows.

**Comment by DCubix** [comment]
Aren't you the guy with the low end PC? If so, we can't do much to overcome that. Batching isn't magic

**Comment by lostscience** [comment]
Yes i am.

**Comment by lostscience** [comment]
I believe the information still maybe important to you.

**Comment by BluePrintRandom** [comment]
Don't have 5,412 x cubes in the viewport,

Have 1 on a hidden layer and spawn them in a row per frame,  all instances
of the same cube.

Should make it almost instant

**Comment by youle31** [comment]
This seems not a bug. Someone will do a tutorial about mesh batching when it will be officially released. I guess it might be long to create the batch if you do a loop with more than 5000 objects in python. But You only have to do it once. What matters is not the loading time. It's the fps after the batch has been created.

**Comment by lostscience** [comment]
But blueprintrandom is' nt that already possible with regular blender's bge.

**Comment by lostscience** [comment]
And also the blender program sticks when i x out.Meaning it prevents me from x ing out a couple of minutes.

**Comment by youle31** [comment]
Wait for the 0.1.4 release to test. If you still have issues, you can open a pull request, but join a test file, make pictures, give us maximum useful infos. For now, I close.

**Comment by BluePrintRandom** [comment]
I accidentally closed my request / bug with static draw call batching
It is still an open issue,  I clicked respond and close on accident*

**Comment by youle31** [comment]
It's me that closed this request made by lostscience. What is the link of Your: "request / bug with static draw call batching" ?

**Comment by BluePrintRandom** [comment]
https://github.com/UPBGE/blender/issues/366

**Comment by BluePrintRandom** [comment]
Disregard last link sorry>

https://github.com/UPBGE/blender/issues/365
