### ISSUE TITLE
Parallax maps do not work correctly on backfaces

### ISSUE THREAD

**Issue by sdfgeoff** [UPBGE/blender#367]
I was trying to make a piece of corrugated iron with just a parralax map, and this is the result:
![backface](https://cloud.githubusercontent.com/assets/13490050/22137017/552b79e2-df3d-11e6-9d06-883c0c25e50b.jpg)

The close object is facing upwards, and the parrallax map works really well. The further object you are seeing the backface, and the parrallax map has issues - seems to discard the wrong fragment sample.

**Comment by youle31** [comment]
Great! Except for the bug haha. I don't really know if if it Is a bug... Did You try to make a second texture with inverted colors for the backface in gimp (i have no idea if it could work). Can You share a test file so we can try to find a solution?

**Comment by youle31** [comment]
http://pasteall.org/205657/diff seems to do the stuff for the backface

**Comment by youle31** [comment]
https://github.com/UPBGE/blender/pull/368

**Comment by panzergame** [comment]
Fixed in 3721f98f40456ef94fc80927f35cad4da06edab0, thanks for report.

**Comment by youle31** [comment]
what do you think about that? http://pasteall.org/211056
http://pasteall.org/pic/show.php?id=111561

Shouldn't be at least an option?

**Comment by youle31** [comment]
no answer . I close

**Comment by lordloki** [comment]
Hi @youle31, I think that parallax inverted on backface should be the wanted. Therefore it should be an optiion at least.

**Comment by youle31** [comment]
ok :P so I reopen the request haha

**Comment by youle31** [comment]
I'd like to test backface with @sdfgeoff texture to see if the shader works correctly or not...

**Comment by panzergame** [comment]
When the normal is inverted the pixel order seems inverted too:
![capture datant de 2017-01-25-06h34min06s](https://cloud.githubusercontent.com/assets/8046004/22280431/90b89402-e2c8-11e6-8257-8eb10392461b.png)
![capture datant de 2017-01-25-06h34min01s](https://cloud.githubusercontent.com/assets/8046004/22280433/9596ecbc-e2c8-11e6-868a-64f7e29015d6.png)

**Comment by panzergame** [comment]
If i do 1 - textureSample depending on the face it fix the pixel order.

**Comment by youle31** [comment]
ok cool :) We'll chat about because I don't "get" the pixel order issue but if you have a good solution that's awesome :)

**Comment by sdfgeoff** [comment]
The image I used was:
![tire](https://cloud.githubusercontent.com/assets/13490050/22319275/0e97d25c-e3e6-11e6-8e07-02ebfee494e8.png)

**Comment by Erstus** [comment]
Initially described issue is now fixed. Maybe open new issue for inverted depth.

**Comment by youle31** [comment]
@sdfgeoff : Thanks very much for sharing your texture: It is great for tests.

**Comment by DCubix** [comment]
Fixed? 😛
