### ISSUE TITLE
Bug: Crash at exit

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#370]
test file: https://drive.google.com/file/d/0B3GouQIyoCmrc1M0Q1BEcHhEdjQ/view?usp=sharing
first bad commit: https://github.com/UPBGE/blender/commit/4be59a3eca2c9b0997aa57af0389c84f4c1f6291

seems an openGL error

**Comment by youle31** [comment]
I tried to look at apitrace, understood nothing, then a nvidia program, could not reproduce the crash when debugging with this program then I read the commit message: In our case, the leafs are mesh slot nodes and they are ordered by the distance between the mesh slot and the camera and I found an useful info :P.

So I stop to talk about my life (or I continue?).

When I am in camera view the crash doesn't happen anymore (Happens only if I am in viewport camera)

**Comment by youle31** [comment]
in RAS_DisplayArrayBucket::GenerateTree, happens only here:

else if (sort) {
		for (RAS_MeshSlot *slot : m_activeMeshSlots) {
			slot->GenerateTree(&m_upwardNode, upwardLeafs);
		}

		m_upwardNode.SetParent(upwardRoot);
	}

**Comment by panzergame** [comment]
Fixed in 98504334418d2db96fab42528e9ae826c75c6622, thanks for report.
