### ISSUE TITLE
Mipmapping / Anisotropic filtering bug

### ISSUE THREAD

**Issue by robzilla-beats** [UPBGE/blender#371]
There is an issue where anisotropic filtering does not shade normal textures correctly in the external player.  It produces hard edges and steps. Disabling mipmaps though python solves this as a temporary workaround, but can we get mipmapping working correctly?
External:
![external](https://cloud.githubusercontent.com/assets/2640996/22184336/62ab2596-e095-11e6-8302-775b86efb90e.png)
Internal:
![internal](https://cloud.githubusercontent.com/assets/2640996/22184337/62abef58-e095-11e6-831c-161a827bef29.png)
BA Thread: 
https://blenderartists.org/forum/showthread.php?414523-Texturing-normal-shading-sharp-edges-on-external-player

**Comment by robzilla-beats** [comment]
adding example .blend


[mipmaps_ex.blend.zip](https://github.com/UPBGE/blender/files/722125/mipmaps_ex.blend.zip)

**Comment by panzergame** [comment]
Fixed in 17afca0b861bb2f34bcda2a453f10bc0f1079cb3.
