### ISSUE TITLE
Precompiled version wont start. libgomp 4.0 not found.

### ISSUE THREAD

**Issue by Erstus** [UPBGE/blender#373]
This issue is with precompiled version, so it's only about ease of installation. It might be that download page is somewhat misleading, making me think, that following those instructions would be enough.

So i followed the guide in [download.upbge.org](url) for 64-bit linux mint 17 to download stable release of UPBGE. After executing given code in terminal I expected the dependencies to be in place.
`sudo apt-get update && sudo apt-get install blender llvm-dev libpugixml-dev`

However, when executing blender, an error appeared:
> /home/linux64latest/blender: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /home/linux64latest/blender)

**Comment by panzergame** [comment]
The last version is now containing a static OpenMP. @Erstus : Could you please check that it's now working ?

**Comment by Erstus** [comment]
That's good. I got it working right away. Note that I'm not on the exact same system now, but a very similar one. Most likely I will have the same results on both, but i will check that on the weekend.

**Comment by Erstus** [comment]
Confirmed, that's fixed now.
