### ISSUE TITLE
GE Crashes on start

### ISSUE THREAD

**Issue by elmeunick9** [UPBGE/blender#374]
When I press "P" or launch blenderplayer with the default scene Blender crashes, also crashes with any other scene. It doesn't happen with BF Blender 2.78a. I get the following error on the terminal:
### 
C:\Users\Maou\Downloads\upbge-master-batch\Release>blender.exe` -d
Switching to fully guarded memory allocator.
Blender 2.78 (sub 4)
Build: Wed 01/18/2017 09:05 PM Windows
argv[0] = blender.exe
argv[1] = -d

_Note: No (valid) 'C:\Users\Maou\AppData\Roaming\Blender Foundation\Blender\2.78\
config\startup.blend' found, fall back to built-in default.

read file
  Version 272 sub 2 date unknown hash unknown

ordered
 OBCube
 OBLamp
 OBCamera
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
found bundled python: C:\Users\Maou\Downloads\upbge-master-batch\Release\2.78\py
thon
addon not found: 'cycles'
libpng warning: iCCP: known incorrect sRGB profile
ED_undo_push: Blender Render
GPUShader: compile error:
===== shader string 1 ====
 1  #version 130
===== shader string 2 ====
 2  #extension GL_ARB_texture_query_lod: enable
===== shader string 3 ====
 3  #define GPU_ATI
 4  #define CLIP_WORKAROUND
 5  #define BUMP_BICUBIC
 6  #define BIT_OPERATIONS
===== shader string 4 ====
 7  #if __VERSION__ < 140
 8  /* Manual implementation of inverse(mat4) for GLSL version before 1.40,
 9   * copied from https://github.com/stackgl/glsl-inverse/blob/master/index.gls
l
10   */
11
12  mat4 inverse(mat4 m) {
13      float a00 = m[0][0], a01 = m[0][1], a02 = m[0][2], a03 = m[0][3],
14      a10 = m[1][0], a11 = m[1][1], a12 = m[1][2], a13 = m[1][3],
15      a20 = m[2][0], a21 = m[2][1], a22 = m[2][2], a23 = m[2][3],
16      a30 = m[3][0], a31 = m[3][1], a32 = m[3][2], a33 = m[3][3],
17
18      b00 = a00 * a11 - a01 * a10,
19      b01 = a00 * a12 - a02 * a10,
20      b02 = a00 * a13 - a03 * a10,
21      b03 = a01 * a12 - a02 * a11,
22      b04 = a01 * a13 - a03 * a11,
23      b05 = a02 * a13 - a03 * a12,
24      b06 = a20 * a31 - a21 * a30,
25      b07 = a20 * a32 - a22 * a30,
26      b08 = a20 * a33 - a23 * a30,
27      b09 = a21 * a32 - a22 * a31,
28      b10 = a21 * a33 - a23 * a31,
29      b11 = a22 * a33 - a23 * a32,
30
31      det = b00 * b11 - b01 * b10 + b02 * b09 + b03 * b08 - b04 * b07 + b05 *
b06;
32
33      return mat4(
34              a11 * b11 - a12 * b10 + a13 * b09,
35              a02 * b10 - a01 * b11 - a03 * b09,
36              a31 * b05 - a32 * b04 + a33 * b03,
37              a22 * b04 - a21 * b05 - a23 * b03,
38              a12 * b08 - a10 * b11 - a13 * b07,
39              a00 * b11 - a02 * b08 + a03 * b07,
40              a32 * b02 - a30 * b05 - a33 * b01,
41              a20 * b05 - a22 * b02 + a23 * b01,
42              a10 * b10 - a11 * b08 + a13 * b06,
43              a01 * b08 - a00 * b10 - a03 * b06,
44              a30 * b04 - a31 * b02 + a33 * b00,
45              a21 * b02 - a20 * b04 - a23 * b00,
46              a11 * b07 - a10 * b09 - a12 * b06,
47              a00 * b09 - a01 * b07 + a02 * b06,
48              a31 * b01 - a30 * b03 - a32 * b00,
49              a20 * b03 - a21 * b01 + a22 * b00) / det;
50  }
51  #endif
===== shader string 5 ====
52  void main()
53  {
54      gl_Position = gl_Vertex;
55      gl_TexCoord[0] = gl_MultiTexCoord0;
56  }
Vertex shader failed to compile with the following errors:
ERROR: 3:6: error(#230) Overloaded functions must have the same parameter qualif
iers in
ERROR: error(#273) 1 compilation errors.  No code generated_

I'm using Windows 7 Professional SP1 x64 , with an ATI Movility Readon HD 5650. On Windows 10 it worked with the drivers provided by windows update unitil eventually the drivers itself broke.

This is with running the build made by Akira_San (on blenderartists), but it also happens with the current builds from upbge.org.

**Comment by Akira1San** [comment]
Made a new build with the latest master: Test - https://drive.google.com/open?id=0B6yNvVGWiWysZEpOVmZ6cXpXZjQ

**Comment by elmeunick9** [comment]
@Akira1San 
I tried with this build, it also crashes.

It doesn't crash with 1.0.0 Fixed (https://download.upbge.org/download/release/windows64/UPBGEv0.1.0b2.78Windows64Fixed.rar), so the bug must have been introduced later.

**Comment by youle31** [comment]
I think @panzergame forgot to put gpu_shader_lib.glsl in a cmakelists. I build and upload

**Comment by elmeunick9** [comment]
I tried with 0.1.1 (works) and 0.1.2 (fails).

**Comment by youle31** [comment]
I'm not sure in fact... Overloaded functions must have the same parameter qualifier. I'll google it

**Comment by youle31** [comment]
This is the build I made but I think finally it won't solve the issue: https://drive.google.com/file/d/0B3GouQIyoCmrTHdDM0xnYjZZa1k/view?usp=sharing

You can still test.

Else do you have a development environment to see if when we don't overload inverse function in gpu_shader_lib.glsl and fix the code in gpu_shader_vertex.glsl (related to instancing) it works?

**Comment by youle31** [comment]
Could you try 0.1.1 with geometry instancing enabled on the cube please?

**Comment by elmeunick9** [comment]
Enabling geometry instancing on 0.1.1 makes the all objects with that material disapear, but the GE starts without giving any error message (and everything else seems to work). The last build you posted also crashes.

**Comment by youle31** [comment]
This is the kind of bug that is very very hard to fix as we can't reproduce it. But as I'm on windows, if you are interested (and if you have a good internet connection), I can help you to install a development environment to build upbge, go into the sources and try to help to solve the bug.

(To install dev environment and build upbge the first time, it can take around an afternoon).

Else I guess if you install lastest drivers from AMD you won't have this bug anymore...

**Comment by elmeunick9** [comment]
Unfortunately installing latest AMD drivers is something I can't do, since those are borken (I'm using the drivers subministred by HP, aka the original drivers).

I've already compiled blender and UPBGE a few times, but always on Linux. I've just installed MVSC2015 today, tomorrow I can't but in a few days I'll try to make a build and see if I can fix the bug (you'll probably find me on IRC asking for help).

**Comment by panzergame** [comment]
I simulate a GLSL 1.20 and 1.10 environment but no error. @elmeunick9 : Could you try compile a version with the lines from blender/source/blender/gpu/shaders/gpu_shader_lib.glsl commented ?

**Comment by panzergame** [comment]
@elmeunick9 : Could you sent all the OpenGL informations through glxinfo ?

**Comment by elmeunick9** [comment]
@panzergame 
I'm on Windows 7, no glxinfo here. I can give you a system-info.txt if it's of any use:

SDL:
===========================================

Version: 2.0.4
Loading method: linked (WITH_SDL_DYNLOAD=OFF)

Other Libraries:
===========================================

OpenColorIO:  1,  0,  9
OpenImageIO:  1,  7,  8
OpenShadingLanguage: Blender was built without Cycles support
OpenVDB: Blender was built without OpenVDB support
Alembic: Blender was built without Alembic support

OpenGL:
===========================================

renderer:	'ATI Mobility Radeon HD 5650'
vendor:		'ATI Technologies Inc.'
version:	'4.0.10188 Compatibility Profile Context'
extensions:
	GL_AMDX_debug_output
	GL_AMDX_vertex_shader_tessellator
	GL_AMD_conservative_depth
	GL_AMD_debug_output
	GL_AMD_draw_buffers_blend
	GL_AMD_name_gen_delete
	GL_AMD_performance_monitor
	GL_AMD_sample_positions
	GL_AMD_seamless_cubemap_per_texture
	GL_AMD_shader_stencil_export
	GL_AMD_texture_cube_map_array
	GL_AMD_texture_texture4
	GL_AMD_transform_feedback3_lines_triangles
	GL_AMD_vertex_shader_tessellator
	GL_ARB_blend_func_extended
	GL_ARB_color_buffer_float
	GL_ARB_copy_buffer
	GL_ARB_depth_buffer_float
	GL_ARB_depth_clamp
	GL_ARB_depth_texture
	GL_ARB_draw_buffers
	GL_ARB_draw_buffers_blend
	GL_ARB_draw_elements_base_vertex
	GL_ARB_draw_indirect
	GL_ARB_draw_instanced
	GL_ARB_explicit_attrib_location
	GL_ARB_fragment_coord_conventions
	GL_ARB_fragment_program
	GL_ARB_fragment_program_shadow
	GL_ARB_fragment_shader
	GL_ARB_framebuffer_object
	GL_ARB_framebuffer_sRGB
	GL_ARB_geometry_shader4
	GL_ARB_gpu_shader5
	GL_ARB_gpu_shader_fp64
	GL_ARB_half_float_pixel
	GL_ARB_half_float_vertex
	GL_ARB_imaging
	GL_ARB_instanced_arrays
	GL_ARB_map_buffer_range
	GL_ARB_multisample
	GL_ARB_multitexture
	GL_ARB_occlusion_query
	GL_ARB_occlusion_query2
	GL_ARB_pixel_buffer_object
	GL_ARB_point_parameters
	GL_ARB_point_sprite
	GL_ARB_provoking_vertex
	GL_ARB_sample_shading
	GL_ARB_sampler_objects
	GL_ARB_seamless_cube_map
	GL_ARB_shader_atomic_counters
	GL_ARB_shader_bit_encoding
	GL_ARB_shader_objects
	GL_ARB_shader_subroutine
	GL_ARB_shader_texture_lod
	GL_ARB_shading_language_100
	GL_ARB_shadow
	GL_ARB_shadow_ambient
	GL_ARB_sync
	GL_ARB_tessellation_shader
	GL_ARB_texture_border_clamp
	GL_ARB_texture_buffer_object
	GL_ARB_texture_compression
	GL_ARB_texture_compression_rgtc
	GL_ARB_texture_cube_map
	GL_ARB_texture_cube_map_array
	GL_ARB_texture_env_add
	GL_ARB_texture_env_combine
	GL_ARB_texture_env_crossbar
	GL_ARB_texture_env_dot3
	GL_ARB_texture_float
	GL_ARB_texture_gather
	GL_ARB_texture_mirrored_repeat
	GL_ARB_texture_multisample
	GL_ARB_texture_non_power_of_two
	GL_ARB_texture_query_lod
	GL_ARB_texture_rectangle
	GL_ARB_texture_rg
	GL_ARB_texture_rgb10_a2ui
	GL_ARB_texture_snorm
	GL_ARB_timer_query
	GL_ARB_transform_feedback2
	GL_ARB_transform_feedback3
	GL_ARB_transpose_matrix
	GL_ARB_uniform_buffer_object
	GL_ARB_vertex_array_bgra
	GL_ARB_vertex_array_object
	GL_ARB_vertex_buffer_object
	GL_ARB_vertex_program
	GL_ARB_vertex_shader
	GL_ARB_vertex_type_2_10_10_10_rev
	GL_ARB_window_pos
	GL_ATI_draw_buffers
	GL_ATI_envmap_bumpmap
	GL_ATI_fragment_shader
	GL_ATI_meminfo
	GL_ATI_separate_stencil
	GL_ATI_texture_compression_3dc
	GL_ATI_texture_env_combine3
	GL_ATI_texture_float
	GL_ATI_texture_mirror_once
	GL_EXT_abgr
	GL_EXT_bgra
	GL_EXT_bindable_uniform
	GL_EXT_blend_color
	GL_EXT_blend_equation_separate
	GL_EXT_blend_func_separate
	GL_EXT_blend_minmax
	GL_EXT_blend_subtract
	GL_EXT_compiled_vertex_array
	GL_EXT_copy_buffer
	GL_EXT_copy_texture
	GL_EXT_direct_state_access
	GL_EXT_draw_buffers2
	GL_EXT_draw_instanced
	GL_EXT_draw_range_elements
	GL_EXT_fog_coord
	GL_EXT_framebuffer_blit
	GL_EXT_framebuffer_multisample
	GL_EXT_framebuffer_object
	GL_EXT_framebuffer_sRGB
	GL_EXT_geometry_shader4
	GL_EXT_gpu_program_parameters
	GL_EXT_gpu_shader4
	GL_EXT_histogram
	GL_EXT_multi_draw_arrays
	GL_EXT_packed_depth_stencil
	GL_EXT_packed_float
	GL_EXT_packed_pixels
	GL_EXT_pixel_buffer_object
	GL_EXT_point_parameters
	GL_EXT_provoking_vertex
	GL_EXT_rescale_normal
	GL_EXT_secondary_color
	GL_EXT_separate_specular_color
	GL_EXT_shadow_funcs
	GL_EXT_stencil_wrap
	GL_EXT_subtexture
	GL_EXT_texgen_reflection
	GL_EXT_texture3D
	GL_EXT_texture_array
	GL_EXT_texture_buffer_object
	GL_EXT_texture_buffer_object_rgb32
	GL_EXT_texture_compression_bptc
	GL_EXT_texture_compression_latc
	GL_EXT_texture_compression_rgtc
	GL_EXT_texture_compression_s3tc
	GL_EXT_texture_cube_map
	GL_EXT_texture_edge_clamp
	GL_EXT_texture_env_add
	GL_EXT_texture_env_combine
	GL_EXT_texture_env_dot3
	GL_EXT_texture_filter_anisotropic
	GL_EXT_texture_integer
	GL_EXT_texture_lod
	GL_EXT_texture_lod_bias
	GL_EXT_texture_mirror_clamp
	GL_EXT_texture_object
	GL_EXT_texture_rectangle
	GL_EXT_texture_sRGB
	GL_EXT_texture_shared_exponent
	GL_EXT_texture_snorm
	GL_EXT_texture_swizzle
	GL_EXT_timer_query
	GL_EXT_transform_feedback
	GL_EXT_vertex_array
	GL_EXT_vertex_array_bgra
	GL_EXT_vertex_attrib_64bit
	GL_IBM_texture_mirrored_repeat
	GL_KTX_buffer_region
	GL_NV_blend_square
	GL_NV_conditional_render
	GL_NV_copy_depth_to_color
	GL_NV_explicit_multisample
	GL_NV_float_buffer
	GL_NV_half_float
	GL_NV_primitive_restart
	GL_NV_texgen_reflection
	GL_SGIS_generate_mipmap
	GL_SGIS_texture_edge_clamp
	GL_SGIS_texture_lod
	GL_SUN_multi_draw_arrays
	GL_WIN_swap_hint
	WGL_EXT_swap_control

Implementation Dependent OpenGL Limits:
===========================================

Maximum Fixed Function Texture Units:	8
Maximum DrawElements Vertices:	2147483647
Maximum DrawElements Indices:	16777215

GLSL:
Maximum Varying Floats:	64
Maximum Vertex Attributes:	16
Maximum Vertex Uniform Components:	1024
Maximum Fragment Uniform Components:	1024
Maximum Vertex Image Units:	16
Maximum Fragment Image Units:	16
Maximum Pipeline Image Units:	32

**Comment by panzergame** [comment]
@youle31 : I pushed a branch named `ge_glsl_inverse` with a check under version 130. Could you please compile it and send it here ?
@elmeunick9 : When @youle31  will provide the build could you test it ?

**Comment by Akira1San** [comment]
ge_glsl_inverse https://drive.google.com/open?id=0B6yNvVGWiWysLTA5OEV3X0ZwM2c

**Comment by elmeunick9** [comment]
@Akira1San 
As mentioned in the referenced issue, I updated the drivers, 0.1.3 doesn't even start now. The build you posted does start, but again crashes when starting the GE, the errors are the same but in diferent locations:

$ ./blender
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
GPUShader: compile error:
Vertex shader failed to compile with the following errors:
ERROR: 3:10: error(#230) Overloaded functions must have the same parameter qualifiers in
ERROR: 3:15: error(#230) Overloaded functions must have the same parameter qualifiers in
ERROR: 3:31: error(#230) Overloaded functions must have the same parameter qualifiers in
ERROR: error(#273) 3 compilation errors.  No code generated


Error: EXCEPTION_ACCESS_VIOLATION


To me it seems that 130 should not define the "inverse" function, but my rotten ATI drivers define it anyway, so we have a name collision. Isn't it possible to change the name to "_inverse"?

P.S. There is any way to debug Blender faster? It takes ages to compile very time I make a change, and the actual gpu_shader_lib.glsl file doesn't appear on my VS project, so I have to use datatoc.exe to generate the .c file each time (and I think I'm doing it wrong).

**Comment by youle31** [comment]
Hi, about bluiding blender, you don't have to build from scratch each time. If you make a modif in cmake, I think you can:
- Run Cmake -> configure + configure + generate
- Open blender.sln
- Right click on INSTALL in solution explorer
- Build

else you can skip the first step. This will only rebuild the needed files. Also, in mosts cases, for rebuild, you can right click on ALL_BUILD then build. It is faster but doesn't take into account changes you did in some files (python files for example...)

**Comment by Akira1San** [comment]
msvs2015, open the blender.sin and rmb install - build. And if theres is change in code i use build again, so its faster that way.

**Comment by elmeunick9** [comment]
@Akira1San
How is DirectX related to blender, doesn't use OpenGL only?

I did not understand much of what you said... you mean remove the "INSTALL" project and build again? I'm sure it must be something else, probably some build option you disabled when doing that last build.

**Comment by Akira1San** [comment]
I mean a program wanted to install "Microsoft directx sdk june2010" i dont remember if it was for blender...

**Comment by Akira1San** [comment]
My drv version is old, pic: http://pasteall.org/pic/show.php?id=112153
Maybe if you try that version.

**Comment by panzergame** [comment]
@elmeunick9: Just to be sure, you have a black render in the viewport before trying to start the BGE ?

**Comment by elmeunick9** [comment]
No, everything works fine before trying to start the BGE.
Or "worked" fine, after the drivers update Blender doesn't even start now.
I'll have to rollback.

2017-02-08 14:22 GMT+01:00 panzergame <notifications@github.com>:

**Comment by Akira1San** [comment]
Ive made a new build with vs 2013, try; https://drive.google.com/open?id=0B6yNvVGWiWysbDhMMEdIakNiMzg

**Comment by elmeunick9** [comment]
@Akira1San
Blender works now, but again crashes on GE start. So, as I understand, builds made with VS2013 only fail on the shader, while builds made with VS2015 fail on both.

**Comment by panzergame** [comment]
@Akira1San or @youle31 : Could you compile again the `ge_glsl_inverse` branch in MSVC2013 and send the builds here please ?

@elmeunick9 : Could you test one of these builds and report the message in console starting with:
``` Compile shader with version directive:  ```

**Comment by panzergame** [comment]
oops

**Comment by youle31** [comment]
https://drive.google.com/file/d/0B3GouQIyoCmrM0VZaFd3LXlicDA/view?usp=sharing

**Comment by elmeunick9** [comment]
$ ./blender -d
Error: EXCEPTION_ACCESS_VIOLATION

So, it wasn't MSVC15 the cause of the crash at the start? I'm pretty lost now.

**Comment by Akira1San** [comment]
my build(vs2013_64b), latest master: https://drive.google.com/open?id=0B6yNvVGWiWysVHRVS2J5b0tjTGM

**Comment by youle31** [comment]
It seems there are 2 problems:
- Blender crashes at start
- When Blender doesn't crash at start, there's an issue with glsl inverse custom implementation and your drivers -> For this last issue, revert manually b5238de3623d93c2484fa7ac532b4bd988190ac8 and 81d0d0468343025b70a1f49e5e0351e91070071f would solve the issue (but you couldn't use geometry instancing). But if you can't start blender, you can't check.

As we can't reproduce the bugs, the only ways would be:
- That you can run Blender with a debugger like Visual studio debugger and try to debug it but it needs experience with debuggers.
- That you find a more recent driver than the ones provided by HP for ATI Movility Readon HD 5650 but not the lastest drivers if they causes issues...

**Comment by elmeunick9** [comment]
@youle31 
Yes that's the situation. On last build (by @Akira1San) it started, but crashed again on the shader. This is the full output from the console (again, it looks to me like "version" in the shader is wrong, since my drivers are perfectly capable of running 330 core):

C:\Users\Maou\Downloads\upbge-pre015-masterbuild-vs2013\Release>blender.exe -d
Switching to fully guarded memory allocator.
Blender 2.78 (sub 4)
Build: Mon 02/27/2017 09:49 PM Windows
argv[0] = blender.exe
argv[1] = -d

Note: No (valid) 'C:\Users\Maou\AppData\Roaming\Blender Foundation\Blender\2.78\
config\startup.blend' found, fall back to built-in default.

read file
  Version 272 sub 2 date unknown hash unknown

ordered
 OBCube
 OBLamp
 OBCamera
found bundled python: C:\Users\Maou\Downloads\upbge-pre015-masterbuild-vs2013\Re
lease\2.78\python
addon not found: 'io_scene_3ds'
addon not found: 'io_scene_fbx'
addon not found: 'io_anim_bvh'
addon not found: 'io_mesh_ply'
addon not found: 'io_scene_obj'
addon not found: 'io_scene_x3d'
addon not found: 'io_mesh_stl'
addon not found: 'io_mesh_uv_layout'
addon not found: 'io_curve_svg'
addon not found: 'cycles'
libpng warning: iCCP: known incorrect sRGB profile
ED_undo_push: Blender Render
GPUShader: compile error:
===== shader string 1 ====
 1  #version 130
===== shader string 2 ====
 2  #extension GL_ARB_texture_query_lod: enable
===== shader string 3 ====
 3  #define GPU_ATI
 4  #define CLIP_WORKAROUND
 5  #define BUMP_BICUBIC
 6  #define BIT_OPERATIONS
===== shader string 4 ====
 7  #if __VERSION__ < 140
 8  /* Manual implementation of inverse(mat4) for GLSL version before 1.40,
 9   * copied from https://github.com/stackgl/glsl-inverse/blob/master/index.gls
l
10   */
11
12  float inverse(float m) {
13    return 1.0 / m;
14  }
15
16  mat2 inverse(mat2 m) {
17    return mat2(m[1][1],-m[0][1],
18               -m[1][0], m[0][0]) / (m[0][0]*m[1][1] - m[0][1]*m[1][0]);
19  }
20
21  mat3 inverse(mat3 m) {
22    float a00 = m[0][0], a01 = m[0][1], a02 = m[0][2];
23    float a10 = m[1][0], a11 = m[1][1], a12 = m[1][2];
24    float a20 = m[2][0], a21 = m[2][1], a22 = m[2][2];
25
26    float b01 = a22 * a11 - a12 * a21;
27    float b11 = -a22 * a10 + a12 * a20;
28    float b21 = a21 * a10 - a11 * a20;
29
30    float det = a00 * b01 + a01 * b11 + a02 * b21;
31
32    return mat3(b01, (-a22 * a01 + a02 * a21), (a12 * a01 - a02 * a11),
33                b11, (a22 * a00 - a02 * a20), (-a12 * a00 + a02 * a10),
34                b21, (-a21 * a00 + a01 * a20), (a11 * a00 - a01 * a10)) / det;

35  }
36
37  mat4 inverse(mat4 m) {
38      float a00 = m[0][0], a01 = m[0][1], a02 = m[0][2], a03 = m[0][3],
39      a10 = m[1][0], a11 = m[1][1], a12 = m[1][2], a13 = m[1][3],
40      a20 = m[2][0], a21 = m[2][1], a22 = m[2][2], a23 = m[2][3],
41      a30 = m[3][0], a31 = m[3][1], a32 = m[3][2], a33 = m[3][3],
42
43      b00 = a00 * a11 - a01 * a10,
44      b01 = a00 * a12 - a02 * a10,
45      b02 = a00 * a13 - a03 * a10,
46      b03 = a01 * a12 - a02 * a11,
47      b04 = a01 * a13 - a03 * a11,
48      b05 = a02 * a13 - a03 * a12,
49      b06 = a20 * a31 - a21 * a30,
50      b07 = a20 * a32 - a22 * a30,
51      b08 = a20 * a33 - a23 * a30,
52      b09 = a21 * a32 - a22 * a31,
53      b10 = a21 * a33 - a23 * a31,
54      b11 = a22 * a33 - a23 * a32,
55
56      det = b00 * b11 - b01 * b10 + b02 * b09 + b03 * b08 - b04 * b07 + b05 *
b06;
57
58      return mat4(
59              a11 * b11 - a12 * b10 + a13 * b09,
60              a02 * b10 - a01 * b11 - a03 * b09,
61              a31 * b05 - a32 * b04 + a33 * b03,
62              a22 * b04 - a21 * b05 - a23 * b03,
63              a12 * b08 - a10 * b11 - a13 * b07,
64              a00 * b11 - a02 * b08 + a03 * b07,
65              a32 * b02 - a30 * b05 - a33 * b01,
66              a20 * b05 - a22 * b02 + a23 * b01,
67              a10 * b10 - a11 * b08 + a13 * b06,
68              a01 * b08 - a00 * b10 - a03 * b06,
69              a30 * b04 - a31 * b02 + a33 * b00,
70              a21 * b02 - a20 * b04 - a23 * b00,
71              a11 * b07 - a10 * b09 - a12 * b06,
72              a00 * b09 - a01 * b07 + a02 * b06,
73              a31 * b01 - a30 * b03 - a32 * b00,
74              a20 * b03 - a21 * b01 + a22 * b00) / det;
75  }
76  #endif
===== shader string 5 ====
77  void main()
78  {
79      gl_Position = gl_Vertex;
80      gl_TexCoord[0] = gl_MultiTexCoord0;
81  }
Vertex shader failed to compile with the following errors:
ERROR: 3:10: error(#230) Overloaded functions must have the same parameter quali
fiers in
ERROR: 3:15: error(#230) Overloaded functions must have the same parameter quali
fiers in
ERROR: 3:31: error(#230) Overloaded functions must have the same parameter quali
fiers in
ERROR: error(#273) 3 compilation errors.  No code generated


Unable to create a GPUShader for builtin shader: 7
Error: EXCEPTION_ACCESS_VIOLATION

**Comment by panzergame** [comment]
@significant-bit : Could you take a short look at this issue ? Also i saw on of your commit in blender2.8 talking about the OGL context version given by AMD drivers, could it be related ?

**Comment by DCubix** [comment]
Is this fixed?

**Comment by panzergame** [comment]
Blender 2.8 will request OGL 3.0 with a valid `inverse` function.
