### ISSUE TITLE
Font issue with linked blends

### ISSUE THREAD

**Issue by sdfgeoff** [UPBGE/blender#377]
Fonts in subfolders using linked groups don't work. Seems they don't know that the path of the font should be relative to the path of the blend it was linked from.

Example structure:
[FontLinkedGroupExample.zip](https://github.com/UPBGE/blender/files/731498/FontLinkedGroupExample.zip)

**Comment by youle31** [comment]
I think this report should be adressed to BF blender. I'll have a quick look however.

You can still open a bug report here: https://developer.blender.org/maniphest/project/2/type/Bug/

If you open a bug report, you can paste the bug report link here and I'll add infos to your bug report if I find something interesting.

**Comment by sdfgeoff** [comment]
Has been fixed over here:
https://github.com/simedis/blender/commit/cce795a86761fdd45ad4c457881c4d870bc9ec8a

**Comment by youle31** [comment]
Sorry I was wrong, I reopen the issue

**Comment by panzergame** [comment]
Did this commit fix the issue: 6f8c7afcaa0a126b3e82c61e72cc15244913e077 ?

**Comment by youle31** [comment]
Oh sorry I didn't see that you made a fix for this bug panzergame.
