### ISSUE TITLE
LibFree makes BGE crash in some cases

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#382]
Hello! Just googled to see if I was doing something wrong, but it seems an slippery problem, according to various sources. The more relevant ones:

https://developer.blender.org/T40555
https://developer.blender.org/D1004
https://developer.blender.org/T32775

Basically, I have a function that loads and/or frees map chunks according to the current map chunk (for an easy open world like system). On a simple game it works well, but the BGE is crashing on a more complex setup, specifically when it needs to LibFree the chunks (LibLoaded as "Scene"), or it simply crashes when exiting the BGE, in both cases printing "Error: EXCEPTION_ACCESS_VIOLATION" in the console.

See the simple project (working): https://github.com/joelgomes1994/bge_openworld
See the complex project (crashing): https://github.com/joelgomes1994/bge_dw

Both projects are loading scenes through LibLoad in "Scene" mode, and each map chunk is assembled through linked libraries. In "bge_dw", the "load_chunks" function is inside of "//scripts/player/spatial.py". I don't know if it's relevant.

Oh yes, the system is Windows 7 64 bit, and tested on UPBGE 0.1.2, 0.1.3 and  0.1.4.

**Comment by joelgomes1994** [comment]
Just deactivated animations from "//libs/vegetation/bushes.blend", now it stopped crashing when exiting BGE, and most of the times it LibFree map chunks, but still crashes sometimes. As I read somewhere, LibLoading an "Scene" where animations play leads to crashes and unexpected behavior.

**Comment by panzergame** [comment]
@joelgomes1994 : Could you test with the recent master ?

**Comment by joelgomes1994** [comment]
Sorry for the late response, @panzergame .
Is there any minimal build available? I can't build by myself.

**Comment by panzergame** [comment]
@youle31 or @AkiraSan1 ? :P

**Comment by youle31** [comment]
https://drive.google.com/file/d/0B3GouQIyoCmrSXlmNnBHUXdaVEU/view?usp=sharing

**Comment by joelgomes1994** [comment]
Working very well now, with no crashes or error messages, both in the embedded player and standalone player. Nice job with the fix, and thanks a lot! :smile:

**Comment by youle31** [comment]
Thanks for feedback! I close the report then :) Thanks panzergame!
