### ISSUE TITLE
Bug: On scene restart, bge.logic is not freed

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#383]
https://www.dropbox.com/s/84yk99zkw5bzxsw/waterRestartScene.blend?dl=0

https://blenderartists.org/forum/showthread.php?415218-Help-with-water-reflection-on-scene-restart

**Comment by lordloki** [comment]
Related to https://developer.blender.org/T36779

**Comment by panzergame** [comment]
I spent sometimes ago to ensure that the `Texture` instances are freed at game restart, but theirs python proxy is still alive and in bge.logic.
The only thing odd here is that if you test with an other python type like an integer, the value set in bge.logic is correctly deleted.

**Comment by youle31** [comment]
@panzergame : In the test file I shared on BA, I tested with an integer that seemed not freed on scene restart (There is a .blend)

**Comment by panzergame** [comment]
I mismatch the comparison, your file is restarting the scene not the game, as other scene could be still active the bge.logic modules is not reload because these active scene could use variable into bge.logic shared between scenes.

If you want to avoid error you could check that the `Texture` into bge.logic is valid or not: `bge.logic.reflection.invalid`.

@youle31, @lordloki : Do you agree that the behaviour is normal ?

**Comment by youle31** [comment]
Yeah I agree. I think this is to the user to adapt the script in this case. So we could leave a note in the bug report mentionned by @lordloki and close it, then close this one.

**Comment by youle31** [comment]
@lordloki : Do you agree that it is to the user to use your "fix" in this situation? Do you agree to close the report in BF and this report?

On BF we can leave a message like: bge.logic module must not be freed at SCENE restart because it is useful to store variables after scene restart, and also to store data at all moment during runtime. bge.logic must only be freed in the case we use restart GAME with actuator or python API. So we consider that this is not really a bug and close it.

We could eventually add a note in the doc about bge.logic not freed at scene restart in the doc...

**Comment by lordloki** [comment]
@youle, @panzergame: Yes, I agree with both. I will leave a message in BF pointing that bge.logic module only is freed at game reload not at scene reload. I will close that BF Bug when I add the comment in bge.logic documentation. 

We can close this bug.

**Comment by youle31** [comment]
Thanks @lordloki for review and for BF bug report update!
Thanks @panzergame for review!

I close this.
