### ISSUE TITLE
Bug: freeze at embedded player start

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#384]
https://blenderartists.org/forum/showthread.php?415158-HELP-Needed-to-test-UPBGE-0-1-4-Windows-Builds

If you have the same bug, please add infos here:

- GPU, OS
- All infos I asked in blenderartists thread.

Thanks!

**Comment by elmeunick9** [comment]
Isn't this the same than #374? They seem to be related. By the way, I updated my drivers, now it doesn't crash when starting the GE, now it crashes when starting Blender itself, that's some useful update ATI made here.

**Comment by youle31** [comment]
I don't know if it is related because you talk about a "crash" whereas the others talk about a "freeze" and they haven't console outuput as far I understood (and the #384 bug only occurs in embedded, not in standalone)... But we are in the same kind of situation where we "need" necessarly someone who can reproduce the bug and run the file in a debugger with breakpoints.

**Comment by youle31** [comment]
This one is SOLVED (Thatimster feedback on BA). UPBGE Builds have to be done with MSVC 2013. I let the issue opened while ge_c26642 is not commited.

**Comment by lordloki** [comment]
It was a bug really rare. I think it is related to ATI cards and related to International/IME/NDof CMake activation. I hope that when we merge with BF blender we can solve it (then we will count with developers with ATI card).

**Comment by youle31** [comment]
Hello @lordloki : I'm not sure this bug is related to elmeunick bug. Actually, I'm wondering if it doesn't concern more the devs who are updating MSVC 2015 librairies but noone can be sure as we didn't get enough infos about it. What we know for sure is that with the same build options in cmake, build worked for Thatimster whereas when we build with MSVC 2015, it didn't work. Of course this could also concern Visual studio 2015 that would forgot to dispaly an important warning.

But however I doubt the fact we'll build now with MSVC 2013 will solve #374 that seems more related to inverse function implementation for GLSL VERSION < 140 as far I understood...

I like your expression: "Frankenstein build :P" hehe

**Comment by youle31** [comment]
We had 2 feedbacks: 1 from Thatimster and another from hanzo on BA that told us the issue was solved. I hope this will be the case for everyone. So I close this for now.
