### ISSUE TITLE
Bug: Culling issue?

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#385]
http://pasteall.org/blend/index.php?id=45382

I have culling issues in this file when I'm  in camera view and when I move... I don't know if it comes from my scripts. I just open issue. I'll make tests later.

I confirm: I have not this in BF bge. The bug was already there in 0.1.3

Nothing to do with the bug: https://www.youtube.com/watch?v=7CbD0KnD4XA ... Just to show an animated forest :)

(Oh also there is a minor issue with batching -> crash when we try to batch the child of an armature... just to remember)

**Comment by panzergame** [comment]
Fixed in ef1e4c5f359e1aeacad3d32e0c983d9dc7d5fa42.

**Comment by youle31** [comment]
I just tested and the bug is still here for me...

**Comment by panzergame** [comment]
@youle31 : I amended the commit yesterday, are you sure that you pulled it ?
I tested again but i didn't see the bug any more.

**Comment by panzergame** [comment]
Fixed in cc1f990d553e853b73ff48f9bce8e3ddf3f5415d.

**Comment by youle31** [comment]
Thanks very much! I'll try when I'll have time

**Comment by youle31** [comment]
Works! :)
