### ISSUE TITLE
Gamepad Speedlink Strike NX Wireless, not detected

### ISSUE THREAD

**Issue by minitrope** [UPBGE/blender#386]
Hi,

I have a Speedlink gamepad that is not detected by the current UPBBGE (0.1.4).
When I try to list gamepads with `bge.logic.joysticks` I get a list of `None`.
The Gamepad is detected in other games.

How can I help to move this forward, since I have the hardware?

**Comment by lordloki** [comment]
Hi,
We need your help to add a new gamepad. 
You need download the antimicro program from: https://github.com/AntiMicro/antimicro/releases
After, follow the instructions from: https://github.com/AntiMicro/antimicro/wiki/Adding-A-New-Game-Controller-Mapping-under-AntiMicro and send us the "SDL 2 Game Controller Mapping String".
After that I will add the gamepad to our database and I will create a pull request against main SDL2 controller database too.

**Comment by minitrope** [comment]
AntiMicro detects the gamepad correctly and has the following mapping string:
`030000005e0400008e02000010010000,X360 Controller,platform:Linux,a:b0,b:b1,x:b2,y:b3,back:b6,start:b7,guide:b8,leftshoulder:b4,rightshoulder:b5,leftstick:b9,rightstick:b10,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,`

The same definition seems to be present in `DEV_JoystickMappingdb.h` so I don't see why the gamepad is not already detected. Thanks for the quick response though, and I'm happy to help if you need more info.

**Comment by panzergame** [comment]
Hello @minitrope, i have some questions:
1) What's your OS ?
2) Did you used a pre-compiled version from download.upbge.org ?
3) Do you have sdl2 in your system ? (i think yes as you generate the mapping).

**Comment by minitrope** [comment]
1. Ubuntu 16.04
2. Yes
3. No (I got the gamepad string on a different machine)

Should I install SDL2 and see if that changes anything?
