### ISSUE TITLE
Performance: Animated trees

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#388]
https://blenderartists.org/forum/showthread.php?415363-Another-infinite-runner-(in-forest)

Runs very faster in BF bge than in upbge (even when I uncheck sky background and if I put all materials on constant) Maybe I forgot something?

Perfs on my PC:

- BF: 400+ fps
- upbge: ~290 fps

@Akira_san signaled an issue last time with animations and I told him this was probably not an issue but maybe I was wrong. I have to check if in animated trees the problem comes from animations.

Actually, I'm not 100% sure that it comes from animations but I think this is the problem. I have ~the same perfs in BF and upbge when I disable animation on tree (layer 2). Note: in BF it uses Vertex Arrays also... Animations work better with Vertex Arrays + DL than VBO? When I put in VBO in BF blender it is still faster than in upbge... Was there an animation culling in BF bge that is not in upbge?

**Comment by panzergame** [comment]
Animations looks like the issue, the other time are lower in UPBGE than in BFBGE for me.
@youle31 : If you have time could you try to bisect the recent releases ? Thanks in advance.

**Comment by youle31** [comment]
I was not motivated today but I'll try next night. Maybe cu tonight!

**Comment by youle31** [comment]
First bad commit: c58e72689ddda0e033ba397a059c7ad0e8c4f531 (I didn't saw it, it was the second commit after 0.0.1 release :) )

**Comment by youle31** [comment]
I think there are 2 reasons for the performances decrease:
1) UpdateIpo was executed in threading.
2) in static void update_anim_thread_func, there was a culling test to update only needed IPOs

**Comment by panzergame** [comment]
Fixed in 9ee38dcde84476b3d6af566bf981c7f0d68c6906.
