### ISSUE TITLE
Bug: Animated UV Texture is crashing and buggy

### ISSUE THREAD

**Issue by jutilities** [UPBGE/blender#39]
When i want to use animated UV textures in BGE it constantly crashes, when i use .png files.
When i use .jpg files it kinda works but only buggy. The Sprites doesnt go in the correct order and sometimes its just a glitchy texture.

I have no real idea why but for sure I am not the onlyone.

**Comment by youle31** [comment]
Is this upbge related? or bge?
Can you provide a .blend?
Can you tell us if it worked in Blender 2.75?
Can you test with the last buildbot version to see if the bug is still here: https://builder.blender.org/download/

**Comment by jutilities** [comment]
yep, i will test it with the latest build and will document it further. Gimme some time :)

**Comment by panzergame** [comment]
Since we don't have more detail or file to test, i set the issue as invalid temporary. @jutilities: i will remove the tag when it will be ok.

**Comment by panzergame** [comment]
No answers, i close it.

**Comment by jutilities** [comment]
yeah sorry, when i have the time i will repost it with Pictures and better description!
