### ISSUE TITLE
Fix creating embedded window for BGE.

### ISSUE THREAD

**Issue by parshin-pn** [UPBGE/blender#391]
I'm trying to embed player in my desktop application and found a small bug in [GPG_ghost.cpp](https://github.com/UPBGE/blender/blob/master/source/gameengine/GamePlayer/GPG_ghost.cpp#L407) at line 407:
```cpp
GHOST_IWindow *window = system->createWindow(title, 0, 0, 0, 0, state,
GHOST_kDrawingContextTypeOpenGL, glSettings, parentWindow);
```
Argument `parentWindow` implicitly converting to `bool` value as long as function `createWindow` takes 10 arguments.

Attach [patch](https://gist.github.com/parshin-pn/8936f865cdfd30c137bdd935b895f87a).

**Comment by panzergame** [comment]
@parshin-pn : Thanks for the bug and fix. I'm currently committing it.

**Comment by panzergame** [comment]
Committed in 33cc843a1a2ec6c39f75f4fa14e5534cbe6dca18.
