### ISSUE TITLE
Bug: Profile texts not drawn correctly

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#396]
http://pasteall.org/pic/show.php?id=112836
http://pasteall.org/blend/index.php?id=45661

**Comment by youle31** [comment]
happened first beetween 0.13 and 0.1.4

**Comment by youle31** [comment]
First bad commits: This 849d065e81b730db397f7d6db0734a8362654951 or that: 385f61355687b84aa5984eb8ded6201d447bd8f2

**Comment by youle31** [comment]
http://pasteall.org/266978/diff

**Comment by panzergame** [comment]
Fixed in e45199e5cdc6e34e914c2eccbe74baa2abd74b6d
