### ISSUE TITLE
OffScreen Color Attachments: Only the first works.

### ISSUE THREAD

**Issue by DCubix** [UPBGE/blender#397]
When you create an OffScreen that has multiple color attachments, only the first color attachment can be written to, the others just don't work (gl_FragData[0] is the same as gl_FragColor by default)

Test blend: http://pasteall.org/blend/index.php?id=45680

**Comment by youle31** [comment]
fixed in https://github.com/UPBGE/blender/commit/536ff879466997f4ea6e7faf6d9c9c2082be1917
