### ISSUE TITLE
Сlean mixing lighting

### ISSUE THREAD

**Issue by ondredeniso** [UPBGE/blender#399]
When a lot of mixed lights, shows as critically in some cases. Maybe need clamp values from lamp energy between 0.0 - 1.0 on material diffuse? Or something other (optionally)?

![lamps](https://cloud.githubusercontent.com/assets/23156358/23330612/60173d42-fb6b-11e6-9439-7c6cbe29cf5d.png)

https://drive.google.com/open?id=0B3I8RJRCxuwic2lEZWhMVUdCalk

**Comment by youle31** [comment]
In my opinion it's a normal behavior that when you add 2 lamps, it is brighter than when you add only one lamp. Like in the reality no? I take the responsability to close the issue. If a dev doesn't agree, he can reopen the issue.

**Comment by ondredeniso** [comment]
you disappointed. unity has clamped materials, why blender can not?

**Comment by ondredeniso** [comment]
# youle31 is be very useful feature in big game projects, i 1000000% sure!!!!!!!!!!!11

**Comment by ondredeniso** [comment]
unwatch & unstar. bad upbge

**Comment by youle31** [comment]
pfff. I'm not god. I just estimated reading what you suggested that it was not very useful. It's viewport code, not our main action domain, you can clamp lamp.energy yourself in python ( min(maxEnegy, max(minEneergy, energyValue)) ).
I estimated this was not prior, that I don't wanted to code it myself. I proposed the other devs to reopen if they find it interested.

**Comment by youle31** [comment]
(they receive automatically a message when I close something and when you submit a features request)

I think we'll forbid features requests because this leads to this kind of situation where the user feels disappointed and the developer (who doesn't want particularly to be an asshole) is disappointed too.

**Comment by ondredeniso** [comment]
sry for my  melancholia. we are was dont understand ourself. I suggest make feature option for materials for avoid unwanted brightness, is minimal viewport changes, but much gpu diffuse shading.
