### ISSUE TITLE
visibilty with the lod system

### ISSUE THREAD

**Issue by lostscience** [UPBGE/blender#40]
Could we have the visibility of an object tied into upbge the lod system?Like if you are certain 
distance away from it would become visible.If you are not within that distance it would stay invisible.

**Comment by lordloki** [comment]
I think that you can do that at this moment replacing the object by an empty when you reach certain distance (using current LOD system, i mean)

**Comment by panzergame** [comment]
@lordloki: not really, you may set an empty mesh, but this mesh will process all pre draw call.
@lostscience: How do you see that option ? A box to check in the lod brick (visible or not for this distance to the next distance) ?

**Comment by lostscience** [comment]
Yes a box to check.Then you can use the lod setting for distance for the visibility.

**Comment by panzergame** [comment]
The problem here is that only non-culled object proceed LOD, but invisible object are considerate as culled too.

**Comment by panzergame** [comment]
No more activity ?
