### ISSUE TITLE
feature request: Edit Video Texture module to accept PIL image

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#41]
currently I can't pass a PIL image to a texture slot without processing each pixel, this is quite slow.

could we add a function to accept a PIL image and pass it to a texture?

this will open up in game dynamic painting and in game destruction and in game character modifications like decals etc.

**Comment by panzergame** [comment]
Does PIL support python3.5, and does it wrote in C python API ?

**Comment by BluePrintRandom** [comment]
It looks like they are getting PIL ready for 3.5 (it may work now) but it's not listed in supported yet*
(when you look at the GIT for PILLOW)

**Comment by youle31** [comment]
Hi, I just tested bge with pillow and it seems to work (not easy but it works): https://drive.google.com/file/d/0B3GouQIyoCmrYXRWbmMweW41dEk/view?usp=sharing (Pillow compiled for Windows 64 bits and python 3.5 64 bits -- tested with last upbge sources)
- I loaded an image with Pillow
- converted it into pixels
- bound it in a bgl.Buffer
- I changed the source of the current texture to be the bgl.Buffer

That's not what you wanted to do?

**Comment by BluePrintRandom** [comment]
Yes that is exactly what I wanted, but for some reason it kept spitting out
a size error.

**Comment by youle31** [comment]
Could you send the error log, please? Do you open the file file a 2.77 64 bits version on windows?
What if you replace imbuf = Buffer(GL_BYTE, [im.size[0]*im.size[1]*3], data) with
imbuf = Buffer(GL_BYTE, len(data), data)?

**Comment by youle31** [comment]
Seems to work for everyone, so I close the feature request.

**Comment by BluePrintRandom** [comment]
Can we re open this 

I can pass a PIL image into the buffer, but bgl.buffer is very very slow

it's passing a pointer, and then bge.buffer has to re-parse the data I think

so you don't pass a whole image at 1 shot.
