### ISSUE TITLE
Bug: Issue with properties

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#414]
Probably related to commit that remove STR_String and replace with std::string ?

http://pasteall.org/blend/index.php?id=45822

in layer 1 the objects have a property player in radar and near sensor. But the sensors doesn't send pulse when the object is near an object with "player" property.

**Comment by youle31** [comment]
forgot to check actor on sphere sorry

**Comment by BluePrintRandom** [comment]
I have had stuff like this happen so often (digging through a ton of code over something silly I have done on accident or a invalid assumption
)
