### ISSUE TITLE
Bug: with batching

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#416]
http://pasteall.org/blend/index.php?id=45832

steps: press P

The cubes are duplicated with shift+D

Another minor bug: crash when you try to batch armature children

**Comment by panzergame** [comment]
@youle31 : In your file every object is trying to make a batch group with all other objects which could at this moment be also a batch group. This behaviour is forbidden in d1beb8784a5785417c81d7de76009383584b11ab.

**Comment by youle31** [comment]
ok :) Thanks for bug fix
