### ISSUE TITLE
Pass changes to a mesh to GPU using VBO ->only pass changes

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#42]
right now if you edit one single vertex, it has to pass the entire mesh to the gpu at each change,

Moguri said you could pass a VBO that was just the changes to the gpu instead, allowing the user to manipulate large meshes XYZ and RGB without lag.

useful for
-  in game terrain editing 
-  in game modeling 
-  real time destruction 
-  in game splat map editing

**Comment by panzergame** [comment]
It's interesting, But, how to detect which vertices are modified ? Set a modification flag per vertices ?
If this is the only case we need first to optimize data send to the VBO.

**Comment by BluePrintRandom** [comment]
how about when we move a vert or change the vertex color , add it to the list?

**Comment by panzergame** [comment]
So just a list of index of vertices ? maybe the index + a modifiaction flag like the current one in RAS_MeshObject.
e.g:
>struct VertexModified
>{
>   unsigned int index;
>   char flag;
>}

So it will be : 
>RAS_MeshObject::SetVeterxModified(array, VertexModified(index, RAS_MeshObject::POSITION_MODIFIED)

**Comment by panzergame** [comment]
To reduce the glBufferSubData call i have an idea: 
We store all vertex index in a list, we sort the index and iterate on all indices.
If an index = next_index - 1 we remove the index (if it's not the first one). By doing this we will get a list of continuous modified vertexes, e.g:
0:9, 16:18, 150:201

After this sort stage, we use glMapBufferRange to update these part of the buffer (iirc we can multi thread these call) and finally a glUnmapBuffer.

**Comment by youle31** [comment]
Would this be compatible with GLSL shaders already compiled (gpu_material.c and gpu_shader_material.glsl) that use gl_Vertex?

**Comment by BluePrintRandom** [comment]
Why did you close this?

**Comment by DCubix** [comment]
I have a better approach. Whenever the user calls the method to change a vertex or the vertex data, switch a boolean isChanged to true, then before rendering check if it has been changed. Then switch the isChanged variable back to false and update the vertex data in the VBO.
