### ISSUE TITLE
minor issue: debug string in debug mode

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#424]
Debug: Add part : 1224, start index: 2820096, index count: 2304, start vertex: 603432, vertex count: 493

Can we remove this for debug mode?

**Comment by panzergame** [comment]
in the RAS_BatchingArray you could remove this print just by replacing `#ifdef DEBUG` by `#if 0`. The print is still useful for special debugging.

**Comment by youle31** [comment]
ok I commit

**Comment by youle31** [comment]
Fixed in https://github.com/UPBGE/blender/commit/b98369988c5ddb82d4ee4dec939528f814b54887
