### ISSUE TITLE
Parallax not working?

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#426]
I tried to set up parallax, but it doesn't work. I checked parallax UV for all the textures and parallax for the heightmap, but it didn't give any effect. What might I be doing wrong?

**Comment by youle31** [comment]
In this folder: https://drive.google.com/drive/folders/0B8EITuogwZr6YkIyRFdIVmo5NkE?usp=sharing , the files with filename prefixed with "parallax don't work?

**Comment by adriansnetlis** [comment]
Oh, sorry - my fault. Parallax must be in alpha channel. Would be cool if you added switch for it (to use alpha or color for parallax).

**Comment by youle31** [comment]
It would be too complex in my opinion. I close th issue
