### ISSUE TITLE
Weird Specular Offset With Normalmaps

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#427]
Somehow the normalmaps seem to offset specular lighting(can't tell for sure if diffuse too).

EDIT - took a look at diffuse and it looks offsetted too.

Possible reason - normalmaps are changing normals in range 0...1 instead of -1...1

Here are screenshots:
![normaloff](https://cloud.githubusercontent.com/assets/6423934/23866792/9496097c-0822-11e7-86ad-2e1b5fe0b9e3.png)
![normalon](https://cloud.githubusercontent.com/assets/6423934/23866799/9d3bf9ec-0822-11e7-8d2b-79806dcc8bba.png)
![normaloff2](https://cloud.githubusercontent.com/assets/6423934/23866803/a0d07114-0822-11e7-9025-8ea5e256499d.png)
![normalon2](https://cloud.githubusercontent.com/assets/6423934/23866808/a3a91396-0822-11e7-9f09-9df324aff9c8.png)

**Comment by youle31** [comment]
Do you have an example file? If you scale the UV with S+Y+-1, does this solves the issue?

**Comment by adriansnetlis** [comment]
Once changing normalmap to one with parallax in alpha(or maybe just removing wrong parallax) it become normal. Guess I found the issue.

**Comment by youle31** [comment]
okok, so I close
