### ISSUE TITLE
How to use texture as a stencil for reflection's LOD bias?

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#428]
I want to use a texture to determine LOD bias of reflections(as a roughness map). How to do it in UPBGE?

**Comment by youle31** [comment]
on the reflection texture, choose mipmap filtering in filtering options, then set your lodbias.

**Comment by adriansnetlis** [comment]
Yea, that's not what I want right now. I want to use texture to vary this option.

**Comment by Akira1San** [comment]
Can it be done using material nodes... im just thinking.

**Comment by youle31** [comment]
I don't think it's possible: the code for lodbias looks like this for 1 texture in a shader:

vec4 color = texture2D(tex, texcoords, lodbias);

For reflections (cubemaps, planars), texcoords are automatically computed (you can't set it yourself in Blender).

The lodbias is applied on all the texture (cubemap or planar). A stencil or another texture won't "revert" the blur/lodbias that is already computed for the reflection texture. After, maybe there are workarounds to to what you want or fake what you want.

**Comment by adriansnetlis** [comment]
The
vec4 color = texture2D(tex, texcoords, lodbias);
is done on **pixel basis**. Thus you can have different lodbias on different pixels. Than you extract the stencil value from texture on that pixel(using UV coordinates for mapping stencil or whatever else is selected). And than the obtained value can be multiplied by a specified value(e.g. if it's 1 than it is multiplied by the maximum mipmap level to make it completely rough, while if it's 0.1, it's 10 times smaller).
I guess it's not as hard.

Alternatively you could make a roughness based reflection where you get 2 mipmap levels nearest to the texture input and blend them. Also don't apply distance mipmap fade in this case.

**Comment by youle31** [comment]
So why do You ask?

**Comment by DCubix** [comment]
He's just asking for something that I've been asking for quite a long time now.
@adriansnetlis as a workaround, you can create 2 versions of the same texture, and set one to be rough and the other to be sharp, then add a stencil in between them.

**Comment by adriansnetlis** [comment]
@DCubix Yea, but it's not yet 100% correct as inbetween values have the sharp reflection visible in them.

@youle31 I ask because this isn't implemented and I don't know how to do it. I am hoping that some of you may do it ;)

**Comment by panzergame** [comment]
I agree to set a value for lod bias in the texture node as only this node is doing the texture sample and that the argument are only the UV which is already an input and lod bias which will be an input.

**Comment by DCubix** [comment]
#471

**Comment by adriansnetlis** [comment]
:+1: Must try!
