### ISSUE TITLE
imageRender() not rendering alpha on texture

### ISSUE THREAD

**Issue by nestanqueiro** [UPBGE/blender#431]
Hello, I'm trying to render a texture with `texture.ImageRender(scene, scene.objects["render_camera"], 512, 512, 1, 2)`
and setting the `source.alpha =True`, and the `source.background = (0.0,0.0,0.0,0.0) `, but the texture is rendered with full alpha. 
I made an [example ](http://pasteall.org/blend/index.php?id=45938) where I pass the texture to a glsl shader to tint red some selective objects, but you can see from the example that everyting is getting tinted... 

Am I missing something, or is it a bug? In blender official branch one can only get the alpha to render correctly if blenderplayer is started with the -a option, but in upbge it also doesn't work... 
Thank you

**Comment by panzergame** [comment]
Confirmed, the horizon color in KX_WorldInfo doesn't support alpha. Will be fixed.

**Comment by nestanqueiro** [comment]
ok, I've been setting up a linux build environment, and just compiled version 0.1.5. I'll keep an eye on this and recompile as soon as it gets fixed! Thank you.

**Comment by panzergame** [comment]
@nestanqueiro : Could you try to compile and test the branch `ge_world` ? Else i'm going to provide a linux release on the server.

**Comment by nestanqueiro** [comment]
Sorry... just seen the message... will get source today, and as soon as I compile, I'll post!

**Comment by nestanqueiro** [comment]
@panzergame : Just compiled, tried same file... and now I'm getting results... even in the embedded player, it reads the texture correctly and passes it to the shader (shader was wrong, by the way... alpha setting was inverted)
trying the external player with -a option now gives same results as official blender! I think that if it doesn't mess anything else, you can call this fixed! (I will give it a more thorough test in the next few days, and if I find anything I'll Post)
Thanks

**Comment by panzergame** [comment]
Ok, thank you for the tests.

**Comment by nestanqueiro** [comment]
doing further tests I wonder if its a bug, or just some silly compile error of mine, but trying to play video textures from file just gives me black textures... I can play the video files on video editor, but not on game engine... If I configure the texture to /dev/video I can see my webcam, but not my video files...
I updated ffmpeg to 3.2 and recompiled, but still with the same issue. With your previous version on windows I can play my files, but not with my build, so can anyone else try to recompile this ge_world branch (maybe a windows version) so we can have further opinions before issuing a new bug report?

**Comment by panzergame** [comment]
@nestanqueiro : Did you enabled `WITH_CODEC_FFMPEG`in the cmake options ?

**Comment by youle31** [comment]
hello, here is a windows 32 bits build of ge_world + a video test file: https://drive.google.com/file/d/0B3GouQIyoCmrM0VZaFd3LXlicDA/view?usp=sharing

For me it works

**Comment by nestanqueiro** [comment]
@panzergame : yes, and I can play the files in the video editor... that's why I find it odd... I think that if  `WITH_CODEC_FFMPEG` wasn't enabled I wouldn't even see them on VSE... AFAIK that is the only option needed to enable video, right? I know that there may be issues with some codecs not beeing enabled on system ffmpeg because of copyright issues, but then I wouldn't be able to see the video at all...

**Comment by nestanqueiro** [comment]
@youle31: I downloaded your file, and although it plays video, it's not the ge_world branch.... nor does it contain a video file example... maybe wrong upload?
the other 0.1.5 build I had also played video, but did not have the alpha channel on the horizon and zenith color...

I think some of my problems where due to the fact that the system becomes very slow and the delay for the uniforms wasn't enough, so I got only black... it's much worse with mp4 files... barelly works with 3gp, and I got it to work with some avi's

I have another[ simple demo file](http://pasteall.org/blend/index.php?id=46155) that requires a video file to test (just add the name to the "movie" property of the plane and have the video file next to the blend file...)
Could you please test it and check if you  have video playback with 2 suzannes over it... at at a decent framerate (regardless of missing aspect ratio corrections)

I get framerates of close to 1... or 0.5 fps... depending on codecs.... could it be system ffmpeg related?

Thanks

**Comment by youle31** [comment]
ooops sorry I shared the wrong link: https://drive.google.com/file/d/0B3GouQIyoCmrdk5FeUlyZ004SzQ/view?usp=sharing

**Comment by nestanqueiro** [comment]
thanks! but with your new build I cant't get transparency to work either... works just like the main branch... one should get an overlay of the alpha texture over the video file.. but it gets no alpha... 
It works on my build, just very slow with some codecs (I'm starting to thing it may be ffmpeg related... ). 
Can you please test my file? thanks

**Comment by youle31** [comment]
If I understand you want that where suzanne is rendered the video will be transparent?

**Comment by nestanqueiro** [comment]
yes... so that you can overlay the suzanne with the alpha property over the video... (later I will make other parts of the video transparent as well with a shader, and I want to see the rest of the scene as background...)

**Comment by youle31** [comment]
I'm sure you can playing with blendtypes. I played a bit and I think I did the inverse of what you wanted: https://drive.google.com/file/d/0B3GouQIyoCmrWkZGSGowNXpNMEk/view?usp=sharing

I think you don't need a shader. Just remember that black is vector3(0.0, 0.0, 0.0). When you multiply it with video color, video color becomes black. because videoColor * vec3(0.0)  = vec3(0.0).

I'll continue to play a bit with the file to see and edit if I find what I guess you want to do

**Comment by youle31** [comment]
It's a bit messy, and finally I used a 2D filter... http://pasteall.org/blend/index.php?id=46156
I don't know if this was exactly what you wanted to do but there are many possibilities with that I guess :P

**Comment by nestanqueiro** [comment]
@youle31: I see you're trying something called "superblack" keying, instead of using alpha channel, you use near black, but that will never give you a semi-transparent object in front of video... 
I think the problem is you still don't have alpha render on your build... 
I also finally got it to work here (I think my computer was lagging on some process, because It started running smoother after a reboot...)
I'll post a video of what I'm getting on my build, so you can compare with your results...

**Comment by youle31** [comment]
I built ge_world...

**Comment by nestanqueiro** [comment]
@youle31: it should look different now... [here ](http://dai.ly/x5h782j)is what this was all about... I still have to get rid of the delay between alpha render, but it's almost there

Video is from www.hollywoodcameraworks.com

**Comment by youle31** [comment]
ah ok very cool :)

**Comment by nestanqueiro** [comment]
@youle31: Can I ask you to share your windows build? I can only test this on Linux, because I don't have a windows building environment... With your build I could check if some of the problems I'm facing are due to my systems ffmpeg... I'm failing miserably at building ffmpeg from source on my OpenSuse...

**Comment by youle31** [comment]
the built I shared with videoplay example is ge_world built

**Comment by nestanqueiro** [comment]
I couldn't get it to work there... If you try my last file, do you see the 2 suzannes overlayed on video?

**Comment by youle31** [comment]
No, I don't know what is wrong, but I checked the hash of my build and this corresponds to ge_world 6aadc0e413c6

**Comment by nestanqueiro** [comment]
Using MT_Vector4 is fundamental to have an alpha enabled viewport to composite with video. Mostly since Decklink module was added, people have been using this to compose graphics on top of video, and with MT_Vector4 you can provide an RGBA feed to do semi-transparent overlays on video...

In one of the examples you provided, you used RGB values under 0.01 to switch to video... that option either has the object, or the video... with MT_Vector4... you can chose the alpha channel of an object to do de compositing... part of one, and part of the other...

**Comment by youle31** [comment]
no, there is not such an option. I have WITH_GAMEENGINE_DECKLINK and WITH_CXX11 (but c++ 11 is enabled by default on windows so normally we don't have to check it).

I didn't understood because in the patch alpha seems set to 1.0f anyway... But I don't know decklink...

**Comment by lordloki** [comment]
Check this commit: https://github.com/UPBGE/blender/commit/8529b2f925c2a0f0cfa3ffe9218519b55223107e

I think you need to uncomment #define WIN32_COMPOSITING in intern/ghost/intern/GHOST_ContextWGL.h to make it work in windows (and after compile, of course :-))

**Comment by youle31** [comment]
@lordloki : Ok thanks! So this seems a "linux only" feature as we'd need to change the sources and download a specific DLL to make it work...

**Comment by lordloki** [comment]
@youle31 I think that the dll will be available in the windows system from Vista and up

Maybe we will have to include "Dwmapi.lib" library when we compile (apart from uncomment WIN32_COMPOSITING)

**Comment by youle31** [comment]
Yes, sorry, I did a translation error :P

**Comment by lordloki** [comment]
apply https://gist.github.com/lordloki/b0b4949e8ab70b91c30814e59631a519 over ge_world branch and it will works :-)

**Comment by youle31** [comment]
Thanks @lordloki , great :)

**Comment by panzergame** [comment]
@lordloki : Could you manage a review from BF about your patch ?

**Comment by lordloki** [comment]
ok.

**Comment by lordloki** [comment]
@nestanqueiro could you test with this build? https://mega.nz/#!oskz0BDL!uvtzWduiDicsiv2ulzWI58YYbmvVy1VTOttB43vpZQA

**Comment by nestanqueiro** [comment]
@lordloki: Just tested, and it still doesn´t have alpha... textures from imageRender still come black, full alpha on background, and no viewport transparency, so my example still breaks in windows... even with the -a blenderplayer option... Do you want me to setup a simples example to test?

**Comment by lordloki** [comment]
Yes, if you could supply me a .blend plus 1 image with the correct result would be very useful. Thanks in advance.

**Comment by nestanqueiro** [comment]
@lordloki: I've corrected the first file I uploaded, with [this one](http://pasteall.org/blend/index.php?id=46178), because it's actually quite simple, even if you ignore the shader part... 
If you get the alpha to render on the plane you see on the right, that will mean it is working... notice in the video you can get the outline of the alpha objects on the texture rendered on that plane

[here](http://dai.ly/x5hc8o8) is the demo of what should be happening in windows (sorry, I forgot to remove the audio from that video file)

**Comment by youle31** [comment]
It works only in debug builds, not release builds

**Comment by panzergame** [comment]
The last version of ge_world seems to fix all the issue, @nestanqueiro Could you confirm too ? For the moment i merge into master.

**Comment by youle31** [comment]
I confirm that the last nestanqueiro file works for me in last master in release mode (windows32)

**Comment by nestanqueiro** [comment]
@panzergame: I still don't have a build system setup for windows... I can do further tests if I can maybe use one of  your builds, or youle31's... 
You may want to try the file that I posted earlier
[upbge_ImageRender_alpha_video_II.zip](https://github.com/UPBGE/blender/files/909599/upbge_ImageRender_alpha_video_II.zip) that is supposed to act like [this ](http://dai.ly/x5hc8o8)video... It's almost the same, but forwards the texture to a shader... 
Thank you for all your effort on this!

**Comment by youle31** [comment]
@nestanqueiro : Hi, upbge 0.1.6 has been released. It is on the website upbge.org . Is it working for you? Can we close this issue? Thanks!

**Comment by nestanqueiro** [comment]
Yes, I've been using it for a few days, and the alpha is working... I think this issue is solved... I just didn't post sooner because I did not understand the previous post (External Player - Win32 White Flash Fix #459), and if there where any other implications with it... 

Thank you all!
