### ISSUE TITLE
Bug: Lamp preview shows world after switching from world tab

### ISSUE THREAD

**Issue by Momel15** [UPBGE/blender#433]
If you are in world tab in the properties panel and switch to the lamp tab, the preview panel is showing the world preview instead of the lamp preview (see pictures).
This happens to all types of lamps.

**The bug occurs when:**

- You were in world settings and moved to lamp settings
- You can move to another tab and back, the problem doesn't get solved

**The preview gets back to normal when:**

- The lamp values are changed
- The upbge window gets moved
- The upbge window gets resized (width, height doesn't change anything until the height is around the half of the screen size)
- The properties panel gets resized (same as above, mostly width and so on...)
- You switch to texture tab and then back to lamp settings

Closing the properties panel (e.g. by changing it to 3D view) and reopening it doesn't help.

So I think this is because of missing UI redrawing. I have no clue on how Blender code works but this might be causing it.

![upbge_bug_lamp](https://cloud.githubusercontent.com/assets/17685000/24058275/ce2896e8-0b4a-11e7-8fe0-7e2399437a1d.jpg)
![upbge_bug_world](https://cloud.githubusercontent.com/assets/17685000/24058274/ce27efb8-0b4a-11e7-972c-35694653886b.jpg)

UPBGE 0.1.5
Windows 8.1 64 bit

**Comment by panzergame** [comment]
I can reproduce the bug in native blender, so i reported it in https://developer.blender.org/T51318.

**Comment by Momel15** [comment]
Hi,

sorry, i totally forgot to check this 😓 Thank you :)

Btw: I don't know how to report a bug to BF Blender, is this only allowed for devs?

**Comment by panzergame** [comment]
Everyone registered to blender phabricator could report a bug, else i let the issue open for the BF devs.

**Comment by DCubix** [comment]
Is this fixed?

**Comment by panzergame** [comment]
Fixed in https://developer.blender.org/rB849e77b1f957b25ac9223a3dc510e234f4467fd1.
