### ISSUE TITLE
Possible Bug: Reflections don't get overlaid by diffuse color ramp when environment lighting is enabled

### ISSUE THREAD

**Issue by Momel15** [UPBGE/blender#434]
This might be a bug, but maybe I just made a mistake or so.

On a plane, I have a reflection texture and a diffuse color ramp to fake a fresnel effect without the need of using nodes.

For demonstrative purposes, I colored the non reflective part of the mesh green and set the interpolation to constant (you can see it on the attached pictures)

If environment lighting is disabled, the non-transparent part of the ramp overlays the reflection. But: when it is enabled, the reflection overlays the non-transparent part (it looks like "add" blending mode, which seems to come from environment lighting) so the fake fresnel effect doesn't work anymore.

![upbge_a](https://cloud.githubusercontent.com/assets/17685000/24059058/d520e498-0b4d-11e7-8d29-021eafc17184.jpg)
![upbge_b](https://cloud.githubusercontent.com/assets/17685000/24059060/d5251914-0b4d-11e7-96a6-19c4a5e7b042.jpg)
![upbge_c](https://cloud.githubusercontent.com/assets/17685000/24059059/d52257ce-0b4d-11e7-8107-01f1b67c572c.jpg)

UPBGE 0.1.5
Windows 8.1 64 bit

**Comment by panzergame** [comment]
Hello, could you provide an example test ?

**Comment by Momel15** [comment]
http://pasteall.org/blend/index.php?id=46467

As it seems, every texture causes that behavior, it isn't caused only by reflection textures

**Comment by panzergame** [comment]
I got similar results in vanilla blender and with a UV texture, I don't know if this is a bug, if you're certain report it to blender as the environment lighting was implemented in.
