### ISSUE TITLE
[Request] method to write / read gameObjects to disk by filename 

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#436]
currently if any modifications are to be done to meshes inside the game engine, one cannot save these gameobjects, and must instead create these gameobjects from scratch,

in an open world game, a tree structure is used to load distant objects in and out of the scene based on the players movement,

I had been under the impression that the new BPPLayer would allow this, but since it does not, can we add it somehow ? 

scene.sendObjectsToDisk([objects],"path/filename")

scene.loadObjectsFromDisk("path/filename") 

(all objects in list are moved to disk and unloaded from scene)

when recalling objects, their world position, rotation, vertex data, and properties and physics mesh etc, are all preserved in the file, a method to ensure materials that are loaded are not loaded again will also likely be needed.

**Comment by youle31** [comment]
We discussed it with panzergame and BPR:

1) BPR finally found a python solution to his problem.
When we don't need to save a large amount of data (for example, only objects positions, orientations, scale, a bit of mesh data, like vertices normals, location, color...), we can do this with python as BPR did.

2) If we implemented this in gameengine code, this would be totally different. Why save only some data and discard another data? We'd need to implement a new converter (like the one we have to convert Blender data in Game Engine format but to do the inverse operation). The code of the converter is extremely long and complex. So we could do it but we'd need a full team working on it during 1 year :P . So this is not realistic with our capabilities in my opinion. Conversion handles physics, logic, objects data... We have an entire folder in gameengine dedicated to conversion: https://github.com/UPBGE/blender/tree/master/source/gameengine/Converter

**Comment by lordloki** [comment]
There would be another possibility (to investigate):

At this moment, there is a function to export most collision shape types, rigid body info, constraints and soft body data in a .bullet file.

That is:
`import PhysicsConstraints;`  
`PhysicsConstraints.exportBulletFile("testFile.bullet")`

There is no function to import it into BGE but there is an example in Bullet/Demos/SerializeDemo into Bullet library download.

But but this will take time. So many time.

**Comment by BluePrintRandom** [comment]
It is ok, I managed to stream using unaccellerated  python atm, to and from
a dictionary *

https://youtu.be/NIvpGbYmrUM

**Comment by BluePrintRandom** [comment]
- this will be a long term issue -
Writing .blend (for export potentially) [whom knows how the engine will be uses]

-writing converted game data for streaming - (like lord loki suggested)-

both are useful*
