### ISSUE TITLE
Bug: users preferences empty

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#439]
https://drive.google.com/file/d/0B9SMh1EBaTriM1lkYUZRaFBtUnM/view
Bug reported on irc by tdg.

**Comment by panzergame** [comment]
@youle31 : Did tdg is still around a available to test with the recent master ?

**Comment by youle31** [comment]
no, no news... I guess this bug is related to his environment, maybe addons cache or whatever... He'd need to be in contact with him to try to help him. We can't do anything for now, so I think we can close this

**Comment by panzergame** [comment]
We can't work on this bug report because of the lack of info, reopen when this situation become false.
