### ISSUE TITLE
BGFX rendering library

### ISSUE THREAD

**Issue by lostscience** [UPBGE/blender#44]
Could you impliment BGFX rendering library like akira_san posted?

**Comment by DCubix** [comment]
We don't know that library, and it would take too long to learn. So it's not a priority right now.
I marked this issue/request as invalid.

**Comment by panzergame** [comment]
For the moment all modifications are in the BGE code except minor modification in viewport/RNA/DNA...

But implementing BGFX request a full rewrite of every part which use OGL. We can't...

**Comment by Akira1San** [comment]
This have been discussed, so it can be closed.
