### ISSUE TITLE
Feature request: support for instanced rendering

### ISSUE THREAD

**Issue by aksyom** [UPBGE/blender#442]
Let's say I got the world positions and rotations for 100000 trees. If I put this thru the standard BGE pipeline where each tree VBO is sent, with it's transformation data, to the GPU instance by instance, it is possible to saturate a computer's memory and/or bus. And if not saturation, the call overhead from 100000 glDrawArrays and glUniform* will be very costly in itself regardless.

Instead, in this case an instanced render pass would be the best solution.  Build a separate array of transformation matrices, which encodes the location, transformation and scale of each individual tree.  After binding all the necessary VAOs (and their VBOs) as required by the BGE standard shaders, bind one extra VAO+VBO which contains per-instance transformation matrices (and other instanced data). Call glVertexAttribDivisor() for each of attributes declared in the instanced array. Then call  void glDrawArraysInstanced() with the instance count parameter set to 100000. The actual geometry will be sent to the GPU buffer only once, and the shader programs will be called 100000 times. Each shader can then access the input data from the instanced array (which was set with divisor) as if they'd access normal per-instance data, but this time the data will be streamed separately.

There's also the possibility to not create a new VAO+VBO for instanced data, but instead just bind an array uniform which includes the transformation matrices etc. The shaders can then access the per-instance data using gl_InstanceID as index. The problem with this method is that hardware sets limits to the maximum number of uniform arrays and/or their maximum element count.

The shader generators or shaders would also have to be adjusted, but that should be easy.

This rendering technique will save an enormous amount of bandwidth, because the actual geometry data is sent to GPU only once. People use this in their projects to render things like trees, foliage and other similar things where a single mesh is rendered in different locations many times.

I even got a suggestion on how to enable this via main UI: just have an "Instanced Render" checkbox for every mesh object. Then if the user has linked instances of that particular mesh, they would be rendered together in one draw call.

Of course, since BGE does not support hardware skinning or array uniforms yet, this would not support animation at first. But that would be okay, since instanced rendering is mostly used for foliage and most of it is static anyway.

I made this request because I could not find any clues in the documentation in regards to this feature, and I am not experienced enough with the codebase to implement this feature myself.

Would it be possible or feasible to implement this?

More information:
https://www.khronos.org/opengl/wiki/Vertex_Rendering#Instancing
https://www.khronos.org/opengl/wiki/Vertex_Specification#Instanced_arrays

PS. Was it okay to post feature requests here? If there was another channel for these, I humbly apologize.

**Comment by DCubix** [comment]
That feature is already implemented! You enable it in the Material. And to use it correctly you must duplicate objects with Alt+D.
So all the objects with that material will be drawn using instancing.

**Comment by aksyom** [comment]
OMG! :D You had even this feature! COOL! Thanks guys, you rock! :P

I could not find this in the documentation, my bad. I guess I'll make a blog post and tutorial about this feature sometime later so that people can hit it with Google :P

**Comment by panzergame** [comment]
@aksyom : You're welcome to do documentation from the user point of view.

**Comment by BluePrintRandom** [comment]
dupligroup instances also work right?
