### ISSUE TITLE
Bug: Normal culling test wrong for Big objects

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#443]
test file: http://pasteall.org/blend/index.php?id=46072
.diff to apply to run the test: http://pasteall.org/321405/diff

green = normally Rendered by debug cam (the one with frustum drawn)
red: not rendered

**Comment by youle31** [comment]
http://www.bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=9&t=11597

**Comment by youle31** [comment]
in this commit: https://github.com/UPBGE/blender/pull/412/commits/b25667ac3ed16160be614769812727f34ffc6918
void KX_KetsjiEngine::DrawDebugLightFrustum

each frame I updated mins and maxs. Is it the same for AABBs?

**Comment by DCubix** [comment]
Since culling refactor is almost done, can I close this?

**Comment by youle31** [comment]
I don't know. @panzergame made a patch when occlusion culling is disabled. But occlusion culling is enabled by default and it uses bullet's culling algorithms (with false positives). I don't know if we'll change that or not.

**Comment by youle31** [comment]
I think we can close this finally, let's just forget false positives
