### ISSUE TITLE
Bug: component property text/names grayed out

### ISSUE THREAD

**Issue by Momel15** [UPBGE/blender#444]
I'm not sure if this is a bug, but as you can see in the attached image, the text/names of the component properties are grayed out so they are very hard to see.

Windows 8.1 64bit
UPBGE 0.1.5

Thank you :)

![upbge_bug_components](https://cloud.githubusercontent.com/assets/17685000/24330451/c9ecacc4-121e-11e7-97f9-22b7582d078a.jpg)

**Comment by panzergame** [comment]
I could not reproduce this issue with the recent master, could you confirm that you do ?

**Comment by Momel15** [comment]
Unfortunately I don't know how to compile it. I tried this once with BF Blender, but it didn't work and I had a bunch of error messages :(

Is there a buildbot or something like that? Is there anything else I can do (also in terms of gathering more informations about the bug)?
