### ISSUE TITLE
[Bug] bge.render.setMousePosition(x,y) not working

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#447]
bge.render.setMousePosition(x,y) is not working for me

**Comment by BluePrintRandom** [comment]
bge.render.setMousePosition(int(x),int(y))

spits an error - "Tuple object is not callable"


while


bge.render.setMousePosition = [ int(x), int(y)]  

throws no error it just does not move the mouse

**Comment by panzergame** [comment]
Make sure `x` and `y` are not a tuple. The second line just call nothing.

**Comment by BluePrintRandom** [comment]
I mutated it into a tuple on accident 

apparently 
bge.render.setMousePosition = [ int(x), int(y)]

breaks 
bge.render.setMousePosition() 

forver after it's ran
