### ISSUE TITLE
Blender VR git is open *

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#449]
https://github.com/BlenderVR/source

**Comment by adriansnetlis** [comment]
I'm just wondering - could we get a VR editor for Blender &&/|| UPBGE any soon? It'd be a cool thing, to be honest:D

**Comment by Maujoe** [comment]
Hm I'm not a developer but personaly I would say there are other priorities before they spend their time for features like VR in the (UP)-bge. Just my opinion ;)

**Comment by BluePrintRandom** [comment]
Its already in a branch of blender*

There is a patch for OpenHMD for editing, and for use in engine *

I believe Theonlybouncer is working on it*

**Comment by BluePrintRandom** [comment]
https://developer.blender.org/D2133#60417

**Comment by BluePrintRandom** [comment]
https://github.com/BlenderVR/source/issues/50#issuecomment-291084250

the patch creator says it should work with upbge**

**Comment by lordloki** [comment]
I will check it although I don't have any VR device

**Comment by BluePrintRandom** [comment]
Google cardboard using usb 3.0 and riftcat can pretend to be a occulus if
you have a newer phone

On Apr 4, 2017 4:36 AM, "lordloki" <notifications@github.com> wrote:

I will check it although I don't have any VR device

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/UPBGE/blender/issues/449#issuecomment-291473758>, or mute
the thread

**Comment by adriansnetlis** [comment]
@BluePrintRandom No need for new phone, just need for one with gyroscope and decent GPU.

**Comment by BluePrintRandom** [comment]
Google pixel has a much much faster screen refresh etc,

 all daydream ready phones are setup to run much higher frame rates I
think.

**Comment by DCubix** [comment]
Since we can't afford expensive VR setups, I'll close this for now!
