### ISSUE TITLE
Cannot render 2 materials with reflection/refraction textures with nodes

### ISSUE THREAD

**Issue by DCubix** [UPBGE/blender#450]
It was working on 0.1.4, I will share the .blend and you can see the node setup in there.
Here's a screenshot:
![screenshot_1](https://cloud.githubusercontent.com/assets/5081992/24527863/12e76d46-1572-11e7-976f-553b37fe1301.png)

.blend: http://pasteall.org/blend/index.php?id=46123

**Comment by youle31** [comment]
Only one texture is rendered. When I put a breakpoint at the end of loop in BlenderDataConversion lines 1841 ->1872, it is hitted only one time... We can check the loop maybe, and check number of materials.

**Comment by youle31** [comment]
So I know what is wrong. To be converted, material must be assigned to 1 face at least.

**Comment by youle31** [comment]
prototype piece of code: http://pasteall.org/331080/diff

**Comment by panzergame** [comment]
The branch `ge_node_material`is converting every materials contained in a mesh, for me it's fixing the issue here, but i have to check that it didn't introduced some.

**Comment by panzergame** [comment]
Fixed in master: 85100f4a32d859c753f5fd4fb86674f404d2dc51.
