### ISSUE TITLE
Website Bug: Python API search doesn't work

### ISSUE THREAD

**Issue by Momel15** [UPBGE/blender#451]
[The UPBGE Python API](https://pythonapi.upbge.org/search.html) search page doesn't work, there is only a text "Searching..." but nothing happens. Next to the "search button" there is a label `Preparing search...`. Even after 15 min I get no results. On [blender.org](https://docs.blender.org/api/blender_python_api_master/search.html), this works properly and after a few seconds all the results are shown.

Windows 8.1 64bit
Firefox 52.0.2 32bit

Google Chrome doesn't work too, so I think it's not related to the browser used.

**Comment by Maujoe** [comment]
Yep the same here on firefox.

**Comment by youle31** [comment]
Hello, this is because of recent changes in BF Blender. I opened a bug report: https://developer.blender.org/T51114

**Comment by panzergame** [comment]
fixed for me, @Maujoe : could you confirm ?

**Comment by Momel15** [comment]
Fixed for me too :) Thank you 👍
