### ISSUE TITLE
KX_WorldInfo: API for Environment Lighting?

### ISSUE THREAD

**Issue by Maujoe** [UPBGE/blender#452]
Hello UPBGE-Team,

I noticed that the Environment Lighting settings in the world tab have no Python api for the bge so we can't access the values ingame. I would be very happy if you could add this to KX_WorldInfo in the future.
(Especially because I try to support a game project with my custom shader(s)).

So basically there would be 3 settings like:
-environmentLightingEnabled
-environmentEnergy
-environmentColor

..or something like that.

It would be very nice if this would be possible in terms of your time and priorities.
Maujoe

**Comment by panzergame** [comment]
Hello Maujoe, you want acces to these values for read and/or write ?

**Comment by Maujoe** [comment]
@panzergame In my case I only need to read the values and pass it to my shader. But In terms of flexibility it's maybe better to add access in both ways at least for the energy in my opinion.

**Comment by youle31** [comment]
Someone on IRC (dr2d4) asked what he could do to help in upbge. I told him this stuff seemed not too complex and indicated him a similar patch to help him if he wants to test: https://github.com/UPBGE/blender/commit/887962d5b6d6cb5440a9c91721239bcf9095412e

**Comment by DCubix** [comment]
Is this Partially fixed or 100% fixed? Can I close this?

**Comment by Maujoe** [comment]
@youle31 Thanks :)
@DCubix I think it's not 100% fixed yet.

It would nice if there would be also an api to read (read only) the environment color/ if the environment lighting is enabled. (How I mentioned above, but no stress :)).

**Comment by youle31** [comment]
Done in https://github.com/UPBGE/blender/commit/ff22b63ebe6721dc7d7d3dbc816cacd77fb80416
