### ISSUE TITLE
Bug: maybe related to scene converter refactor

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#454]
BGMC 23: Eternity
worked in 0.1.5
in master click on Play in MainMenu scene doesn't work. Open Main menu scene and see logic bricks setup (mouseover+click on play -> remove main menu scene+start another scene

check city of time (bgmc 23) too when you display a text near a monument

**Comment by lordloki** [comment]
I cannot open it yet (i cannot at this moment) but the logic remove the menu scene first and after starts other scene or it only start other scene?. In the first case, you wouldnt open other scene after remove main menu scene as you have removed the sca bricks belonging to that scene. You should start other scene directly without remove main scene first. Or im wrong?

**Comment by youle31** [comment]
@lordloki : Many of bgmc 23 games doesn't work anymore... I didn't checked all the logic bricks setups. But it worked in 0.1.5, and it doesn't work anymore.

**Comment by youle31** [comment]
sounds fixed in https://github.com/UPBGE/blender/commit/864139f758f16decb8689b8bbae8774240049c89
