### ISSUE TITLE
Big Alpha regression since 0.0.2

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#456]
See the images titles for upbge versions. The blend have a grass with alpha.
blend: http://pasteall.org/blend/index.php?id=46208
image1: http://pasteall.org/pic/index.php?id=114446
image2: http://pasteall.org/pic/index.php?id=114447

**Comment by panzergame** [comment]
Sapristi ! Shadow aren't rendered into the vanilla BGE. If you disable the shadow in UPBGE the performance back to normal.

@Akira1San : Also what gives a test with the current master ?

**Comment by Akira1San** [comment]
Oh i didnt know.
Image: http://pasteall.org/pic/show.php?id=114476
In here, bf bge 278c still gives some more fps.

**Comment by Akira1San** [comment]
Found it. new image: http://pasteall.org/pic/show.php?id=114478
The regression starts from upbge 011

**Comment by DCubix** [comment]
Is this still valid?

**Comment by panzergame** [comment]
@Akira1San : Could you check that the shadow render is made in 0.1.0 and 0.1.1, for me it isn't, but it is proceeded in higher version like 0.1.6.

**Comment by panzergame** [comment]
If i take care to select VBO in BFBGE (VA + DL can be faster in some GPU even if it is totally deprecated), disable shadows, use constant material in UPBGE excepted for category "Material" and "Lamp", and of course use GLSL in BFBGE :

BFBGE :
![bfbge_grass](https://cloud.githubusercontent.com/assets/8046004/25675070/6b798b0c-303d-11e7-8003-825f152f1f2a.png)


UPBGE :
![upbge_grass](https://cloud.githubusercontent.com/assets/8046004/25675077/75187d62-303d-11e7-8992-2a9216d6e4cf.png)

**Comment by Akira1San** [comment]
Ive made a new test, image: http://pasteall.org/pic/index.php?id=115225 (see the titles for version number)
This time master(build vs2015) shows a better fps. The shadows are off. But bfbge still shows more fps. Ive made a comparison with old upbge versions and 009 give more fps the bf bge. So i dont know if thats normal or something from my AMD video drivers.

**Comment by BluePrintRandom** [comment]
I think modern shader code is slightly slower from what I understand, than
a fixed function pipe,

but gives you access to stuff that make if faster.
(like forward+ lamp culling and tessellation)


I could be wrong, but I think this may be expected*

**Comment by Akira1San** [comment]
@BPR what fps do you get?

**Comment by BluePrintRandom** [comment]
I will check out when I get my pc back
(soonish)

**Comment by panzergame** [comment]
@Akira1San : In your test did you apply the options i talked ?
UPBGE:
   Enabe constant uniforms expected for light and material in material panel.

BFBGE:
   Select VBO storage in scene panel.
   Select GLSL.

Both:
   Disable shadow in light panel.

**Comment by Akira1San** [comment]
Yes i did, made a video: https://www.youtube.com/watch?v=7Sqog0Sb1C8&feature=youtu.be
I dont understand why do i have more fps in bf bge in this scene.

**Comment by panzergame** [comment]
You set constant material options before the video ?

**Comment by Akira1San** [comment]
yes

**Comment by Akira1San** [comment]
Upbge version 0.1.0 gives more fps than bf bge, and after 011 it stats to drop for me.

**Comment by youle31** [comment]
first bad commit between 0.1.0 and 0.1.1: https://github.com/UPBGE/blender/commit/887962d5b6d6cb5440a9c91721239bcf9095412e

**Comment by youle31** [comment]
Even with constant I have a big fps decrease after the commit I mentionned in the previous commit :S (465->430) I don't understand...

**Comment by youle31** [comment]
Fixed in https://github.com/UPBGE/blender/commit/add0ef6b95b7113eea7a1228be15288d5758fec8
