### ISSUE TITLE
strange issue with parenting, and bounding boxes

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#458]
if I remove parent / set parent on text in a single frame and then call on the hierarchy
(object.parent) it says object does not have a parent.

however I use this all the time and it works fine normally

Next, if I use 'show bounding boxes' it fixes it.
I think maybe it's some sort of strange culling thing?

https://www.youtube.com/watch?v=E24z5y9O1Ok

**Comment by youle31** [comment]
hello, we'd need a simple test file.

**Comment by BluePrintRandom** [comment]
steps to make file crash blender
1.load file
2. turn view bounds off 
3.test pie menu does not work
4. turn bound on (pie menu works)
5. turn bound off (pie still works) 
6. revert file 
7. turn off view bounds
8. pie menu crashes blender

**Comment by BluePrintRandom** [comment]
on further inspection it was starting the game the second time without restarting that made the code work

I remade the system from scratch, and avoided parenting the text to the hitbox intially, and spawned them separately and parented on the next frame, and it fixed my issue.
