### ISSUE TITLE
External Player - Win32 White Flash Fix

### ISSUE THREAD

**Issue by rNdm74** [UPBGE/blender#459]
On Windows when the external player was run with an .blend file the window canvas would flash white then load the file.

Cause: GHOST_SystemWin32.cpp on line 454. The WNDCLASSW hbrBackground was set to (0x0000000) which produced the white flash.

Fix: Modifiy line 454 to (HBRUSH) GetStockBrush(BLACK_BRUSH) and the problem is now solved.

.diff to solve the bug: http://pasteall.org/348071/diff

**Comment by youle31** [comment]
The commit which introduces line 454 is https://developer.blender.org/rB8529b2f9 (Benoît Bolsee commit about alpha background and -a option)... There is some doc here: https://msdn.microsoft.com/fr-fr/library/windows/desktop/ms633576(v=vs.85).aspx . @panzergame and @lordloki and @ben2610 : What do you think?

@ben2610 : We recently enabled by default alpha background in upbge: https://github.com/UPBGE/blender/commit/ebeb9567406d94c7ededd341df27449cee3f2ddc and https://github.com/UPBGE/blender/issues/431 on windows too :)

**Comment by panzergame** [comment]
Fixed in ebc91ed9a43c88f991a29d53d9f084b4dff8006d.
