### ISSUE TITLE
Compile help

### ISSUE THREAD

**Issue by alabd14313** [UPBGE/blender#46]
Can you help me to compile this fork.
I clone repos and compile it, but I don't see it's features like parallax and cubemap and ...!

**Comment by panzergame** [comment]
@alabd14313 : How can i help you if you don't give any infos ? i even don't know your OS....

**Comment by alabd14313** [comment]
OK!
Arch linux.
I didn't test it on ubuntu 14.04.
I compiled it successfully. Please help me in git submodules or cmake special setting that needed or ...?
I decided to build it in  arch linux and ubuntu to help linux users for test, but I need your help.
Your binary release in upbge.fr have library problems.
Thnx!

**Comment by panzergame** [comment]
@alabd14313 : UPBGE has not differences with blender about compilation. So you can reuse the blender documentation : http://wiki.blender.org/index.php/Dev:Doc/Building_Blender
