### ISSUE TITLE
Webcam texture not working

### ISSUE THREAD

**Issue by Erstus** [UPBGE/blender#462]
Hello. Webcam texture /dev/video0 appears just plain black, no errors.
Using: Linux Mint 18, UPBGE 0.1.6.

Here's a test file: pasteall.org/blend/index.php?id=46263

I managed to get it working in BFBGE, but there's almost 2 second delay and it only works if the v4l1compat.so or v4l2convert.so is preloaded before starting blender like this:
`export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libv4l/v4l2convert.so; blender`

In UPBGE however, it does not work even with method above.
Also, maybe it would be possible to make manual pre-loading unnecessary for UPBGE somehow.(pre-load by-default?)

**Comment by youle31** [comment]
Hi, No webcam to test for me...

**Comment by Erstus** [comment]
Maybe you can virtualize it with this line:
`sudo modprobe v4l2loopback exclusive_caps=0; gst-launch videotestsrc ! v4l2sink device=/dev/video0`

After that I can get a test video with colors and static noise appear in BFBGE, but not UPBGE the same as with real webcam, so it might not matter.

**Comment by panzergame** [comment]
@Erstus: Hello, you downloaded or self-compiled a version of UPBGE ?

**Comment by Erstus** [comment]
I'm having problems with compiling so right now i have only tried this with downloaded version.

**Comment by nestanqueiro** [comment]
@Alexander: Your file is working fine on my machine... using Opensuse 42.1,
my own build, not the downloaded one... I can try on the "official" but I
think It's going to be the same...

**Comment by panzergame** [comment]
@Erstus, the built version were not with the libv4l support, i'm fixing it currently.

**Comment by Erstus** [comment]
@nestanqueiro, thanks for testing. It's understandable, that this might work better in locally built version. I'm trying to get it compile on my machine tomorrow.

@panzergame, nice find.

**Comment by panzergame** [comment]
The last build should be fixed.

**Comment by DCubix** [comment]
I guess this can be closed....?
