### ISSUE TITLE
Bug: filters + aaa samples 2x or hdr 

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#464]
Setting the AAA samples to 2x or hdr will make the screen show black noise. Removing some of the filter will fix the noise.
Video: https://www.youtube.com/watch?v=r18YVmTo7f4&t=16s
blend; http://pasteall.org/blend/index.php?id=46269

**Comment by panzergame** [comment]
I can't reproduce the issue in current master, can you ?

**Comment by Akira1San** [comment]
Its fixed. :)

**Comment by Akira1San** [comment]
Ops, nope. Set AA samples to 2x and you see noise.

**Comment by youle31** [comment]
Hello, I can't reproduce the bug on my machine (GTX 970 last drivers from nvidia, Windows 10 64). I tried all AA samples settings.

**Comment by Akira1San** [comment]
Ive packed the textures, maybe it was was cos of missing textures. Link: https://drive.google.com/file/d/0B6yNvVGWiWysblhyN3pETDNhUWs/view
Just select the camera, set Faster SSAO to ON and AA samples to 2x, then youll see noise.

Edit: tested the first uploaded blend and i see black noise, so its not from the textures. I guess, then it must be from my AMD R7 200 series. (Nooo!)

**Comment by youle31** [comment]
@DCubix has an ATI card, maybe he can reproduce the bug ?

**Comment by panzergame** [comment]
@Akira1San : The GLSL line:
```
float n = noise1(vec2((ang-timer/9.0)*16.0,dist*32.0))
```

Fails to compile for me, in this line you mean a summary of two noise value (vec2 x and y) ? Please.

**Comment by panzergame** [comment]
Confirmed, i have a little dark band only with multisamples:
![hdr_2x_filter](https://cloud.githubusercontent.com/assets/8046004/25772941/3d498d56-3275-11e7-8843-efbedfae158e.png)

**Comment by Akira1San** [comment]
Yep, it was from the filter. When i removed it and set hdr and aa sample, i dont see any black noise. The filter is from the forum examples..

**Comment by panzergame** [comment]
@Akira1San : Could you test with latest master please ?

**Comment by Akira1San** [comment]
Its fixed. :)
