### ISSUE TITLE
Pybullet to support bge

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#465]
http://www.bulletphysics.org/mediawiki-1.5.8/index.php/Using_pybullet

It says it will support bge :D

**Comment by youle31** [comment]
I tried some times ago to make pybullet work but this failed on p.connect(p.GUI). This wiki doesn't seem up to date with last bullet 3 sources. Anyway, this is not an upbge bug. TwisterGE told me he already managed to make jbullet (with java) work, so maybe he can help if you want to test in the bullet GUI.
I close this for now.
