### ISSUE TITLE
Bug: Crash at exit

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#466]
test file: http://pasteall.org/blend/index.php?id=46307 (BPR BGMC entry)
debug infos: http://pasteall.org/pic/show.php?id=114825
steps to reproduce the bug: Go out the cage and let the player die. a new player is spawned elsewhere. Press ESC -> crash

**Comment by BluePrintRandom** [comment]
code is licenced - https://creativecommons.org/licenses/by-sa/3.0/us/
Code by Jacob Merrill

**Comment by BluePrintRandom** [comment]
making the player armature skin unique fixed the issue

it looks like a animation / instancing bug*

**Comment by panzergame** [comment]
@BluePrintRandom : Could you confirm that 90933f2 is fixing the issue ? And if yes close the issue please.

**Comment by youle31** [comment]
For me it fixes the crash but when the player is spawned elsewhere, the bots are killing each other :P But it can come from a script mistake ( @BluePrintRandom ?)

**Comment by youle31** [comment]
No answer from @BluePrintRandom . I close
