### ISSUE TITLE
Matcap segfault

### ISSUE THREAD

**Issue by alabd14313** [UPBGE/blender#47]
Hi!
When I click on matcap checkbox (in shading), blender crased.
Arch Linux
Here is /tmp/blender-crash.txt :
`
Blender 2.77 (sub 0), Commit date: 1970-01-01 00:00, Hash unknown
bpy.context.space_data.use_render_border = True  # Property
bpy.context.space_data.use_render_border = False  # Property
bpy.context.space_data.use_render_border = True  # Property
bpy.context.space_data.use_render_border = False  # Property
bpy.context.space_data.show_camera_path = True  # Property
bpy.context.space_data.show_camera_path = False  # Property
bpy.context.space_data.show_bundle_names = True  # Property
bpy.context.space_data.show_bundle_names = False  # Property
bpy.context.space_data.show_textured_solid = True  # Property

backtrace
/home/.../bin/UPBGE/blender(BLI_system_backtrace+0x1d) [0x1271dad]
/home/.../bin/UPBGE/blender() [0x95f866]
/usr/lib/libc.so.6(+0x33330) [0x7ff2010d2330]
/home/.../bin/UPBGE/blender(GPU_create_gl_tex+0x506) [0xed3f06]
/home/.../bin/UPBGE/blender(GPU_texture_from_preview+0x75) [0xee3995]
/home/.../bin/UPBGE/blender(GPU_pass_bind+0x7f) [0xee5fff]
/home/.../bin/UPBGE/blender(GPU_material_bind+0x82) [0xee0372]
/home/.../bin/UPBGE/blender(GPU_object_material_bind+0x27f) [0xed622f]
/home/.../bin/UPBGE/blender() [0xf67fe7]
/home/.../bin/UPBGE/blender() [0xa51020]
/home/.../bin/UPBGE/blender(draw_object+0x18d3) [0xa5ed13]
/home/.../bin/UPBGE/blender() [0xa2ade4]
/home/.../bin/UPBGE/blender(view3d_main_region_draw+0x181) [0xa2e971]
/home/.../bin/UPBGE/blender(ED_region_do_draw+0xa37) [0xc15e57]
/home/.../bin/UPBGE/blender(wm_draw_update+0x674) [0x9667c4]
/home/.../bin/UPBGE/blender(WM_main+0x28) [0x961f98]
/home/.../bin/UPBGE/blender(main+0xecb) [0x942ffb]
/usr/lib/libc.so.6(__libc_start_main+0xf0) [0x7ff2010bf710]
/home/.../bin/UPBGE/blender(_start+0x29) [0x95f309]
`

**Comment by panzergame** [comment]
Is this happen in normal (non-UPBGE) blender ?

**Comment by alabd14313** [comment]
In both (blender and BGE).

**Comment by alabd14313** [comment]
Here is arch linux build:
[UPBGE-0.04-2.77.tar.gz](http://www.mediafire.com/download/lht8sx27owdi7di/UPBGE-0.04-2.77.tar.gz)

**Comment by panzergame** [comment]
We can't manage this bug in high priority, because:
1) it's not a UPBGE or BGE bugs, but only viewport
2) It's happening in normal blender, so blender viewport guys are the best to fix it.

**Comment by panzergame** [comment]
@alabd14313 : Please report the bug to https://developer.blender.org/maniphest/
Blender developers are the right persons to fix a non-BGE bug (not only is not caused by us).
