### ISSUE TITLE
How to get texture from it's bind code?

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#475]
Using offScreen makes me able to access texture's bind code(an integer value). However, I have one filter that renders to offScreen as a mipmapped 1x1 pixel image. I need to access the image's pixel data in python. If I could get the ImageTexture/VideoTexture module of the offScreen texture, than I could use imageToArray to obtain required data. But I have no idea how(and if) this is possible. Does anyone know how to do it?

**Comment by DCubix** [comment]
The offScreen system doesn't use VideoTexture at all. It's not possible.

**Comment by adriansnetlis** [comment]
So I can't read individual pixels of the offScreen in Python? :cry:

**Comment by youle31** [comment]
you can do it like that: http://pasteall.org/blend/index.php?id=46404 but I guess it is slow

**Comment by youle31** [comment]
sorry I didn't noticed it was for 2d filters... But you can still apply the same hack converting your 2D filter as a material shader on a plane in front of the screen, use ImageRender offscreen, then extract pixels.

**Comment by panzergame** [comment]
The method proposed by @youle31 is the best one in my opinion. You just have to get the bindcode, bind manually the texture, get the pixel data in a BGL buffer, unbind the texture and then do what you want with the buffer.

In the performance side it's the same as VideoTexture as internally we do very similar operations.

Is this issue resolved ?

**Comment by youle31** [comment]
So the best seems to convert 2D filter as material shader and do like I did in my file.
