### ISSUE TITLE
Parallax UV in nodes

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#476]
Currently you can't access parallax UV in nodes. However, if using material with parallax, but setting some of textures in node editor, than there is a problem that the textures don't match up with what you expect to see...

**Comment by panzergame** [comment]
Could you provide an example file ?

**Comment by adriansnetlis** [comment]
Um... I will try to make one. But here are steps to reproduce the problem:
>create material, add parallax normal map.
>add one more texture and set it to use parallax UV.
all looks good at the moment
>now set the material to use nodes, plug the material in output.
>for an example, add a texture input into material color.
>add geometry node and plug it's UV output into texture's vector input.

Now you see that the color of material doesn't match up with, for example, it's normals. For this, we need to have a parallax UV added to the Geometry node.

**Comment by panzergame** [comment]
Could you test the new parallax node in master ?

**Comment by panzergame** [comment]
The new parallax node should do the job.
