### ISSUE TITLE
Request: Make Vsync off by default

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#477]
Currently Vsync is on by default in every scene you make, but its best to let the user choose to set it on if he wants. For me i always set it to off, cos it drops frames.

**Comment by youle31** [comment]
@Akira1San : hello, this is something you can save using file>save startup file so as everyone has its own preferences, I think this can be done by the user.

**Comment by Akira1San** [comment]
Good point. It can be closed.

**Comment by youle31** [comment]
ok
