### ISSUE TITLE
Bicubic Mipmap Filtering Option

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#479]
Currently UPBGE filters mipmaps using linear(I don't know if it's bilinear or trilinear) filtering. This is good for performance, but, however, it doesn't look good. It looks fine in most cases, but when it's about blurring the texture using mipmaps(e.g. a blur-requiring 2D filter like bloom or DoF, or a reflection texture with high roughness) - in those cases it looks terrible and often also looses accuracy. Bicubic filtering gives much better results at a cost of slight performance decrease. As far as I know, OpenGL offers to set the mipmap filter type to many types, like nearest, bilinear, trilinear aswell as bicubic. It'd be cool if we could switch between nearest, linear and cubic interpolation types for mipmaps. And even better case would be if this could be toggled seperately for render targets(filters) and for textures(IDK if this is possible, though).

**Comment by DCubix** [comment]
The filtering for textures is only changeable by changing the texture parameter for MIN and MAG filters. Just ding it and change it. Hence, it's not possible to change it on-the-fly currently.
I'll investigate!

**Comment by panzergame** [comment]
Excepted this: https://www.khronos.org/registry/OpenGL/extensions/IMG/IMG_texture_filter_cubic.txt (which is ES only) i found nothing about bicubic filtering in hardware.

@adriansnetlis : We are using trilinear filtering.

**Comment by adriansnetlis** [comment]
OK! It seems that the cubic filtering can be done in GLSL. It's applied to linearily filtered texture by adjusting it's coordinate system in subpixel level. This is more complex than I thought.

**Comment by panzergame** [comment]
Eevee will pull its bicubic texture filtering.
