### ISSUE TITLE
New lod method

### ISSUE THREAD

**Issue by lostscience** [UPBGE/blender#480]
Would you think about implimenting Volumetric Billboards?

**Comment by panzergame** [comment]
Isn't the same as depth transparency/soft particle ? : https://doc.upbge.org/releases.php?id=0.1.0

**Comment by DCubix** [comment]
@panzergame it's this https://www.youtube.com/watch?v=l05HgqQbUs4
It's quite complex, we need to think about this when we have a new renderer.

**Comment by lostscience** [comment]
Yes you are right.It is that video.When is the new renderer going to be put in?I mean what version of the upbge is it going to be in?

**Comment by DCubix** [comment]
That's not certain yet

**Comment by lostscience** [comment]
On post 3 in the video it says lod1,lod2 and lod3. If you looked at the video.
