### ISSUE TITLE
Bug: Scaled texts takes a lot of memory

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#482]
test file: http://pasteall.org/blend/index.php?id=46473
steps: press P (if it doesn't crash, look at memory usage. If you want to make it crash, scale the text (in the viewport))

**Comment by panzergame** [comment]
Indeed, BLF is using a cache of all the glyphs generated for each size...

**Comment by youle31** [comment]
wow, BLF BLF.... Thanks for your investigations!

So I close?

**Comment by panzergame** [comment]
I tried to do something clearing the cache when there's too many glyph cache but it's not the best idea as the user could really use a lot of different cache and clearing it would recreate the glyph at every render...

An other solution is to expose to the user a clearing cache function, e.g: ```KX_FontObject.clearCache()```

I don't know for the moment.

**Comment by youle31** [comment]
ok I let it opened while the question has no answer.

**Comment by panzergame** [comment]
I prefer a BLF developer solutions here as the issue is also shared with blender.
