### ISSUE TITLE
Bug: Crash with 2D filter offscreens

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#483]
test file: http://pasteall.org/blend/index.php?id=46483

(the pulse mode is enabled for python script)
steps: press P

**Comment by panzergame** [comment]
Confirmed. Only the python call to glGetTexImage is making the crash in the next call to glClear internally, i'm not fully sure that it's a OGL error and not a BGL buffer memory error.

@youle: Do you have the same behaviour with glReadPixels in python ?

**Comment by youle31** [comment]
@panzergame : The crash doesn't happen when at the end of the main script we add filter.removeOffscreen() (Sorry I forgot to note that in the bug report). I'll try glReadPixels and edit

**Comment by youle31** [comment]
I thought it was related to offscreens but it seems related to bgl so I close because it's too easy to make blender crash with bgl. Sorry to haven't noticed that before :P
