### ISSUE TITLE
Bug: Behaviour changed with SphereInsideFrustum

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#485]
test file: https://drive.google.com/file/d/0B3GouQIyoCmrTmNSQWx1RUVncGc/view

In the script sun.py, there is a check with cam.sphereInsideFrustum (it shouldn't be there but I got the script from another file). The behaviour with this function has changed. I don't know if this is really a bug.

**Comment by panzergame** [comment]
Sorry i can't download the file, the link seems invalid.

**Comment by youle31** [comment]
I close this too as it's not important bug
