### ISSUE TITLE
Cannot make LibLoad from libloaded object

### ISSUE THREAD

**Issue by vlad1777d** [UPBGE/blender#488]
I don't know, is it allowed, but: after I ask LibLoad from Libloaded object, game crashes.

Error: 
`Blender Game Engine Started
Logic loaded.
pure virtual method called
terminate called without an active exception
Аварийный останов`

Example: https://vk.com/doc16425447_445772208 (tar.xz archive of .blend files)
(in all .blend files all needed .py files are opened)
File to launch: ./world/village_1700/willage_1700.blend

Best regards,
Vladislav

**Comment by youle31** [comment]
@vlad1777d : hi, is it fixed?

**Comment by vlad1777d** [comment]
@youle31 , hello, I didn't build new upbge with that commit yet (I tried to build upbge one time, but I couldn't).
If there's ready build with it, I can check.

**Comment by vlad1777d** [comment]
@youle31 , no, in this upbge: UPBGEv0.1.7b2.78Linux64.tar.xz	2017-05-08 21:41 	67M
from here: https://download.upbge.org/download/release/linux64/

error is absent:
`Blender Game Engine Started`
`Logic loaded.`
`player loaded`
`Blender Game Engine Finished`

**Comment by youle31** [comment]
ok, so if you consider the problem is solved ("error is absent") you can close it.

**Comment by vlad1777d** [comment]
The issue is closed =)
