### ISSUE TITLE
bgmc23 nuke game give errors

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#489]
Tested on latest master( morning build. :) )
Nuke game gives errors, that cos frame drop.
Image: http://pasteall.org/pic/show.php?id=115325

**Comment by panzergame** [comment]
These message means that there's in a lot of mesh materials unused, the performance issue was here before we implemented this message.

**Comment by Akira1San** [comment]
This message is not in the Upbge 016, but it started to show in master build. But yes i understand it, i only wanted to report it. :) It can be closed.

**Comment by panzergame** [comment]
Indeed this debug message was added in 0.1.7.
