### ISSUE TITLE
Nuklear GUI - small UI for in-game.

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#493]
Nuklear - A single-header ANSI C gui library; https://github.com/vurtun/nuklear

I found this small lib, based on imgui, that supports skins. I think it looks nice for Upbge build-in gui, what do you developers think?
Quote: 
This is a minimal state immediate mode graphical user interface toolkit written in ANSI C and licensed under public domain. It was designed as a simple embeddable user interface for application and does not have any dependencies, a default renderbackend or OS window and input handling but instead provides a very modular library approach by using simple input state for input and draw commands describing primitive shapes as output. So instead of providing a layered library that tries to abstract over a number of platform and render backends it only focuses on the actual UI.

Features:
Immediate mode graphical user interface toolkit
Single header library
Written in C89 (ANSI C)
Small codebase (~17kLOC)
Focus on portability, efficiency and simplicity
No dependencies (not even the standard library if not wanted)
Fully skinnable and customizable
Low memory footprint with total memory control if needed or wanted
UTF-8 support
No global or hidden state
Customizable library modules (you can compile and use only what you need)
Optional font baker and vertex buffer output

**Comment by youle31** [comment]
In my opinion, as UI is really to do in blender with planes, or little polys to make buttons, logic bricks attached to buttons, custom textures.... the user can easily make his own UI, unique, easy to design in an overlay scene, fast enough.

We could choose to add a lib for UI, but this has 2 main disadvantages:
- If too much users use the same lib, their UI will not be unique/custom and if we see several games with same UI buttons, windows..., this is not really fun.
- You need to press P to see your UI in action whereas if you design your UI in an overlay scene in camera view, you see directly how it will look like.

I think the user can already choose an external lib for UI if he wants like BGUI or TwisterGE UI. But there is no need in my opinion to pack an UI in the blender sources.

Advanced users can also choose to design their own UI with bgl if they want.

But it's so simple to do an UI in an overlay scene, with your custom buttons and icons that you modelize directly in Blender, that I don't see the necessity to pack another lib in the sources that we'll have to maintain.

**Comment by Akira1San** [comment]
While we can use planes and overlay scenes, its not really ideal. Its more like a hack, but works so far.
disadvantages 1: That really dont make much sense, its an ui and you could add your game skin.
2: That would be normal. We have the same situation with 2d filters. :)
Well i think, bgui and TwisterGE uses bgl, that is slow and they both are abandoned.

While i understand what you mean, maybe the situation could change after 2.8.

**Comment by panzergame** [comment]
@Akira1San The nuklear library seems to have only one format of checkbox/button menu, is it modifiable ? If not this could be limiting the user.

**Comment by Akira1San** [comment]
Sorry, i dont really know.
