### ISSUE TITLE
Bug: Crash with modifiers

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#494]
test file: https://drive.google.com/file/d/0B3GouQIyoCmrLUM1ZmJNbVpNSkU/view?usp=sharing

steps: Press P -> crash

EDIT: Didn't happen in 0.1.7

**Comment by youle31** [comment]
First bad commit: 8e2a271c587466580bc13bfe7eb65424f906b672

**Comment by panzergame** [comment]
Fixed in 114230c4c2bd47a3f4efbf1dcc657299ebb325dd.
