### ISSUE TITLE
Bug: Texture missing

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#495]
BGMC 23 All Games Pack\Blender 2.78\BGMC 23 The demon's key\

The sword is not textured. It worked in 0.1.7. I'll bisect.

**Comment by youle31** [comment]
first bad commit: 034494a422b1a8fb8c1d69fded4f534e065b80aa  (doubled check)

**Comment by Akira1San** [comment]
I see this sword in master, img: http://pasteall.org/pic/index.php?id=115842

**Comment by Akira1San** [comment]
Sorry, wrong build, the texture is missing.

**Comment by Akira1San** [comment]
I removed the modifier and the texture is seen.

**Comment by youle31** [comment]
simpler test file: http://pasteall.org/blend/index.php?id=46732

it seems ms->m_pDerivedMesh->drawFacesTex(ms->m_pDerivedMesh, CheckTexDM, nullptr, nullptr, DM_DRAW_USE_ACTIVE_UV); handled objects with modifiers and texture drawing.

For reference to update the code:

https://developer.blender.org/D2683#258757a0

**Comment by panzergame** [comment]
Fixed in ac2fba3fcf4a0541d81fab95047de757fddfb17c.
