### ISSUE TITLE
Bug: Water demo 0.99 broken

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#497]
I guess the first bad commit is: https://github.com/UPBGE/blender/commit/0aad13556673322ede2f9c5430cabad9c3f35d7e but it can be parent or commits from the day, I didn't checked yet.

Press P, glowing filter missing

**Comment by youle31** [comment]
I confirm this is the commit I mentionned which is the first bad commit.

**Comment by youle31** [comment]
http://pasteall.org/411799/diff fixes the issue

**Comment by panzergame** [comment]
Fixed in b56245d86c80789d9bee669d7c4daa7e3fb8e79e.
