### ISSUE TITLE
Static libs missing from Linux release

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#50]
Downloaded from https://download.upbge.fr/releases/
Could be WITH_STATIC_LIBS is off and/or static versions of libs are missing from the build machine.

Some dynamic libs it couldn't find:
libpython3.5.so.1.0
libGLEW.so.1.13
libopenal.so.1
libfftw3.so.3
libjack.so.0
libSDL2-2.0.so.0
libtiff.so.5
libOpenImageIO.so.1.6
... possibly others, had to stop here

**Comment by DCubix** [comment]
Did you run /blender/build_files/build_environment/install_deps.sh?

**Comment by pqftgs** [comment]
Negative.  My test machine was a fresh install of Debian with nothing extra.
Official BF Blender works fine, but only because they statically include these libs for portability.  Unfortunately it (almost) doubles the executable size, but it's a small price to pay for a good end-user experience across distros.

**Comment by panzergame** [comment]
pqftgs has made a install_deps script for static libs

**Comment by pqftgs** [comment]
Use `modified_install_deps.sh -- static` in combination with the buildbot CMake scripts.  There may be additional requirements depending on the build host, but this is good enough for my purposes.

I put a build up if anyone's interested:
https://pqftgs.net/downloads/upbge-e750061-linux-glibc219-x86_64.tar.bz2

**Comment by panzergame** [comment]
The issue is now solved, static libs are already used for 0.0.5.
