### ISSUE TITLE
Bug: Crash with study room

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#504]
https://drive.google.com/file/d/0B3GouQIyoCmrLUM1ZmJNbVpNSkU/view?usp=sharing

I guess this comes from https://github.com/UPBGE/blender/commit/e5a06efab465ee97c4579ed05c9419f36f6bdfd2 but I'm not sure. iirc this didn't happened in 0.1.8

**Comment by Akira1San** [comment]
Yep, its this commit. Removing the modifiers stop crashing. I think, the user should really know not to use modifiers.

**Comment by panzergame** [comment]
Fixed in 48e96c867d09b97d7a2c850aa4d1e73d71a499b5.
