### ISSUE TITLE
Zombie Object warning on storing appended CList

### ISSUE THREAD

**Issue by sdfgeoff** [UPBGE/blender#507]
I was having severe issues with UPBGE segfaulting, and believe that this error has the same root cause, although it does not crash (but if you throw in a few libloads and dynamicly created constraints like the system I was working on, I'm sure it will...)

Simplest blend:
http://pasteall.org/blend/index.php?id=46905

It's fine while playing the game, but on endObject or at the end of the game, you will get ZombieObject warnings.

**Comment by panzergame** [comment]
It should be fixed in latest master, could you confirm ?

**Comment by sdfgeoff** [comment]
Will test on Monday

**Comment by sdfgeoff** [comment]
Seems fixed to me. Thanks
