### ISSUE TITLE
[performance] play sound is very expensive

### ISSUE THREAD

**Issue by solhrdulik69** [UPBGE/blender#508]
try play any wav 16 44100 (mono or stereo) sample (and any length), logic up by >3%. in completed game is make players angry, when many play sound instances. 

for reproduction this crappy sh*t, load and play sound via sound actuator. is be same, if play sound through aud scripts. 

im on windows 8.1 os.

**Comment by lordloki** [comment]
Could you pass us any blend file to test?. 
Really, sound performance depends in a lot factors:
- Wav files only for SFX effects. In that cases if you want 3d sound you should be use mono files.
- Use Mp3 instead of Ogg files for music (mp3 is less demanding)
- How many sounds are you trying to play at same time?
- Are these sound totally different or instances from same sound?
- Are you using some kind of LOD for sound? (i.e. far than 10 BU then sound is stopped)
- etc, etc

**Comment by solhrdulik69** [comment]
hello dear lordloki.

here tested play sound per one hit (on 1500 mhz cpu). the logic up very huge for play tiny-little samples o0.
in completed game may be 3-10 sound instances, and, fps great drop down in this moments. 

![huianus](https://user-images.githubusercontent.com/23156358/27226515-21bfb760-52a8-11e7-9b8b-09de0c0d4f64.png)

**Comment by lordloki** [comment]
I have no performance issue, 10 simultaneous and different sounds. Always between 1-2%

![Sounds](http://pasteall.org/pic/show.php?id=116434)

**Comment by solhrdulik69** [comment]
2% is many for sounds). Anyways, many years ago when sound lib was switched from sdl to openal, playsound do more correctly on windows. But, play per sound (from start) is expensive, high load cpu for mystic background calcuations on my notebook and modern pc my tester. Totally is shows dramatically.

**Comment by panzergame** [comment]
I have not much time these day but i can advice you how to test the performance: looks at tools like uftrace : https://github.com/UPBGE/blender/wiki/Uftrace-timing-profiler, perf (linux only) or callgrind (valgrind based).

I hope that it's only a bad usage of audaspace but it could not and be a problem only related to the library…

**Comment by lordloki** [comment]
@panzergame I will check those tools to profile. Anyway, for 2.8 nexyon will update audaspace to 1.3 version. This version includes multithreading and it will be quicker than previous versions. I will test it.

Note: 2% is not much for current games. The sound part takes around 5%-7% (see for example openarena openal issues with 14% https://blog.lwjgl.org/openal-performance-improvements/)

**Comment by BluePrintRandom** [comment]
Speaking in terms of ms logic would be ideal,

Separation of game logic cost and sound cost in the profiler would also be
ideal.

Thank you upbge devs!!!!

**Comment by solhrdulik69** [comment]
@BluePrintRandom yeah, and include EAX for nice effects. Someone dev was make it, but he missed. So f game maker have sound effects, bge never (LOL?)
