### ISSUE TITLE
[Request] Change bloom when implementing Eevee shaders

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#512]
Current Eevee bloom uses additive blending. For low dynamic range old-gen scenes it was OK because they weren't physics-based. However, the Eevee goal is physically accurate shading. And adding light(out of nowhere) is not physically accurate. I suggest using mix blending. Please, save us from the ugly looks, please! :pray:

**Comment by panzergame** [comment]
Could you talk with clement about this on IRC ?

**Comment by adriansnetlis** [comment]
On which channel?

By the way, I think that bloom doesn't need to be changed at all, except for the blending mode. It's almost good. Just it's default threshold must be 0, intensity must be extremely low and HDR must be enabled. This is the proper (PBR) way of Bloom. But still, adding it to scene's color is not right, instead must be mixed in.
