### ISSUE TITLE
Font keeps not packing, when moving files

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#516]
in manic mack, I am having a bunch of trouble with packing fonts.

every time I save the file and share it, they are missing,
(the text object has the font type selected but the font is corrupted or something?)

is there a way I can link to a font in a local directory to prevent this?

**Comment by panzergame** [comment]
This is issue is related only to UPBGE ?

**Comment by BluePrintRandom** [comment]
No, however I trust your skills better to sort out where the bug is,  and
help notify the BF with a patch or solution,

Bad packing of images and fonts has been a issue now for a while,

**Comment by BluePrintRandom** [comment]
https://developer.blender.org/T51860

**Comment by youle31** [comment]
yeah, this issue seems not related to upbge
