### ISSUE TITLE
Can't change material's specularIntensity at runtime

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#518]
Hello! I've made up an example file in Blender Artists ([here](https://blenderartists.org/forum/showthread.php?433208-Materials-edited-in-game)), answering a question, and I can't change a material's specularIntensity value at runtime. I don't know if it's a bug, but since I can change the other attributes, I believe it is.

Tested in official 2.78 build and UPBGE 0.1.8 build, works the same on both.
EDIT: In official 2.78, the emit attribute doesn't work too, but in UPBGE it works.

Test file: http://pasteall.org/blend/index.php?id=47002

**Comment by youle31** [comment]
hi, 
For emit this is because of this line:
if (GPU_link_changed(shi->emit) || ma->emit != 0.0f || !(ma->constflag & MA_CONSTANT_MATERIAL)) {

So you can set your emit in realtime if constant material option (in material tab) is not checked and if you set your emit (before runtime) at 0.0001 for example.

I think this is the same issue with specular intensity, maybe this line: if (GPU_link_changed(shi->spec) || ma->spec != 0.0f || !(ma->constflag & MA_CONSTANT_MATERIAL))

**Comment by joelgomes1994** [comment]
Nice, @youle31 ! The emit solution works (setting an value higher than 0.0 before runing), but the specularIntensity don't work with the same solution.

**Comment by youle31** [comment]
In material tab, constant values option, you have to ensure that "texture" is not checked

**Comment by joelgomes1994** [comment]
It is unchecked, but it still don't change the value of specularIntensity.

![image](https://user-images.githubusercontent.com/19820741/27584793-cc601d94-5b0f-11e7-9765-18d3b621b771.png)

**Comment by youle31** [comment]
I don't know for specular intensity but the BI material panel will be removed I guess with eevee integration so this button will disappear

**Comment by panzergame** [comment]
Could you test again in master ?

**Comment by joelgomes1994** [comment]
@panzergame Me? If so, can you provide a test build (Windows 7 64x), please? I can't build.

**Comment by panzergame** [comment]
Hi, i'm not a windows user, but i will ask @youle31 to take some time making a tiny release please ?

**Comment by Akira1San** [comment]
Master build- win64 vs2015: https://drive.google.com/file/d/0B6yNvVGWiWysTS04QzBBYkQ3Tkk/view

**Comment by joelgomes1994** [comment]
Now it's working nice, tested all the others properties again to be sure.
Nice work and thanks, guys!

**Comment by panzergame** [comment]
Thanks @Akira1San for the builds.
