### ISSUE TITLE
[request] Area lights

### ISSUE THREAD

**Issue by Fin11** [UPBGE/blender#519]
https://www.youtube.com/watch?v=3JUYFGkmE1Y
If you add it in UPBGE, it will be very cool :)

**Comment by BluePrintRandom** [comment]
they have tried, but the lamps have some serious bugs as I recall*

**Comment by youle31** [comment]
We'll use Eevee area lights

**Comment by Awesomeplayer** [comment]
are you guys already on it?

**Comment by lordloki** [comment]
Closing this feature request as it will come with the eevee integration.

Thanks for your time
