### ISSUE TITLE
[Request] Expose all already working material nodes in UI

### ISSUE THREAD

**Issue by AeroLynx** [UPBGE/blender#520]
Hello UPBGE Team!

There is a bunch of really cool texture nodes, which are already working in the BGE (2.78 and up). See BA Thread: https://blenderartists.org/forum/showthread.php?413444-Cycles-material-texture-nodes-working-in-Blender-2-78

However, it seems like they are not exposed in the Node Editor for some reason when the Game Engine is set as Render Engine. One has to switch to Cycles, add them and switch back to BGE - this is way too "hackish" in my opinion and only accessible to people who read the BA thread. So - I suggest to expose all working material nodes in the Node Editor UI.

Kind regards,
AeroLynx

**Comment by youle31** [comment]
We'll use new eevee nodes so I guess this won't be implemented

**Comment by AeroLynx** [comment]
I just looked into a daily build - it seems like these are part of the EEVEE nodes as well. 
Great, thank you!

**Comment by panzergame** [comment]
Eevee will expose the maximum nodes useable.
