### ISSUE TITLE
eevee shaders to work in UPBGE as well as bloom and lamps

### ISSUE THREAD

**Issue by Awesomeplayer** [UPBGE/blender#521]
Hey :)
are you guys gonna bring Eevee materials into UPBGE? if so, can you still keep the same material panel as in UPBGE right now even tho the shader looks like Eevee?
also, the bloom in Eevee is nice, would ve great if you guys somehow put that into UPBGE as well.
whats more important is the Area lamp support,
maybe this is too much to ask all at once or maybe you guys are already on it, just lemme know :)

**Comment by lordloki** [comment]
Hi,

you can see how the eevee integration takes form in several upbge branchs. 
Closing this feature request as it will comes with the eevee integration.

Thanks for your time.
