### ISSUE TITLE
Planar Reflection Vector not Aviable in Nodes

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#522]
When you have a planar reflection texture and you want to use it in nodes(e.g. for texture controlled LOD bias), you run into a problem - there is no vector that works for the texture. Whichever vector you plug into the texture, it's always black. It would be good if you could use the "view" vector there and make the texture work properly.

**Comment by youle31** [comment]
I guess we'll use eevee planar reflections so maybe we'll have to remove our feature.

**Comment by adriansnetlis** [comment]
Yea. I agree that you shouldn't worry about the existing graphical features, but instead should focus on implementing Eevee, getting it work well and making it as customizable as possible :)
