### ISSUE TITLE
Binding cube map to a 2D filter don't work.

### ISSUE THREAD

**Issue by HG1-Public** [UPBGE/blender#529]
Cube map texture only works if I bind it with bgl.
Binding with bgl also only works if you don't use reflect for the texture coordinates.

[cubeMapBug.zip](https://github.com/UPBGE/blender/files/1132945/cubeMapBug.zip)

**Comment by adriansnetlis** [comment]
So many issues with texture binding at custom shaders... :laughing:

**Comment by youle31** [comment]
This is not an "issue"... The code is just http://pasteall.org/465393/c
We could reserve a slot to cubemaps

**Comment by HG1-Public** [comment]
> This is not an "issue"...
What did you mean with that is not an issue. Actually it binds a cubemap as a GL_TEXTURE_2D. That is not an issue for you?

I don't know what you mean with reserve a slot to cubemaps.

But basically you need to check if the texture is a cubemap or not.
```
			glActiveTextureARB(GL_TEXTURE0 + i);
			if (m_isCubeMap) {
				glBindTexture(GL_TEXTURE_CUBE_MAP, m_textures[i]);
			}
			else {
				glBindTexture(GL_TEXTURE_2D, m_textures[i]);
			}
```

**Comment by youle31** [comment]
I just mean: this is not supported in the current code.
Yeah I guess you can do it either with a boolean added to setTexture function or what I thought about is to say
glActiveTextureARB(GL_TEXTURE0 + 7);
glBindTexture(GL_TEXTURE_CUBE_MAP, m_textures[7]);
voilà...

**Comment by HG1-Public** [comment]
No I think to reserve a slot to cubemaps is not a good idea.
1. We loosing one texture slot if no cubemap is used.
2. If I want to bind a second cubemap (blurred or cubemap switching) it will not work.
3. The user need to know that he has to use the 7th texture slot for cubemaps.

**Comment by youle31** [comment]
yeah

**Comment by panzergame** [comment]
@HG1-Public : Could you test ge_filter_cubemap ?

**Comment by HG1-Public** [comment]
What do you mean by ge_filter_cubemap?

**Comment by panzergame** [comment]
The branch ge_filter_cubemap (we have the convention to name the branch with prefix ge_).

**Comment by panzergame** [comment]
```image.setCubeMap(3, id, "iChannel0")``` works for me in your file.

**Comment by HG1-Public** [comment]
Works fine for me too.

**Comment by BluePrintRandom** [comment]
can each object have a unique reflection map?

can this map be generated by spherical harmonics and a pre-generated grid
of probes?

can we mix realtime cubemap of only dynamic objects, over static generated
reflection using Z-buffer of realtime probe?


thanks!

**Comment by panzergame** [comment]
Could you test again in master ?

**Comment by HG1-Public** [comment]
Works fine in master.
