### ISSUE TITLE
MathFu math lib: could it replace Moto?

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#53]
C++ math library developed primarily for games focused on simplicity and efficiency
http://google.github.io/mathfu/index.html -webpage
https://github.com/google/mathfu - github

MathFu is a C++ math library developed primarily for games focused on simplicity and efficiency.
It provides a suite of vector, matrix and quaternion classes to perform basic geometry suitable for game developers. This functionality can be used to construct geometry for graphics libraries like OpenGL or perform calculations for animation or physics systems.

The library is written in portable C++ with SIMD compiler intrinsics and has been tested on the following platforms:
Android
Linux (x86_64)
OS X
Windows

Optimization:
MathFu is optimized using SIMD instructions (including NEON for ARM and SSE for x86 architectures). SIMD optimization is enabled by default based upon the target platform and compiler options used to build a project. In addition, MathFu provides compile time options to modify code generation, see Build Configurations for more details.

Could this be a replacement for the Moto library?

**Comment by panzergame** [comment]
@Akira1San : I saw quickly the API this morning, it's interesting but it requests to investigate on the API compatibility.

So i propose you to look at files named MT_VectorX.h MT_MatrixXxX.h and MT_Quaternion.h.
Find for each functions the coresponding one in mathfu or if it's impossible, the coresponding code.

This will help a lot to switch (if it's possible).

**Comment by Akira1San** [comment]
Ill see what i can do.

**Comment by lostscience** [comment]
When you get the build ready.I want to test it.

**Comment by Akira1San** [comment]
Looking again at MoTo_vector2.h i saw, that some functions are missing from Mathfu:
MT_fuzzyZero, MT_fuzzyEqual, MT_distance, MT_distance2, MT_angle, MT_triple
mt_cross in glsl mapping - mathfu::cross

**Comment by lostscience** [comment]
Is that bad news or good news?

**Comment by Akira1San** [comment]
No actually its not missing. Thats just coded from bf devs. So i guess, there will be a little adjustments.
