### ISSUE TITLE
[Bug?] Cubemap LOD bias in nodes create flat-like look.

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#531]
[CubemapProblem.blend.zip](https://github.com/UPBGE/blender/files/1138847/CubemapProblem.blend.zip)
If you open this test file, you'll see a monkey with cubemap. It uses LOD bias so it's blurred. That's exactly how it must be. However, it also gets a flat look on it. You can clearly see distinct polygons, which each gets a color of cubemap evenly distributed among it's surface. This starts to happen once one pixel of cubemap is getting around the size of polygon or bigger from the viewers perspective.

**Comment by panzergame** [comment]
The opengl normal interpolation looks not really perfect, here the normal in the fragment:
![normal](https://user-images.githubusercontent.com/8046004/28995370-e3a839ae-79e7-11e7-8508-0db6027a7ce7.png)

And here the Y derivative of the normal multiplied by 5:
![dfdy](https://user-images.githubusercontent.com/8046004/28995369-e3a3f9ca-79e7-11e7-8ffa-ad598eae664d.png)

As you can see the derivative is not smooth and then the cube map lod calculation which is based on texture position/vector derivative will fail here.
