### ISSUE TITLE
Modifier in non-visible layer causes segfault

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#540]
Started at a31e011
Backtrace http://pasteall.org/486759

To replicate:
1. Add a mirror modifier to the default cube
2. Move the cube to a non-visible layer
3. Start the game engine.  Blender will crash.

Workaround = manually apply modifiers

**Comment by panzergame** [comment]
Could you test again in master ?

**Comment by pqftgs** [comment]
Looks good
