### ISSUE TITLE
Crash when endObject() is used incorrectly on a child

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#541]
This script incorrectly tries to end a child that should have already ended with the parent:
```
import bge

cont = bge.logic.getCurrentController()
owner = cont.owner
child = owner.children[0]

owner.endObject()
child.endObject()
```

-2.78 silently ignores the error
-UPBGE crashes

The crash started somewhere after v0.1.8.
Correct behavior would be to throw an error or warning.

Test file: http://pasteall.org/blend/index.php?id=47286

**Comment by pqftgs** [comment]
Similar crash: Put the parent and child in a group and call group.endObject()

**Comment by solhrdulik69** [comment]
very hot problem. im too use group objects for ragdolls. and crashes is unlike.

**Comment by pqftgs** [comment]
Ran bisect, the crashing starts at 2a43f1b but in previous commits they don't get deleted.

**Comment by panzergame** [comment]
Could you test again in master ?

**Comment by pqftgs** [comment]
Fixed, thank you!
