### ISSUE TITLE
Performances with lights (eevee branch)

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#544]
In this file: http://pasteall.org/blend/index.php?id=47304 we can see that in such case, lights and shadows update seems not needed I think (we can comment rendershadowbuffers to see). After we comment shadow buffers, I'm wondering if there is a way to compare viewport and ge performances for mesh rendering

I don't know if there is a kind of mesh batching of the dragons in the viewport. Yeah changing animations framerate to 60 we can see that viewport rendering is faster. We could try to know why.

**Comment by youle31** [comment]
update: the light influence area is not the same as in eevee viewport (larger in ge)... Maybe this explains a part of performance difference

**Comment by youle31faggot** [comment]
Im wanna kill you in real, and dont cry my pissed baby, youle31

**Comment by panzergame** [comment]
Could you give more details please, I don't really understand the issue here.

**Comment by youle31** [comment]
No it's just that compared to the viewport, I remarked that our implementation was slow and we have not the same visual result sometimes. But as it's low priority, I close it for now
