### ISSUE TITLE
LibLoaded objects are not lit by existing scene

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#546]
Tested in master. Started somewhere after v0.1.8
To replicate: LibLoad a scene that has no lights. Loaded objects will not receive lighting.
Test file (must be extracted): https://www.dropbox.com/sh/5ttns1gcf6uljkb/AABsW94A9vAUAzsIqOryxu1_a/temp/libload.zip?dl=0

**Comment by panzergame** [comment]
Can you check in recent master ?

**Comment by pqftgs** [comment]
Fix confirmed
