### ISSUE TITLE
UPBGE Debug Build End Scene Crash

### ISSUE THREAD

**Issue by HG1-Public** [UPBGE/blender#549]
bge.logic.getCurrentScene().end() will crash with debug build. The release build works.
Actually I don't have a normal BGE Debug build or a UPBGE 64 bit build for testing. So I don't know if it is a general bug.
Windosws 7 64 bit
UPBGE latest version 32 bit

[UPBGE Debug End Scene Crash.zip](https://github.com/UPBGE/blender/files/1189696/UPBGE.Debug.End.Scene.Crash.zip)

![crash](https://user-images.githubusercontent.com/18644197/28812583-ab5af712-7695-11e7-98ee-2e4ce454bd38.jpg)

**Comment by panzergame** [comment]
I noticed that when the game requests an exit at the logic state the render just after is made, and in your case the rendering need to access to the first scene to render the background.
I think that exiting just after the logic step without doing a render is the solution but it introduces one render less than before. It is important to keep the compatibility here ?

**Comment by panzergame** [comment]
branch `ge_exit_scene`

**Comment by HG1-Public** [comment]
No crash any more, but now the ESC exit key don't work.

**Comment by youle31** [comment]
in bool KX_KetsjiEngine::NextFrame(), return doRender && m_doRender && m_scenes->GetCount() > 0; seems to fix the issue

**Comment by HG1-Public** [comment]
> in bool KX_KetsjiEngine::NextFrame(), return doRender && m_doRender && m_scenes->GetCount() > 0; seems to fix the issue

Works for me.

**Comment by panzergame** [comment]
@HG1-Public : It's fixed in `ge_exit_scene`, now i discard the render if the logic step request an exit and also test for exit event after the possible render.

**Comment by HG1-Public** [comment]
@panzergame your version works for me too.

**Comment by HG1-Public** [comment]
I got some random crashes with panzergame's version. But actually I am not 100% sure if it is caused by his patch. I will make some run's with youle31 version.
![error](https://user-images.githubusercontent.com/18644197/29002643-641efef0-7aa7-11e7-9c72-638978753300.jpg)

**Comment by HG1-Public** [comment]
Hm seems not be different bug. Because it also crash randomly with  youle31's version.
