### ISSUE TITLE
Delayed KX_GameObject.endObject causing logic errors

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#554]
Not really an UPBGE issue since it's been like this forever.
By design KX_GameObject is delayed until the next frame. But in cases where you're calling from a controller on a different object, the ended object will sometimes process another logic tic, resulting in unexpected errors.

There's a number workarounds but I feel like this should be an engine-side fix... any thoughts?

Test file below. It doesn't happen consistently so you might have to run a few times. Look for "That was unexpected" in the console.

EDIT
New file with some fixes
http://pasteall.org/blend/index.php?id=47393

**Comment by HG1-Public** [comment]
> (Not sure why the screen turns black... but that's unrelated)
The objects list contains any object in the scene. So your code can also delete the empty, lamp and camera.

Also you named your script test.py.  The module test is already existing in Python so it will conflict with it.

**Comment by pqftgs** [comment]
Fixed and fixed. New test file:
http://pasteall.org/blend/index.php?id=47393

**Comment by panzergame** [comment]
@pqftgs : The object is destroyed only at the end of the logic frame, but it still remains with a valid python proxy until this time, what is the real issue here ? You can still act on it even if it is considered useless.

**Comment by panzergame** [comment]
If I summarize the test case:
```
For each object:
    Process logic (script):
        Check for "ended" prop
        Choose a random object
        Delete this object
        Add it the "ended" property
```

So here as objects are delete only at the end of the of the logic step, so all objects will proceed logic, and as one controller of an object can tag an other object as ended and that same object doesn't have proceeded its logic, then you have your debug message.

But this doesn't mean that objects proceed an extra logic step, they are just unlucky to process logic between debug tag (property "ended").

**Comment by pqftgs** [comment]
That's exactly the problem. It's weird design that catches people off-guard. When calling **endObject** I expect that object to be gone, but instead it processes more logic depending on how "lucky" you are. I'd expect this behavior from something like "endObjectDelayed".

But - if fixing it requires a major re-factor, then I wouldn't bother. Just another quirk to deal with.

**Comment by panzergame** [comment]
Imagine you run a script in a object that end it, how many user wills produce crash or invalid python proxy when reading something after the call to endObject ?

**Comment by pqftgs** [comment]
Quite a few actually. I don't think you quite understand what I'm getting at, my example wasn't very good... It's quirks like these (among several others) that cause hard-to-track bugs later on.

Regardless - I now know to design around this.

**Comment by justinbarrett** [comment]
I agree, it is odd the way it works. I myself had some errors recently due to this. Now instead of ending the objects that caused the problem I move them to a trash can and let them die after their next logic tick...it was a bit tricky since I was not certain of the issue...I figured it out, but a new person to games development would likely just give up. I'm not sure if it should be fixed or better documented?
