### ISSUE TITLE
Blender exits when you press P key. (v0.1.8b)

### ISSUE THREAD

**Issue by SalatielSauer** [UPBGE/blender#556]
Windows 7 32bit
Netbook, 2 ram.

My Default cube its a Yellow cube, for some reason...

And when i press P key the Blender closes.

Here is a gif http://gph.to/2vNQdp3

And when i try to play the blenderplayer:
http://i.imgur.com/VTk1nca.png

When i add another object:
http://i.imgur.com/8tH0iz4.png

Console:
http://i.imgur.com/SNxBzow.png

**Comment by panzergame** [comment]
Hello,

Could you provide your OpenGL information or at least the console output of blenderplayer ?

**Comment by youle31** [comment]
@SalatielSauer : hi, is this version working (rendering normally the default cube) ?

**Comment by SalatielSauer** [comment]
Hi, panzergame, youle31, bellow the OpenGL info:

OpenGL:
===========================================
renderer:	'AMD Radeon HD 6200 series Graphics'
vendor:		'ATI Technologies Inc.'
version:	'4.2.11566 Compatibility Profile Context'

The console:
http://i.imgur.com/dsKoHj4.png
(i dont added addons in the Upbge, but the blender is trying to read my custom addons from a wrong file... lol?)

The 0.1.8RevertInverse default cube is rendering normally
http://i.imgur.com/e4ICTnj.png

Here is the console when i run in blenderplayer in 0.1.8RevertInverse:
http://i.imgur.com/0F4OSRL.png

But, in 0.1.8RevertInverse, when i press P key, the game start, when i press ESC (playing the game) the Blender closes...

**Comment by SalatielSauer** [comment]
Hi again, so... Any idea how to fix this issue?

**Comment by youle31** [comment]
Hi, for the first issue, the problem is related to AMD drivers which doesn't support custom GLSL implementation of inverse function https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/inverse.xhtml . So I simply removed the implementation of inverse from our code. Normally this should have solved the first bug mentionned (but geometry instancing should not work).

About crash at exit, I can't reproduce this issue. If @panzergame can reproduce issue with revert_inverse branch, we can maybe do something. If no developer can reproduce the issue, we can't fix it.

On your side, you can try different version of the drivers (older or newers) for AMD Radeon HD 6200 with normal versions of upbge 0.1.9: https://drive.google.com/drive/folders/0B8EITuogwZr6Mi1EQW5FbERqTHc?usp=sharing
If 1 driver works this is jackpot. Else we can do nothing directly.

If you don't find drivers which work with upbge 0.1.9, the only thing possible would be to install a development environment (visual studio 2013, cmake, git, svn...) on your computer and try to compile upbge in debug mode, run it with visual studio debugger, and find where the crash happens in the code. But this is complex if you have no experience with Blender development and debuggers.

**Comment by panzergame** [comment]
Hello,

@SalatielSauer : Could you test the blenderplayer in recent master and report us the full console log please ?
(@youle31, @Akira1San: Could you make a windows build please ?)

**Comment by youle31** [comment]
I shared the link to windows releases in my previous posts. Else the releases are now available here too: https://download.upbge.org/.

There are command lines to start blender here: https://docs.blender.org/manual/de/dev/advanced/command_line/arguments.html to have some infos.

But as this is the same bug than elmeunick and that we didn't manage to solve his bug, I fear that we can't do anyting. I hope the new AMD drivers work :S

**Comment by Akira1San** [comment]
build-  Win64 vs2015, link; https://drive.google.com/open?id=0B6yNvVGWiWysSmdJY1BTaFJoNXM
I was thinking, since SalatielSauer have OGL 4.2 profile, maybe switching to a OGL Core profile could fix the issue. So no need to use _exts.` After all notebooks with AMD got a OGL 4x version.

**Comment by Nemescraft** [comment]
Hello, I have this issue as well with 0.1.9, however, it quits on one file, it doesn't on another. 

The file that crashes has some logic in it, referring to a Vehicle Wrapper script, set to run Always on a True Pulse.

Here is the file: [https://drive.google.com/file/d/0B7LoxcFlq1GRSDVYWk1oa2JnNFk/view?usp=sharing](url)

Here is my code:
`from bge import logic, constraints
import mathutils

cont = logic.getCurrentController()
scene = logic.getCurrentScene()

own = cont.owner

vehicle = constraints.createVehicle(own.getPhysicsId())

for wheel in scene.objects:
    if "Wheel" in wheel.name:
        wheelPos = wheel.localPosition
        downDir = mathutils.Vector((wheelPos.x, wheelPos.y, wheelPos.z - 5.0))
        axleDir = mathutils.Vector((wheelPos.x + 1.0, wheelPos.y, wheelPos.z))
        #create the wheel
        vehicle.addWheel(wheel, wheelPos, downDir, axleDir, 1.0, 1.0, False)`

**Comment by panzergame** [comment]
@SalatielSauer, @Nemescraft : Could you display the full output of blenderplayer running in a console please ?

**Comment by SalatielSauer** [comment]
Hi @panzergame , Sorry, I already sent everything I could send, tell me step by step how to get the information you need...

**Comment by Nemescraft** [comment]
I solved my problem, thanks!

**Comment by panzergame** [comment]
@Nemescraft : How did you do ?

**Comment by panzergame** [comment]
@SalatielSauer : Open a console and then run blenderplayer with the file name as argument, then copy and send the output messages in console.

**Comment by Nemescraft** [comment]
@panzergame actually I solved this a while ago, the problem was I was running the vehicle setup every frame, instead of just once

**Comment by Akira1San** [comment]
@SalatielSauer, try this build. Made with VS 2015 64b:
https://drive.google.com/file/d/0B6yNvVGWiWysRjJVWjdPZlNIRnM/view

**Comment by youle31** [comment]
hello, @SalatielSauer && @elmeunik: this is a win32build: https://drive.google.com/file/d/0B3GouQIyoCmrWmF4N1JTaFZYclk/view?usp=sharing
@SalatielSauer : Do you still have problem with textured cube/crash at exit in this build?
@elmeunik: Is this working for you?
Thanks for your feedbacks!

**Comment by elmeunick9** [comment]
@youle31 
Unfortunately (for the sake of solving this bug) i've bought a new computer. I still have the old one, but let's say that it's not that accessible to me anymore. I'll try the build on the old computer when I can, but expect at least 3 weeks until then.

**Comment by SalatielSauer** [comment]
Hi @youle31 , i tested the upbgePre0.2.0win32, the Default Cube is not yellow anymore, and the Blender dont closes when i press P, but, the Blender closes when i press ESC (exit)...

@panzergame do you mean, to run the blenderplayer via cmd? sry, i dont know how to do... 

@Akira1San yep, i use Windows 32...
