### ISSUE TITLE
Bug: Problem with uvs

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#557]
last master 9/08 evening.

There is a problem with UVs in desert level. The sand is not mapped correctly. I'll bisect later

**Comment by panzergame** [comment]
Is bb2e8f13b30915020442a3ca340cfc2af2300170 fixing it ? (same time you opened the report :P)

**Comment by youle31** [comment]
Ah? I can't check now but last time i checked this commit (i think this was this commit but maybe it was another) fixed the black character issue but not the uv on the sand... i'll check again this night or tomorrow. Bye!

**Comment by Akira1San** [comment]
tested the latest master build, img: http://pasteall.org/pic/index.php?id=117875

**Comment by youle31** [comment]
Fixed, Thanks @panzergame !
