### ISSUE TITLE
Python console crash.

### ISSUE THREAD

**Issue by alabd14313** [UPBGE/blender#561]
Hello!
Arch Linux
Upbge Hash c1aa3078f2
Nvidia GT 710

I have a crash when trying to use python console. Here is backtrace:
http://pasteall.org/510612/text

**Comment by panzergame** [comment]
@alabd14313 : I can't reproduce the fix if it assumes that it is in default scene as you didn't provide example file.

**Comment by alabd14313** [comment]
The default scene have this crash.

**Comment by youle31** [comment]
I can't reproduce the crash too :/ I don't know if we'll be able to solve this if we can't reproduce it...

**Comment by panzergame** [comment]
@alabd14313 : Still current ?

**Comment by alabd14313** [comment]
Unfortunately yes. I still have this bug.

**Comment by panzergame** [comment]
@alabd14313 : Could you try on an other linux distribution ?

**Comment by alabd14313** [comment]
Excuse me for late response. I try to test it on openSUSE soon.

**Comment by alabd14313** [comment]
It seems this bug solved in v0.2.1.
Thanks!
