### ISSUE TITLE
startGame and linking break relative file paths

### ISSUE THREAD

**Issue by sdfgeoff** [UPBGE/blender#563]
Relative filepaths aren't handling changes in blend file properly. Namely:
 - If you use the start game actuator to a different path
 - If you link a file from a different path
Then the textures and fonts will be lost.

I have attached an game showing a complex but not atypical setup. If you start from "Dreamrider.blend" no textures show (it uses startgame to a different folder). If you start "Game.blend" then linked textures are missing.
[Dreamrider.zip](https://github.com/UPBGE/blender/files/1225939/Dreamrider.zip)
This project works fine in BFBGE

Also note the different appearance in the trail material. I am unsure why as no texture is used.

**Comment by panzergame** [comment]
Should be fixed in master.

**Comment by sdfgeoff** [comment]
The textures work, but the font is still missing.

**Comment by panzergame** [comment]
Should be fully fixed by 3c8bc59aa91022ee7d1e3d05e6c4724c944a3331.

**Comment by sdfgeoff** [comment]
Yup, confirmed as fixed.
