### ISSUE TITLE
Implement Filters for ImageBuff

### ISSUE THREAD

**Issue by DCubix** [UPBGE/blender#564]
Currently almost all other image sources such as VideoFFmpeg and ImageFFmpeg have the `filter` property, and it works.
This is not the case for ImageBuff, the filter property does nothing.

**Comment by youle31** [comment]
this: http://pasteall.org/516633/diff
was working for this file: http://pasteall.org/blend/index.php?id=47521
So maybe we can say in load function that when we use load and the source is imageBuff, then use the second size... It need to be investigated and tested with all types of sources and all filters
