### ISSUE TITLE
crash after about 5 seconds (0.1.9)

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#565]
http://pasteall.org/blend/index.php?id=47520

press P and wait, or hold space in upbge 0.1.9 = crash

**Comment by youle31** [comment]
I don't know if this is really a bug but this is crashing from this commit: https://github.com/UPBGE/blender/commit/2a43f1b114315eddc37d2296c875b40fb1a447e9

**Comment by youle31** [comment]
I confirm this is fixed. Thanks panzergame!

**Comment by BluePrintRandom** [comment]
thanks gentleman 👍
