### ISSUE TITLE
UPBGE - Eevee Volumetric Branch, game crash if Post Process Stack is enabled.

### ISSUE THREAD

**Issue by RodrigoMedeirosrRS** [UPBGE/blender#568]
Hello, I found the following problem: When I activate any of the Post Process Stack options, everything works normally in the viewport, but when I press the "P" button to execute the game code, the blender crashes.
![export](https://user-images.githubusercontent.com/7956669/29496663-ad192cf0-85ad-11e7-8cdf-390ec1856199.png)

**Comment by youle31** [comment]
I didn't even tested it yet (I added these options yesterday or 2 days ago to the render panel of blender game). Sorry, we can't accept issues for now as we are in the early stages of eevee adaptation
