### ISSUE TITLE
Set 3D viewport in game via script is not working properly inside UPBGE for some reason.

### ISSUE THREAD

**Issue by chicortiz** [UPBGE/blender#569]
Hi there UPBGE team.

I'm writing for trying to understand why a certain file is behaving diferently inside the UPBGE in comparison to the default Blender Game Engine.

The .blend is hosted here (spacebar inside UPGE adds the backgorund scene and forces the intended result):

https://drive.google.com/file/d/0Byr4NYScNOlRbFM5QzFYVk11OVE/view?usp=sharing

What this Blender file does is pretty basic: It puts one camera upon, over another one.  This can be very usefull for having two viewports inside game.

1) Image reference 1: https://2.bp.blogspot.com/-Hu_A5AUu7k8/WZn_nICxWQI/AAAAAAAAFAY/uQBl4j_vtykKlSGL-0QNtT5S48HhdlqDwCLcBGAs/s1600/Screenshot%2Bfrom%2B2017-08-20%2B18%253A22%253A11.png

2) Image Reference 2: https://3.bp.blogspot.com/-0AKjBZXyzDY/WZn_nO4b7HI/AAAAAAAAFAQ/SLiCZY66PCEsRqeScTxitQjrV4eAhgpRgCLcBGAs/s1600/Screenshot%2Bfrom%2B2017-08-20%2B18%253A22%253A25.png

3) Image reference 3: https://3.bp.blogspot.com/-E8OSnNX1bzw/WZn_nIkI6dI/AAAAAAAAFAU/b6Qazj1kehEl-yUSphRZouYVj337qQLngCLcBGAs/s1600/Screenshot%2Bfrom%2B2017-08-20%2B18%253A23%253A00.png

If I use the default Blender Game Engine this works straight forward. 

But when I try to use it inside UPBGE I need to put a background scene to force it working properly.

I'm using UPGE 0.1.9

Script being used:

___
CC Updated to Blender 2.5 by Andre Ortiz and HG1
C import bge
import bge

C get controller
cont = bge.logic.getCurrentController()

C get owner
own = cont.owner

C get Window width	
width = bge.render.getWindowWidth()

C get Window height
height = bge.render.getWindowHeight()

C set viewport
own.setViewport(0, 0, int(width * 1/1), int(height))

C enable viewport
own.useViewport = True`
___

C = Comment

Could you explain what is going on here? :?

Thank you! 

P.S.: Terminal is empty.

**Comment by youle31** [comment]
hi, I don't know what changes have been done in upbge which can explain the different behaviors in bge/upbge but normally I think setViewport is more intended to split the screen into several parts than to do overlay/background display. To do overlay/background, it's better to use what you said, a background scene or an overlay scene.

**Comment by panzergame** [comment]
The issue here is that we render the background for each camera with the world settings and the camera matrices (for environment map). So even if I can disable the background render of the second camera you will not have the background for the both...

**Comment by chicortiz** [comment]
No problem guys. 
I can add an empty scene, linked to an always sensor to do the job ;) 

I think the game I'm making can benefit a lot from your geometry instancing feature that you did, so in the end is a good deal ;)

I think I'm asking for something that is too specific for my situation. It's a kind of "no question" in the community context. 

Thank you so much for you patience with this demand anyways. :P
