### ISSUE TITLE
Duration the new object lives (time) is crashing UPBGE

### ISSUE THREAD

**Issue by chicortiz** [UPBGE/blender#570]
Hello again UPBGE team!

I found something wrong today:

Suppose I have a cube and over this cube I have an empty. 
This empty adds another object that has a collision sensor connected to it.

The purpose of this collision sensor is to end the object when it hits another object with a certain property. Until here nothing wrong...

BUT!

If I add a duration for the object to live (actuator "edit object", option "add object" / Time)  as son as the object hits another one, UPGE crashes.

Why? : (( : (( : ((

xD

Thank you for your time!

UPGE 0.1.9

.blend hosted here:

https://drive.google.com/file/d/0Byr4NYScNOlRZ2U2aDRfRWdmNUk/view?usp=sharing

LOG
___
chico@chico-linux:~/Downloads/UPBGEv0.1.9b2.78Linux64$ ./blender
Color management: using fallback mode for management
Read prefs: /home/chico/.config/blender/2.78/config/userpref.blend
found bundled python: /home/chico/Downloads/UPBGEv0.1.9b2.78Linux64/2.78/python
Read blend: /home/chico/Desktop/Concepts/ColateralDev/Colateral 2017/UPBGE end object Bug.blend

Blender Game Engine Started
Writing: /tmp/UPBGE end object Bug.crash.txt
Segmentation fault (core dumped)
chico@chico-linux:~/Downloads/UPBGEv0.1.9b2.78Linux64$
___

CRASH .TXT:

Blender 2.78 (sub 5), Commit date: 2017-08-13 21:23, Hash 7215575f17

backtrace
./blender(BLI_system_backtrace+0x30) [0x1bdd510]
./blender() [0x102f321]
/lib/x86_64-linux-gnu/libc.so.6(+0x36cb0) [0x7f1a2e9bfcb0]
./blender(_ZN8KX_Scene15LogicBeginFrameEdd+0xdb) [0x13d06eb]
./blender(_ZN15KX_KetsjiEngine9NextFrameEv+0x23c) [0x13b10dc]
./blender(_ZN11LA_Launcher15EngineNextFrameEv+0x17) [0x13a8f97]
./blender(_ZN11LA_Launcher14EngineMainLoopEv+0x89) [0x13a9199]
./blender(StartKetsjiShell+0x1e2) [0x13a7a92]
./blender() [0x112ff4d]
./blender() [0x1036fb2]
./blender() [0x10382bd]
./blender() [0x1038778]
./blender() [0x1038c38]
./blender(wm_event_do_handlers+0x3bd) [0x103913d]
./blender(WM_main+0x18) [0x102ffa8]
./blender(main+0x414) [0xfa18d4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f1a2e9aaf45]
./blender(_start+0x29) [0x102be89]

**Comment by youle31** [comment]
Hi, the bug has been fixed just after 0.1.9 release: 47aa53308775164d079daae4a36cb7b84f17ae80

Maybe we'll do a 0.1.9a release. I already uploaded a build for windows with this fix: https://drive.google.com/file/d/0B3GouQIyoCmrRGJxMVVpZ3UtNGM/view?usp=sharing

I close the issue but if you need another build (on another OS), we can maybe do it. You can still ask here

**Comment by youle31** [comment]
@panzergame : Hello, do you have a recent linux build to share with chicortiz?

**Comment by chicortiz** [comment]
Guys if you are to busy don't worry, I can compile it again later on. I
learned with you how to do that. :)

2017-08-21 13:54 GMT-03:00 youle31 <notifications@github.com>:

**Comment by panzergame** [comment]
https://download.upbge.org/download/buildbot/branch/UPBGE_master_v0.1.9b2.78d22082017h54424e1Linux64.tar.xz

**Comment by chicortiz** [comment]
Hi Panzer thank you very much! I just compiled the last build a few minutes
ago. This build that I compiled works fine.

Unfortunately your package doesn't. Gravity is not working for the added
object for example. I think It could be some problem on my side, since I'm
on Ubuntu 14.04 which is quite old. ;)

2017-08-22 11:27 GMT-03:00 panzergame <notifications@github.com>:
