### ISSUE TITLE
Crash when using smart UV project?

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#573]
Is anyone with Windows + AMD able to replicate this?
1. Select the default cube
2. Enter edit mode
3. Hit U -> Smart UV Project
Blender crashes. Windows gives the old "Blender is not responding" popup.

I can't actually replicate this myself. The user says it only happens in UPBGE. He tried 0.1.3 and 0.1.9. It's fairly recent laptop with AMD APU. The video driver was recently updated as well.

**Comment by Akira1San** [comment]
Ive got AMD R7 200 series and no crash.
