### ISSUE TITLE
crashing bug! end object? 1.9

### ISSUE THREAD

**Issue by REALHanzo** [UPBGE/blender#574]
yeah, I think it has something to do with the end object logic brick, I shoot the gun in my game, the bullet hits the wall and crashes UPbge right after.

time to break out those fly swatters once again ;)

**Comment by justinbarrett** [comment]
I also had crashes using endObject(), but only one one particular object...I have not had any other crashes since I coded my way around it...but it did crash repeatedly and expectedly UPBGE 1.9 Linux.
It was an enemy who shot fireballs and used scene.addObject to create them...It may be related to that.

**Comment by youle31** [comment]
This issue has been fixed just after 0.1.9 release. We have to upload a new release on the website. We'll inform you. Anyway, thanks for bug report!

**Comment by youle31** [comment]
waiting we decide if/when we do another 0.1.9 release, here, is a win64 build with the fix included: https://drive.google.com/file/d/0B3GouQIyoCmrRGJxMVVpZ3UtNGM/view?usp=sharing

**Comment by justinbarrett** [comment]
oh thanks! not necessary, but great response time.

**Comment by BluePrintRandom** [comment]
.1.9.a justin*

**Comment by Akira1San** [comment]
I agree for an 019a version.
The bgmc 25 game Ant panic dont crash anymore.

**Comment by REALHanzo** [comment]
thanks very much for the link youle31, even I don't really use the root blender development and they want to scrap the GE and that sucks because I'm primarily a game developer and I know blender has a great and awesome potential with our without the GE but for me the GE internal for blender is the primary reason I use it above other 3d software. I have so many reasons otherwise to use blender but that a heck of a reason for me... If I start making money off of my project I want to start funding the development of UPBGE, and if all goes well I'll certainly give back to the developers for trying to keep the dreams of all the blender game developers alive thank you so much.

**Comment by justinbarrett** [comment]
I am fully aware of the release system...I mean that there may be a few more bugs that popup over the next month and it may be better to wait. :)
