### ISSUE TITLE
material ramp error?

### ISSUE THREAD

**Issue by REALHanzo** [UPBGE/blender#578]
I had noticed this problem before I'm not sure why this happens but when I try to use the ramps the material totally disappears :P I think it may have to do with the number of lamps or shadows but I don't think that this should be an issue because sometimes it works fine and sometimes not so it may be worth looking into.

**Comment by panzergame** [comment]
Do you have a file reproducing the bug ? Did it happens in BFBGE too ?

**Comment by panzergame** [comment]
I can't reproduce such issue, I'm closing it waiting for proper information.
