### ISSUE TITLE
External Python components do not load

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#58]
The ge_components branch returns an error when using external components:
```
ImportError: No module named 'testcomponent'
Unable to load component from testcomponent
```
This happens because the current blend directory is not added to sys.path until the game starts.  I'm running this script as a temporary workaround:
```
import sys
sys.path.append('/path/to/your/folder')
```

**Comment by panzergame** [comment]
@pqftgs : I understand the solution and it's the only one, but why blender doesn't do that by default ? I would love see the explication.
If there's a real reason or we don't find why, we can add the path before loading and remove it after (i suppose BGE does the same).

**Comment by panzergame** [comment]
Done in ac9de39bb715fcb48f435de1ea3ae47f762e0da6
