### ISSUE TITLE
Shaky camera with use frame rate off

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#587]
Ive compiled the latest master and using this template -> https://blenderartists.org/forum/showthread.php?291532-Third-Person-Shooter-Movement-Example-File/page3 The bottom one.
When switch the "use frame rate off" the camera starts to shake, but with "use frame rate on" it dont. so i dont know if its a bug or its something with the python script.

**Comment by panzergame** [comment]
Did it happens in 0.1.9 ?

**Comment by Akira1San** [comment]
Ops, forgot to add it to the description. No it works fine in 0.1.9
The same file makes the camera go to the bottom in mathfu branch.

**Comment by youle31** [comment]
I can't reproduce the shake

**Comment by panzergame** [comment]
I have the player transformed in a missile when i uncheck use framerate, but this comes from bullet ""issues"" and is fixed by moving the player a little bit up.

**Comment by Akira1San** [comment]
It looks like i had a merge problem, but now its fixed after re building.
