### ISSUE TITLE
getReactionForce() to work at last?

### ISSUE THREAD

**Issue by Kosvor2** [UPBGE/blender#588]
https://pythonapi.upbge.org/bge.types.KX_GameObject.html#bge.types.KX_GameObject.getReactionForce

**Comment by panzergame** [comment]
https://developer.blender.org/T17853

**Comment by BluePrintRandom** [comment]
so there is a work around,

 if we store any forces applied by the object in a frame, and it's linV that frame, the next frame we can compute the change of speed.

this works however it's not ideal.
say we get squished by two equal and opposite sized semi trucks and our linV does not change.

would be ideal is 

collision.hitObjectImpulses where each collision object stores a vector that is the world force applied by the collision.

**Comment by panzergame** [comment]
maybe this: https://pythonapi.upbge.org/bge.types.KX_CollisionContactPoint.html#bge.types.KX_CollisionContactPoint.appliedImpulse

**Comment by BluePrintRandom** [comment]
o it's just what I always wanted :D

thanks panzergame!
