### ISSUE TITLE
Bug: BGMC 23 2.77 level alley2

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#589]
The character animations are not played correctly

**Comment by youle31** [comment]
in sintel desert I have issues with animations too

**Comment by panzergame** [comment]
Could you try to make a simple test file please ?

**Comment by panzergame** [comment]
Fixed in master 0b038a998cb07cba75fcc89b2eeae29960ae8e8f.

**Comment by youle31** [comment]
Thanks! I confirm
