### ISSUE TITLE
Scripts imported by components are not reloaded at game start

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#59]
Components branch, as a workaround I'm reloading modules at the top of my component scripts like so:
```
import imp
imp.reload(modulename)
```

Failure to do this also preserves the context of modules imported in-game, so you get data-freed errors accessing variables like bge.logic.mouse

**Comment by panzergame** [comment]
@DCubix : Can you look at this ?

**Comment by pqftgs** [comment]
Example http://www.pasteall.org/blend/41179

Steps to replicate:
1. Press the component reload button
2. Start the game
3. Observe console errors
```
line 4, in test
AttributeError: 'str' object has no attribute 'mouse'
```
It works when the component is *not* reloaded with the UI
Using imp.reload also makes it work

**Comment by panzergame** [comment]
Fixed
