### ISSUE TITLE
Bug: crash with vehicle at exit

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#593]
debug trace: http://pasteall.org/pic/show.php?id=118620
file: http://pasteall.org/blend/index.php?id=47778

edit: recents commits related to vehicle: 
https://github.com/UPBGE/blender/commit/3341047b55953636ec72e3b66e396e2657353e09
https://github.com/UPBGE/blender/commit/4fd14072bd7375d0e5d99096fb22582b1840ba88

**Comment by DCubix** [comment]
Also, the wheels are shaking and `applyBraking` has a delay after activating

**Comment by panzergame** [comment]
I failed reproduce the crash even while running valgrind.
About the wheel shaking it looks that bullet doesn't support non-normalized vector for axis and down direction.
I propose you to normalize these vector internally to avoid any user errors.

**Comment by youle31** [comment]
Thanks for explanation panzergame! About the crash, i'll reconnect after my night. Now we have a cool all in one template for vehicle, that's cool. Thanks TwisterGE!

**Comment by panzergame** [comment]
The crash was fixed in the last release (0.2.0).

**Comment by youle31** [comment]
I forgot tp close sorry
