### ISSUE TITLE
Textures broken when import from BGE

### ISSUE THREAD

**Issue by artutava** [UPBGE/blender#596]
There's a problem that happens when you import objects from bge. Colors in objects change, and UV maps get broken. When you open a .blend file created in traditional blender, character colors don't change, but uv maps still get broken.

**Comment by panzergame** [comment]
Hello, please provide an example file. What do you mean by importing objects, using LIbLoad ?

**Comment by BluePrintRandom** [comment]
my guess is he is used to multitexture :D

**Comment by artutava** [comment]
character in viewport
![image](https://user-images.githubusercontent.com/32049791/30533917-2d7dc820-9c32-11e7-8269-d7b1fe4d4837.png)
character in player
![image](https://user-images.githubusercontent.com/32049791/30533964-70276ba4-9c32-11e7-8a1e-33cfbba73269.png)

**Comment by justinbarrett** [comment]
I apologize if this is just noise...
    do you have two UV maps? I do not think there is enough info in these two images for them to realistically diagnose the problem...it would be better to provide a link to a blend...I am not having any issues here...I frequently go back and forth...I must add that I am NOT using 2.79 yet though.

**Comment by artutava** [comment]
the problem is that i don't have authorization to send the file. but i can send some prints.
![image](https://user-images.githubusercontent.com/32049791/30551311-7a8ffaa0-9c70-11e7-9442-4754154427b1.png)
![image](https://user-images.githubusercontent.com/32049791/30551331-88a3072c-9c70-11e7-94a6-4591a7173018.png)
![image](https://user-images.githubusercontent.com/32049791/30551372-a4cb8c3a-9c70-11e7-80fd-38cb4b7c2b42.png)

**Comment by Akira1San** [comment]
Try to append the file.

**Comment by panzergame** [comment]
@artutava : Could you try making a minimum file reproducing the bug please ?

**Comment by panzergame** [comment]
@artutava : Could you test with a recent master ?

**Comment by artutava** [comment]
I have tried with UPBGE 0.1.9 and UPBGE 0.2.0.
here's the model in BGE. 
![image](https://user-images.githubusercontent.com/32049791/31267241-cc98a5dc-aa4d-11e7-978e-77d38d089f8c.png)
And here's the model in upbge.
![image](https://user-images.githubusercontent.com/32049791/31267256-d6c1e05a-aa4d-11e7-86df-dba2d8c71100.png)

Here's the blend file and textures.

[bug artutava.zip](https://github.com/UPBGE/blender/files/1361865/bug.artutava.zip)

**Comment by Akira1San** [comment]
The bug is fixed in the latest master. Made a pic: http://pasteall.org/pic/index.php?id=119228
