### ISSUE TITLE
Feature request: Preserve component property values when reloading

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#60]
At the moment, reloading the component resets all custom property values.  This is very inconvenient for development/debugging.

Proposed solution:  Re-insert old values when the property name and type are unchanged.

**Comment by pqftgs** [comment]
Actually, preferred behavior would be reloading the script at game start.  This would probably fix other issues too.

**Comment by panzergame** [comment]
@DCubix : We should use a special function for the reload instead of free the old component and load a new one.

**Comment by panzergame** [comment]
Done, see commits
