### ISSUE TITLE
Tile Image Animation still buggy in 0.2.0

### ISSUE THREAD

**Issue by BlenderDoc** [UPBGE/blender#601]
UpBGE Hash 9171e96a15
Win7 64 - AMD R9 380

Hi. The Tile Image Animation is still buggy in UpBGE 0.2.0. It only works with a workaround:

After loading the Image, don't enable the Animation or Tile!
Insert the Animation and Tile Values first into the grayed out Fields.
Now enable Animation.

**Comment by panzergame** [comment]
Please provide a file with a packed image in.

**Comment by BlenderDoc** [comment]
Hi, here is one.

[UpBGE_TileTex_Bug.zip](https://github.com/UPBGE/blender/files/1354115/UpBGE_TileTex_Bug.zip)

It can be, that after a fail and reload, the workaround does not work also. In that Case, you has to close and reopen UpBGE Blender.

**Comment by panzergame** [comment]
Fixed in master.
