### ISSUE TITLE
Bug: with sensor.status

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#602]
http://pasteall.org/blend/index.php?id=47925

it seems that sensor.status doesn't behave correctly here unless I do a mistake (objects are added twice when we enable tap the first time, else objects are added twice always)

**Comment by panzergame** [comment]
The file is working properly for me, only one objects is added each 200 logic steps. @youle31 Could you check again with the current master please ?

**Comment by youle31** [comment]
@panzergame : For me, the first time the script which add cones is called, it adds 2 cones. If I remove tap, it adds 2 cones each time whereas I do a check if sensor.status == bge.logic.KX_INPUT_JUST_ACTIVATED to add only 1 cone. I'll show you

**Comment by panzergame** [comment]
@youle31 : In the script you first activate an actuator then define a function, the first time the script is loaded (when you call the script function addObject), the head of the script is read and activate the actuator which add an object more than the one in addObject (the script one) function. The other time the function is called the script is already read and don't do it again. 

To summarize this behaviour is normal.

**Comment by youle31** [comment]
But why when you disable tap the object is added twice each time... i'm confused. I have to do more tests and compare with bf blender

**Comment by youle31** [comment]
I surely did a mistake, sorry, so I close that. Thanks for your time panzergame
