### ISSUE TITLE
Turn off mist on 3D view also disable from BGE (when using nodes)

### ISSUE THREAD

**Issue by UnidayStudio** [UPBGE/blender#609]
I'm creating a game that I use some node materials. The mist works fine, but if I disable them on the 3D preview (Right Panel (pressing N) >> Display >> Uncheck World Mist), the mist is also disabled on the game engine, but JUST for  the materials using nodes.

Thanks.

**Comment by panzergame** [comment]
Did the issue happens in blenderplayer too ?

**Comment by UnidayStudio** [comment]
Interesting... in Blenderplayer everything works fine... Just in the Embedded Player...

**Comment by panzergame** [comment]
Fixed in 9a778192d2a1102e7a225d1c9bd210a2a26e4d2a, close if confirmed.
