### ISSUE TITLE
Segmentation fault when reloading a component with multiple users

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#61]
Tested with f327199 (ge_pycomponents branch)

To replicate the crash:
1. Add a component to an object
2. Duplicate the object
3. Hit the component reload button

bt: http://www.pasteall.org/66319

**Comment by panzergame** [comment]
I cannot reproduce the bug, can you confirm that you can ?

**Comment by pqftgs** [comment]
Nope, no more crash!  Closing this
