### ISSUE TITLE
material animating doesnt work

### ISSUE THREAD

**Issue by mushroomeo** [UPBGE/blender#612]
material animating diffuse color didnt work on 0.2.1, but worked on official blender 2.79 BGE with exactly same settings

i just animated diffuse color from 1 to 10 frames and setup always sensor to action and its not working

**Comment by panzergame** [comment]
@mushroomeo : Did you checked that the material doesn't use constant options ?

**Comment by mushroomeo** [comment]
well its really confusing to turn of constant values to able to have material animation...

**Comment by ThyQueen** [comment]
I have the exact same problem. I don't seem to be able to animate any material at all.
It doesn't matter whether I put keyframes in the object, the material or the texture, the animation just won't get rendered at all. Have a look at this video here: https://www.dropshots.com/miracleshappensgoogl/date/2019-04-23/22:14:13
