### ISSUE TITLE
UPBGE 0.2.1 crashes when trying to add an overlay scene that doesn't exist

### ISSUE THREAD

**Issue by Momel15** [UPBGE/blender#615]
`bge.logic.addScene("hud", True)`

The scene doesn't exist in the file (it is supposed to be in a linked group, so in the file it is linked to it works). Just put it in a script, if you comment out the line everything works, if not -> hit "p" and UPBGE 0.2.1 crashes immediately, console says: Error: EXCEPTION_ACCESS_VIOLATION.

After i found the bug, I copied the msvcp120.dll and msvcr120.dll into the upbge 0.2.1 folder because there was a bug in 0.2.0 with crashing blender connected to that problem (#598 ), but it didn't solve the bug

In 0.2.0 everything works fine

**Comment by panzergame** [comment]
Please provide example files.

**Comment by panzergame** [comment]
Fixed in master, please close issue if confirmed.

**Comment by Momel15** [comment]
http://pasteall.org/blend/index.php?id=48066

It's just one line of code so i thought that you don't need a file, sorry

**Comment by Momel15** [comment]
Unfortunately I can't compile UPBGE myself (tried it a bunch of times and always get a long list of errors), so can another one confirm that the bug its fixed or make a build? Thanks :)
