### ISSUE TITLE
KX_GameObject.playAction and Action actuator problem

### ISSUE THREAD

**Issue by DCubix** [UPBGE/blender#616]
It plays with 1 frame lag when using addObject...
Example: http://pasteall.org/blend/index.php?id=48065 (press space)

**Comment by youle31** [comment]
Hello, I've only a workaround, but maybe it is enough. It is just to have the scale set to 1 at the first action frame: http://pasteall.org/blend/index.php?id=48078

**Comment by youle31** [comment]
ah weird. I don't understand, I downoaded again the file, moved to animation view, selected the action and pressed P without changing anything and the bug was not here anymore

**Comment by panzergame** [comment]
Each frame we evaluate the sensors of all objects and activate the following controller and actuators, so if an object is activated during controller or actuator then its sensor were not and will be only evaluated the next time.
So you have one frame when adding an object where the logic does nothing and "it's normal". To fix this issue you can move in python and call `playAction`.

**Comment by youle31** [comment]
@panzergame : Hello, what is weird is that even without changing any option, just when you select action in dopesheet and when you see the keyframes in N tab, this is fixing the issue... Maybe it's only in this file. I don't really know.

**Comment by panzergame** [comment]
@youle31 : Your modification set the object state to the one of the animation at the first frame, if you remove the action play you can see that the transform of the first animation frame is kept.

**Comment by DCubix** [comment]
If it were only in that file, I would not have problems in my actual game file.
And no, it's not normal, i'm using Python that's why I said KX_GameObject.playAction in the title!

I recompiled master and now I get a crash at game start related to a KX_Scene.addObject combined with playAction.

**Comment by panzergame** [comment]
Tested in lst master:
[video.zip](https://github.com/UPBGE/blender/files/1408587/video.zip)
http://pasteall.org/blend/index.php?id=48116

**Comment by DCubix** [comment]
Yeah, it works now but I found another issue.
Add a property to the Cube and it crashes when you press space.

**Comment by DCubix** [comment]
According to my investigations and the crash log, this is related to 80a07ec4959cedd9555865e67a3e4340016c3f84 and/or 53ed0c484f68ea54c12c1b89e34546d0664d88aa

**Comment by DCubix** [comment]
Thanks, it works!
