### ISSUE TITLE
SegFault after calling function that uses a KX_MeshProxy subclass

### ISSUE THREAD

**Issue by TryExceptElse** [UPBGE/blender#617]
This is a weird one. 

The linked 'crash.blend' will result in a SegFault on the second time it is run in the embedded player, but not when run in the standalone player.

In it,  a single module exists, within which a class extending KX_MeshProxy is defined, and a function using it.

The first time the blend is run, nothing unexpected happens. The second time (or rarely, the third time) the blend is run, Blender encounters a segfault and crashes.

Encountered in upbge versions 0.2.0 and 0.2.1 built from master branch on 18 October, 2017.

[crash.blend](http://pasteall.org/blend/index.php?id=48077)

[crash log](http://pasteall.org/621628)

**Comment by youle31** [comment]
I just begun investigations. This looks a bug hard to solve. I noticed that when the subclass is created with bge.types.KX_MeshProxy instead of types.KX_MeshProxy, it didn't crash. The crash occurs in SCA_PythonController code.

**Comment by youle31** [comment]
I can reproduce the crash with KX_VertexProxy too, but not with KX_BlenderMaterial (which inherits from EXP_Value too) neither with KX_GameObject. So what's wrong with KX_MeshProxy, KX_VertexProxy compared to KX_BlenderMaterial for example?

**Comment by panzergame** [comment]
KX_VertexProxy, KX_PolyProxy and KX_MeshProxy are temporary objects created only at the access contrary to KX_BlenderMaterial which is permanent.

**Comment by TryExceptElse** [comment]
Should it throw an error when extended in python then?

**Comment by youle31** [comment]
@panzergame : In TryExceptElse test file and mine, I have different errors. I'll discuss it with you on irc if you want (some are related to globalDict, other only to KX_MeshProxy)

**Comment by youle31** [comment]
this: http://pasteall.org/636669/diff is fixing the crash but I don't know if this is correct

**Comment by panzergame** [comment]
@youle31 : In ge_mesh_copy and ge_mesh_builder I will request to store a KX_Scene pointer in the mesh, to do it properly I will need to create a class like KX_MeshObject.
I'm thinking to move the python interface to KX_MeshObject similar to what is made for material:
RAS_IPolyMaterial/RAS_MeshObject ---> KX_BlenderMaterial/KX_MeshObject (permanent python proxy).

I would like to know if renaming python KX_MeshProxy to KX_MeshObject is fine for you, as the proxy will be permanent.

**Comment by youle31** [comment]
re, yes, it sounds good to me

**Comment by panzergame** [comment]
From current master and using KX_Mesh instead of KX_MeshProxy makes the file work.
