### ISSUE TITLE
vertex colors geometry node gamma incorrect - upbge 021

### ISSUE THREAD

**Issue by DaedalusMDW** [UPBGE/blender#619]
with color management set to "None", vertex colors from the geometry node are wrong.  vertex paint in material works properly.  if i remember right, this behavior goes back to one of the first versions.

vertex colored a 0.5 gray:
![vertcol_node](https://user-images.githubusercontent.com/26656082/31763466-f5328ea0-b483-11e7-9ca9-83cf639bd5f3.PNG)
![vertcol_paint](https://user-images.githubusercontent.com/26656082/31763467-f5415b6a-b483-11e7-8e8e-3bfd6d240d36.PNG)

**Comment by DaedalusMDW** [comment]
this is broken in vanilla 2.78c, but works in 2.74.  not sure about in between.

**Comment by Akira1San** [comment]
To find the commit the broke it, you should test 2.75 too.

**Comment by DaedalusMDW** [comment]
all versions ive tested, (2.74-2.78) the material paint doesnt change per color management.

2.74 and 2.75 node colors get brighter with "sRGB"
2.76 and up node colors get darker with "None"

**Comment by panzergame** [comment]
@DaedalusMDW : Do you reported your bug to the blender bug tracker ?
