### ISSUE TITLE
Add radius to mathutils BVHTree

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#62]
if we have enough functionality in python, we can actually start taking over 
blender itself in the bge.....

with mathutils  bvhTree -> getFacesInRadius 

get all faces that collide with sphere of R radius,

we can begin to operate on models in BPY to take over C based systems, and have the same functionality exposed to C.

Basically we can remake the system to empower the user, and expose systems to users, that they may then use in unintended ways.

**Comment by BluePrintRandom** [comment]
use cases -> paint weights, splatter maps of large maps, in game sculpting , in game or in bpy vertex selection, in game / in bpy face selection using circle brush.

**Comment by panzergame** [comment]
This is game specific feature ?

**Comment by BluePrintRandom** [comment]
Both, you can use it in real time damage, and in game mesh manipulations of
vertex color or to select faces to operate on via bpy network sockets (like
agoose slice demo) so you could operate on mesh data in game, other
ideas... Plus this one u could push to master,

This is game specific feature ?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/UPBGE/blender/issues/62#issuecomment-198548560>

**Comment by BluePrintRandom** [comment]
You can close this, it was added to master,

You can merge the patch
