### ISSUE TITLE
reinstancePhysicsMesh not working in latest master

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#622]
it could be my build set up however reinstancePhysicsMesh is not working for me in recent build.

**Comment by BluePrintRandom** [comment]
http://pasteall.org/blend/index.php?id=48132

file example

**Comment by youle31** [comment]
First bad commit: 766896053c90cdf012aeb8701d707fdddaf54e15

**Comment by youle31** [comment]
Thanks @panzergame ! it works for me.
@BluePrintRandom : I updated ge_normals with panzergame commit. To update your branch do:
git checkout ge_normals (to go on ge_normals)
git pull (to update)
if git pull doesn't work, do:
git pull origin ge_normals
then build

**Comment by BluePrintRandom** [comment]
Thanks !!!!
