### ISSUE TITLE
Scale Rotate Grab pb in 3D view

### ISSUE THREAD

**Issue by jologithub** [UPBGE/blender#623]
Hi, here is a simple 3D scene 
on upbge 0.20   
V2.79.1
win10

there is an empty at 0,0,0   
      a (grey) cone at 0,0,0
   this 2 objects are "alone" without parenting

there is a python script attach on the empty (by always logic brick)
  (but the bug appear without running the play mode

red pyramide is parented with green cube

The bug is :
   on the 3D view, while making Grab Scale or Rotate operation on
   the empty or the cone  the green cube and the red pyramide follow the same operations.

there is no reason for that  

this only occur if the empty or the cone are at 0,0,0 position.
[test_parent.zip](https://github.com/UPBGE/blender/files/1420210/test_parent.zip)

**Comment by Jesusemora** [comment]
you have proportional editing on. press O.
i think it's not a bug, and it's not related to bge. the developers of upbge only modify bge code, if it's a bug, it must also be in bf blender.

**Comment by jologithub** [comment]
you are right, this is the same behavior in blender.

thanks for the rapid reply.

is there a standard way to close or clear this isuue ?
