### ISSUE TITLE
endObject() crashing blender

### ISSUE THREAD

**Issue by justinbarrett** [UPBGE/blender#625]
I am having an issue with all versions after 0.1.8 on linuxmint(latest stable 64bit)crashing blender completely when calling scene.endObject()  when running GE from the interface. If I run from the stand alone player It only crashes the player.
I get an error Totblock: 303

but in 0.1.8 I do not...occasionally I get Totblock: 1, but I do not see any concern for this.

I could upload the scene, but it is 85MB...

I am just wondering if anything changed in the way instanced objects were handled or anything in the base code that might affect this....the crashing also occurs under main branch 2.79, but I have not investigated earlier versions of that...I know an endObject() can possibly be interfered with while waiting for code to finnish running. But even by disabling all this excess code I get the crash.

**Comment by panzergame** [comment]
Make a simple file reproducing the bug please.

**Comment by justinbarrett** [comment]
I am sorry, I know this is just noise to you. I cannot reproduce it...I know that is a poor excuse, but even after I disable all code using the inventory system and I write a simple endObject() script it still produces the same crash and error....

This is pretty much a dead end for me as I cannot properly reproduce this...and uploading my entire game file is just not an option....I will just close this and continue to use 0.1.8
