### ISSUE TITLE
occlusion culling not working in 0.2.1

### ISSUE THREAD

**Issue by justinbarrett** [UPBGE/blender#626]
Occlusion culling does not seem to work in 0.2.1 but seems fine from 0.8.1 to 0.2.0...I'm really not certain what the cause is.

**Comment by panzergame** [comment]
It's certainly working in recent master after commit ea982886870d619ec82b2ddff04d0b400095c120.

**Comment by justinbarrett** [comment]
It is not working for me on LinuxMint 64...I am using the build after you bundled python V3.6
this blend works as I stated above on all but 0.2.1
https://accidentaldevelopment.weebly.com/uploads/1/0/8/3/108320803/occlusion_test.blend

**Comment by justinbarrett** [comment]
Re-downloaded V0.2.1 and it still has the same functionality...it fails basically...and not to open a new issue, but I also get no interaction between dynamic obj. and col. sensors...all these issues "seem" to have started after python V3.6...I'm not sure if any of these things have anything to do with each other, but thought I would bring it up since they may be related to one another....the same applies for my endObject() crashing...I do not know if it is due to the py V 3.6 update or not....

**Comment by panzergame** [comment]
@justinbarrett : A release version doesn't change, when I mean recent master it's the commit after the last release. You should either compile the recent master or ask someone to compile it.

**Comment by panzergame** [comment]
8166b30adbfc35c91265761cf3d12a2f858607db

**Comment by justinbarrett** [comment]
I saw the commit, thank you.
