### ISSUE TITLE
set rotation does not update()

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#629]
test file
[rt2.zip](https://github.com/UPBGE/blender/files/1435619/rt2.zip)

setting a bone rot and calling update is not working

(I am trying to curve the road using armatures)

**Comment by panzergame** [comment]
This is not working in BFBGE, could you confirm ?

**Comment by BluePrintRandom** [comment]
set rot does not work in bf bge but set position does apparently

**Comment by panzergame** [comment]
Fixed in eb0374af4a1de75628c137436bd5fd3e5f475daa, though your file should use `r.z` instead of `r.y` to rotate the bones, after this you also need a location shift.

@BluePrintRandom : please check now that issue comes from your file only, if yes close the report.
