### ISSUE TITLE
Dissolve triangle mesh into many convex hulls

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#63]
There is script in bullet somewhere (the forum) to dissolve a triangle mesh into many convex hull objects (not game objects- bullet sub objects) 

this would be handy to have as a physics type.

**Comment by DCubix** [comment]
Why is that needed?

**Comment by BluePrintRandom** [comment]
it makes it so objects won't pop through ever, unless they are going
ridiculously fast (fast enough to skip the width of the convex hull in 1
frame) even then I don't think they pop through near as easy as a triangle
mesh.

Triangle mesh have no volume, but convex hulls do, so dissolving the
triangle mesh into many convex makes simulations much harder to break.

the generated shapes would not be added to scene.objects (I would prefer if
they were not added to scene.objects)
