### ISSUE TITLE
Crash when linking a scene to a blend when another linked scene in this blend is currently open/active

### ISSUE THREAD

**Issue by Momel15** [UPBGE/blender#630]
If you link a scene into a main file and there is another linked scene active, blender will crash. If you make a non-linked scene active in the file before linking it works.

This bug is also a BF Blender Bug, but as they are currently working on 2.8 (it will have new asset management so the linking function will no longer be implemented maybe?), I don't know if they will fix this.

Example files: https://www.dropbox.com/s/lzol07ds02sf70q/linking_scenes_bug.zip?dl=1
(Open main.blend and try to link link_b when "scene" is open and when "link_a" is open)

**Comment by panzergame** [comment]
The bug you are reporting happens while the game engine is not running, we didn't touched the linking part in UPBGE, you should report your bug to blender bug tracker.
