### ISSUE TITLE
Can't compile in Lubuntu

### ISSUE THREAD

**Issue by rivenblades** [UPBGE/blender#631]
I can't compile in Lubuntu.When i hit make,it gives me 
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

I have done all the above steps from :https://wiki.blender.org/index.php/Dev:Doc/Building_Blender/Linux/Ubuntu/CMake

However this fails in :cd ~/blender-git/blender;make
i have g++ and gcc 5.4.0

**Comment by lordloki** [comment]
You must to activate c++11 standard in CMakeList.txt options

**Comment by rivenblades** [comment]
How to do it exactly?
In blender/CMakeLists.txt i edited at line 523:set(WITH_CXX11 ON)

**Comment by rivenblades** [comment]
a ok i added it before the if(APPLE) at line 515
Thanks for the help.
Another guy complained about codecvt when the make process was at 93%.If it happens to me, I'll ask again!!

**Comment by lordloki** [comment]
You're wellcome. Thanks for using UPBGE
