### ISSUE TITLE
navMesh.replaceMesh('mesh',1,1) + navmesh.rebuild() does not change the navmesh

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#633]
I believe rebuild is supposed to create a new navmesh after mesh updates or replacement has happened,

I am not sure why but this appears to be failing

http://pasteall.org/blend/index.php?id=48266
steps to see bug

press P to play

press space bar to run
```python
import bge


def main():

    cont = bge.logic.getCurrentController()
    own = cont.owner
    own.draw(0)
    own.replaceMesh('Navmesh',1,1)
    print('Replacing mesh')
    
    own.rebuild()
    print('rebuilt')
main()
```

this shows the bounds of the original mesh, not the new mesh 

rebuild does not appear to be working* or replace mesh does not change the mesh used by the navmesh?

**Comment by panzergame** [comment]
There's a way in KX_NavMeshObject to convert from KX_Mesh but is never used and also nav mesh have an extra CD_RECAST layer that i have to identify…

**Comment by panzergame** [comment]
I finished a patch (currently writing the commit message), but I noticed that even rebuild with a mesh including detailed nav mesh information was doing nothing…
