### ISSUE TITLE
Camera falls to the ground in fpsengine template

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#634]
Found this bug while testing the fps template for my project. The head cube falls to the ground in Upbge 021-022. It dont on bf bge and upbge 019. the cube is set to dynamic col.

link; https://drive.google.com/open?id=1czGQafDLpsoIfXDSN3nrp0ZKR2kzLrvD

**Comment by HG1-Public** [comment]
Seems that there has something changed regards to the physic engine.
In the previous version of Upbge you was able to join a dynamic object with an other dynamic object. So the child would act like as a static object.

I don't know if this a new feature or a bug.
But for now you can set the cube.001 manually to static to get it work.

**Comment by Akira1San** [comment]
Setting it to static works, thx.

**Comment by panzergame** [comment]
Fixed in master: 067da32bf00a0917f2deceb7dbe8e88ef6f6f9a1.
