### ISSUE TITLE
upbge.org: expired security certificate 

### ISSUE THREAD

**Issue by MoritzBrueckner** [UPBGE/blender#637]
Firefox doesn't load the page anymore, it says the http certificate expired on thursday (23/11/2017).
Unfortunately Firefox doesn't allow (only in this case, usually it works?) adding an exception, so currently there is no possibility to open e.g. the upbge api with firefox.

**Comment by justinbarrett** [comment]
its the way firefox handles these certificates now makes it impossible to visit the site..no way to add exceptions, even disabling security features does not let you enter...I hate the way tech is headed sometimes...I'm sure the certificates could be updated, but tbh, I do not know how....

In short...same problem here.

**Comment by panzergame** [comment]
Fixed.

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/55489409-c6c5a400-5629-11e9-8652-45d6ef2db779.png)
![image](https://user-images.githubusercontent.com/13716824/55489537-fecce700-5629-11e9-9eec-7385d7da7997.png)

This is an issue again.

**Comment by Frankjore** [comment]
Now the problem is greater, nor opera, nor chrome, allow access because they say that the page no longer exists, I think they have closed it. It's the end of UPBGE.

**Comment by BluePrintRandom** [comment]
I have a recent copy of master win_64 and shuvit has cloned the API.

wkk is looking at getting buildbot up.

Panzergame has been unreachable about renewing the website.

**Comment by marechal-p** [comment]
@Frankjore ah indeed, nice catch.

What do you think about hosting some pages for UPBGE on GitHub directly?

**Comment by ChildishGiant** [comment]
I guess it's time for [Armory](https://github.com/armory3d/armory) to take over 😕

**Comment by lordloki** [comment]
I have access to upbge domain provider. @marechal-p or @blueprintrandom when you are ok with the new site we can do the change.

**Comment by ChildishGiant** [comment]
I'd recommend using github pages to host with a custom domain. As long as you don't need any server side/back end stuff, it's great.
https://help.github.com/en/articles/using-a-custom-domain-with-github-pages

**Comment by Frankjore** [comment]
Ok. Thank you for your work, lordloki. You will communicate when it is possible to access the page.

**Comment by marechal-p** [comment]
@lordloki You can continue sending me details at marechap.info@gmail.com, such as do we need to host the website and simply point the domain to that, what exactly is it that you have?

**Comment by ThyQueen** [comment]
I get the following:
Unable to connect

Firefox can’t establish a connection to the server at upbge.org.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

We cannot download the program!

**Comment by marechal-p** [comment]
> We cannot download the program!

Well, your are writing this on the project's repository, with all the sources and instructions to build it...

Meanwhile things are tried to bring it back up, will take some time.

**Comment by lordloki** [comment]
Ok, I pointed out upbge.org domain to github new upbge-web project. I added to @marechal-p @BluePrintRandom @youle31 to admin for this project. If you need another ones please send me a message.
I need 24 hours more to enforce HTTPS until then you will see the classic non-https message.

**Comment by marechal-p** [comment]
The domain seems to be available now, and pointing to the repository you created, perfect!
