### ISSUE TITLE
"Build failed" in Windows, "M_PI_2: undeclared identifier"

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#638]
Hello! I'm not being able to build my UPBGE for some time. I didn't edited the content of the sources, just pull and rebuild everytime. I've deleted all my clone and release directories, cloned the repository again and tried to rebuild, but the problem persists.

EDIT: Additional information - Windows 7 Ultimate 64 bit, MVSC 2015, trying to build x86 version of UPBGE.

Here's a screenshot of the console showing the actual errors:
![cmd_preview](https://user-images.githubusercontent.com/19820741/33280064-03ca58f8-d388-11e7-814f-04a8f0ebe51b.png)

**Comment by youle31** [comment]
hi, Akira_san reported the same issue. Apparently it comes from the commit where master is based on (not sure).

Anyway, #include "BLI_math.h" at the top of rna_object.c and KX_CharacterWrapper (iirc) fixes the compilation issue

**Comment by joelgomes1994** [comment]
Thanks, @youle31 , it's working now!
Please, commit this fix to the master to avoid others having the same issue. Thanks. ;)

**Comment by youle31** [comment]
hi, if the compil error comes from the commit upbge is based on, maybe it's better to wait for the next merge to have "official fix" and avoid a conflict between BF/upbge sources

**Comment by joelgomes1994** [comment]
Fixed on 3c89e96528cc1ad4404669442b0f5fd09b789fa2 , thanks for that. Closing the issue.
