### ISSUE TITLE
Slow parent bug - Child obj position turns into 'not a number' values

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#639]
Tested on latest master build. When slow parent is enabled, the child object (after some motion) disapears and its position becomes (nan, nan, nan). Other attributes may be affected as well, but I didn't tested all of them.

How to reproduce the bug: https://www.youtube.com/watch?v=RcEyUlO6jMM

Test file: http://pasteall.org/blend/index.php?id=48428
Test file attached too: [ex_slow_parent_realtime.zip](https://github.com/UPBGE/blender/files/1511825/ex_slow_parent_realtime.zip)

EDIT: This bug seems only to happen when the slow parent is at value 0.0 or near it (like 0.1), in any other higher value it seems not to happen.

**Comment by panzergame** [comment]
Could you test with recent master including de197383e1dcfe08166a7d8e725cf5457b369725 ?

**Comment by joelgomes1994** [comment]
@panzergame No issues in latest master, running smoothly. Nice work!

**Comment by lordloki** [comment]
Closing. Thanks for report and testing
