### ISSUE TITLE
Group instances not spawning + segmentation fault

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#64]
Tested with build 243da53.  Bug does not exist in BF 2.76 - 2.77
When a group member ends, subsequent attempts to spawn the group will fail.
Similarly after a group object ends, spawning the group will cause a segmentation fault.

Example: http://www.pasteall.org/blend/41134

**Comment by panzergame** [comment]
Fixed in 96dffdb9f5727495f07f8804fb09af20d3d383c3
