### ISSUE TITLE
physics% too high in latest compiled master branch

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#641]
Compiled latest master - physics% too high.
image: http://pasteall.org/pic/index.php?id=120675
game used bgmc 26 - Base512 - vincius

**Comment by Akira1San** [comment]
One more test - BGMC 23 Onikiri Demon slayer - image: http://pasteall.org/pic/index.php?id=120707
When the enemy started to spawn, the physics spiked.

**Comment by panzergame** [comment]
When did the issue began ? from which commit/date ?

**Comment by panzergame** [comment]
Confirmed.

**Comment by Akira1San** [comment]
fixed in master.
