### ISSUE TITLE
Question: Any plans for binaries? (Save as game engine runtime)?

### ISSUE THREAD

**Issue by chicortiz** [UPBGE/blender#642]
Hi guys!

Sorry to ask this here (if it's annoying you please delete or close this one), but Does the actual version of UPGE comes with the "Game Engine: Save as Game Engine Runtime) add-on? 

(game_engine_save_as_runtime.py) 

(https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Game_Engine/Save_As_Runtime)

Thank you very much for your patience,

Ortiz

**Comment by joelgomes1994** [comment]
There are some newer and better addons, like Game Publishing and Build Game. Although I think those addons should provide a option to not embed game files in exe, just in a separated game data folder.

**Comment by chicortiz** [comment]
Wow! That's Awesome. Thank you Joel! :)

**Comment by BluePrintRandom** [comment]
bp player has been integrated, and is itself do for upgrades at some point
in the near future.

**Comment by panzergame** [comment]
@chicortiz : Normally the addon should work as we didn't modify it and its dependencies, just enable it in user preference.

**Comment by chicortiz** [comment]
Hi Guys!

Thank you so much! You are so kind.
Sorry for the laziness. 

(‘-’*)
