### ISSUE TITLE
Bug: with textures

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#644]
Hello,
test file: http://pasteall.org/blend/index.php?id=48434 (There are weird bands on the ground) in last master

**Comment by panzergame** [comment]
The commit 5d84885e002023041b3bf4b6cf04b9638fb61862 up during a bisect, but after some debug work it looks that this commit only show an old bug: When the user use a custom shader the mesh is drawn along texco (glTexCoordPointer) and not only attributes, but these texco have a odd behaviour about UV, it considerate that all textures use an unique UV layer.

In the file of this report two UV layers are needed in the shader, but 4 texco are defined with addresses out of vertex stride finally to get unique layers…

What I propose to solve this bug is to copy the attributes behaviour, each texture UV coordinates accessed from shader (gl_MultiTexCoordX) should link to an existing UV layer even if all of them link to the same layer.

**Comment by panzergame** [comment]
I temporary fixed this issue in 11214b785917d78bb6301436b506a7dc2177020c, could you check that there's no major issue introduced please ?

**Comment by youle31** [comment]
hello, your fix prevents bands but the render is not as before (textures mapping seems incorrect)

**Comment by panzergame** [comment]
The normal map in the shader seems not working for a long time… I don't know what was the expected result.

**Comment by youle31** [comment]
@panzergame: I'll try to bisect (normally all the tiles are the same size) (les carreaux de carrelage ont normalement la même taille). 

@Panzergame, @lordloki  && @TwisterGE: nothing to do with but if you're interested: https://lists.blender.org/pipermail/bf-committers/2017-December/048940.html (if you want we could discuss it. As I broke many things, I was thinking to restore only the most important and do a "small" game engine, maybe just with 1 scene rendering, and eevee render). I fear if you don't help me, we won't have any game engine at 2.8 start. What do you think? (We can discuss it by mail if you prefer)

**Comment by youle31** [comment]
@panzergame: the expected result is : http://pasteall.org/pic/show.php?id=120799 . It worked in 0.2.2. I begin the bisect

**Comment by youle31** [comment]
The first bad commit is: https://github.com/UPBGE/blender/commit/5d84885e002023041b3bf4b6cf04b9638fb61862

**Comment by panzergame** [comment]
Previously the memory layout for vertex data of format 1uv 1color was on 64 bytes, the uv was at offset 48 and the color at offset 56, but the color wasn't the last memory part of the vertex. There's a padding of 4 bytes : 56 (offset color) + 4 (= size color) + 4 (pad) = 64.

As described below the texture coord were totally wrong and so gl_MultiTexCoord1 was asking for data at the second uv layer which is uv offset + (2 * 4) (= size uv) = 56. This point to the beginning of the color data and resulted in a UV data of (const, 0.0) as the color was the same for all the vertices and that the padding was to 0.

But with the new vertex data layout the padding is removed (don't know exactly its previous motivation) and the memory layout is as follow: vertex size: 52, uv offset: 40, color offset: 48.
So the fake second uv data resulted in (const, pos x of next vertex) as the color was still constant but that the y of the uv pointed to the x member of the position of the next vertices: 40 (= uv offset) + (2 * 4) (= size uv) + 4 (float size of uv x) = 52.

If we back to the example file, in the shader we use a lightmap sampled at position gl_MultiTexCoord1, but if we copy the lightmap sample to fragment color we have everything white in older UPBGE  and BFBGE, if we replace gl_MultiTexCoord1 by a constant we have similar result. In UPBGE before my fix the lightmap sample resulted in odd lines but constant lines. This confirm the memory issue.

My fix restored the lightmap even if the file seems to not use for a long time (BFBGE used UV2 = (0.0, 0.0)...).

**Comment by youle31** [comment]
@panzergame : Ah ok, thanks very much for you investigations and your answer. So this is a change of padding in vertex format which caused the changement of behaviour. (I don't really know why there was a padding. In BF blender sources there was this comment in vertex format struct: http://pasteall.org/704047 but I don't know why alignment can change performance). Maybe @significant-bit can answer (it seems there are some things related in gwn_vertex_format.h but it is beyond my understanding) if you want to ask him.
Anyway, I close this issue as this is is just a small backward compatibility issue.
