### ISSUE TITLE
Performances/bug: every man sky

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#645]
BGMC22/2.78a/every man sky/launcher: the file is very slow, I don't really know why, there are some messages in the console. I continue my tests with last master

The performance issue is also in BGMC 22/caves.blend (2.78a) / and in Horsey adventures (same folder) 

in all these files there are messages in the console, don't know if the performance leak comes from there

**Comment by panzergame** [comment]
Could you copy the console message and maybe screencast the profiler in current master and in 0.2.1 or 0.2.2 please ?

**Comment by Akira1San** [comment]
every man sky/launcher - the same physics bug as my issue.

**Comment by youle31** [comment]
Every man sky: http://pasteall.org/696427 Maybe it comes from the new API for gravity? Sorry I haven't time to check now (family)

**Comment by panzergame** [comment]
Fixed in 56d085510290e295548409719e4a75465cd66097.
