### ISSUE TITLE
Bug: Issue with keyboard it seems

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#646]
BGMC 23: Knights of Suzanne. The space bar to jump doesn't seem to work correclty
There are some messages in the console

**Comment by panzergame** [comment]
Could you paste the console messages please ?

**Comment by youle31** [comment]
Knights of suzanne: http://pasteall.org/696452 : debug prints?

**Comment by panzergame** [comment]
I can jump when pressing space. (086255edf5c8abbf298a92d95fde71b4c4e79452).
