### ISSUE TITLE
bug: physics?

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#647]
bgmc23/2.78/toy story: with the character, move left and try to jump on the cube. It's like if the cube had a sphere collision box (not the same as before)

**Comment by panzergame** [comment]
Is this theory confirmed by the physics draw ?

**Comment by youle31** [comment]
No, if you want to look at this bug, you can have a look at scena2. The cartons (weird constraints or armatures...). Else there is still weird text in the console: http://pasteall.org/696473

**Comment by panzergame** [comment]
Thanks for report, issue fixed in 7250e3c8671a5c8c68312a3b3672ecfe7e7e5adc.
