### ISSUE TITLE
resetVertexColor(uniqueToObject)

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#649]
resetVertexColor()
could setback all vertex color to default value for mesh

resetVertexColor(True) 
would set to default value on a  instance of the mesh hpwever the vertex color map would be unique to a object

(similar to how reinstancePhysicsMesh(3rd arg works)

**Comment by panzergame** [comment]
> resetVertexColor()
could setback all vertex color to default value for mesh

This mean storing the color of each layer and each vertex, I don't think enough users need it to implement a data copy internally.

> resetVertexColor(True)
would set to default value on a instance of the mesh hpwever the vertex color map would be unique to a object

A mesh data can't be unique per object, the best way to simulate it is to duplicate the mesh, I forgotten to push the branch ge_mesh_copy. In this branch you can duplicate meshes in python using `KX_MeshProxy.copy()`.
