### ISSUE TITLE
UPBGE main website not updated for a long time.

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#652]
Im making a notice, last updated for version 019. :)

**Comment by justinbarrett** [comment]
Yeah, I'm sure there is a lot of other stuff going on...but to some it makes it appear as though UPBGE is no longer being supported or developed..
    I myself see there is always something happening, just pointing out how it may look to new users...

**Comment by panzergame** [comment]
The main website is not updated up to 0.2.2, thanks for report.
