### ISSUE TITLE
How do update scene to frame?

### ISSUE THREAD

**Issue by parshin-pn** [UPBGE/blender#654]
Hello, guys!

I want to use NLA in Blender Game Engine and I need some advice how to update scene to a particular frame (as same as changing frame in TimeLine). Is there any function to perform this action (not necessary in Python API, I can use C++ code)? Or is it possible anyway?

Thanks

**Comment by panzergame** [comment]
Hello,
You should look at user external time through python functions:
https://pythonapi.upbge.org/bge.logic.html#bge.logic.setUseExternalClock
https://pythonapi.upbge.org/bge.logic.html#bge.logic.setClockTime

The first function disable time advancement and the second is used to set time you want. The animation will be updated to the desired frame if you correctly started them at the beginning.

**Comment by parshin-pn** [comment]
Thanks, panzergame. But it seems not what I'm looking for. As I understand, I can set my own timer for GE logic but it doesn't solve problem of updating NLA animations without logic bricks. Although I wrote custom NLA reader and sequencer for my task, I'm still looking for something similar to anim_sys.c in BGE.
