### ISSUE TITLE
Suggestion - Add Actuator Timer.

### ISSUE THREAD

**Issue by kholyphoenix1** [UPBGE/blender#655]
Hello, 

It would be interesting to have an 'actuator' that does timing control.
Sensor + Controller + Actuator (Timer).
This would allow you to create animations using motion + timer

```
Sensor (Left Click + Mouse Over)
Controller (And)
Actuator (Timer)
Actuator (Motion)
=
Motion with timer end ...
```

Thanks for listening.

**Comment by panzergame** [comment]
Hello,
Should not be this in a controller, a controller kept active for N frames after his activation ?

**Comment by kholyphoenix1** [comment]
It is true. What you said makes sense. Thank you!

**Comment by lordloki** [comment]
Closing. Thanks.
