### ISSUE TITLE
Latest master fail to compile - win81 64b vs2015.

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#658]
Error log: http://pasteall.org/723045
output log; http://pasteall.org/723048

**Comment by youle31** [comment]
hello, I confirm. I tried to fix, but my fix must not be good because pathfinding still crashes after. MSVC wants we allocate arrays with new it seems but I didn't found the good fix (http://pasteall.org/724718/diff fixes the issue but I don't know if you want to use this)

**Comment by Akira1San** [comment]
fixed in master now.
