### ISSUE TITLE
Feature request: Add overlay/background scenes with Python

### ISSUE THREAD

**Issue by Momel15** [UPBGE/blender#66]
Hey,

what do you think about a Python command which adds an overlay/background scene?

Like `scene.addOverlayScene("overlayScene")`? The only problem is that you currently can't access inactive scenes. Would that be possible?

**Comment by youle31** [comment]
hi, you can already add scene like that: https://www.blender.org/api/blender_python_api_2_77_release/bge.logic.html?highlight=addscene#bge.logic.addScene

This suppose you know the scene name.

I made a patch to access inactive scene names but it has not been merged. We'll discuss it with other devs.

**Comment by panzergame** [comment]
Please open an other issue or rename it, for the moment i close it.

**Comment by youle31** [comment]
@Momel: bge.logic.getInactiveSceneNames() is merged. It will be available in the next release:

http://www.pasteall.org/blend/41248
