### ISSUE TITLE
Build failed due to KX_NavMeshObject.cpp errors

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#660]
Windows 7 64 bit, MSVSC 2015 32 bit

Can't build from latest master. I even tried to revert some commits, and delete the folder to clone it all again, but the error persists. Can you give me some advice / fix this in master? Thanks.

![image](https://user-images.githubusercontent.com/19820741/34073296-aa302692-e27d-11e7-8f98-f8fcad4291f2.png)

**Comment by lordloki** [comment]
Fixed in master now. Thanks for report.
