### ISSUE TITLE
Suggestion -  Exchanging Material (Similar to 'Replace Mesh')

### ISSUE THREAD

**Issue by kholyphoenix1** [UPBGE/blender#662]
Hello,

I think it would be interesting that in 'Logic Brick' we could change the Material in the Actuator similar to the 'Edit Object -> Replace Mesh' function. You could have the 'Change Material' option where you would display the Material of the object itself.

This would prevent you from creating other objects to solve the problem. I created a menu in the game and had to create 2 objects where the second one changes color giving the illusion that the menu changed color more that in fact another object was activated.

Thanks!

**Comment by kholyphoenix1** [comment]
@panzergame , Would it be interesting to implement it?

**Comment by panzergame** [comment]
Hello, did you look at:

https://pythonapi.upbge.org/bge.types.KX_MeshProxy.html#bge.types.KX_MeshProxy.replaceMaterial

**Comment by kholyphoenix1** [comment]
Thanks!
