### ISSUE TITLE
Bug in Motion Actuator dRot

### ISSUE THREAD

**Issue by MkeC** [UPBGE/blender#664]
I recently upgraded from UPBGE 1.8 to 2.3 and blend I am working on started acting strangely.

I tracked the problem to a bug in the Motion Actuator.
Using Python (e.g. dRot=theta), values of theta less than or equal to 0.00034 radians  seem to be totally ignored.

**Comment by panzergame** [comment]
@MkeC : Could you provide an example file please ?

**Comment by MkeC** [comment]
Sorry.  Try this.

The green cube and blue cube should both orbit the center.   The blue cube fails because dRot is less than 0.00035.
[orbitTest.zip](https://github.com/UPBGE/blender/files/1596318/orbitTest.zip)
