### ISSUE TITLE
Crash of blenderplayer when running specific project

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#665]
Hello! I have a issue with a project... I can run any other project in embedded player and blenderplayer, however the following project crashes when running on blenderplayer. I have no time right now to discover from which commit the problem started, but from what I know the problem is related to Python (disabling all Python functions in script with the pass keyword makes the project work on blenderplayer) and at 0.2.3 tag it's working normally on both embedded player and blenderplayer. I will try to investigate more.

[map_editor.zip](https://github.com/UPBGE/blender/files/1632931/map_editor.zip)

EDIT: Updated test file. Still I couldn't find the commit which the issue starts.

**Comment by nestanqueiro** [comment]
just tried it and I have no crash... I can't figure out how to load the files, but I can create and save my maps, both on embedded and on blenderplayer...

**Comment by joelgomes1994** [comment]
@nestanqueiro I just updated the file, the old one was not able to load the maps, this one does, and have some additions. Are you using the latest master and Windows? In my build it still not working.

**Comment by nestanqueiro** [comment]
@joelgomes1994 : It all works ok, both on windows latest official build, and on linux, latest as well... it now loads and saves, both on embedded and blenderplayer... although you have a few warnings on autostart sensor, and at sometime during loading or saving I run into an error on map_editor.py line 144, in mouse behaviour.... it probably didn't save correctly... I could not repeat the error... but I haven't tryied that hard to find it again... Nice work, by the way! Cheers

**Comment by joelgomes1994** [comment]
Thanks for the feedback!
You will not confirm the crash on official builds, it works on them (I've tested it as well, until official 0.2.3), the issue starts on more recent commits, building from source. I will try to provide you my latest master (UPBGE 0.2.3 32 bit for Windows), and you try and tell if it works. But for now, stay with the screencast of two different versions of UPBGE running the project: https://www.youtube.com/watch?v=u4dazRaBH0Y

**Comment by joelgomes1994** [comment]
By the way, @youle31 , you do use Windows, right? Could you test the project on your latest master's blenderplayer to confirm the crash, please? Thanks.

**Comment by youle31** [comment]
hi, I confirm the crash with blenderplayer: http://pasteall.org/pic/show.php?id=122720

**Comment by panzergame** [comment]
@youle31, @lordloki : I tested on linux without errors, is the issue still actual for you on windows ?

**Comment by youle31** [comment]
Seems there's an issue in embedded too now for me (the game exits when I select the map)

**Comment by joelgomes1994** [comment]
@youle31 The same to me.

The problem may be related to memory issues, because when the map is clicked, the project does the following:

- Changes the scene from main menu to editor.
- Gets each tile information (loaded from file into globalDict) and spawns each tile into the editor.
- Saves the reference of each added tile object in a dictionary in the scene. Example: `scene['map_dict']['tile_object'] = tile_object`

The issue probably is related to the referencing of objects in the scene object, but that's only a guess.

**Comment by panzergame** [comment]
Can you test https://download.upbge.org/download/release/windows32/UPBGE_master_v0.2.4d2018101313h086255eWindows32.zip ?

The last release introduced many fixes related to libloading.

**Comment by joelgomes1994** [comment]
@panzergame For a long time I didn't experienced crashes (except for the 32 bit build, now fixed). The `map_editor.zip` works like a charm in latest master, on both x64 and x86 builds, both on embedded and standalone player. Close the issue if you're done, everything is fine to me.

**Comment by lordloki** [comment]
I confirm that it works in latest master. Thanks for reporting
