### ISSUE TITLE
Adapted PlayStation Controller not Detected by BGE

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#667]
I have a PlayStation 1 controlller connected to my computer with USB adapter. It definetly shows under my input devices with type "Joystick" and name PlayStation(R)3 controller, so I know it's there. However, I checked through all 8 joystick input channels in BGE, and it's just not there. Printing cont.sensors["Joystick"].connected says False for all joysticks from index 0 to 7.
I really don't understand why is that the case, since it does work on other apps. Anyways, here is some info regarding it:
![controllerinfo](https://user-images.githubusercontent.com/6423934/34644203-836185c4-f33a-11e7-8233-6622ff09d9b6.png)

**Comment by adriansnetlis** [comment]
Some additional notes after doing some research on Google.

- I have installed `libsdl2-2.0.0` and `libsdl2-dev` packages
- I have properly mapped my controller to match the Xbox controller mapping

**Comment by lordloki** [comment]
Hi,

Could you install antimicro application (https://launchpad.net/~ryochan7/+archive/ubuntu/antimicro)?
Then, following the instructions to mapping your joystick using https://github.com/AntiMicro/antimicro/wiki/Adding-A-New-Game-Controller-Mapping-under-AntiMicro

At last, copy here the mapping string that you will find under the SDL2 Game Controller Mapping String field.

**Comment by adriansnetlis** [comment]
Your given link is to 15.10 and older. Since I'm on Xenial (16.04.3 LTS), I had to use ppa:mdeguzis/libregeek.

Anyways, this is the output:
`030000004c0500006802000011010000,PS3 Controller,platform:Linux,a:b14,b:b13,x:b15,y:b12,back:b0,start:b3,guide:b16,leftshoulder:b10,rightshoulder:b11,leftstick:b1,rightstick:b2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b8,righttrigger:b9,dpup:b4,dpleft:b7,dpdown:b6,dpright:b5,`

**Comment by lordloki** [comment]
It is strange as this mapping it is already included in our internal database.

Please, download this file (sdlgamecontrollerdb.txt) and put it under the same directory as blenderplayer. Don't rename the file.
https://mega.nz/#!hlFBTSTJ!JADrAkt_q7I0fs57YkO5Ky_ZdmThMGBgHZcy7ul2jsQ

**Comment by adriansnetlis** [comment]
Still not working...

**Comment by lordloki** [comment]
Could you paste the console output?

**Comment by adriansnetlis** [comment]
It doesn't output anything related to controllers or anything. Just the default stuff that it always prints (something related to color management when opening Blender, also Blender Game Engine started and Blender Game Engine finished). Printing joystick.connected (where joystick is a sensor) outputs False.

**Comment by adriansnetlis** [comment]
An idea quickly came in my mind - why don't I try to download the latest stable version of UPBGE and try if it works there? What I didn't expect tho, is that it would actually work. It detects the controller now. The console output: `Debug: Game Controller (PS3 Controller) with index 0 initialized` and `Debug: Game Controller (PS3 Controller) with index 0 closed`
Maybe I had to enable one of the `WITH_`s when building from source code?

**Comment by lordloki** [comment]
You should enable WITH_SDL when building from source code.
Anyway, I'm glad that it works for you.

**Comment by adriansnetlis** [comment]
OK! Thanks for info.
