### ISSUE TITLE
Bug with plane normals

### ISSUE THREAD

**Issue by Simi4** [UPBGE/blender#669]
Tested UPBGE Version: 0.2.3
Operating System: Windows 10 x64
Graphics Card/Driver: Intel(R) HD Graphics 4400 / 4.3.0 - Build 20.19.15.4642

Demo:
![8](https://user-images.githubusercontent.com/33279413/34738720-fac3cdb4-f58a-11e7-88bc-593f17136da0.png)
![9](https://user-images.githubusercontent.com/33279413/34738719-faa528a0-f58a-11e7-9e4a-c8df8cd22991.png)

File:
[untitled1.zip](https://github.com/UPBGE/blender/files/1616329/untitled1.zip)

**Comment by BluePrintRandom** [comment]
is scale applied?

the plane is upside down no?

**Comment by Simi4** [comment]
I attached blend-file to Issues
