### ISSUE TITLE
Feature request: Sort overlay/background scenes (like a layer system?)

### ISSUE THREAD

**Issue by Momel15** [UPBGE/blender#67]
Hey,

it would be great if there could be an actuator/Python command to sort overlay scenes. It could work like the states/layer system.

Is that possible?

**Comment by panzergame** [comment]
@Momel15: can you propose an API ?

**Comment by Momel15** [comment]
Maybe something like `scene.setLayer = 2`? It would be great if you could also add it to the scene actuator, maybe like the animation layer at the animation actuator.

I don't know if that could work because I don't know how the bge renders/calculates the scenes. You have probably better ideas for that.

**Comment by pqftgs** [comment]
As scenes must be rendered sequentially, I think a good approach is `scene.shift_up()` or something similar.  A quick look of the codebase didn't show scenes being accessed by list position, so I think this should be safe.  Just as long as the memory address remains un-changed.

**Comment by panzergame** [comment]
Why not "scene.layer = 0" ?
If two scenes are on the same layer one of it is not rendered, the user have to know that.
During the render stage we will just iterate on all scene and find the one which layer 0, 2, 3, ....

**Comment by DCubix** [comment]
"If two scenes are on the same layer one of it is not rendered"
We would have this problem (each image in the GIF is a scene): 
![output_v0rvza](https://cloud.githubusercontent.com/assets/5081992/13996035/52bc0f16-f102-11e5-941d-826d273ca7c6.gif)

**Comment by pqftgs** [comment]
In my opinion the layer approach is too quirky.  Typical layers in blender use all members of the selected layer, not just 1 undetermined element.

I definitely think move up/down is the best/cleanest method - especially since most games only have 1-3 active scenes.  Yet this also allows sorting arbitrary scenes, as opposed to layers that are limited by the UI.

2nd choice is to give scenes a priority value.  Those with the same priority would be rendered from oldest -> newest.

Now if you excuse me, I'm going to have a seizure.

**Comment by panzergame** [comment]
What about using a second list writeable e.g bge.logic.getSceneLayerList() :
[0, 2, 1]
For 3 scenes, in order first, third and second.

So currently we have two system:
- priority system with scene.layer/priority
- list system with bge.logic.getSceneLayerList()

@Momel15, @pqftgs, @DCubix, @youle31   : What's the best ?

**Comment by panzergame** [comment]
~2 months without answer, i considerate this as a dead project then.

**Comment by Momel15** [comment]
> @Momel15, @pqftgs, @DCubix, @youle31 : What's the best ?

Sorry for my very, very late answer on this issue, but I thought that one of the addressed developers would suggest a good solution because I don't know much about how Blender works "behind the scenes" (I'm not sure if you can say this in English^^)  and I think that you have a better knowledge of things so you could decide better.

But because I saw the note on the http://developer.upbge.org/ page, I decided to reopen this issue (if that's ok for you) and add my two cents.

I think that both systems are good, so you could decide which one is easier to implement. Actually they are not that different as far as I understood. I wrote this issue because I wanted to ensure that e.g. a scene that contains a mouse cursor can always stay on top, even if another scene is added later.
