### ISSUE TITLE
Bug: maybe related to GlobalDict

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#670]
http://pasteall.org/blend/index.php?id=48711

steps: try to select units (blue triangles) doing a rectangle with the mouse -> python script issue.

I'll complete the bug report later

**Comment by youle31** [comment]
between 0.2.0 and 0.2.1

**Comment by youle31** [comment]
first bad commit 766896053c90cdf012aeb8701d707fdddaf54e15 I'll try find more infos

**Comment by youle31** [comment]
the commit and the test file are too complex, let's just forget this for now

**Comment by panzergame** [comment]
Bisect commit confirmed.

**Comment by panzergame** [comment]
Because every meshes are now using the same structures and that every polygons are now triangles for optimization and homogeneous reason, script assuming a polygon to have 4 vertices are wrong and was really unsafe before.

The script in the file is doing:
```python
            ...
            vert_length = poly.getNumVertex()
            
            for v in range(vert_length):
                index = poly.getVertexIndex(v)
                
                vertex = mesh.getVertex(0, index)
                
                xyz_pos = vertex.getXYZ()
                
                point = get_point(vertex.getXYZ(),obstacle.worldTransform)
                                
                poly_points.append(point)
            
            obstacle_check_list.append(poly_points) 
            
        #obstacle.endObject()     
     
    
    ### check points and place a cross if inside  
        
    for x in range(own["resolution"]):
        for y in range (own["resolution"]):
            
            
            ### change spacing for larger or smaller grid,
            ### the grid size is not important for the check
            
            spacing = own["scale"]
            
            point = mathutils.Vector([x*spacing,y*spacing,1.0])           
            
            blocked = check_point_inside(point,obstacle_check_list)   
```

And `check_point_inside`is 
```python
def check_point_inside(point,areas):

    blocked = False
    
    for area in areas: 
        if not blocked:           
        
            quad_p1 = area[0]
            quad_p2 = area[1]
            quad_p3 = area[2]
            quad_p4 = area[3]
```

`quad_p4` is impossible to initialize.

**Comment by youle31** [comment]
Ok thanks very much for your explainations. This file seems to work: http://pasteall.org/blend/index.php?id=50319

Then each time we do a loop with polygons we have to consider that each poly is a triangle, then in my file I had to use mathutils.geometry.intersect_point_tri_2d (with triangles) instead of mathutils.geometry.intersect_point_quad_2d (with quads).

This is a little backward compatibility issue, i don't know if you want to add something in the documentation.
