### ISSUE TITLE
[Suggestion] UPBGE release builds for AUR

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#675]
Hi!
I recently switched to Arch Linux and I'm really liking it. I especially enjoy the great application management provided by yaourt. I, however, still had to download UPBGE manually. This is not as convincing. I think it would be great if UPBGE Arch Linux builds were available at AUR. What do you think about this idea?

**Comment by lordloki** [comment]
Sorry @adriansnetlis, at this moment we don't have so much development power to make a UPBGE Arch linux build.
