### ISSUE TITLE
Collision bounds are wrong when origin is not in geometry center

### ISSUE THREAD

**Issue by vlad1777d** [UPBGE/blender#678]
Hello.

Collision bounds of any object are wrong if it's origin is not at it's geometry center.
This screenshot demonstrates one of such examples:
![screenshot from 2018-02-24 23-21-40](https://user-images.githubusercontent.com/12682937/36635219-eff55b34-19b9-11e8-8c5d-4a0b39b36fc6.png)

Cases when you can meet need not to place origin into geometry center:
- grass, character, house (to place it on the ground right)
- any objects which need to be rotated around certain point,
- etc.

Suggestion: calculate object's center depending on it's geometry center and place collision bounds' geometric center right to object's.

Best regards,
Vladislav.

**Comment by joelgomes1994** [comment]
You could simply parent the visual mesh object to an invisible collision mesh object, each object with its own purposes. The collision bounds at the object's origin has never been a problem to me using this method.

And, if I'm not wrong, this change would need to be made on Blender's source code, and UPBGE team is allowed to change only the BGE's source code.

**Comment by vlad1777d** [comment]
@joelgomes1994 , thank you, I already did so.
But this refers to game engine, so I don't think, it's the reason not to correct it =)

**Comment by justinbarrett** [comment]
well, it is the intended behavior so there is nothing to correct...this would maybe fall under an improvement or feature request...

BUT I do think it would be nice to be able to adjust the min max bounds via slider...and the ability to center it....but it is not necessary...just if someone feels inclined :)

**Comment by vlad1777d** [comment]
@justinbarrett , as for me, I think that object bounds must, at least, more-less match with object, not to take only half of object. It doesn't match - bug =)

Agree with all other.

**Comment by justinbarrett** [comment]
No, it is not a bug....

ctrl + alt + shift + c   
select origin to geometry....this will center it....it is based on the geometry bounds and centered on the orgin

**Comment by vlad1777d** [comment]
@justinbarrett , I don't need origin to be in center of geometry.
Such things, like characters, grass and all stuff which is placed automatically must have origin in it's lower point, which will be placed on ground.

**Comment by panzergame** [comment]
The collision box of bullet supports as parameters only a half extend vector, which mean that the center of the body is also the center of the box.

The easiest way to fix it might be to use a compound parent object with an empty shape at the correct center.

**Comment by vlad1777d** [comment]
@panzergame, thank you, used cube with "convex hull" bounds for this.

I just thought, that calculating object center by origin is not very good idea, so I thought, that game engine could use calculated geometry center instead of it.

**Comment by panzergame** [comment]
Origin is useful for mass center and so we will not automatically compute it.
