### ISSUE TITLE
Added object time weirdness

### ISSUE THREAD

**Issue by pqftgs** [UPBGE/blender#68]
The time argument for scene.addObject is advertised as frames, but then converted to "sort-of" seconds (hard coded at 50fps...) resulting in unexpected behavior.

Solution 1:
Make it count frames instead.  Easy & keeps old stuff compatible.

Solution 2:
Make it accept time (in seconds) as the argument, and decrement based on the time scale.  Superior behavior but breaks compatibility.

**Comment by panzergame** [comment]
Solution 3:
Make it count frames by time from last frame.

**Comment by panzergame** [comment]
The documentation i now fiwed and later it will possible to pass a half 1/50 frame.
