### ISSUE TITLE
Security issue imposed by python components

### ISSUE THREAD

**Issue by organicpencil** [UPBGE/blender#682]
Malicious users can auto-run scripts before you get a chance to look at the code, even with the "auto-run scripts" setting disabled. Until this gets resolved I would NOT open blends from untrusted sources without first reviewing it from an older version of blender.

@panzergame @DCubix

**Comment by vlad1777d** [comment]
@organicpencil , you want to say, that they can write "bad" code inside of python component definition, which will be runned when Blender will read .blend file, right ?

**Comment by organicpencil** [comment]
@vlad1777d correct

Full steps to replicate:
1) Add a component to an object
2) Save
3) Add the malicious code then save again
4) Next time the file is loaded (or module reloaded) the bad code will run

Example component:
```
import bge
from collections import OrderedDict

### Bad code
import sys
sys.exit(0)
###

class ThirdPerson(bge.types.KX_PythonComponent):
    """Basic third person controls

    W: move forward
    A: turn left
    S: move backward
    D: turn right

    """

    args = OrderedDict([
        ("Move Speed", 0.1),
        ("Turn Speed", 0.04)
    ])

    def start(self, args):
        self.move_speed = args['Move Speed']
        self.turn_speed = args['Turn Speed']

    def update(self):
        keyboard = bge.logic.keyboard.events

        move = 0
        rotate = 0

        if keyboard[bge.events.WKEY]:
            move += self.move_speed
        if keyboard[bge.events.SKEY]:
            move -= self.move_speed

        if keyboard[bge.events.AKEY]:
            rotate += self.turn_speed
        if keyboard[bge.events.DKEY]:
            rotate -= self.turn_speed

        self.object.applyMovement((0, move, 0), True)
        self.object.applyRotation((0, 0, rotate), True)
```

**Comment by BluePrintRandom** [comment]
we just need to have the default behavior not to run the components, and to
ask permission instead like py modules.

**Comment by Anarchokawaii** [comment]
So what does python component mean in this context?

**Comment by BluePrintRandom** [comment]
@panzergame  - can we add a switch to run components or not/maybe a way to expose all components / check yes/no one at a time?

**Comment by panzergame** [comment]
It looks like the WITH_PYTHON_SECURITY option was designed for the same issue for blender scripts, I never experimented it.

If someone want to experiment something I will review it.

**Comment by lordloki** [comment]
component enable/disable as per python script is committed in master

**Comment by panzergame** [comment]
Thank you

**Comment by BluePrintRandom** [comment]
Thank you!

**Comment by vlad1777d** [comment]
Sorry, didn't got it, how was it fixed ?)

**Comment by lordloki** [comment]
The same option to disable python scripts now disable python components too. This option is off by default but the user can set ON and save user preferences
