### ISSUE TITLE
Save file in UPBGE, then open it in blender, then press "P" to play but...

### ISSUE THREAD

**Issue by rickyteng** [UPBGE/blender#686]
I try to make game logic in UPBGE, then use blender to make scene.

After I save file in UPBGE(UPBGEv0.2.3b2.79Windows64) then open it in blender(2.79b), it seems game engine is not working. Everything is freezed.

The same file is working in UPBGE.

[createByUPBGE.zip](https://github.com/UPBGE/blender/files/1918087/createByUPBGE.zip)

**Comment by BluePrintRandom** [comment]
upbge have different sensor and structures

do you use a motion sensor logic brick?

**Comment by rickyteng** [comment]
OK, I understand.

Story is :
I use UPBGE, my frend use blender.
I just send my blender file to my friend, ask him to play.

Thanks your reply.
