### ISSUE TITLE
Wire materials rendering bug

### ISSUE THREAD

**Issue by Anarchokawaii** [UPBGE/blender#690]
![bug1](https://user-images.githubusercontent.com/16331212/39399233-e24adebc-4adf-11e8-889f-84ed90fa4b45.JPG)
![bug2](https://user-images.githubusercontent.com/16331212/39399234-e25cbd62-4adf-11e8-9c90-d1954eb63070.JPG)
![bug3](https://user-images.githubusercontent.com/16331212/39399235-e2712d60-4adf-11e8-8d34-97237cd10ba0.JPG)

here we  have a triangle rendering behind another one,

**Comment by BluePrintRandom** [comment]
Is this this way in bf blender as well?

**Comment by Anarchokawaii** [comment]
by bf blender i am assuming you mean regular blender. i havn't tried it yet but here it is.
![inbfblender](https://user-images.githubusercontent.com/16331212/39399976-0bb145cc-4aed-11e8-9fb5-cf37f5ba8240.JPG)
![inbfblender1](https://user-images.githubusercontent.com/16331212/39399977-0bc322ec-4aed-11e8-90dd-0fd760900cd3.JPG)

**Comment by adriansnetlis** [comment]
I think some sort of culling has to do this. I doubt there is this perfect occlusion culling that culls individual faces in BGE so I'd be it's backface culling doing that. Try disabling it and see what difference it makes.

**Comment by Anarchokawaii** [comment]
i turned backface culling on and off and it didn't do anything. i think it's this specific line that it's having trouble with. i added the line in and selected it to show you. 
![thisline1](https://user-images.githubusercontent.com/16331212/39409924-7f0aff6e-4bb4-11e8-9b0d-9e4e0424f89a.JPG)
![thisline2](https://user-images.githubusercontent.com/16331212/39409925-7f1eaea6-4bb4-11e8-81ba-acfcb9271e28.JPG)

**Comment by panzergame** [comment]
Could you please provide an example file ?

With this test file all the wires of the cylinder and the sphere are visible.
http://pasteall.org/blend/index.php?id=49579

**Comment by Anarchokawaii** [comment]
here ya go http://pasteall.org/blend/index.php?id=49621

**Comment by panzergame** [comment]
Ok, there's some misunderstanding…

First the wire render (pressing Z) is not the same as wire materials (wire mode in material panel). Wire materials respect the edges of the polygons contrary to the wire render which just draw only triangles as for solid render but with lines (indeed it's just an OpenGL settings).
Second the material backface culling settings always override the backface culling setting in the viewport, at the end only the materials settings are used, in your file the material is using backface culling.

To summarize it's not a bug.
