### ISSUE TITLE
opencl bullet

### ISSUE THREAD

**Issue by lostscience** [UPBGE/blender#7]
Are you going to try to impliment opencl bullet?It would be a nice feature to have.

**Comment by youle31** [comment]
Hi, This feature could be integrate when Blender will upgrade to bullet 3 in a few years but this is not for now. Bullet code is very complex and we don't change it/neither any Blender developper I think (until its integration in Blender). The bullet code is made externally to Blender so you can consider it as an external library that we use without changing it. So I close the request :)
