### ISSUE TITLE
Control additional repositories

### ISSUE THREAD

**Issue by lordloki** [UPBGE/blender#704]
Currently, I have 2 issues:
- Blender lib repository: I have to use SDL lib > 2.0.6 for new SDL controller format
- Blender add-ons repository: I want to modify game_engine_publishing.py to include new features

Then, the possible solutions:
- Using our own lib and add-ons repositories: 
   - Pros: we can customize them to our necessity
   - Cons: we have to sync them every release

- Take control outside the repositories and make each developer aware of the tricks to be done before releasing a new release (i.e. copy modified addon to the corresponding folder, compile with the necessary library instead of the one in lib/, etc).

What do you think?

**Comment by panzergame** [comment]
It is fine to use separated repository, just take care of rebasing frequently. About the addons we can target it in the UPBGE repo, for the library just add it in the build documentation.

**Comment by supermoaaa** [comment]
i think for the first solution for the addons is great. Perhaps you can make a news section on website
download page for the addons ?  
and a download option in user preferences of UPBGE .

I can improve and update my addon 
https://blenderartists.org/t/add-character-addon/698877/9

if you want have a frist addon

for the lib i don't know

**Comment by panzergame** [comment]
@supermoaaa : Do you have a good experience in blender addons ?

**Comment by supermoaaa** [comment]
no it's my first addon but i have a big experience of python bge code and I learn for have one in addons

if you want to remember how i am, I'm moaaa in blenderclan:

http://blenderclan.tuxfamily.org/html/modules/newbb/viewtopic.php?topic_id=43707&viewmode=flat&order=ASC&start=0

**Comment by lordloki** [comment]
OK, 
addons repository created and pointed from upbge-blender repository.
Lib modifications noted on wiki windows/linux build instructions.
