### ISSUE TITLE
Alpha Hashing for Discard Transparency

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#712]
Alpha hashing is a method that uses alpha clipping with dithering to create illusion of semi-transparent objects. When combined with multisampling and/or TAA, it can create pretty solid looking smoothing for foliage and similar stuff. At the same time, it's based on discarding parts of mesh from rendering like alpha clip.

**Comment by DCubix** [comment]
But this is UPBGE man :stuck_out_tongue:

**Comment by adriansnetlis** [comment]
Crap that's what happens when you don't look where you post :D UPBGE would benefit from this too.
