### ISSUE TITLE
Can anyone tell me what is wrong with this component that i can't use it?

### ISSUE THREAD

**Issue by Anarchokawaii** [UPBGE/blender#713]
i tried loading this component i wrote

```
import bge
from pathlib import Path
from collections import OrderedDict

class FileLoader(bge.types.KX_PythonComponent):
    args = ([
        ("foo","foo"),
        ("bar","bar"),
        ("baz","baz")
    ])
    
	def start(self,args):
        cw = Path(blender.expandPath("//"))
        with cw/"Land.vs" as LandDOTvs:
            landvs = LandDOTvs.read()
        print(landvs)
    def update(self):
        pass
```

but every time i try to add it i get "no module named FileLoader or script error at loading". i have a .py at the end of my file. it worked with the example component given [here](https://twisterge.blogspot.com/2017/09/the-basics-of-upbges-python-components.html). it's not a bug i don't think. im just not sure what i am doing.

**Comment by panzergame** [comment]
Did you look at the console for more information about python errors ?

**Comment by panzergame** [comment]
Also for args there's no OrderedDict instantiation.

**Comment by Anarchokawaii** [comment]
okay i got it. inconsistent use of tabs and spaces so i clicked the "convert whitespace to tabs" button. you can close this now.
