### ISSUE TITLE
Windows build error (Visual Studio 2015)

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#722]
![image](https://user-images.githubusercontent.com/19820741/42013108-0ce76c28-7a72-11e8-8151-d05e11894a35.png)

When reverting the commit 11be475ef855b3bc23cfea4bde95b023324130bb the compilation is successfull.

**Comment by youle31** [comment]
I'll look at that. Just few things to do before

**Comment by youle31** [comment]
@joelgomes1994 : I have no error but I compile with Visual studio 2017 and win 64 libs. I removed 32 bit libs because BF will probably drop 32 bits support. Looks like an alignment error in 32 bits. Can you try to compile in 64?

**Comment by youle31** [comment]
I have no compilation error with VS 2017 and 32 bits libs but the cube is not rendered... That's another issue

ensure you are on master:

git checkout master

Then ensure all is up to date:

cd lib\win64_vc14
svn update
cd ..\..\
cd lib\windows_vc14
svn update
cd ..\..\upbgeSources
git pull --rebase
git submodule foreach git pull --rebase origin master

then compile from scratch. I'll check for the not rendered cube

**Comment by youle31** [comment]
@joelgomes1994 : I think this is bzztploink (Ray Molenkamp or a name like that) who maintains libraries. He proposed to drop 32 bits support because there will be less work for him (and for other reasons), but they'll maybe wait the final 2.7 build to be published to do that, unless there is a strong argument to keep 32 bit libs in 2.8. But one day or another, you'll have to download 64 bits libs I guess, so... The only problem is for the ones who don't have a computer with X64 architecture support

**Comment by lordloki** [comment]
I confirm that no cube is rendered with win32 compilation although I have no warning with alignment related.

**Comment by panzergame** [comment]
Sorry, I forgotten that MSVC is not managing argument stack alignment, to fix this issue the function SetViewMatrix must receive a const reference and do a copy internally.

**Comment by joelgomes1994** [comment]
No errors on x64 build, but it's still giving errors on x86 build. Close this issue or will this be fixed?

**Comment by joelgomes1994** [comment]
![build_error_x86](https://user-images.githubusercontent.com/19820741/42334089-cf46b900-8052-11e8-8019-0c7aff5b4624.png)

Again, an issue only to x86 build on latest master, the x64 build is ok.

**Comment by lordloki** [comment]
You have to run CMake again and sets WITH_SYSTEM_OPENJPEG to ON

**Comment by joelgomes1994** [comment]
My bad, I deleted all the files and generated all build files again, now it builds with no errors, at least for the x64, i'm finishing the x86 build right now. Sorry for the false positive, I'll close the issue again when the x86 build ends successfully.

**Comment by joelgomes1994** [comment]
Build successfully at both x86 and x64, but the issue with the x86 at #797 persists. Closing current issue.
