### ISSUE TITLE
Spherical Area Light Fall-Off Attenuation

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#728]
So currently this is how inverse squared calculation looks:
`attenuation = 1.0 / pow(distance / the_distance_number_in_light_settings, 2);` (it may look a bit different, but that's the math.
However, this does not provide the best results possible. Real lights have radius.
Sourcing for this(https://imdoingitwrong.wordpress.com/2011/01/31/light-attenuation/), you can calculate spherical area light attenuation by this calculation:
`attenuation = 1.0 / pow(distance / radius + 1.0, 2);`
If one wanted to keep the distance setting, radius can be multiplied by the distance number in light settings. 
This is not very costly calculation by itself, however, the source provides even additional optimizations for deferred rendering.

Now adding "radius" option in light settings and switching to this equation could provide pretty nice results.

**Comment by panzergame** [comment]
Thanks for the detailed report, I leave it to new developer to get experience:
The fragment shader `source/blender/gpu/shaders/gpu_shader_material.glsl`need to be modified by adding a new attenuation function and a check added in gpu_material.c to select it.

**Comment by lordloki** [comment]
This was already implemented by @DCubix in the ge_brdf branch (https://github.com/UPBGE/blender/commit/eb97104d06e965239e42129dcb2536491c65f28e#diff-cd270f0456f47fde6ee278bee899bdb7R1810). Maybe we can commit it to master.
I will test it.

**Comment by lordloki** [comment]
committed in master. Thanks for testing and proposal
