### ISSUE TITLE
Navmesh Clear Data: Blender stop responding.

### ISSUE THREAD

**Issue by UnidayStudio** [UPBGE/blender#746]
It crashes if you click on "NavMesh Clear Data" and press P to play. To fix, you've to reset index values again.

I already pressed Clear Data. So just press P and enjoy it stop responding. :)

Blend file:
http://pasteall.org/blend/index.php?id=49940

**Comment by panzergame** [comment]
Bug confirmed.

**Comment by lordloki** [comment]
Closing. Fixed in master. Thanks for reporting.
