### ISSUE TITLE
Libload crashes instantly

### ISSUE THREAD

**Issue by Cotaks** [UPBGE/blender#751]
```py
from bge import logic

def load(cont):
    
    own = cont.owner

    path        = logic.expandPath('//asset_0.blend')
    load        = logic.LibLoad(path,'Scene', async=True)

    load.onFinish = next_frame


def next_frame(status):

    print(status.timeTaken)
```

blend: [libload crashes.zip](https://github.com/UPBGE/blender/files/2198805/libload.crashes.zip)

**Comment by panzergame** [comment]
Hello, you are missing the file "asset_0.blend" in your packet.

**Comment by Cotaks** [comment]
Oh sorry, you can grab a basic startup blend and use that or here it is with the asset.

[libload_crashes_2.zip](https://github.com/UPBGE/blender/files/2199157/libload_crashes_2.zip)

it's about upbge 0.2.3 hash fb9d84f

**Comment by panzergame** [comment]
@Cotaks : Could you provide informations about your OS and hardware ?
I tried your example and everything worked fine, I checked with a debug build and valgrind and didn't catch any memory violation.

**Comment by Cotaks** [comment]
using the build from here: https://blenderartists.org/t/latest-upbge/1118398/2
as soon as i hit p upbge shutsdown.

Windows 10 Pro 64 Bit(all updates).
rx 470 nitro+ oc 4 GB
16GB Ram
ryzen 5 1600 (stock)
HDD x2 seagate baracuda 2T
SSD samsung 850 evo

runs from a HDD

**Comment by Momel15** [comment]
Tested it on my machine and it worked using the BA build. No error or warning at all

Windows 8.1 64 Bit
Nvidia Geforce GTX 750Ti
Intel i5

But most of the time the blend doesn't get loaded (there is no cube). Sometimes it works, sometimes not...

**Comment by Cotaks** [comment]
@panzergame 

Here is my proof: https://youtu.be/ovA3AUHbK5M

First my project in blender itself( it works like this: main blend libloads a level, that level.blend libloads assets), then the uploaded file, then trying in upbge.

Before you say, you made the .blend with official not with upbge, true, but i also created 2 new blend to test it (the uploaded files are created in upbge)

**Comment by panzergame** [comment]
The last commit is delaying the component creation at the merging stage and should fix the python threading issue.
