### ISSUE TITLE
Interface Cleanup and Improvements

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#756]
Hello! Here's a proposal to remove some useless stuff from UPBGE's interface and improve the current one.

- **Info** editor
   - Rename renderer from *Blender Game* to *UPBGE*
- **3D View** editor
   - **Add** context menu
      - Remove non-compatible objects from menu, like **Speaker, Force Fields**, etc *(only for *UPBGE* renderer, don't know if it's possible)*
- **Properties** Editor
   - **Scene** tab
      - Remove **Keying Sets** panel *(hardly would apply to game dev process)*
      - Remove **Audio** panel *(don't affects GE)*

There's a chance of some of those features being useful on GE and I don't know how (like the **Color Management** / **Color Space** stuff), but I'm sure the remaining aren't useful (like the **Audio** panel, only working in **Blender Render**).

Thanks. :smile:

**Comment by adriansnetlis** [comment]
Bake panel is often used for quick AO or normal baking (although I more often bake AO in Cycles), removing it makes no sense.
Color management, instead of being removed, should work for GE (being able to switch between sRGB and Linear or even using built-in Filmic tonemap is always a good thing).

Color space for images matters even in game engine. Like you want to set that to Linear for normalmaps, roughness maps, metallness maps etc. Makes difference and can fix things that would appear broken otherwise.

**Comment by UnidayStudio** [comment]
I liked the idea to remove things that don't work in BGE and change from Blender Game to UPBGE. But I also think that we should try to make some of the things that don't work to work (Idk if english works this way, but you get the point): The Speaker object (The Converter should convert them into an empty with a sound component, or something like this), Color Management (yeah, It will be great to see this working) and Audio. I also use Bake very often to get information from the high poly versions of my models.

**Comment by joelgomes1994** [comment]
@adriansnetlis Thanks for the remarks, it's a proposal of removing useless features in GE, so I will update the top post according to the replies. Nice to know about the color management (although I didn't noticed changes in GE).

@UnidayStudio Although I agree implementing those features (specially a functional Audio panel), I think they don't fit in a 'cleanup' issue, which aims to be easy and fast to implement (to remove stuff?). However, it would be redundant to use an Speaker object, as any object type can be a sound source in 3D space. The idea is to cleanup interface to avoid useless features to be accessed, even if it means to remove the useless features and then add them again once they are implemented in GE.

**Comment by panzergame** [comment]
About the add context, lattice is still used to mesh construction.
