### ISSUE TITLE
TTS lib - Native support

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#757]
https://techcrunch.com/2017/12/19/googles-tacotron-2-simplifies-the-process-of-teaching-an-ai-to-speak/

is there any way we could absorb tacotron2 as a included lib in upbge?

I need it for B_pecs - The TTS in proloque2go sounds robotic and grainy.(my daughter uses it to speak)

I also think with the right training model - it could produce thousands of voices for game  actors.
(so it could do anything from Cortana type tasks in games / narration to helping kids talk)

(so a large game could have a tiny file size apart from the training data)

maybe we try in a branch?

I have a intel Atom X64 tablet on the way for testing.

I don't think I can just pip install it and call it- do to memory space w/py and tensorflow.

**Comment by marechal-p** [comment]
https://pypi.org/search/?q=tts

Also from what I am reading, tacotron implementations are highly experimental as of today.

It is also the kind of service that can run on the side, so the best prototype would be just that: a separate process with some i/o interface to command the text-to-speech functions.

As this is also a very niche issue, I would suggest you to hack at it if it is your area of interest :)

**Comment by BluePrintRandom** [comment]
well, we have audaspace module - sound api - which is nice

but with tacotron + py + shape keys + dialog = games with very in depth story telling without
a huge animation overhead.

I think it should be experimental, and then if favorable merged.
(the source is open no?)

**Comment by marechal-p** [comment]
What sources then ?

**Comment by lordloki** [comment]
@BluePrintRandom I marked as a feature with low priority and to be opened later.
I am also interested in TTS as Indie games lacks of translations and voices.
Meanwhile I close it.
