### ISSUE TITLE
Get all lighttypes?

### ISSUE THREAD

**Issue by Maujoe** [UPBGE/blender#76]
At the moment you can only get the light type of spot-, sun- and pointlamps but I know that HG1 has made a patch to get the other lightypes (hemi). 
I don't know how to compile patches for testing and there is also the question whether it's better to break compatibility or not see post #17: [http://blenderartists.org/forum/showthread.php?389535-Light-shader-GLSL](url)

Maybe that is interessting for upbge (also BF bge) and it would be helpful for custom shaders that use lamps because at the moment I must give every lamp a property with the lamp type manually.

**Comment by panzergame** [comment]
@Maujoe : Just access to the Hemi lamp type ?

**Comment by Maujoe** [comment]
yes, at the moment area and hemi lights will be returned as pointlights (type: 2) and as long area lights are not implemented they are not needed but without acces to hemi light the type function is a little bit uncompleted in my opinion.

**Comment by panzergame** [comment]
Done in 4a9c6ca916d7e0c8d22b22130040812b68182b1c
