### ISSUE TITLE
Update shader uniforms automatically (predefined functions for lightdata)?

### ISSUE THREAD

**Issue by Maujoe** [UPBGE/blender#77]
Hey,

I often use custom shaders in the bge and I notice that it costs some performance (logic) if you must update uniform every times for example when I use lamps I have to update the lamp orientation and the position every frame for every custom shadermaterial. So in my opinion it would be nice when this uniforms could be updated automatically by the engine because I think it would be faster than to make it in python (?). Maybe you could add predefined functions for lightposition and orientation to the setUniformDef() function?

**Comment by youle31** [comment]
Maujoe: you can use gl_LightSource[i].position, gl_LightSource[i].diffuse and some other attributes (all attributes aren't supported by Blender and the position is a little bit inaccurate but I don't know how to fix that for the moment)

**Comment by Maujoe** [comment]
Yes that's right but that only seems to work for 8 lamps so far I test it. I think everything higher than gl_LightSource[7]. give you an error ("error C1068: array index out of bounds"), maybe the predefined array has an limit of 8.

**Comment by Jay-Parker** [comment]
Correct me if I'm wrong, but doesn't GLSL throw up errors if you don't use all the uniforms passed to a shader. If so, a predefined function would only be useful for those trying to replicate blender's shader code or something similar.

**Comment by Maujoe** [comment]
Yes, thats right but with predefined function I mean more something like setUniformDef() than gl_LightSource[i] so that we only pass uniforms that we need one time to a shader and then they will be automatically updated. The glsl code for uniforms must be added by the user depending on which uniforms he want to use.

For example when I use setUniformDef("timer", bge.logic.CONSTANT_TIMER) one time when I create the shader the timer will updated without that I must passed it every frame manually.
[http://bgepython.tutorialsforblender3d.com/Shader/setUniformDef](url)

But it's only an idea .

**Comment by panzergame** [comment]
> setUnifromDef("lamp", BL_Shader.LAMP_UNIFORM, sce.objects["Lamp"])

Where "lamp" is inthe shader :

> struct lamp {
>     int type;
>     vec3 position;
>     vec3 color;
>     float distance;
> }

The struct can be shorter e.g :

> struct lamp {
>    vec3 color;
> }

@Maujoe, @youle31  This looks fine to you ?

**Comment by panzergame** [comment]
Talking about the internal sources the inheritance will look like:
BL_UniformDef :
---------------------- BL_LampUniformDef
---------------------- BL_ObjectUniformDef
---------------------- BL_CameraUniformDef

**Comment by Maujoe** [comment]
Yeah,  thats looks good. I also use struct at the moment. Sorry maybe thats what you meant but would it also allow mutiple lamps in one struct? I'm not sure but I think it would make things easier.

For example we have 16 lamps:
uniform struct lamp
{
	int type;
        vec3 position;
	float distance;
	vec3 color;
        ....
} light[16]; 

So we can interate over the lamps also with a for loop like light[index].type...

**Comment by panzergame** [comment]
>setUnifromDef("lamp[0]", BL_Shader.LAMP_UNIFORM, sce.objects["Lamp0"])
>setUnifromDef("lamp[1]", BL_Shader.LAMP_UNIFORM, sce.objects["Lamp1"])
>setUnifromDef("lamp[15]", BL_Shader.LAMP_UNIFORM, sce.objects["Lamp15"])

**Comment by youle31** [comment]
Why not? But I don't know how to code that in the sources.

And what attributes will contain Light struct, Camera struct, Object struct? 

@Maujoe, what do you think about?
Did you make performance tests to see exactly what was the source of the slow down (is it the fact to pass 3 floats to the shader? Or is the shader slower because the light moves? Do you have a performances test file that show the impact of binding uniforms in python each frame?

@panzergame: for active_camera (current view), we have already an API: http://bgepython.tutorialsforblender3d.com/Shader/setUniformDef
But this doesn't prevent to make a new API for several cameras if needed.

**Comment by Maujoe** [comment]
All in all the performance is still okay but in my opinion the logic use is too high only for recreating the blender material (depending on the amount of custom shaders and lamps). Maybe I'm wrong and integrated function don't help much or are unnecessary.

But I have made a little example, how you can see I only update the position and orientation of the lamps every frame (material, mist , light properties will only update once at the beginning)

You can also deaktivate the pulse mode of the shader an attach the last module controller, it's a update function thats update the uniforms directly from a shaderlist to save time because there are less for loops.
[example.zip](https://github.com/UPBGE/blender/files/198725/example.zip)

**Comment by youle31** [comment]
Thanks for the example. I slightly modified it to make our performance tests easier: http://www.pasteall.org/blend/41276

**Comment by Maujoe** [comment]
Okay, hope thats helps. 
One note to your modification for more acurate performence tests, you can deaktivate pulse mode for the "shader.main" controller as long you don't update uniforms with the shader.main function.
