### ISSUE TITLE
Bone.worldTransform 

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#773]
Right now to get a bones world orientation is kinda complex.

May we add Bone.worldTransform?

**Comment by panzergame** [comment]
What are you using currently ?

**Comment by BluePrintRandom** [comment]
ok, I just found that it's not as complex as I once thought

the bones orientation is relative to it's armature origin apparently

I thought each bones orientation was relative to it's parents transform.
[which would make things a bit more complex in long chains]

but I was wrong!!

I will close this unless anyone could chime in any other advantages.
