### ISSUE TITLE
How far from OpenGL_ES compatibility is UPBGE now?

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#78]
How far from OpenGL_ES compatible is UPBGE now?

What all needs to be done to have a android blender player?

Thank you.

**Comment by panzergame** [comment]
Pretty far, because we need to rewrite a lot of things in non-BGE code and fix builtin shader value like gl_Color.

**Comment by BluePrintRandom** [comment]
after a few releases can updating the render/rasterizer etc to use modern GLSL be a priority?

is there any way to have a 'legacy mode' (for people on older GPU?) and a modern mode?
(keep existing drawing mode but socket it?)

Should I look for a android Developer to invite to the team?
