### ISSUE TITLE
Make: 'copysign': macro redefinition

### ISSUE THREAD

**Issue by Samusoidal** [UPBGE/blender#780]
![command prompt](https://user-images.githubusercontent.com/28611086/43842629-a3235750-9ada-11e8-951f-a89d74c36e76.jpg)
I am trying to build UPBGE for the first time and I get the above message. I have downloaded the sources and my repo is up to date with this one.  
Is there anything else I should be doing to make sure this goes through?

Sorry, I'm pretty new to building apps on Windows.

**Comment by panzergame** [comment]
Are you sure that there's no error message before ? The one you reported is a warning only.

**Comment by lordloki** [comment]
It is a issue with msvc2015 compiler only. We are trying to get a solution valid for all compilers.
Meanwhile, in that line you can replace __func__ by "" to continue compiling.
