### ISSUE TITLE
some errors on windows 10 64bit

### ISSUE THREAD

**Issue by RomStef** [UPBGE/blender#785]
Hi , i have compiled upBGE for windows without errors but when i use it ,  sometimes return me this error

![dll_error](https://user-images.githubusercontent.com/20901566/43956882-1ab9618e-9ca6-11e8-9766-ffc6de0c4ee8.PNG)

Sometimes i click on ignore and the program continue to work but somtimes the program crash without reason.

using the  overlap function of BVHTree without collision , the program return this error in console :
![mathutils_error](https://user-images.githubusercontent.com/20901566/43957079-d2d5ae3a-9ca6-11e8-81d2-45a72e3d2335.PNG)

using the xml library , the program return this error in console :
![xml_error](https://user-images.githubusercontent.com/20901566/43957166-23b73fee-9ca7-11e8-9010-b3135ed67f1e.PNG)

Opening another test file (saved with the 0.2.3 stable of upbge), in the splash screen and when i start the blenderPlayer , the program return me this error :

![runtime_error](https://user-images.githubusercontent.com/20901566/43957308-b2534720-9ca7-11e8-9124-56c40da5ad55.PNG)

I have follow the steps on wiki and the command i have used for the compilation is "make full x64 2017" because i have installed visual studio2017.

https://wiki.blender.org/wiki/Building_Blender/Windows

Thanks in advance

**Comment by lordloki** [comment]
I will check it:
1- Have you compile with Debug option?
2- I will investigate in the other issue that you have opened.
3- xml issue is because you haven't compiled python with expat library inside
4- Investigating

**Comment by RomStef** [comment]
no , i have not compiled with debug option.
i have run the command "make full x64 2017" . the debug option must be specified to be enabled... i think.

Thanks

**Comment by RomStef** [comment]
i have recompiled upBGE with "make release x64 2017" and now all work without errors. i think the "make full" enable the debug option .
