### ISSUE TITLE
overlap function for BVHtree not working in BGE

### ISSUE THREAD

**Issue by RomStef** [UPBGE/blender#786]
as i said in the title , when i call the overlap function of BVHtree for testing overlapped faces between two different BVHtree the programm says the object has no attribute 'overlap'

**Comment by lordloki** [comment]
Could you attach a little example?

**Comment by panzergame** [comment]
I could not reproduce this bug on linux with:
```python
mesh = …
mesh.constructBvh().overlap(mesh.constructBvh())
```

**Comment by RomStef** [comment]
with no example , i have try just like the mathutils BVHtree :

"""
import bge
import mathutils

#Objects

water = bge.logic.getCurrentController().owner
terrain = bge.logic.getCurrentScene().objects['terrain']

#Meshes
waterMesh = water.meshes[0]
terrainMesh = terrain.meshes[0]

print(dir(waterMesh.polygons[0]))

#BVHtrees
waterBVHTree = waterMesh.constructBvh
terrainBVHTree = terrainMesh.constructBvh

#Test overlapped faces
overlappedFacesList = terrainBVHTree.overlap(waterBVHTree)
overlappedFacesList.sort()

print(overlappedFacesList)
"""

where water and terrain are two intersected planes

**Comment by RomStef** [comment]
i have missed the brackets , sorry

**Comment by RomStef** [comment]
Sorry, i have to return on this issue because the overlap function work but don't return any value.
here an example  :
[Uploading test_bvh_overlap.zip…]()

**Comment by panzergame** [comment]
@RomStef : the file link seems incorrect.

**Comment by RomStef** [comment]
[test_bvh_overlap.zip](https://github.com/UPBGE/blender/files/2286205/test_bvh_overlap.zip)

**Comment by panzergame** [comment]
The BVH is construct from the mesh and can't include the object transformation because meshes are shared.
In your example file, the water plane have a transformation and without it it doesn't intersect the ground. Applying the location on the plane mesh is fixing the issue.

Though a lot of people will encounter this issue, @RomStef, @BluePrintRandom: Do you think interesting to pass a matrix to `constructBvh` to represent the object transformation ?

**Comment by panzergame** [comment]
@RomStef, @BluePrintRandom ?

**Comment by BluePrintRandom** [comment]
Maybe a bool, world or local?

**Comment by vlad1777d** [comment]
Strange, but in my case, seems, player and some cubes intersect always, regardless they don't actually intersect.

Example:  https://www.youtube.com/watch?v=4Lsk84Gb9TY

Here you see, that BVHTree always says that there are some intersected faces, but if you'll look to coordinates, than you'll see that they'll be the same only when I jumped on one of that blocks.

Can somebody tell me, what I'm doing wrong ?)

**Comment by BluePrintRandom** [comment]
Are you transforming the bvhtree to the correct world space?

**Comment by vlad1777d** [comment]
@BluePrintRandom , ah, no.
Thanks )
I missed that, I thought, that it was fixed in PR to account that transfor automatically =)
