### ISSUE TITLE
Components not running with LibLoad

### ISSUE THREAD

**Issue by UnidayStudio** [UPBGE/blender#789]
If you add an object with python components in one .blend file and libload this .blend into your game, the Python Components will not run (even with load_scripts = True).

**Comment by panzergame** [comment]
@UnidayStudio: Is it fixed for you ?

**Comment by panzergame** [comment]
@UnidayStudio : Is master working for you ? I pushed 7f358894b1a3bf3dd26cb8195f195ea878fb8777 that fix synchronous libload of objects with components.

**Comment by UnidayStudio** [comment]
@panzergame Fixed in master! But again: The components will only work if I enable this in user preferences (which is bad).

**Comment by panzergame** [comment]
See ge_userpref. #809
