### ISSUE TITLE
Request: Movement Sensor

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#8]
A sensor that detects when a object has moved or rotated

Potential use = triggering dormant AI if they are moved as collision sensor will always detect the ground the unit is resting on. Will be used to change actor animation states in wrectified (like walk or fall etc)

Thank you.
BPR

**Comment by youle31** [comment]
Hi, we discussed the usefulness of a new sensor of this type, but we are not convinced about, as we can easily do that with a small python script:
eg: if object.worldPosition != previousObjectPosition or object.worldOrientation != previousObjectWorldOrientation: do something.

Write a new sensor requires a big piece of code in several files, and we can't write a new sensor for all what can be done with a little python script.

We haven't decided yet to not do it, but we wanted to ask you in what other cases do you think this new sensor could be useful? Thanks

**Comment by BluePrintRandom** [comment]
many units can sit dormant, not polling anything, friendly or enemy/AI and when acted upon from outside influences, activate their logic, for instance a manager could push pieces around, that animate themselves only if they move etc,

basically it allows for many instances of 'ALWAYS' to be replaced with 'Movement'

Even monster agreed it was a good Idea for once 
their are actually many use cases (Mines?)

as collision = always for any object under gravity

a 'movement' sensor, would only trigger if it was moved.

**Comment by panzergame** [comment]
@BluePrintRandom : Maybe if you make this sensor more complex we can implement it.
Like let the user choose the precision error, choose an axis, local or global, use rotation, position or scale...

**Comment by BluePrintRandom** [comment]
exactly, it could double as a 'is falling' sensor, or a 'is rising sensor' etc,

a property it could also expose is the change in position or the change in orientation, 

Thank you,

**Comment by BluePrintRandom** [comment]
Other potential uses, for logic based coding, 
if local velocity y > x trigger true

Could be used to change animations when a speed threshold is reached in logic, without python, 

or a jet could pop out it's landing gear if local y is lower then x  without python, 

I love python, don't get me wrong, there are just many times when you don't want to run always, and this helps break away from that.

**Comment by youle31** [comment]
I'm still sceptical... I know that trigger something if an object moves can be useful, as thousand mini scripts that you can do on your own. And we can't do a sensor that does everything.

Always sensor is not a "bad" thing. Anyway, It is executed each frame, as mouse movement sensor (even if you uncheck pulse mode, the states activated, active, released are checked).

Furthermore, you can already do such things with a sensor "actuator" which can check if an actuator is active and has force, dLoc etc... If you want to check if another object is moving you can do that: http://www.pasteall.org/blend/39986 or such things...

I don't know...

**Comment by BluePrintRandom** [comment]
I am talking about

always--------(all python to run actor)

vs

movement----(all python to run actor)


and I know of a few ways to efficiently do this anyway using a manager that
tracks all the entities I need a movement sensor in
and just sets a bool (Moved = True)

    import bge
    cont = bge.logic.getCurrentController()
    MovementManager = own

    if type(MovementManager['ListOfTargets']) is str:
        MovementManager['ListOfTargets']=[]
        for objects in bge.logic.getCurrentScene().objects:
            if 'MoveTag' in objects:

MovementManager['ListOfTargets'].append([objects,objects.worldPosition.copy())
    else:
        for objects in MovementManager['ListOfTargets']:
            Diff = objects[0].worldPosition-objects[1]
            Mag = Diff.magnitude
            if Mag>(threshold):
                objects['Moved']=True
            else:
                 objects['Moved']=False
            objects[1]=objects.worldPosition.copy()


I understand how to do this effectively on my own, however it feels like
it's something that should be already included from day 1.

I can do almost anything in the engine as it is, this would just increase
efficiency and add a layer of polish to the bricks,

**Comment by BluePrintRandom** [comment]
https://www.youtube.com/watch?v=28sa9eFUJMU&feature=youtu.be here is my own
solution

and the file

http://www.pasteall.org/blend/39987

this is useful for me etc, however it is not as useful to the people still
trying to wrap their head around logic bricks,
etc.

**Comment by youle31** [comment]
Could you please draw the sensor as you imagine it and I'll try to make something

**Comment by BluePrintRandom** [comment]
![movedsensorversionzero](https://cloud.githubusercontent.com/assets/7190873/12160556/12b2d8ce-b4a2-11e5-9e21-8932b93e6c2b.png)

And here we are

there is room for expansion etc, But I think the dropdown would have

(magnitude) , (Axis -X) , (Axis X) , (Axis Y), (Axis -Y) etc

and a check box for local / world

**Comment by youle31** [comment]
I made it. I'm waiting for the other devs opinion about. It still have to be improved... http://www.pasteall.org/63236/diff

**Comment by BluePrintRandom** [comment]
Thank you, it opens up very easy to use character animation to novices.

and will allow for less logic usage for python professionals.

**Comment by panzergame** [comment]
@BluePrintRandom :  see https://github.com/UPBGE/blender/commit/205e1b4b10fbb1f733dc21a11c9d5827eed02c0d in https://github.com/UPBGE/blender/tree/ge_movement_sensor. Can you test if it work currently ? Other commits will add the sensibility control, rotation and velocity.

**Comment by BluePrintRandom** [comment]
Sure, do you have a link to a win32 or win64 build?

I don't have a suitable build environment yet, and I am terrible at it :P

**Comment by Akira1San** [comment]
BPR, since i could compile, so you could too. Look here -> http://blog.machinimatrix.org/building-blender/

**Comment by BluePrintRandom** [comment]
youle helped me. I have a build with the sensor in it, 
I will try and make a nice demo of what the sensor can do,

when do you think sensitivity will be in?

I was thinking about something..... what if you had 6 check boxes in a version ?
(X+ X-), (Y+,Y-) (Z+ Z-)
and if any of the checked axis are tripped, the pass a positive pulse?

So you can do - if X+--------and-------play walk
if not Z+ and Z---------------/

and use far less bricks.

**Comment by DCubix** [comment]
Since this feature is already implemented, I think I can close this.

**Comment by BluePrintRandom** [comment]
Are all the python bindings in?
