### ISSUE TITLE
Libload/ Libfree have issues with multiple scenes.

### ISSUE THREAD

**Issue by RockyMadio** [UPBGE/blender#805]
If you execute libload and libfree on a single scene, it will work perfectly fine.
But if this scene is having an overlay scene OR being a background scene of another scene, after libfreeing the data, the game will crash right away.

You can reset the scene , but libload will not longer work. It says that library is still loaded, but nothing will appear.

I hope this issue will be set on high priority.
http://pasteall.org/blend/index.php?id=50213
http://pasteall.org/blend/index.php?id=50214

the test data has a great size for testing purpose.

**Comment by RockyMadio** [comment]
S to load, and A to free

**Comment by panzergame** [comment]
@RockyMadio : Could you test the branch ge_bug_fix_805 please ?
