### ISSUE TITLE
Is it possible to use the regular soft body simulations in the game engine?

### ISSUE THREAD

**Issue by Amir-Arsalan** [UPBGE/blender#806]
When I click on the game engine and want to declare an object as soft body, I realized that the soft body properties are different than the non-game engine soft body physics. I guess the game engine's soft body physics are not using the stuff in `softbody.c`. Is that right? So I wonder, is it possible to somehow use the kind of soft body physics that is available in Blender internal or Cycles in the game engine?

**Comment by panzergame** [comment]
softbody.c is a blender implementation of soft body, the game engine is using bullet 3d library.
It's hard to merge the both.
