### ISSUE TITLE
Proposal: change to material editor and shaders

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#82]
With the upcoming change to OpenGL 3.2 and ES 3, and removing the BI. The BGE uses the material editor from the BI render, thats going to get removed. So I propose to create a new material editor and shaders in order to remove the overload. An example would be the material editor from Mike Pan.
Link to images here -> https://github.com/mikepan/BlenderGEResourceKit/tree/master/Media
Reworking the shaders, so that they can be easily extended and maintained in order to add method such as PBS and Opengl ES 2. Also creating an Ubershaders looks interesting.
So what do you think?

**Comment by DCubix** [comment]
Simplifying the shaders would be a great idea for BGE. We don't need most of the stuff. Like some diffuse and specular modes.
I agree with this

**Comment by BluePrintRandom** [comment]
:+1:
