### ISSUE TITLE
Vsync python

### ISSUE THREAD

**Issue by gionnigio** [UPBGE/blender#820]
i dont really know if it is bug or its intentional but:

bge.render.setVsync(bge.render.VSYNC_ON)  
bge.render.getVsync() 
returns 1

bge.render.setVsync(bge.render.VSYNC_OFF)
bge.render.getVsync() 
returns 0

bge.render.setVsync(bge.render.VSYNC_ADAPTIVE)
bge.render.getVsync()
returns 0 as vsyncoff

upbge 0.2.3

**Comment by youle31** [comment]
hi, I don't really know what is swap interval but if there is a possibility to display a warning when "adaptative vsync" is not supported, it can be useful i guess too. Else, to be honest, i'm not familiar with vsync...
