### ISSUE TITLE
Issues with new Startup.blend and new theme

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#823]
1. cycles disappeared from engines list
since 08b087401e2b51eb32d42cf1281e0d15e533f3a2

I think the default startup.blend file has been saved whereas cycles was not compiled, then it is not available anymore in engines list (just a guess)

**Comment by lordloki** [comment]
2. Noodle curving set to 0 in new theme.

The link between nodes is a straight line now as noodle curving is sets to 0. The default value should be 10.

**Comment by lordloki** [comment]
3. Pop up when Move object to other layer

When move object to other layer, layers are not visibles as are the same color than the contour

**Comment by panzergame** [comment]
@lordloki, @youle31 : I pushed fix commits in master, please check and close if the bug is actually fixed.
Thanks for reporting.

**Comment by youle31** [comment]
Hi, it sounds good to me at first glance. Thanks!

**Comment by lordloki** [comment]
Checked and works like a charm.
Good work!
