### ISSUE TITLE
Compilation error on windows x64

### ISSUE THREAD

**Issue by RomStef** [UPBGE/blender#829]
[cMake_Error.txt](https://github.com/UPBGE/blender/files/2365647/cMake_Error.txt)

**Comment by panzergame** [comment]
@youle31, @lordloki Do you have the same cmake check failure ?
@RomStef : Does your CPU/system support SSE ?

**Comment by RomStef** [comment]
how can i check if my system support SSE ?
i have an intel I7-7500 and geforce GTX950M on my laptop

**Comment by lordloki** [comment]
@panzergame I don't have this error

**Comment by youle31** [comment]
I can't reproduce this error (libs up to date (svn update), i7 8700k, visual studio 2017, fresh master, win 10 64)

**Comment by nestanqueiro** [comment]
Hi all, I'm also having a compilation error, but I'm on Linux... should I open a new issue, or can I post it here, since it is also a compilation error? 
Feel free to delete the post, or move it elsewhere if this is in any not correct, then and I'll post again in the correct place.

The error I'm getting is around 98% of completion:
```
/builds/blender-git/blender/source/gameengine/Ketsji/KX_ObstacleSimulation.cpp:424:6: error: no match for ‘operator*=’ (operand types are ‘mathfu::vec2 {aka mathfu::Vector<float, 2>}’ and ‘double’)
   dv *= fabs(maxDeltaSpeed / ds);
```

any idea on how to get around this? thanks in advance

**Comment by nestanqueiro** [comment]
My libs are up to date, I run install_deps.sh just before compiling and it compiled a bunch of new deps... I also had python 3.6 as default, but after changing to 3.7 it still gives the same error....

**Comment by RomStef** [comment]
now it works, thanks a lot guys

**Comment by VictorHiroshi** [comment]
@RomStef how did you solve the missing python.h error? I'm facing the same issue here but couldn't find out how to solve it.

**Comment by RomStef** [comment]
Update the repository and recompile the project

Il lun 22 apr 2019, 16:14 Victor Hiroshi Bastos Inoue <
notifications@github.com> ha scritto:

**Comment by VictorHiroshi** [comment]
Thank you. =)
