### ISSUE TITLE
crash with a game (maybe related to bullet)

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#838]
![bububullet](https://user-images.githubusercontent.com/10052509/45649180-e3a1ec00-baca-11e8-8e36-8daff90a51a1.jpg)

test file:

https://www.dropbox.com/s/w2usg4m4wos42ra/Colladiration.blend?dl=0

steps: Press P and wait 0.5 seconds

**Comment by lordloki** [comment]
Maybe #define BT_THREADSAFE 1 
Will help with the crash.
See
https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=10232&start=105#p38432

**Comment by Akira1San** [comment]
It dont crash with branch UPBGE_v0.2.3_ge_physics_Windows64.zip

**Comment by youle31** [comment]
list of files causing issues related to bullet:

- On discord: https://cdn.discordapp.com/attachments/290595893931933696/495430775987109898/dum_game.blend
(go to level 1 scene, play, crash when you have all coins - simple file)
- The Akira san's file: https://www.dropbox.com/s/w2usg4m4wos42ra/Colladiration.blend?dl=0 (same as the 1 shared at the top of the thread)
- BGMC 22:
Horsey adventures -> crash at exit (press ESC)
Terminus north: crash at exit (press ESC)

I'll edit if I find others

**Comment by panzergame** [comment]
@youle31 Can you please reconfirm that my commit fixed the issues please ?

**Comment by youle31** [comment]
Fixed in https://github.com/UPBGE/blender/commit/8d97babd888749a6490c3aabdbcdd57f5f80919e Thanks @panzergame !
