### ISSUE TITLE
AttributeError: module 'VideoTexture' has no attribute 'VideoFFmpeg'

### ISSUE THREAD

**Issue by ethicalfive** [UPBGE/blender#839]
I followed the tutorial here: https://blenderartists.org/t/how-add-texture-animation-video-in-bge/693622/2

It works fine in vanilla BGE but I have a problem loading this line in UPBGE:
`        logic.video.source = texture.VideoFFmpeg(movie)`

I get the resulting error:
`Error: And(Plane.052), Python script error
Traceback (most recent call last):
  File "/home/sam/Desktop/Hex_upbge.blend/video.py", line 20, in play
AttributeError: module 'VideoTexture' has no attribute 'VideoFFmpeg'
Blender Game Engine Finished
`
In UPBGE's API it includes the same line causing the problem as in the above tutorial example.
https://pythonapi.upbge.org/bge.texture.html?highlight=logic%20video%20source%20texture%20videoffmpeg%20movie#basic-video-playback

Also loading the .mkv file results in a pink texture whereas using a .avi gives the correct static image but it still results in the same error as above, viewing the mkv and the .avi with that same module plays fine in vanilla BGE too.

**Comment by panzergame** [comment]
What is the source of you blender binary ? (from download.upbge.org or manually compiled)

**Comment by ethicalfive** [comment]
I compiled it using install_deps.sh  from github

**Comment by youle31** [comment]
Hi, I already had this error. This was because WITH_CODEC_FFMPEG was not enabled in cmake (linux compilation)

**Comment by ethicalfive** [comment]
> Hi, I already had this error. This was because WITH_CODEC_FFMPEG was not enabled in cmake (linux compilation)

Hey youle31! That was the problem! Only I used the make line it told me to run instead of using cmake.

install_deps.sh told me to run make with this line:
`make -j4 BUILD_CMAKE_ARGS="-U *SNDFILE* -U *PYTHON* -U *BOOST* -U *Boost* -U *OPENCOLORIO* -U *OPENEXR* -U *OPENIMAGEIO* -U *LLVM* -U *CYCLES* -U *OPENSUBDIV* -U *OPENVDB* -U *COLLADA* -U *FFMPEG* -U *ALEMBIC* -D WITH_CODEC_SNDFILE=ON -D PYTHON_VERSION=3.6 -D PYTHON_ROOT_DIR=/opt/lib/python-3.6 -D BOOST_ROOT=/opt/lib/boost -D Boost_NO_SYSTEM_PATHS=ON -D WITH_OPENCOLORIO=ON -D OPENCOLORIO_ROOT_DIR=/opt/lib/ocio -D OPENEXR_ROOT_DIR=/opt/lib/openexr -D WITH_OPENIMAGEIO=ON -D OPENIMAGEIO_ROOT_DIR=/opt/lib/oiio -D WITH_CYCLES_OSL=OFF -D WITH_LLVM=OFF -D WITH_OPENSUBDIV=ON -D OPENSUBDIV_ROOT_DIR=/opt/lib/osd -D WITH_OPENVDB=ON -D WITH_OPENVDB_BLOSC=ON -D OPENVDB_ROOT_DIR=/opt/lib/openvdb -D WITH_ALEMBIC=ON -D ALEMBIC_ROOT_DIR=/opt/lib/alembic"`

I changed it to: 
`make -j4 BUILD_CMAKE_ARGS="-U *SNDFILE* -U *PYTHON* -U *BOOST* -U *Boost* -U *OPENCOLORIO* -U *OPENEXR* -U *OPENIMAGEIO* -U *LLVM* -U *CYCLES* -U *OPENSUBDIV* -U *OPENVDB* -U *COLLADA* -U *FFMPEG* -U *ALEMBIC* -D WITH_CODEC_SNDFILE=ON -D PYTHON_VERSION=3.6 -D PYTHON_ROOT_DIR=/opt/lib/python-3.6 -D BOOST_ROOT=/opt/lib/boost -D Boost_NO_SYSTEM_PATHS=ON -D WITH_OPENCOLORIO=ON -D OPENCOLORIO_ROOT_DIR=/opt/lib/ocio -D OPENEXR_ROOT_DIR=/opt/lib/openexr -D WITH_OPENIMAGEIO=ON -D OPENIMAGEIO_ROOT_DIR=/opt/lib/oiio -D WITH_CYCLES_OSL=OFF -D WITH_LLVM=OFF -D WITH_OPENSUBDIV=ON -D OPENSUBDIV_ROOT_DIR=/opt/lib/osd -D WITH_OPENVDB=ON -D WITH_OPENVDB_BLOSC=ON -D OPENVDB_ROOT_DIR=/opt/lib/openvdb -D WITH_ALEMBIC=ON -D ALEMBIC_ROOT_DIR=/opt/lib/alembic -D WITH_CODEC_FFMPEG=ON -D FFMPEG_LIBRARIES='avformat;avcodec;avutil;avdevice;swscale;rt;theoraenc;theora;theoradec;vorbisenc;vorbisfile;vorbis;x264;openjpeg'"`

Now its working as expected. Thanks youle :D (the stable prebuilt version had weird game slowing logic usage spikes which i wasn't enjoying!)
