### ISSUE TITLE
I can not compile the UPBGE, Please Help me!

### ISSUE THREAD

**Issue by JJGamerDe** [UPBGE/blender#842]
I have more than 2 months trying to compile the UPBGE and I can not at all
I downloaded the master thousands of times and always made the mistake!
help me I'm going crazy !!!

I do not know what changed to compile, I always compile the blender without problems, but the upbge I never got!

I can not get more detailed information about the process anywhere!

please someone tell me step by step how to compile, I can not take it anymore, I'm 36 years old and I can have a heart attack!!

**Comment by panzergame** [comment]
I don't even know what system your using...

Please provide more information:
- OS
- version (from git)
- the log, I will never bet you have an empty compilation log
- how are you managing dependencies

Please provides such information and we will perfectly able to help you.

**Comment by panzergame** [comment]
Thanks for the information, but I still need some more.
What is the error in the cmake gui pop up ? Also there's a log at the bottom of the GUI, could you paste it here ?

**Comment by JJGamerDe** [comment]
![screenshot_20180923181339](https://user-images.githubusercontent.com/43513644/45933062-7d9ae600-bf5c-11e8-95d5-e33596e4962c.png)


![screenshot_20180923181707](https://user-images.githubusercontent.com/43513644/45933089-e8e4b800-bf5c-11e8-8525-d918b74ffd8a.png)

I think it's something I'm doing wrong, could you please tell me step by step how you compile?

**Comment by nestanqueiro** [comment]
Hi, 
it seems you are missing the libs... in linux you have to run blender-git/blender/build_files/build_environment/install_deps.sh... not sure how to proceed in windows... but surely there must be good tutorials on how to get/compile the libs...

good luck

**Comment by lordloki** [comment]
Yes, you don't have the libraries installed:

```cd C:\blender-git
svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/windows_vc14  lib/windows_vc14```

**Comment by JJGamerDe** [comment]
I believe the procedure is the same.

yes, I tried to use the installdeps most of this error:

![sem titulo](https://user-images.githubusercontent.com/43513644/45933477-00736f00-bf64-11e8-87f6-4d33b2ca0e10.png)

Note: it took me a long time to get a print of the error, the cmd was closing too fast

and as incredible as it seems I think it will not be because I do not have python ...
I forgot to install I had on my other pc
I think I just have PyCharm, which I use!

Okay, I'm going to download python and it's! \o/

**Comment by lordloki** [comment]
You don't need to use install_deps.sh on windows as you have all the libraries you need already compiled in lib/windows_vc14.

The error that you obtain when you run cmake GUI is that CMAKE doesn't find the libraries in lib/windows_vc14 then you need to be sure that you have the libraries there.

Checkout the libraries with the commands that I  put before:
```
cd C:\blender-git
svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/windows_vc14  lib/windows_vc14
```

**Comment by JJGamerDe** [comment]
lordloki

I was doing this plus the libs took too long to download
I downloaded it and it's ready

![screenshot_20180924014344](https://user-images.githubusercontent.com/43513644/45937914-734c0c80-bf9b-11e8-85bc-760312fbbf08.png)

still the same error ...

![screenshot_20180924014442](https://user-images.githubusercontent.com/43513644/45937920-8828a000-bf9b-11e8-9a46-94ada3c3f878.png)

**Comment by JJGamerDe** [comment]
lord loki
oh my god!!!!!!!!!!!!!!!!! it's working!!!

![screenshot_20180924024046](https://user-images.githubusercontent.com/43513644/45938754-44d22f80-bfa3-11e8-9837-64ff71585215.png)

incredible!!!
was not working because I left the libs in
\ blender-git \ blender

I've been trying for a long time!
thank you so much! lordloki!!

**Comment by JJGamerDe** [comment]
incredible!!!
was not working because I left the libs in
\ blender-git \ blender

![123](https://user-images.githubusercontent.com/43513644/45938870-59fb8e00-bfa4-11e8-9534-864a553795f3.png)

incredible!!!
was not working because I left the libs in
\blender-git\blender

I've been trying for a long time!
thank you so much! lordloki!!

**Comment by JJGamerDe** [comment]
I have another problem...

it's just a question: Where do I get as dlls? python37_d.dll,avcodec-58.dll,,avdevice-58.dll?
this upbge version uses the Blender 2.8 files?

**Comment by lordloki** [comment]
you're welcome!

**Comment by panzergame** [comment]
@JJGamerDe : You have to generate solution "INSTALL"

**Comment by lordloki** [comment]
They are in the lib/windows_vc64 folder

I imagine that you are using Visual studio 2017. In the left lateral projects you have to select INSTALL->right button click-> set as default project (or something like that, i don't remember now)-> and build again. It will copy the DLLs from lib folder to Release/Debug folder

**Comment by JJGamerDe** [comment]
this one?
![screenshot_20180924033637](https://user-images.githubusercontent.com/43513644/45939750-4bfd3b80-bfab-11e8-8db3-12e21a492f48.png)

right use the right button and put it to compile ...
he is generating the files
well ... I do not know almost anything about visual studio...

**Comment by JJGamerDe** [comment]
I got it!

but now the upbge is not opening

![screenshot_20180924034646](https://user-images.githubusercontent.com/43513644/45939932-7d2a3b80-bfac-11e8-9cf1-785443e16d56.png)

he does not give any information, when I open it he tries to start and simply closes...

**Comment by lordloki** [comment]
Yes, we know. It is a bug (see #797). We will fix in the next days.
Although you always can test 64bits build that it is working.

**Comment by JJGamerDe** [comment]
I'm downloading the upbge again ...
because this one I used is outdated a week ago ...

![azxc](https://user-images.githubusercontent.com/43513644/45940255-5ec53f80-bfae-11e8-92ff-523796dfc0f2.png)

I think everything is solved! \ O /
many thanks panzergame and mainly lordloki!
I would not have been able to do this without you!

I'll close so as not to disturb ...

You guys are doing a great job with BGE. I would love to donate help, it would be interesting to patreon upbge...

Thank you see you later!
