### ISSUE TITLE
How to uninstall packages that depend on installation on debian

### ISSUE THREAD

**Issue by haizhou37** [UPBGE/blender#849]
I ran the install-des.sh file as upbge suggested, but now I want to completely uninstall all the packages it installs. What should I do？

**Comment by lordloki** [comment]
That it is not easy. You have to note what package were installed and then you should "apt get remove each_one_of_these_packages"

**Comment by panzergame** [comment]
You can look at script install_deps.sh and the packages listed, but though that some packages were certainly installed before and must be not removed.
