### ISSUE TITLE
"New-" level of detail system bug?

### ISSUE THREAD

**Issue by Maujoe** [UPBGE/blender#85]
I have tested a scene in upbge but upbge crashs and first it looked like it's a random problem when the lod switch between object with custom shader and a lod object with blender material. 

But then I have tried to recreate the problem and I notice that the complete lod system is buggy.
In the viewport the lod works right but ingame it doesn't. Sometimes it works, sometimes only some objects will replaced by the lodobject or sometimes none object will replaced. And the problem is completely random and different after revert the file or create/duplicate objects.

I read something about changes on the lod system in the 0.05 release notes, seems there was something wrong because the "old" lod system in BF blender and in upbge 0.04 works fine with the same file. 

[upbge_test.zip](https://github.com/UPBGE/blender/files/221820/upbge_test.zip)

**Comment by panzergame** [comment]
I got the same result in BFBGE and UPBGE, but yes there's a difference between the BFBGE/UPBGE render and the viewport because the viewport doesn't manage the hysteresis. Can you make a video if the problem is still here.

Also you talked about crash on custom shaders, can you provide an example file ?

**Comment by Maujoe** [comment]
Here I upload a smart video packed in a zip file.
[upbge_lodbug_video.zip](https://github.com/UPBGE/blender/files/221940/upbge_lodbug_video.zip)

Yes, I'm not sure because I can't recreate the problem with a custom shader and the crashes are in a large project file with linkin libraries. But I will take a closer look at it and if I find something I will give feedback.

**Comment by panzergame** [comment]
@Maujoe : it's very strange, i can't reproduce the bug, i tried to move the camera duplicate objects ect... but it always work.....

I hope is not due to uninitialized values, which are ok for me and for you...
What's your OS ? Do you built last version ?

**Comment by Maujoe** [comment]
I use the precompiled version (UPBGEv0.0.5b2.77Windows32) from the upbge webside after it was released.

I test it on 2 computers both Win 7 64bit.

**Comment by panzergame** [comment]
@Maujoe : can you try with lastest UPBGE 0.0.6 windows build ?

**Comment by Maujoe** [comment]
Yes, now it works right.
