### ISSUE TITLE
Main file of Colateral Vertigo game adapted for UPBGE.

### ISSUE THREAD

**Issue by chicortiz** [UPBGE/blender#851]
Hello UPBGE fellows!

Today I released an experimental file of my game "Colateral Vertigo" for the UPBGE version 0.2.2

It's a humble file, but it's what I can do to help the UPBGE project for the moment. :)

More details can be found inside the Blender Game Artists post:

https://blenderartists.org/t/colateral-vertigo-game-main-file-released-for-free/1128028

If this "issue" is considered spam, fell free to remove!

Thank you very much for your time

Greetings,

Ortiz

**Comment by lordloki** [comment]
Thank you very much @chicortiz . All the help is well received!! 👍

**Comment by BluePrintRandom** [comment]
Thank you @chicortiz  for the test file - I will close this to give us a better idea of what is in the tracker.

it will still be available in search and in :closed area preserving your file for later use
