### ISSUE TITLE
Why is there no world-space normal input node?

### ISSUE THREAD

**Issue by ethicalfive** [UPBGE/blender#853]
I've spent the last few days messing around with the material node editor trying to get triplanar texturing working and while it works great in one axis, it was not working great in other axises(axii, axuses ?)

After carefully comparing each part of my nodes between a cycles example and my internal blender nodes version, I finally discovered that the problem lies in the Geometry node, the normal output is in viewport space not global space like in cycles.

Here are some examples of triplanar textures using whats available from the node editor in action (from the one viewport angle that looks good (also aware the metaballs will not show in BGE but if i converted them to mesh they would)
https://www.youtube.com/watch?v=gWfrq8B9N0A
https://www.youtube.com/watch?v=gdekuMyYPl8
https://www.youtube.com/watch?v=LTdQKEHkKvE

Im aware that there is a triplanar node setup planned but what im after is a world aligned normal data. I attended a lecture at university hosted by a dev team member from epic games on VFX in unreal4 and they used world aligned normal data for a lot of their examples and now im stuck.

**Comment by ethicalfive** [comment]
i found this patch addressing it on blender developers if that helps https://developer.blender.org/rBS1e5735ab993e0c585f9009246c2c4443fa3430af

**Comment by ethicalfive** [comment]
So it looks like the patch has been applied at some point in the past but because the "use worldspace light params" under the render->shading tab is missing, this makes it a bug?

**Comment by ethicalfive** [comment]
I figured it out, although, it would be nice to have another geometry normal option for world coordinates as well as viewport coordinates.

The option is just missing from the UPBGE version of the render tab, changing to blender internal renderer, the option shows up, you can check it in there and it works in the game engine! :)

So its a minor bug but would be great as a seperate geometry node output too.

**Comment by ethicalfive** [comment]
I struggled with git for awhile and gave up, so here is a patch @lordloki 

https://drive.google.com/open?id=1tip9j6HCeF1-rszdZQZ0EDtTV4X9B4VB

It just adds 

rd = context.scene.render

and 

col.prop(rd, "use_world_space_shading", text="World Space Shading")

to properties_game.py so you can change normals from camera space to world space without having to change to internal render mode to access it. You can also use a vector transform node to change from camera space to world or object space without setting "World Space Shading" but the output with this method doesn't seem to be right.

This combined with using vector transform nodes should effectively close this issue?

**Comment by lordloki** [comment]
Commited at https://github.com/UPBGE/blender/commit/44fb0aea4639e7a6bf9a61525f106fb30134f62c

Thanks for the code. Closing issue
