### ISSUE TITLE
Capsule collision bound doesn't fit object's bounds

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#856]
Hello! The images below explain everything. The example file is at the end.

![image](https://user-images.githubusercontent.com/19820741/46364991-be29ec00-c64d-11e8-8502-4e9836f42864.png)

![image](https://user-images.githubusercontent.com/19820741/46365002-c6822700-c64d-11e8-8fdf-f797a6445d52.png)

[ex_capsule.zip](https://github.com/UPBGE/blender/files/2438922/ex_capsule.zip)

**Comment by panzergame** [comment]
I fixed it in master 607351fd9a2d2f551e6bc1cc9c7c3ed90346cac8

**Comment by joelgomes1994** [comment]
Nice, it's working now, thanks!

![image](https://user-images.githubusercontent.com/19820741/46372834-98f3a880-c662-11e8-81b8-b999d138e770.png)

![image](https://user-images.githubusercontent.com/19820741/46372843-9f822000-c662-11e8-8999-dcd09792dd49.png)
