### ISSUE TITLE
Run `blenderplayer` in headless mode

### ISSUE THREAD

**Issue by marechal-p** [UPBGE/blender#859]
It comes use cases where it would be nice to run a blender game without any window, maybe just a console at most.

This would allow the creation of proper game servers, where the simulation would be using the same environment as client blender games.

**Comment by panzergame** [comment]
Do you mean without window or without drawing context ? Hidden or disabling drawing ?

The easiest way to have a build running without drawing context is to build a new version with a option macro disabling any part using OpenGL.

**Comment by RomStef** [comment]
it's the same and most probably simpler if you program a little python executable as your server, if this is the scope. the server listner open the connection and receive and send information in a json format. without touch blenderplayer.exe maybe we can create an upBgeServerPlayer.exe with a simple console and settings ready to process and distribute informations from clients and include the exe in the distributable release

**Comment by marechal-p** [comment]
> Do you mean without window or without drawing context ? Hidden or disabling drawing ?

The best would be to disable drawing altogether, and only keep logic/physics/animation tics.

> The easiest way to have a build running without drawing context is to build a new version with a option macro disabling any part using OpenGL.

Yes, but it would really be better to pass a flag when we start `blenderplayer`, like `blenderplayer --headless`. Something similar to [Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome).

But I guess it wouldn't be too bad to do like Python does on windows, with 2 executables: `python.exe` and `pythonw.exe`, where the `w` version is the windowless version. Maybe it would also allow to have an executable that is built to not depend on any drawing library, would that improve compatibility for some devices?

**Comment by lordloki** [comment]
For me the second version (upbgeplayerw) would be the most aceptable due to its compatibility

**Comment by panzergame** [comment]
> The best would be to disable drawing altogether, and only keep logic/physics/animation tics.

How would behave on bgl calls or shader compilation ?
I can ask plenty of questions like them, but they all target one common question:
If the goal is to have clients and a server simulating a part of the client, would you run a very specific file for the server which is not the same than the clients ?
By not the same, I mean not adding script, but removing AND adding.

If yes, then we can provide a upbgeplayerw without all options targeting rendering (bge.render, bgl, shaders, filters)

If no, it will be very dangerous to define fallback behaviour.

**Comment by marechal-p** [comment]
> If no, it will be very dangerous to define fallback behaviour.

Agreed.

> If the goal is to have clients and a server simulating a part of the client, would you run a very specific file for the server which is not the same than the clients ?

Conceptually yes, in my case I run the same blend file that serves as an entry point, but the scripts are triggered differently and it libloads what is needed in the new context. So it amounts to what you call `removing and adding (=replacing)` a script :)

For sure blend files being run in headless mode will certainly need to be conceived for this purpose. But it would be nice to be able to run them with the non-headless version (with rendering) in order to troubleshoot issues, if any. But any rendering-specific code will fail once run inside the window-less blenderplayer, this is to be expected in the same way that the `bpy` API causes trouble in standalone too.

**Comment by marechal-p** [comment]
> > If yes, then we can provide a upbgeplayerw without all options targeting rendering (bge.render, bgl, shaders, filters)

+1

But would it be a good idea to add something to `bge.app` a boolean like `headless` to detect at runtime if needed?

**Comment by shuvit-game** [comment]
For some reason I thought this already existed. But +1. Will definitely be necessary when/if I get to multiplayer.

**Comment by marechal-p** [comment]
It is also useful if we try to make integration tests, unlike unittests that cannot work if you import anything from UPBGE in your scripts. Wouldn't be simple to make a small test framework for it, it should also work in normal mode before, but once the headless mode is in one could setup pipelines on their server to test whatever is made.

This to show that it isn't only good for multiplayer, but for testing too. Although it would be really useful for multiplayer.

**Comment by marechal-p** [comment]
Duplicate of https://github.com/UPBGE/blender/issues/12
