### ISSUE TITLE
Crash when export UV layout

### ISSUE THREAD

**Issue by lordloki** [UPBGE/blender#863]
In UV edition screen when we try to export UVs through 'export UV layout' it crashes.

It works in debug mode. Also it works in vanilla Blender.

Example blend: http://pasteall.org/blend/index.php?id=50448

**Comment by panzergame** [comment]
I succeeded exporting on linux.

**Comment by panzergame** [comment]
@lordloki This bug is certainly coming from the BF master and a fix appeared after we did the last merge. 

What we can do is making a new merge now or delay it to the next release.
Firstly you should try with a local branch merged with BF master to confirm that it's the issue.

**Comment by lordloki** [comment]
I was investigating. It crash under bpy.ops.render.render only when uv_export_png.

@panzergame i was reviewing the commits later than our last merge and didn't see any related to this. Do you remember which one was?

**Comment by lordloki** [comment]
I just did a merge with current BF-blender master and crash still happen

**Comment by lordloki** [comment]
BF bug open https://developer.blender.org/T57187
