### ISSUE TITLE
Branch cleanup?

### ISSUE THREAD

**Issue by marechal-p** [UPBGE/blender#870]
https://github.com/UPBGE/blender/branches/active
https://github.com/UPBGE/blender/branches/stale

Would it be a good idea to remove useless branches? Especially merged ones.
133 seems a like a lot...

**Comment by panzergame** [comment]
I did some cleanup this morning.

**Comment by marechal-p** [comment]
Nice, still so many branchesthough, I never really realised how busy you were all on this repo, thank you :)
