### ISSUE TITLE
Override Culling

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#871]
**There's a strange thing about Override Culling.**

as you know the object does not render what is not in your area
this is very good but, in my opinion, as soon as we change the camera the **Override Culling** should also be updated and go to that camera **defined!**

_what this messes up when one person is wanting to do some car and needs to change the camera and the Override Culling is in the other camera_

![1](https://user-images.githubusercontent.com/35436445/46561951-4f0ffa00-c8d0-11e8-9c29-06aa05e2057f.png)

### **Solution:**
to resolve this, first the slaughtering options should not do this in the camera, but in the rendering area:

![frustun](https://user-images.githubusercontent.com/35436445/46562309-ddd14680-c8d1-11e8-82eb-6a6951f32db3.png)

and whenever the camera is switched: `KX_SCENE_SET_CAMERA`

the **Override Culling** also goes to the defined camera

**Comment by panzergame** [comment]
> as soon as we change the camera the Override Culling should also be updated and go to that camera defined!

Similar to `KX_Scene.active_camera` there's a `KX_Scene.overrideCullingCamera` for the override culling camera. And so you can change the camera overriding the culling independently from the one rendering.

I don't see the interest of changing the override culling camera when the rendering camera change, in this case don't use override.

@lordloki, @youle31 : About the UI, maybe putting a camera object field in render panel can be interesting instead of a boolean in camera side ?

**Comment by youle31** [comment]
I didn't understand. Override culling was an option added to debug the culling test of a camera. Then the current behaviour seems good to me. We want to check the culling test of a camera -> we enable override culling camera on this camera to see if the objects in this camera field are inside or outside frustum

**Comment by panzergame** [comment]
@EndSSgamesStudio : What do you think ?

**Comment by panzergame** [comment]
@lordloki, @youle31 What do we do ?

**Comment by lordloki** [comment]
I think that it is an option focused in test/development as "show frustum".
IMO it performs its purpose well and i would leave where it is.

**Comment by BluePrintRandom** [comment]
should we close this?

**Comment by EndSSgamesStudio** [comment]
Sooo...
How would you solve the problem of the "show frustum" of camera exchange? @lordloki

**Comment by lordloki** [comment]
"show frustum" is not prepared either to do camera exchange (at least intentionally). They are options to be used during the development phase of a game or during development of upbge itself. They are not intended to be used during the game.

Therefore, we don't see the lack of exchange feature as a bug. Could you show a case where exchange the camera "show frustum" or "override frustum" are useful in a game? If yes, we have to change our vision

**Comment by lordloki** [comment]
Opppsss i was mixing override culling and show frustum too.

Looking at the examples attached i consider that it is a very useful feature.

Regarding, the UI i think that the boolean in camera panel is right (i don't see necessary the camera object in render) but we need to take into account this value when we change of active camera.

**Comment by lordloki** [comment]
First of all forgive the confusion that has created my lack of knowledge in this area.  I was talking to @youle31 and @panzergame and understood the purpose of override frustum.



First of all I put in situation: there was a moment when there were bugs related to false positives in objects when debugging frustum culling.  Due to this, the "override culling" feature was developed to be able to observe "from the outside" if the frustum culling worked well in the cameras.



That said, frustum culling works in any active camera, even when changing from one camera to the next and without the need to activate override culling.



Therefore, the current functionality of override culling is that it can be visualized which elements are rendered and therefore be able to optimize the design of those elements.



From the point of view of its use within the game does not have any functionality.



Repeat again that the functionality you are trying to achieve is already defaulted by any active camera.

**Comment by EndSSgamesStudio** [comment]
I understand perfectly... @lordloki 
but unfortunately the override culling works on only one camera.

![screenshot_20181102022636](https://user-images.githubusercontent.com/35436445/47895373-bfb22400-de46-11e8-8abd-815e1dacfd13.png)

http://pasteall.org/blend/index.php?id=50624

and I was suggesting putting those properties in the render so that it stays global, not independently, and affects all the cameras, so that none of them does not go without rendering the objects

**Comment by lordloki** [comment]
Exactly, the override culling only works on one camera. But if you don't set the override culling then the frustum culling works in any camera by default.

In the example above, you have the viewport camera and 2 additional cameras. When you set the "override culling" to one of the additional cameras you are cancelling the "frustum culling" to the viewport camera and you are viewing how it is the "frustum culling" in the camera that you set the "override culling". Then you choose the other additional camera and try to set the "override culling" in that camera with wrong result (as override culling is not prepared for this).

But if you don't set "override culling" in any camera you would have:
- You would start the game and you would have the viewport camera and the 2 additional cameras. The viewport camera would have the "frustum culling" working as it is not cancelling by any "override culling".
- Then you change to another camera and in this camera would work the frustum culling.
- Then you would change to last camera and it also works the frustum culling.
In all those camera changes you would see the things through the camera (not as your examples that you see the cameras in 3er person).

**Comment by EndSSgamesStudio** [comment]
> Exatamente, a exclusão de substituição só funciona em uma câmera. Mas, se você não definir o cancelamento de substituição, a seleção do frustum funcionará em qualquer câmera por padrão.
> 
> Basicamente, "substituição de seleção" significa "substituir o frustum atual da câmera ativa (cancelando-a) para definir o frustum em outra câmera para ver se o refugo do frustum funciona de um ponto de vista externo daquela câmera)".
> 
> No exemplo acima, você tem a câmera da viewport e duas câmeras adicionais. Quando você define o "cancelamento de seleção" para uma das câmeras adicionais, você está cancelando o "frustum culling" para a câmera da viewport e está vendo como é a "substituição de tronco" na câmera que você definiu a "substituição de seleção". Em seguida, você escolhe a outra câmera adicional e tenta definir o "cancelamento de remoção" nessa câmera com um resultado incorreto (como cancelar seleção não está preparado para isso).
> 
> Mas se você não definir "substituição de seleção" em qualquer câmera, você teria:
> 
> * Você começaria o jogo e teria a câmera da viewport e as duas câmeras adicionais. A câmera da viewport teria o "frustum culling" funcionando, pois não é cancelado por qualquer "substituição de substituição".
> * Então você muda para outra câmera e nesta câmera trabalharia a seleção do tronco.
> * Então você mudaria para a última câmera e também funcionaria para o abate do tronco. 
>   Em todas essas mudanças de câmera você veria as coisas através da câmera (não como seus exemplos que você vê as câmeras em 3er pessoa).
> 
> Vamos modificar a documentação do usuário para deixar claro o seguinte:
> 
> O abatimento de substituição é um recurso a ser usado quando você está projetando seu nível para verificar quantos objetos estão dentro ou fora do tronco da câmera.
> 
> Você não tem que usá-lo no jogo como você perderia a capacidade de seleção de frustum em todas as outras câmeras.

yea!
I do not believe!
I've been fooled this whole time! 😂
Sorry I did not know!

So basically, by enabling the feature, it takes the camera feature (Viewport) and takes it to the camera you created!
and I looking at the viewport of the camera without the feature seems to be lighter because the feature is in the player's camera (which looks for fewer objects)

resource = Frustum Culling

so Frustum Culling was active all this time!
Perfect!

so this feature does not matter, it just gets in the way!
if you put in your game!

it's really something I did not know! thank you! @lordloki
