### ISSUE TITLE
Physics Type: Character Crash!

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#872]
I was starting to work on my game in the current version of upbge and with that, the UPBGE closed by itself
I started to suspect Bullet 3 and the problem is in the character collision option...

No Crash:

![nocrash](https://user-images.githubusercontent.com/35436445/46565085-53dda980-c8e2-11e8-897b-80c4be77adab.gif)

Crash:

![crash](https://user-images.githubusercontent.com/35436445/46565149-0dd51580-c8e3-11e8-8d46-84776bb6157b.gif)

**Comment by lordloki** [comment]
Fixed in current master. Thanks for reporting!
