### ISSUE TITLE
adjust 2D texture animation

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#877]
for many years this problem haunts many people, especially those who want to use a spritesheet...

_the error consists of the frames that are reproduced from the lower left corner_

![errado](https://user-images.githubusercontent.com/35436445/46645520-9958db80-cb5b-11e8-9b58-ce83a00bd2f0.gif)

_Knowing that the correct one is to reproduce the upper left corner_

![certo](https://user-images.githubusercontent.com/35436445/46645564-d1f8b500-cb5b-11e8-954d-49713727c9f5.gif)

all this and more things were implemented with this addon:
https://www.youtube.com/watch?v=tnoZUUn7bdM 
https://www.blendermarket.com/products/bge-sprite-addon
I have this addon for over 1 year, the problem is that it does not work in UPBGE because of the code that has changed a lot
_so... it would be interesting to adjust this!_ 👍

**Comment by panzergame** [comment]
I would like to have a look, but the sources are not free…
I will avoid paying when the only interest is to debug it.
