### ISSUE TITLE
Testing effort before releasing new UPBGE versions

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#880]
Hello!
Frequently UPBGE creates little bugs as the code is tweaked (like #856, #872, #797, etc), and it's pretty hard to test all the features on the engine to ensure that everything is working fine. So, I thought about making a standard 'quality control' of UPBGE using test files. These test files should cover all the features of the engine, and the builds should be tested in all platforms with all these test files before releasing to public. The testing environment comes with simple tools to aid a rapid testing, like shortcuts to navigate through scenes and test files.

See the repository of the project, read the README and try the current initial test files to get the idea.
https://github.com/bgempire/UPBGE-Tests

**Comment by BluePrintRandom** [comment]
They already do this =)

**Comment by joelgomes1994** [comment]
Oh, my bad, I didn't know the https://github.com/UPBGE/testfiles repository. Closing.
