### ISSUE TITLE
"exception_access_violation" on large text variable on component

### ISSUE THREAD

**Issue by nestanqueiro** [UPBGE/blender#883]
Hi all, 
Just noticed upbge crashes when you enter a large text variable on an argument of a component... (anything longer than 85 characters)

Usually you don't need them so long, but for instance, pasting a longer filename may instantly crash, no warnings...

To replicate the error just create an argument on the basic component of type text and enter something long... (more than 85 letters)...

the error happens also when you enter data after creation of the argument (say you create it with ("test", "test") and then change it to something long on the component interface.... 

thankyou,
Nuno Estanqueiro

**Comment by panzergame** [comment]
Tested, confirmed and fixed in 086255e. If the issue still persists, reopen the issue.
