### ISSUE TITLE
new Addon for UPBGE!

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#888]
I know that here is not a good place to comment on this ...

I've created an addon to help developers build games faster in UPBGE 🆙 
I want to make improvements ...
but only if you have some movement in the repository
because it would not do any good to make the addon if nobody used it ...

on here: https://github.com/EndSSgamesStudio/Addon_Upbge_Game_Objects

I'm also making the addon for the purpose of one day you implement in the UPBGE master! 😄 

![0 2](https://user-images.githubusercontent.com/35436445/46912069-34c6c380-cf43-11e8-8fe4-6b5f6f863c45.png)

**Comment by supermoaaa** [comment]
I have read the code of your addon,
do you know : https://github.com/UPBGE/blender-addons/blob/master/game_engine_add_basic_character.py

I think it's a better way to proposal news options for this rather that creating new one

**Comment by EndSSgamesStudio** [comment]
@supermoaaa 

yea!
From the beginning I was planning to do all this via python, but ...
since I created the system to attach a .blend file, then it would be best to fit everything into one
so I can make improvements by connecting logic bricks
I'm also avoiding having python on objects, so anyone can modify :smile:
