### ISSUE TITLE
up bge 2.4 crash on win32

### ISSUE THREAD

**Issue by supermoaaa** [UPBGE/blender#890]
upbge crash directly when i open it

i have open it with console for see the error: 

![bug](https://user-images.githubusercontent.com/5919160/46909069-d858a980-cf2c-11e8-8eae-7b7ed00d9e12.png)

**Comment by panzergame** [comment]
Did you try this release : https://download.upbge.org/download/release/windows32/UPBGE_master_v0.2.4d2018101313h086255eWindows32.zip ?

The one from download.upbge.org for windows 32 mode "latest" ?

**Comment by supermoaaa** [comment]
yes it's what release

**Comment by lordloki** [comment]
@supermoaaa could you test this build https://mega.nz/#!9xklyCza!QscnCikw8qlp70VZ1aCJAtuYiVr6e8Qrej_pEuDl0uE

It is lastest master + a new fix.
