### ISSUE TITLE
Reflection is not working!

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#892]
was doing some tests to create rain and snow
Snow:

![neve](https://user-images.githubusercontent.com/35436445/46913050-22a54f00-cf5c-11e8-8647-32b3ddad337a.gif)

Rain:I was making a puddle of water, plus the reflection for some reason is not working!

![screenshot_20181014024647](https://user-images.githubusercontent.com/35436445/46913031-baef0400-cf5b-11e8-83f8-30ef80b2d7e0.png)

![screenshot_20181014024812](https://user-images.githubusercontent.com/35436445/46913032-c6422f80-cf5b-11e8-9c29-856a888c419d.png)

Note: I am using the most recent master...

**Comment by panzergame** [comment]
Last master (unknown OS).

UI: of unknown texture material :
![screenshot_20181014_130323](https://user-images.githubusercontent.com/8046004/46914676-e9db9900-cfa0-11e8-82c9-32309cccd5b9.png)
![screenshot_20181014_130407](https://user-images.githubusercontent.com/8046004/46914680-ee07b680-cfa0-11e8-826b-197b5b51296d.png)

Scene look of unknown context:
![screenshot_20181014_125801](https://user-images.githubusercontent.com/8046004/46914686-02e44a00-cfa1-11e8-9f1e-24bf1bfa0a05.png)

Render in engine of the unknown scene:
![screenshot_20181014_125743](https://user-images.githubusercontent.com/8046004/46914616-75a0f580-cfa0-11e8-9cab-35edbf4bdfa5.png)

And unknown file !!
[ge_reflection.zip](https://github.com/UPBGE/blender/files/2476213/ge_reflection.zip)

**Comment by EndSSgamesStudio** [comment]
Os: Windows 10 64bits

![screenshot_20181014180523](https://user-images.githubusercontent.com/35436445/46922206-0648f700-cfdc-11e8-91a7-712868cf7d7f.png)

is not working...

**Comment by lordloki** [comment]
Could you paste the console messages and your system info (Help->system info)
For me it is working too
![image](https://user-images.githubusercontent.com/1015605/46922693-36f55480-d00d-11e8-8045-6be6590bb48f.png)

**Comment by EndSSgamesStudio** [comment]
Jedi Lybrary not found

![as](https://user-images.githubusercontent.com/35436445/46922725-c0902c80-cfe3-11e8-918c-5d5681b691d4.png)

**Comment by BluePrintRandom** [comment]
*...jedi?....*

:|

>

**Comment by EndSSgamesStudio** [comment]
Sorted out!
Is working on: https://github.com/UPBGE/blender/commit/33669669cab258a41839fd4befe6bf76d27e9860


![screenshot_20181014222350](https://user-images.githubusercontent.com/35436445/46925183-ee379e80-d000-11e8-8908-e20482faeeb8.png)
