### ISSUE TITLE
numPolygons incorrect result

### ISSUE THREAD

**Issue by supermoaaa** [UPBGE/blender#893]
I want to see how many faces have a object in game
but went I write this for the base cube:

`from bge import logic as Gl

scene = Gl.getCurrentScene()
Cube = scene.objects["Cube"]

for mesh in Cube.meshes:
     print(mesh.numPolygons)`

the result is 36 instead of 6

Ps sorry I have problem this insert code

**Comment by panzergame** [comment]
Fixed in 8c8b8dbea39b0437b4c1c408ad7cba543618b10b, thanks for report. Note that there's 12 polygons as polygons are fully triangles now.

Please confirm and close.

**Comment by supermoaaa** [comment]
it's ok for me
