### ISSUE TITLE
Strange Color...

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#898]
after this last compilation: https://github.com/UPBGE/blender/commit/0d30856b3c863b37d54f4e1b9b9f32626bb1867f

my game started to present strange colors...

before
![screenshot_20181019214609](https://user-images.githubusercontent.com/35436445/47261126-61c52a00-d49f-11e8-9cd7-d8fe80b31825.png)

after compilation:
![screenshot_20181020191311](https://user-images.githubusercontent.com/35436445/47261129-920cc880-d49f-11e8-85ad-754a54611de2.png)

It is much clearer!
I can not solve...

I believe it is some mistake in GLSL!

or caused the error when opening the game in this build!

but I must discard the last issue because, when opening the game in the previous compilation, the game returns with the original colors!

What do you think it could be? I need help, I have no idea how to adjust it!

**Comment by panzergame** [comment]
Can you share an example file please ?

**Comment by EndSSgamesStudio** [comment]
@panzergame 
right!
Do you have any old compilations?

**Comment by panzergame** [comment]
An old compilation ? You mean an old build ? I can do the test on my own though with the file.

**Comment by nestanqueiro** [comment]
I think you're just missing the new colour management feature... try to change it back to linear to get your old colours back....

**Comment by EndSSgamesStudio** [comment]
@nestanqueiro

> I think you're just missing the new colour management feature... try to change it back to linear to get your old colours back....

I made it...
and it's not ...
when opening the game in the previous compilation the colors come back

**Comment by EndSSgamesStudio** [comment]
@panzergame  
here: http://pasteall.org/blend/index.php?id=50533

**Comment by panzergame** [comment]
This file was edited with a 0.2.4 version during the past three weeks, and so the version of the file is noted as 0.2.4 and the versioning introduced into 0d30856 failed to automate the compatibility……
.
To fix your file you have to to set "sRGB" in "Color Management" panel in texture tab. This thing is done automatically for any new file or files coming from 0.2.3…

@lordloki : I don't have a good solution to solve this versioning issue, maybe we can for next release set the version only after the alpha is stabilized.

**Comment by lordloki** [comment]
Yes, it could be the best solution. Change the version and splash screen just before of final version

**Comment by EndSSgamesStudio** [comment]
@panzergame 
yea...
We've been working on this game since January.
and we've already changed through various versions of Game Engine...

the last compilation made is not working: https://download.upbge.org/download/release/windows32/
20/10/2018
