### ISSUE TITLE
Using Sensors and Actuators logic bricks in Python Component

### ISSUE THREAD

**Issue by Braayy** [UPBGE/blender#899]
I searched how i do that, but i haven't found.
I have tried `bge.logic.getCurrentController()`, but Python Component isn't in controller context so i can't use this.
Have another way to use sensors and actuators in Python Component?

**Comment by BluePrintRandom** [comment]
a reference to the object who owns the component should be able to use

componentOwner.actuators['Actuator']
componentOwner.sensors['Sensors']
