### ISSUE TITLE
Request: Parallax Mapping

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#9]
Add build-in Parallax Mapping. This technique will add more depth or realism to the 3d models of the game developer project. The user will go to the material panel and check the box and adjust the slider value.
Example: Parallax Occlusion Mapping in GLSL  -> http://sunandblackcat.com/tipFullView.php?topicid=28

**Comment by DCubix** [comment]
Also [here](https://www.youtube.com/watch?v=xvOT62L-fQI) and [here](http://www.learnopengl.com/#!Advanced-Lighting/Parallax-Mapping)

I think I can try to implement this. It's not that difficult :+1:

**Comment by carlo697** [comment]
1+ For this to be added, mainly the firsts techniques added can be: parallax mapping and steep parallax mapping, and maybe later can be added: parallax occlusion mapping and/or Relief Parallax Mapping. 

It would be good that materials have an attribute to deactivate the parallax (material.parallaxMapping=bool) and other one for the number of steps (material.parallaxSteps=int), but this can be added later.

**Comment by lordloki** [comment]
There was a patch by angelo miner:
http://www.mediafire.com/download/ppdb4xu29439fnp/parallaxpatchweblfile.zip
https://www.youtube.com/watch?v=ecrbXbzF45w

**Comment by Akira1San** [comment]
Thats awesome.

**Comment by youle31** [comment]
Thanks Lordloki for the link :)

**Comment by Akira1San** [comment]
Parallax Mapping with Offset Limiting: A Per-Pixel Approximation of Uneven Surfaces -> https://github.com/marcusstenbeck/tncg14-parallax-mapping
Looks useful with example files and a pdf doc.

**Comment by youle31** [comment]
I updated the patch from angelo. Thanks very much Lordloki. http://www.pasteall.org/pic/97582
I'll try to contact him to ask his permission to commit that in upbge.

**Comment by lordloki** [comment]
Hi youle, 

I think it is not necessary to ask for his permission. It was a public patch over a GPL code -> automatically the patch is GPL. I think it would be enough giving him credit in the commit and/or the code.

**Comment by Akira1San** [comment]
Cool image. I have a question. Does the Parallax have any kind of lod?

**Comment by youle31** [comment]
@Lordloki: Hi, actually, I think we'll try to contact angelo, because his patch works great with his example file, but I don't know how to reproduce nice normal maps with alpha (in his patch, height for parallax is stored in normal texture alpha channel). TwisterGE is working on this :)

@Akira1San: No for the moment, there is no such feature... I don't know if we can do this (decrease parallax steps according to distance camera>object? I don't know if the render would be nice...)

**Comment by Akira1San** [comment]
In this pdf -> http://developer.amd.com/wordpress/media/2012/10/Tatarchuk-ParallaxOcclusionMapping-Sketch-print.pdf
"We determine the current mip map level directly in the pixel shader and use this information to transition between different levels of detail from the full effect to simple normal mapping. We render the lowest level of details using regular normal mapping shading. As the surface approaches the viewer, we increase the sampling rate for the full parallax occlusion mapping computation as a function of the current mip level. We specify an artist-directable threshold level where the transition between the parallax occlusion mapping and the normal mapping computations will occur."
I guess this lod system is for fps/tps games.

**Comment by youle31** [comment]
@Akira1San: Sounds complex :) 

http://www.pasteall.org/pic/97711 (once we get the technique to create appropriate normal maps with gimp, we can get some good results. Not perfect for the moment hehe)

**Comment by panzergame** [comment]
If you want to test the parallax feature, compile UPBGE on ge_parallax branch.

**Comment by Akira1San** [comment]
Why does the texture have to be with alpha channel?

**Comment by youle31** [comment]
The height/depth is encoded in normal map alpha channel. The shader reads alpha value to set texture height.

**Comment by panzergame** [comment]
Done : 3c673aa0613720fa8763fec3addd1d699417ed22 and 248743c7907132b6c91b90fa6cb07933403a52ff. Some tutorials are coming soon.

**Comment by angjminer** [comment]
sorry for being a year late, but nice. glad to see someone getting use/inspiration out of something i did...

**Comment by youle31** [comment]
@angjminer : Thanks very much for your work! It's @lordloki who showed to us your work. I remember the first time we had it working (it was in our 2.76 branch), that was great :)
