### ISSUE TITLE
vertex.XYZ sometimes returns -nan(ind) as it's values

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#902]
edit: after more carefully looking over the file my issue was from nan values in the orientation matrix*

Thank you,
Jacob Merrill

**Comment by BluePrintRandom** [comment]
I found some more data - I went ahead and printed my world vector I built for the vertex and it's good

it's this line
`P = own.worldPosition+ (vect2[1]*(own['R']+(h) ))
                                
                            #P = Vector([ round(P[0]*rf)/rf,round(P[1]*rf)/rf,round(P[2]*rf)/rf])
                            print('world is '+str(P))
                            
                            
                            #this is where things go screwy
                            local = face.worldOrientation.inverted()* (P-face.worldPosition)  
                            #the error appears to happen when I translate the world point to local space  
                            rf2 = 8
                            print('local is '+str(local))
                            vert.XYZ = local`

**Comment by BluePrintRandom** [comment]
I think I was doing something strange (most people won't call align to the same vector with all 3 axis sequentially) - I have a stable working game- Should we close this or investigate further?
@panzergame

**Comment by panzergame** [comment]
If you don't have issue with one axis alignment, or with 3 alignment of orthogonal vectors, i think we can close the issue.
