### ISSUE TITLE
Character Physics

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#908]
A very strange thing happens

Physics is having a boring problem. it is pushed from a static block... :hurtrealbad: 

![py](https://user-images.githubusercontent.com/35436445/47610239-c562d080-da26-11e8-90c9-71ff54363cde.gif)

Example: http://pasteall.org/blend/index.php?id=50580
compiler = https://github.com/UPBGE/blender/commit/5ac18565b790345c54bc696a4c40f607062f745a

**Comment by lordloki** [comment]
You are using simple motion to WASD motion. You have to use Character motion for WASD motion too.

**Comment by EndSSgamesStudio** [comment]
more is bad to use character movement @lordloki 

the system only lets you use a key!

### making it impossible to go to the other directions:
![screenshot_20181028212444](https://user-images.githubusercontent.com/35436445/47624159-1e4e6980-daf8-11e8-9ad5-40cef0b1883b.png)

example: http://pasteall.org/blend/index.php?id=50592

**Comment by lordloki** [comment]
@EndSSgamesStudio your are right. The character movement doesn't allow additive motion as 'simple motion'. Until it be implemented internally, you can fake it adding more logic describing the 8 states instead of the 4 usual ones.

**Comment by panzergame** [comment]
> The character movement doesn't allow additive motion

@EndSSgamesStudio : The character actuator have an option named 'Add' to achieve this result:

![screenshot_20181029_195332](https://user-images.githubusercontent.com/8046004/47666520-07655100-dba4-11e8-9d15-e99e1a4e0e28.png)

Is the issue solved ?

**Comment by EndSSgamesStudio** [comment]
@panzergame 
interesting!
I was not aware of this logic brick option ...
I think everything is solved with her!
