### ISSUE TITLE
Blend file sandboxing?

### ISSUE THREAD

**Issue by atoms118** [UPBGE/blender#912]
Sorry, this might not be the right place to ask this, but here goes anyways. Say you were developing a simple FPS game that featured user-created maps, where maps were downloaded from an (untrusted) server at runtime. Obviously these map files can't be trusted, so there needs to be some kind of security system in place. Blend files are the easiest way to transport maps since you can pack literally everything you need into them, but the problem is blend files allow scripting and other nasty business that could either screw with the user's computer or, more likely, screw with the game itself. Is there a way to load a blend file/scene into the game, but sandbox it so it can't do any scripting (or anything else that would allow it to interfere with execution). To be clear I'm not concerned about maps that have a stupidly high poly count that crash your game, that's an entirely different beast; I'm just concerned about intelligent interference.

**Comment by RomStef** [comment]
you can load all the stuff from an external blend file into your scene through the libload function.

https://pythonapi.upbge.org/bge.logic.html?highlight=libload#bge.logic.LibLoad

**Comment by atoms118** [comment]
Ah thanks, this is what I need
