### ISSUE TITLE
Z coordinate issue (see attached file)

### ISSUE THREAD

**Issue by ethicalfive** [UPBGE/blender#917]
So I ran into a bug with the checker texture(cycles) where the pattern would glitch like it had overlapping planes, so I decided to replicate it myself and started following some tutorials to learn how to make my own textures.

However I ran into the same issue again, this time with my own texture when i tried to manipulate the Z coordinates. So here is a simple file demonstrating the effect, if you plug in the z value.

It's super annoying and is stopping me from progressing on an urgent project, so if anyone thinks there is an easy fix or know what mechanism is failing here, please let me know.

https://drive.google.com/open?id=1QPot6lhZ5QLt-8x41ZnCgFhmvt5lPeBK

**Comment by panzergame** [comment]
Using "clamp" in modulo operator is fixing the issue.
