### ISSUE TITLE
Build-in GUI -> imgui

### ISSUE THREAD

**Issue by Akira1San** [UPBGE/blender#92]
link to lib -> https://github.com/ocornut/imgui

info: ImGui is particularly suited to integration in realtime 3D applications, fullscreen applications, embedded applications, games, or any applications on consoles platforms where operating system features are non-standard. ImGui is self-contained within a few files that you can easily copy and compile into your application/engine:

If UpBge ever gets a buildin gui, what do you think about imgui lib?

**Comment by alabd14313** [comment]
It'd license is MIT. Please find a GPL!

**Comment by panzergame** [comment]
The library should be in GPL only if it used GPL code, here i don't think it's the case.

**Comment by Akira1San** [comment]
Discussion here -> http://stackoverflow.com/questions/3902754/mit-vs-gpl-license
So its ok to include gpl and mit.

**Comment by DCubix** [comment]
ImGUI isn't that kind of GUI you use for Games. It's most used for 3D Apps.
