### ISSUE TITLE
spawn navmesh via addObject from another layer crashes blender

### ISSUE THREAD

**Issue by Aiavaso** [UPBGE/blender#926]
Title says everything,if i try spawn navmesh via addObject from another hidden layer to active layer it crashes blender

on bge it works fine,but in upbge it just crashes

[UpbgeNavmeshSpawnCrash.zip](https://github.com/UPBGE/blender/files/2553862/UpbgeNavmeshSpawnCrash.zip)

**Comment by panzergame** [comment]
Fixed in b387a7f
