### ISSUE TITLE
Feature Request: Scenes can have different color management

### ISSUE THREAD

**Issue by DaedalusMDW** [UPBGE/blender#927]
there are time when being able to set different color management per scene is necessary.  a 2d hud may benefit from linear colors, but the main scene needs to be srgb.

**Comment by youle31** [comment]
With the current code design, it seems very difficult to do (The color management is done 1 time with a shader (gpu_shader_frame_buffer_frag.glsl)) at the end of the draw loop after all scenes have been rendered. This would introduce to much complexity imo. I close this for now. If a dev is interested, he can reopen.
