### ISSUE TITLE
Mist BUG

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#933]
was working on a "day and night" system
and notice a problem!

The fog does not work in animation!

_as you can see, the fog does not update!_
![1](https://user-images.githubusercontent.com/35436445/48308508-dbf04800-e54d-11e8-9d1e-c802930a15d2.gif)

Bug: before I was thinking it would be a problem in "Startup", but the problem is really in the UPBGE...

here: http://pasteall.org/blend/index.php?id=50691

Compiler: https://github.com/UPBGE/blender/commit/b387a7f3d1e42a49bac509766438c43c64ab312b

**Comment by panzergame** [comment]
Are you disabling constant mist in material ?

**Comment by EndSSgamesStudio** [comment]
@panzergame nop...
