### ISSUE TITLE
Arch linux binary

### ISSUE THREAD

**Issue by alabd14313** [UPBGE/blender#94]
Hi!
Do you want I upload v0.0.6 built in arch linux?
You binary for linux have library dependency problem in arch linux.

**Comment by pqftgs** [comment]
The missing dependency is libtbb.

**Comment by alabd14313** [comment]
Here is latest build (Engine Roar splash screen) and without lib dep error in arch linux:
[UPBGE0.0.6](http://www.mediafire.com/download/quminhv86a9ft85/UPBGE0.0.6.tar.gz)
I try to make an AUR, but currently a bunary package can help more instead of an AUR repos without build.
