### ISSUE TITLE
`aud` module documentation is missing

### ISSUE THREAD

**Issue by marechal-p** [UPBGE/blender#941]
[UPBGE API](https://pythonapi.upbge.org/#standalone-modules) compared to [BGE 2.79 API](https://docs.blender.org/api/2.79/#standalone-modules)

**Comment by youle31** [comment]
confirmed, issues with documentation

**Comment by lordloki** [comment]
Yes, in the refactor of the manual/documentation is included. This docuemntation will be more exposed when new site is available.
Until then check this link: https://upbge-docs.readthedocs.io/en/latest/index.html

**Comment by youle31** [comment]
Thanks for the link lordloki, I close this
