### ISSUE TITLE
Particle Info Node 

### ISSUE THREAD

**Issue by RomStef** [UPBGE/blender#947]
I have tried to develop a dynamic material for particle but the Particle info node doesn't work.
Is it possible that i'm wrong but the node seems buggy. 
I have found this thread written in th 2015 with the bugfix on the bf developer page.

[https://developer.blender.org/T46333](https://developer.blender.org/T46333)

**Comment by BluePrintRandom** [comment]
I don't think particles are supported at the moment in the game engine.

Not working in eevee yet either.

**Comment by youle31** [comment]
as particles are not supported in bge, particle info node might have issues too but this is too low priority and we have to focus on bug fixes for last upbge version, then I close this to clean the tracker, sorry
