### ISSUE TITLE
Can't Acces UPBGE Website

### ISSUE THREAD

**Issue by ditokp** [UPBGE/blender#949]
I have try using my laptop and my phone, but the result is same.

Screenshot:
![screenshot from 2018-11-24 21-57-51](https://user-images.githubusercontent.com/27815899/48969668-6350b780-f034-11e8-930d-99f54170cfab.png)

Thank you very much for reading my issue.

**Comment by EndSSgamesStudio** [comment]
I had noticed this, it's been days like this

it is likely that someone is making changes or may be a problem...
@lordloki

**Comment by panzergame** [comment]
I fixed this issue yesterday.
