### ISSUE TITLE
Segmentation fault on KX_Mesh.transformUV

### ISSUE THREAD

**Issue by vlad1777d** [UPBGE/blender#955]
Just segmentation fault when calling that method.

code:
```python
uv_offset = [0, 0]

def move_clouds ():
	global uv_offset
	import mathutils
	contr		= bge.logic.getCurrentController ()
	obj			= contr.owner

	SPEED_X = 0.1
	SPEED_Y = 0
	# Transform stored original values and write to first channel.
	uv_offset[0] += SPEED_X
	uv_offset[1] += SPEED_Y
	uv_mat = mathutils.Matrix.Translation((uv_offset[0], uv_offset[1], 0))
	obj.meshes[0].transformUV (-1, uv_mat, 0, 1)									# BUG HERE !!!!! <<<<
```

VIdeo with bug:   https://www.youtube.com/watch?v=xM4UTPgwpyc

Steps to reproduce:
- pull repository: `hg clone https://vlad1777d@bitbucket.org/new_novel/oasis`
- move to bookmark with crash: `hg update -r bug/upbge/KX_Mesh.transformUV`
    (or checkout to that commit: "b47eda814a4b")
- open scene in upbge: `upbge ./scenes/dream_tower/dream_tower.blend`
- press P and see a crash

OS: LInux Mint 19 Cinnamon
Kernel: 4.15.0-39-generic
UPBGE: 0.2.4
GPU: Nvidia Geforce GT 840m

P.S. I met near 5 crashes, and some of them are in not often used functions.
I think, maybe not to waste time on fixing this and mark it as "low priority" ?

**Comment by youle31** [comment]
hi, I propose this as a fix: 
`diff --git a/source/gameengine/Ketsji/KX_Mesh.cpp b/source/gameengine/Ketsji/KX_Mesh.cpp
index e930ea9623..03a9e1e5c4 100644
--- a/source/gameengine/Ketsji/KX_Mesh.cpp
+++ b/source/gameengine/Ketsji/KX_Mesh.cpp
@@ -295,11 +295,11 @@ PyObject *KX_Mesh::PyTransformUV(PyObject *args, PyObject *kwds)
 		             "mesh.transformUV(...): invalid uv_index %d", uvindex);
 		return nullptr;
 	}
-	if (uvindex_from < -1 || uvindex_from > RAS_Texture::MaxUnits) {
+	/*if (uvindex_from < -1 || uvindex_from > RAS_Texture::MaxUnits) {
 		PyErr_Format(PyExc_ValueError,
 		             "mesh.transformUV(...): invalid uv_index_from %d", uvindex);
 		return nullptr;
-	}
+	}*/
 	if (uvindex_from == uvindex) {
 		uvindex_from = -1;
 	}
@@ -320,6 +320,12 @@ PyObject *KX_Mesh::PyTransformUV(PyObject *args, PyObject *kwds)
 		const RAS_DisplayArray::Format& format = array->GetFormat();
 		ok = true;
 
+		if (uvindex_from < -1 || uvindex_from > array->GetNumUvLayers()) {
+			PyErr_Format(PyExc_ValueError,
+				"mesh.transformUV(...): invalid uv_index_from %d", uvindex_from);
+			return nullptr;
+		}
+
 		for (unsigned int j = 0, size = array->GetVertexCount(); j < size; ++j) {
 			if (uvindex_from != -1) {
 				array->SetUv(j, uvindex, array->GetUv(j, uvindex_from));
diff --git a/source/gameengine/Rasterizer/RAS_DisplayArray.h b/source/gameengine/Rasterizer/RAS_DisplayArray.h
index 87749cef62..ec4eb0ea8d 100644
--- a/source/gameengine/Rasterizer/RAS_DisplayArray.h
+++ b/source/gameengine/Rasterizer/RAS_DisplayArray.h
@@ -161,6 +161,17 @@ public:
 		return m_vertexData.uvs[layer][index];
 	}
 
+	inline int GetNumUvLayers()
+	{
+		int count = -1;
+		for (int i = 0; i < 8; i++) {
+			if (m_vertexData.uvs[i].size()) {
+				count++;
+			}
+		}
+		return count;
+	}
+
 	inline unsigned char(&GetColor(const unsigned int index, const unsigned short layer))[4]
 	{
 		return m_vertexData.colors[layer][index].m_array;
`

**Comment by youle31** [comment]
test file:
https://drive.google.com/file/d/116OJdaT4d8xskEsEyumGo8PlivMwHx4y/view?usp=sharing

**Comment by youle31** [comment]
I think my fix is wrong in fact as i think we can have an uv in layer 2 and no uv in layer 0... maybe i'll do another fix later. Anyway this is a minor bug

**Comment by youle31** [comment]
Bool UvExist(int layer) if !m-vertexdata[layer].size() return false; then throw python error. Smthing like that

**Comment by youle31** [comment]
This has been fixed by panzergame in last master. Thanks panzergame!

**Comment by vlad1777d** [comment]
Thank you very much!
