### ISSUE TITLE
Upbge 0.2.4 mouse look Y axis only lag on embedded player

### ISSUE THREAD

**Issue by costantan** [UPBGE/blender#962]
On embedded player, there is a lag with the mouse look on the Y axis only ( it is nearly impossible to move) when there are lots of objects in screen (characters with armatures and complex ragdolls in my case).
When playing on standalone player the problem does not exist.
It was not existing at 0.2.3, only at 0.2.4....

Pc specs:
HP 8300 CMT, Cpu i3 3220, Ram 8GB, Gpu GT1030, Hdd SSD 500 GB and SATA 1TB

**Comment by RomStef** [comment]
i think that bug is already solved. Search for the #907

**Comment by costantan** [comment]
Yes my bad, just downloaded the latest version and it ok now. Thanks.

**Comment by RomStef** [comment]
can you close this issue ?
