### ISSUE TITLE
Option to change AA during game [request]

### ISSUE THREAD

**Issue by Jesusemora** [UPBGE/blender#964]
we need a python function to change AA during game, similar to `bge.render.getAnisotropicFiltering()`.
something like:
`bge.render.getAntiAliasing`()
`bge.render.setAntiAliasing`(_level_)

there is no way to change this option other than setting it from the blender settings.

**Comment by adriansnetlis** [comment]
As far as I know, setting MSAA on-fly is quite challenging. Changing it requires reloading some OpenGL stuff. I think this could be done in menu if it loads a separate .blend file (thus loading different rendering system), but changing it in-game would be challenging to say the least. It could work, but the execution time of your proposed function would be quite slow. I may be wrong, but I am pretty sure I'm not. Anyways, screen-space based AA methods that you can code in 2D filters (e.g. FXAA) can be easily switched on/off.

**Comment by lordloki** [comment]
Closing. Committed in master. Thanks for propose it.
