### ISSUE TITLE
F8 bug

### ISSUE THREAD

**Issue by supermoaaa** [UPBGE/blender#966]
F8 don't reload addon if he is in a folder 

no message in console 

work on windows 7 32 bits

**Comment by youle31** [comment]
Hi, I think this is a BF bug. Could you test in last BF blender 2.79 sources: https://builder.blender.org/download/?hc_location=ufi

If this doesn't work here, and if BF coders consider this is a bug, the issue should be reported in phabricator

**Comment by supermoaaa** [comment]
it's work with old version of upbge i work very hard this week but after i can test it

**Comment by youle31** [comment]
As this issue is more related to official Blender, I close it. A bug report can be opened in phabricator
