### ISSUE TITLE
replacePhysicsShape + Character Physics = Crash

### ISSUE THREAD

**Issue by UnidayStudio** [UPBGE/blender#968]
Adding the [replacePhysicsShape](https://pythonapi.upbge.org/bge.types.KX_GameObject.html?highlight=reinstancephysicsmesh#KX_GameObject.replacePhysicsShape) function to change the physics mesh of an object with the "Character" Physics type = Crashes everywhere.

-When the collision bounds is disables, UPBGE only crashes when hit the ground.
-When enabled, UPBGE crashes by pressing P to start the game.

Example file:
http://pasteall.org/blend/index.php?id=50904

**Comment by youle31** [comment]
fixed by panzergame. Thanks!
