### ISSUE TITLE
Crash with Render Attachments

### ISSUE THREAD

**Issue by youle31** [UPBGE/blender#969]
Hello, I had a crash with this file http://pasteall.org/blend/index.php?id=50914

I just added a normal attachment, copied a GLSL filter found on BA and added a custom filter 2D actuator.

It is crashing when I press P. 

RelWithDebInfosBacktrace:

![sans titre](https://user-images.githubusercontent.com/10052509/50063787-32385280-01ae-11e9-80f9-9e62d235d1d3.jpg)

(maybe the shader failed to compile as I just copied/pasted it wihout tweaking? I don't know what is causing the crash for now)

**Comment by panzergame** [comment]
Fixed 670425e7f66ec06d89e2476c18f670a13102f44b
