### ISSUE TITLE
HDR rendering

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#97]
[HDR Rendering](https://en.wikipedia.org/wiki/High-dynamic-range_rendering) is a rendering technicue that renders screen in 64-bit floating-point color range rather than 32-bit integer color range. This allows to have more advanced post processing effects(like the ones in UE4). After that all the image is [tone mapped](https://en.wikipedia.org/wiki/Tone_mapping) and rendered to screen.
It would be great if this would be added to Blender:)

**Comment by panzergame** [comment]
I think we should move the standalone bit quality option in a common place and implement it deeper in the code.

**Comment by adriansnetlis** [comment]
Yeah... I found it being there.
Currently it must be possible to do HDR with tone mapping. However, we need to make it user-friendlier to do.

**Comment by adriansnetlis** [comment]
OK! A little corrections:
I've found out that in scene settings you can disable color management to get the raw image. This is the first step of whole process for HDR.
Than  in the scene settings you can set dynamic color range(from 0.2 to 5.0).
Than I use Reinald's tone mapping in filter to adjust scene. As it's commonly done, I use 2.2 gamma. The exprossure must propably match the color range(but I'm not sure about it, it can also be adjusted, however, it will be 1:1 brightness in this case).
Now there's a problem. Current 8-bit integer(32-bit RGBA) color depth is way too low. It results in bandings and other artifacts. It's due to low color range(24-bit range for the colors which is 16 777 216). This works well when you view the raw HDR(compressed). Of course, it's DARK at the raw image. However, once I map it to use only specific gamma-adjusted area, it becomes low-quality and looks like a 4-bit image(especially at dark zones). In case if we could render 16-bit float(64-bit RGBA color depth), we would have(48-bit range for colors) 281 474 980 000 000 which is 16 777 216 times more colors than the 8-bit integer. This would result in perfect HDR depth accuracy and allow to do any HDR filtering(e.g. for bloom, atmospheric scattering, even AO(to not to use bright objects for shading). I am sure that it would give a huge graphical boost for BGE if 16-bit float depth was implemented as an option.:)

So - anybody agrees with me?:D

**Comment by Akira1San** [comment]
Yep 16 bit is the go!

**Comment by youle31** [comment]
I think this kind of stuff can be done with 2D filters... I don't really understand but we can already have pure white and pure black, no? You don't agree that it's the same as did Martinsh here: http://blenderartists.org/forum/showthread.php?156482-HDR-many-simple-GLSL-2D-Filters-v2-0&highlight=hdr+simple+filters ? See the pictures he shows. If you want to test his .blend with the filters, there's some little things to tweak in the new blender's versions...

**Comment by adriansnetlis** [comment]
No... The deal is that if I set the range in the "world" settings to, e.g 2, than use tonemapping with exprossure of 2(and some gamma aswell), it really allows to do cool HDR filtering(e.g. UE4 type of bloom), however, it results in banding. However, with 16 777 216 times more colors it would look pure even at, e.g. 8.0 float range exprossure. And no banding would occur in any of cases.

**Comment by youle31** [comment]
Do you have an example .blend to show your "banding" issue?

**Comment by adriansnetlis** [comment]
I think I uploaded one once, but I don't remember who I gave it to...

**Comment by youle31** [comment]
I close the issue for the same reason as the other. We can't change RGBA8
