### ISSUE TITLE
Position render attachement.

### ISSUE THREAD

**Issue by panzergame** [UPBGE/blender#970]
As noticed by youle, it could be interesting to have a render attachement to retrieve the position of the fragment.

What I propose is to merge it with "normal" attachement so that we have 3 channels for normal and the last one for Z position.

This is open to debate.

**Comment by youle31** [comment]
It could be interesting to compare what we can see in a 2D filter using GetViewPosition (reconstruct position from depth) and what we can see if we implement it as a render attachment. But first, we'd need to have a good 2D filter resource which works fine and which is using GetViewPosition, GetViewNormal...

There are few things on BA, which we can find searching for global illumination, or SSR 2d filter

**Comment by youle31** [comment]
Another test file: http://pasteall.org/blend/index.php?id=50951
I can't get a proper result but I'll retry again... We can see that HDR attachment option has an impact on the render. There's also the code getViewNormal to test/compare

**Comment by youle31** [comment]
In several files, I tested, coders used to recreate position from depth texture, and as we'll focus on bug fixes, I close this
