### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by EndSSgamesStudio** [UPBGE/blender#974]
OS: Windows 10 64bits
compiler: Visual Studio 2017 64Bits 
Release for 32Bits 
the last Commit: https://github.com/UPBGE/blender/commit/b6e574b54e30647e7380c1389517cdd3dde73dba

![screenshot_20181221024723](https://user-images.githubusercontent.com/35436445/50325339-62903180-04cb-11e9-9a58-8dcadb44a80d.png)

**Comment by EndSSgamesStudio** [comment]
can not instantiate abstract class 

problems: bf_collada   collada.cpp

..\..\lib\Release\bf_collada.lib
C:\blender-git\blender\..\lib\windows_vc14\pthreads\lib\pthreadVC2.lib

I have currently updated libraries
problems in sources and libraries

**Comment by RomStef** [comment]
i have the same issue.

**Comment by lordloki** [comment]
We need to update our sources with last BF master sources

**Comment by lordloki** [comment]
Closing as I did the merge with BF sources few hours ago.
