### ISSUE TITLE
Per-Vertex Physics Settings(softbody, friction)

### ISSUE THREAD

**Issue by adriansnetlis** [UPBGE/blender#98]
Currently the physics settings apply to whole object. This is okay, except for softbodies and friction model. Let's say that we have an object like this:
![problem](https://cloud.githubusercontent.com/assets/6423934/15099545/9c16f22a-1560-11e6-89c3-2dcb02799717.png)
It's pretty obivous that you'll want the icecream to have friction coefficient around 0.1, while the wood stick to have it at 0.4. This is, of course, kind of dumb example.
Also you may propably want the icecream to be less stiff in case if you use softbody physics.
This would be great upgrade of BGE:)

**Comment by DCubix** [comment]
That sounds like a very game-specific feature. Most games don't care about real-life simulations.

**Comment by BluePrintRandom** [comment]
for stuff like simulating a actors shoe it would be handy
(gets caught easily on bottom, while sides are more slippery)

but that is very game specific as well,

**Comment by adriansnetlis** [comment]
I agree that it's a small, game-specific thing. However, this can help us be lead to next gen in physics section(still not enaugh, though, as the softbodies currently are pretty horrible). Oh, and I really need this:D

**Comment by BluePrintRandom** [comment]
what are you making? (just rigid body joint a object there instead and set
it's friction?

**Comment by adriansnetlis** [comment]
It's not only about friction. I think that it would be great to be able to control almost anything in a level of vertices. It's still something low priority, but it would be great. The friction was just an example.
