### ISSUE TITLE
GLSL Material node that accept shadertoy Feature Request

### ISSUE THREAD

**Issue by smithian123** [UPBGE/blender#981]
Hi,
I use bge and upbge for live performances but don't code a lot of it in python (more of an artist). Video textures are bad on performance. Would it be possible to do a version of this composite shader (link below) for material shaders. I'm mainly looking to use plasma style effect but some of the other would be useful for rendered stuff;
https://blenderartists.org/t/custom-build-blender-gmic-shadertoy-glsl-and-python-compositor-nodes/698783

You have to download the dedicated build of 2.79 to see it work in compositing.

Thanks,
Ian

**Comment by youle31** [comment]
hi, this can be done with custom GLSL 2D filters. The code needs to be adapted by the users. I think we won't add new features but only focus on bug fixes. Some users on BA, discord, and other bge forums could help to convert these filters into BGE 2D filters. As we slow down development, and focus on bugs fixes only, i close this for now, but it can be reopened by other devs if they want to answer/work on it
