### ISSUE TITLE
Joystick sensor not working on exported runtime build (bug) 

### ISSUE THREAD

**Issue by HickySnow** [UPBGE/blender#982]
Since Blender version 2.63 the joystick sensors logic bricks for xinput controllers stop working when exporting project as game engine run time build, this makes impossible to publish games made with logic bricks that make use of joystick.

**Comment by HickySnow** [comment]
Not yet. Will try doing the SDL2 for my project soon, but It doesn't change the fact that there is a problem with joystick sensor. Hope they have good solutions for gamepads implemented soon.

**Comment by lordloki** [comment]
I just test in windows with 0.2.4 and it is working perfectly.
Tested with viewport, blenderplayer and exported as runtime. Xinput controller (XBox360 for PC).
Which is your system? Upbge build? joystick?
What are the messages in the console?

**Comment by HickySnow** [comment]
I'm sing the gamepad PG-9021, it works fine in the embedded and stand alone player, but not when export as runtime.
This is the error message:
https://drive.google.com/file/d/1PTgRg6q_CjeKqwDfWufP_n5DDRGbgJsx/view?usp=sharing

**Comment by lordloki** [comment]
I think a quick solution would be copy gamecontrollerdb.txt where you have the .exe

**Comment by lordloki** [comment]
Yes, i saw that the datafiles and scripts folders are not copied. I will see how to fix it.
Thanks for testing.

**Comment by lordloki** [comment]
Commited fix in UPBGE-Addons.
![image](https://user-images.githubusercontent.com/1015605/50742765-ae531280-120f-11e9-9c15-b2fd3e31b34f.png)
Thanks for reporting. Closing.
