### ISSUE TITLE
UPBGE 0.2.4 crashes when i add properties to a ton of objects

### ISSUE THREAD

**Issue by pesmotite** [UPBGE/blender#987]
hey, I'm trying to make an character where when something happens to it, it turns into a ragdoll. the ragdoll itself is going to be invisible and parented to the main character, and when it enters the ragdoll state, it will appear and act like it should. 
![image](https://user-images.githubusercontent.com/46637976/51080427-85b49800-16a9-11e9-9af6-cbb54cc8c296.png)
-
![image](https://user-images.githubusercontent.com/46637976/51080419-69b0f680-16a9-11e9-9d90-84b5e37e7b24.png)
i'm using this property to toggle between inactive and active states, where in active, it'll do all the stuff mentioned before. but, when i copy and paste the property to all of the dude's limbs and run the game, UPBGE crashes instantly, and I don't know why. at first it seems like the engine just doesn't like it when i do this, or i'm pasting it to too many objects. I'd really like some help with this, or a fix in a future build of UPBGE. if you need me to, i'll upload the file.

**Comment by marechal-p** [comment]
> If you need me to, I'll upload the file.

Always do that when possible, such as now :p

**Comment by BluePrintRandom** [comment]
I would group the ragdoll and place it on a hidden layer, and spawn in a group instance of the ragdoll when the player dies / whatever

the group instance can access all group members via obejct.groupMembers to perform logic on them like align them to bones or build 6dof joints in runtime etc.
