### ISSUE TITLE
Make pip installed by default

### ISSUE THREAD

**Issue by joelgomes1994** [UPBGE/blender#992]
Hello!

`pip` is very useful to easily install Python packages compatible with the current UPBGE's Python version and architecture. I use it a lot with UPBGE, and I think it would be interesting to have it installed by default. Probably it's not that hard to do, maybe automating the run of command `python -m ensurepip` after building UPBGE from source should do it.

I don't know why it's not installed by default, when `tests` library (and even `tkinter`) are.

Thanks! 😄 

![image](https://user-images.githubusercontent.com/19820741/51445779-1f0a2c80-1cf0-11e9-95e3-7510e4ff1c15.png)

**Comment by marechal-p** [comment]
https://docs.python.org/3/library/ensurepip.html

> This bootstrapping approach reflects the fact that pip is an independent project with its own release cycle, and the latest available stable version is bundled with maintenance and feature releases of the CPython reference interpreter.

So this paragraph might explain the reasoning why `pip` isn't installed by default :)

On the other hand:

> In most cases, end users of Python shouldn’t need to invoke this module directly (as pip should be bootstrapped by default), but it may be needed if installing pip was skipped when installing Python (or when creating a virtual environment) or after explicitly uninstalling pip.

This paragraph mention the fact that usually `pip` is already bootstrapped by default. But keep in mind that they are talking about Python interpreters, and the fact that pip will be installed when you install said interpreter.

As far as I know, UPBGE currently is just an archive that we need to extract. But if an installer were to exists, it would actually make a lot of sense to propose to install `pip` at that step, indeed.

So right now, running `python -m ensurepip` might be the best solution, given the way that UPBGE is distributed.

**Comment by BluePrintRandom** [comment]
@marechal-p  thanks 

I am going to go ahead and close this.
