### ISSUE TITLE
objects experience THE SHAKE at great distance from center

### ISSUE THREAD

**Issue by orestasvanagas** [UPBGE/blender#995]
here is the problem in detail
https://www.youtube.com/watch?v=Pyr5lWPqfkk&feature=youtu.be
Basically objects start to shake when far enough from center

**Comment by marechal-p** [comment]
Can you give an estimation of the distance from center?

**Comment by orestasvanagas** [comment]
> Can you give an estimation of the distance from center?

30 km (when unit preset is metric (unit scale is 1.0))

**Comment by BluePrintRandom** [comment]
This is a issue with floating point math and rounding errors

It's better to make everything small and adjust gravity to compensate

**Comment by BluePrintRandom** [comment]
this is a issue with floating point rounding errors and cannot be fixed.
