### ISSUE TITLE
Cube maps are not working in recent master.

### ISSUE THREAD

**Issue by BluePrintRandom** [UPBGE/blender#998]
I upbge 0.2.3 cube maps are working, and in my upbge 0.2.4 (pre-release) cube maps are working,

however they are not working in master - I suspect it's the render attachment patch.

**Comment by BluePrintRandom** [comment]
[reflect_sample.zip](https://github.com/UPBGE/blender/files/2793108/reflect_sample.zip)

**Comment by Masterblop** [comment]
Cube "Invisible"
![schermata da 2019-01-25 09-48-01edit](https://user-images.githubusercontent.com/11289405/51735114-c5568900-2086-11e9-849d-45689f63aced.jpeg)
Cube "Visible"
![schermata da 2019-01-25 09-48-08edit](https://user-images.githubusercontent.com/11289405/51735120-c8517980-2086-11e9-9195-295a5e1fa1e1.jpeg)

**Comment by BluePrintRandom** [comment]
Tested with https://github.com/UPBGE/blender/pull/999 confirmed it's fixed!
